### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by filipemerker** [gorhom/react-native-bottom-sheet#10]
Hey, love the project. You up for adding some tests? I could start that for you.
`jest` + `native-testing-library` + `react-hooks-testing-library`?

**Comment by gorhom** [comment]
hi @filipemerker , that would be awesome !

**Comment by filipemerker** [comment]
I'll do it this week than!

**Comment by Angelk90** [comment]
@filipemerker : I'm curious about these tests, where can I find them?

**Comment by JanithaR** [comment]
Would really appreciate tests. Currently, I can't figure out how to get mine working.

**Comment by Angelk90** [comment]
@filipemerker : I'm curious about these tests, where can I find them?

**Comment by Angelk90** [comment]
@filipemerker : I'm curious about these tests, where can I find them?

**Comment by priyangamani** [comment]
jest.mock("react-native-raw-bottom-sheet") @filipemerker about the test cases??

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by suanev** [comment]
updates??????????????????????????????????????

**Comment by Angelk90** [comment]
@filipemerker : I'm curious about these tests, where can I find them?

**Comment by filipemerker** [comment]
Yo, I might do that this year, but I wouldn't hold my breath if you really need this 🤪 Right now open-source is a little low on my priority list.

**Comment by Angelk90** [comment]
@filipemerker : We are curious we have been waiting for a year.
