### ISSUE TITLE
bottom-sheet with snapPoints values greater than 97% does not open

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-bottom-sheet#105]
# Bug

![](https://user-images.githubusercontent.com/20476002/101175737-d0e14680-3645-11eb-92db-347818edf4e2.gif)

Hi @gorhom : 
If I put only one snapPoints with values higher than "97%", does not open (98%, 99%, 100%).
See the code to understand better.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         |2.0.0-alpha.4   |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 1.13.2  |
| react-native-gesture-handler    | 1.9.0   |

## Reproducible sample code

```javascript
const bottomSheetTheme = useCallback(
      (newValue, id) => {
        present(<ThemeModal darkMode={darkMode} onChange={handleThemeChange} />, {
          snapPoints: ['98%'], //<-99%, 100%
          animationDuration: 800,
          overlayComponent: BottomSheetOverlay,
          overlayOpacity: 0.5,
          dismissOnOverlayPress: true,
          animationEasing: Easing.out(Easing.exp),
          handleComponent: handleModal,
        });
      },
      [settings],
  );
```

**Comment by gorhom** [comment]
hi @Angelk90 , could you please try again with alpha 5 :) thanks

**Comment by Angelk90** [comment]
<img width="359" alt="Schermata 2020-12-13 alle 19 32 27" src="https://user-images.githubusercontent.com/20476002/102020516-fbd04680-3d79-11eb-9457-82dfe4cba131.png">

@gorhom , I have installed the version you say, when I try to open it gives me the following error.

**Comment by gorhom** [comment]
Hi @Angelk90 , with alpha 5 the bottom sheet modal became a declarative component, look at the usage example:


https://gorhom.github.io/react-native-bottom-sheet/modal/usage

**Comment by Angelk90** [comment]
@gorhom : ok, this problem still persists even with this version.

**Comment by gorhom** [comment]
@Angelk90 , looking at it now

**Comment by Angelk90** [comment]
@gorhom : I looked, with values above such as "98%", "99%" and "100%" it does not open.

**Comment by Angelk90** [comment]
@gorhom :  `snapPoints={["98%"]}` does not work.

**Comment by gorhom** [comment]
@Angelk90 found the bug 👍

**Comment by gorhom** [comment]
@Angelk90 thanks for reporting this bug ! now this is been fixed with Alpha 6

```bash
yarn add @gorhom/bottom-sheet@2.0.0-alpha.6
```

**Comment by Angelk90** [comment]
@gordon: Ok, it seems solved but the transparent background of dark color that was seen below it that if you clicked them it closed the modal is gone?
