### ISSUE TITLE
Help needed : Why it's not draggable

### ISSUE THREAD

**Issue by boypanjaitan16** [gorhom/react-native-bottom-sheet#110]
I'm following one of the examples https://github.com/gorhom/react-native-bottom-sheet/blob/master/docs/sectionlist.md but I found it is not draggable, how to make it draggable ? I dont find any key about drag thing in props docs

**Comment by gorhom** [comment]
hi @boypanjaitan16, sorry but i'll need to close this ticket because it doesn't follow the issue/bug template.

feel free to create another issue with the template :)
