### ISSUE TITLE
Bottom-sheet which does not close even if you drag down

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-bottom-sheet#111]
# Feature Request

Hi @gorhom , 

it would be possible to implement the possibility of opening a bottom-sheet that does not close if dragged down.

## Why it is needed

Let's consider the example of an app configuration of some parameters, which cannot be continued if the user does not choose an option among those selectable.

**Comment by gorhom** [comment]
you can use `enableContentPanningGesture` & `enableHandlePanningGesture` to block panning gesture

**Comment by gorhom** [comment]
check https://gorhom.github.io/react-native-bottom-sheet/props#enablecontentpanninggesture

**Comment by Angelk90** [comment]
@gorhom : Thx.
