### ISSUE TITLE
[v4] BottomSheet*List doesn't work if it's not a direct child of a BottomSheetModal

### ISSUE THREAD

**Issue by sebastian-nowak** [gorhom/react-native-bottom-sheet#1156]
# Bug

It looks like the scrollable views provided by BottomSheet work only if they're a direct child of a `BottomSheet` / `BottomSheetModal`.

Wrapping a `<BottomSheet*List/>` in another component, even if it's a simple `<View style={{flex: 1}}>...</View>`, is enough to break scrolling.

None of the examples provided at https://gorhom.github.io/react-native-bottom-sheet/v2/scrollables/ work if `<BottomSheet*List/>` component is wrapped in another component.

Maybe this is expected behavior, but it's not documented anywhere on the page I linked to above.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.5   |
| react-native                    | 0.69.6   |
| react-native-reanimated         | 2.9.1   |
| react-native-gesture-handler    | 2.5.0   |

## Steps To Reproduce

1. Open any of the example apps under https://gorhom.github.io/react-native-bottom-sheet/v2/scrollables/
2. Wrap the `<BottomSheet*List/>` in a `<View style={{flex: 1}}>...</View>`
3. Notice that the list is no longer scrollable :-(

Describe what you expected to happen:

1. List should be scrollable

## Reproducible sample code

Just use one of the examples at https://gorhom.github.io/react-native-bottom-sheet/v2/scrollables/.

**Comment by sebastian-nowak** [comment]
FYI this comment from 2021 also mentions the issue: https://github.com/gorhom/react-native-bottom-sheet/issues/266#issuecomment-826122954

**Comment by sebastian-nowak** [comment]
@gorhom, do you know if there's a way to get it to work with nesting?

**Comment by lpmsh** [comment]
Any updates on this? @sebastian-nowak @gorhom 

I'm specifically having trouble with the `BottomSheetScrollView` in v4. When it isn't a direct child of the BottomSheet/BottomSheetModal, nothing is rendered. I've tried using RN's and `react-native-gesture-handler`'s `ScrollView` and things are rendered but they obviously don't work well with the dynamic height of the bottom sheet.

**Comment by serapieTuyishime** [comment]
Use this https://gorhom.dev/react-native-bottom-sheet/components/bottomsheetsectionlist

**Comment by c-info** [comment]
Managed somehow as below

```
import {FlatList} from 'react-native-gesture-handler'; 
import {
  BottomSheetBackdrop,
  BottomSheetModal,
  BottomSheetView,
} from '@gorhom/bottom-sheet';

<BottomSheetModal
        ref={sheetRef}
        enableDynamicSizing={true}
        maxDynamicContentSize={height * 0.75}
        >
        <BottomSheetView style={{flex:1}}>
          <FlatList
            data={Array(30).fill(1)}
            keyExtractor={(__, index) => index.toString()}
            renderItem={_renderItem}
          />
        </BottomSheetView>
      </BottomSheetModal>
```
