### ISSUE TITLE
Backdrop flickers with Reanimated 2

### ISSUE THREAD

**Issue by izakfilmalter** [gorhom/react-native-bottom-sheet#118]
# Bug

Backdrop flickers when opening with Reanimated 2. This is specifically with `BottomSheetModal`. It was working fine on @gorhom/bottom-sheet@1.4.1, but started to flicker when upgrade to 2.0.0.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.1   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

1. Run the example app, but change the version of Reanimated to 2.0.0-rc.1
2. Test a modal with a Backdrop.
3.  Notice that the Opacity starts as 1, and on the next frame goes to 0, then the animation back to 1 begins. 

Describe what you expected to happen:

1. Opacity should start at 0 so that you don't get a flash.

## Reproducible sample code

I tried rocking my own Backdrop and fiddling with the reanimated code, but it seems to be a problem with the `animatedIndex`.

**Comment by gorhom** [comment]
hi @izakfilmalter , could you provide a reproducible sample code so i  could help you :)

**Comment by gorhom** [comment]
this should be fixed with https://github.com/gorhom/react-native-bottom-sheet/pull/175

**Comment by Nevosis** [comment]
To clarifie to other having the issue. You can have the issue with bottom-sheet 2 and without bumping reanimated.
