### ISSUE TITLE
BottomSheetFlatList no scroll

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-bottom-sheet#120]
# Bug

<img width="329" alt="Schermata 2020-12-19 alle 16 24 35" src="https://user-images.githubusercontent.com/20476002/102692870-b5b23180-4216-11eb-8b89-ba4dd2421b8c.png">

Hi @gorhom ,

i am using the `BottomSheetFlatList` to get a list of users, but i am not being able to scroll the items.
I tried to create a basic example on snack.expo, find below the link to try it.

Let me know if you have any questions.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0   |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 1.13.2  |
| react-native-gesture-handler    | 1.9.0   |

## Reproducible sample code

Link: [here](https://snack.expo.io/aEnVMXzqt)

**Comment by gorhom** [comment]
edit `FlatList` container style 
```tsx
  const contentContainerStyle = useMemo(
    () => ({
      flex: 1, < remove this
      backgroundColor: '#ccc',
      //paddingBottom: bottomSafeArea,
    }),
    []
  );
  ```

**Comment by Angelk90** [comment]
@gorhom : I tried, but it doesn't work as you indicated.

**Comment by niraj-khatiwada** [comment]
Is this solved. The BottomSheetFlatlist only works in Android but completely unusable in IOS.
