### ISSUE TITLE
Document how to access the data passed to the .present() method

### ISSUE THREAD

**Issue by gkpo** [gorhom/react-native-bottom-sheet#1282]
# Feature Request

(please 😇) Document how to access the data that is passed to the modal with the `.present({myData: "hi"})` method.

## Why it is needed

The documentation of the `present` method says that it is possible to pass data to a bottom-sheet-modal, but there's no way to find how to access it once you're in the bottomsheet.

From the source: lib/typescript/types.d.ts
```
/**
   * Mount and present the bottom sheet modal to the initial snap point.
   * @param data to be passed to the modal.
   */
  present: (data?: any) => void;
```

## Possible implementation

> So this is how you access the data : .... 🙂

### Code sample

```
// A code example showing how to access the data :)
```

**Comment by aarongriffin-snap** [comment]
bump

**Comment by domeknn** [comment]
Use function as children and data from `.present` will be passed as 1st argument

https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetModal/BottomSheetModal.tsx#L385

```
<Modal>
  {(data) => ... }
</Modal>

**Comment by gkpo** [comment]
Thanks so much, maybe this should be documented! If I can help, I'd be glad to PR

**Comment by iraybi** [comment]
How to access the passed data in footer component?

**Comment by agestaun** [comment]
Just in case someone needs a more elaborated explanation.

Here's a component named `MyBottomSheet` which contains the `BottomSheetModal` from this library:

```
const MyBottomSheet = () => {

...

  return (
      <BottomSheetModal  ref={bottomSheet} {...props}>
        {(data) => (  // 👈 Pay attention to this data received and passed to the children below if children is a function.
          <BottomSheetScrollView>
              <>{typeof children === "function" ? children(data) : children}</>
          </BottomSheetScrollView>
        )}
      </BottomSheetModal>
    );
}
```

To use it passing data:

```
const App = () => {<

  const onPressButton = () => {
      const items = ['a', 'b', 'c'];
      bottomSheet.current?.present(items);
  }

  return (
        <>
            <Button onPress={onPressButton} />
            <MyBottomSheet ref={bottomSheet}>
              {({ data }) => <MyListComponent items={data} />}
            </MyBottomSheet>
        </>
  );
}
```

**Comment by alex-vasylchenko** [comment]
Hi, how to use it with TS? where do I need to declare the type of data that I put to the present function?

**Comment by gabimoncha** [comment]
@alex-vasylchenko you can pass the type / interface / zodSchema as a generic

```ts
        <BottomSheetModal<Activity>
          ref={bottomSheetModalRef}
          {...props}
        >
          {({ data }) => <YourComponent {...data/>}
        </BottomSheetModal>
```

**Comment by jdarshan5** [comment]
> How to access the passed data in footer component?

+1, for this enhancement!

**Comment by M21H** [comment]
> Just in case someone needs a more elaborated explanation.
> 
> Here's a component named `MyBottomSheet` which contains the `BottomSheetModal` from this library:
> 
> ```
> const MyBottomSheet = () => {
> 
> ...
> 
>   return (
>       <BottomSheetModal  ref={bottomSheet} {...props}>
>         {(data) => (  // 👈 Pay attention to this data received and passed to the children below if children is a function.
>           <BottomSheetScrollView>
>               <>{typeof children === "function" ? children(data) : children}</>
>           </BottomSheetScrollView>
>         )}
>       </BottomSheetModal>
>     );
> }
> ```
> 
> To use it passing data:
> 
> ```
> const App = () => {<
> 
>   const onPressButton = () => {
>       const items = ['a', 'b', 'c'];
>       bottomSheet.current?.present(items);
>   }
> 
>   return (
>         <>
>             <Button onPress={onPressButton} />
>             <MyBottomSheet ref={bottomSheet}>
>               {({ data }) => <MyListComponent items={data} />}
>             </MyBottomSheet>
>         </>
>   );
> }
> ```

passing `{typeof children == 'function' ? ({ data }) => children(data) : children}` works better with BottomSheetFlatList

**Comment by mwannags** [comment]
Firstly thank you guys very much for sharing your workarounds / tipps. But:

I am not really getting how it works... as I implement something like:
`{({ data }) => <Text>{data.name}</Text>}`

And i exec .present() like this:
`bottomSheetModalRefMuscleGroupMenu.current?.present({name: "test"});`

I get: Functions are not valid as a React child. This may happen if you return Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

What am I doing wrong?

**Comment by mraoxy** [comment]
@mwannags Same issue here !

**Comment by mwannags** [comment]
> [@mwannags](https://github.com/mwannags) Same issue here !

I have now found a workaround that I am very happy with.

If you have built your BottomSheet component with a forwardRef, you can use an ImperativeHandle to intercept the data you sent along, something like this:

`const YourMenu = forwardRef(( props, ref )) => {
    // STATES
    const [data, setData] = useState({});

    // REFS
    const modalRef = useRef(null);

    // HANDLE
    useImperativeHandle(ref, () => ({
        present: (passedData) => {
            // store the passed data
            setData(passedData);
            // open the actual modal
            modalRef.current?.present();
        }
    }));

    return (
        <BottomSheetModal
            ref={modalRef}
            ...
        >
            {/* content here */}
        </BottomSheetModal>
    );
};`

I haven't tested the code I provided here – it's just an abstract version of what I did in my library. But it should make clear what I mean. And I hope it can help someone

**Comment by pneuviz** [comment]
This is how we use it with Typescript. 

```
type MyModalProps = {
  save: (someData: SomeDataType) => void
}

const MyModal = forwardRef<BottomSheetModal, MyModalProps>(
  function EditVocabularyDetails({ save }, ref) { 
    return (
      <BottomSheetModalProvider>
        <BottomSheetModal<DataFromPresentType> // the type of the data we pass into .present(...)
          ref={ref}
          enableOverDrag
          backdropComponent={(props: BottomSheetBackdropProps) => (
            <BottomSheetBackdrop {...props} disappearsOnIndex={-1} />
          )}
          snapPoints={['90%']}
          enableDynamicSizing={false}
          enableContentPanningGesture
          enableDismissOnClose
          enablePanDownToClose
          style={{ paddingHorizontal: 16 }}
        >
          {({ data }) => (
            <BottomSheetScrollView>
              <CustomComponent to useData - can use useBottomSheetModal to dismiss the modal 
                liveData={data } // data is available here 
                save={save);
                }}
              />
            </BottomSheetScrollView>
          )}
        </BottomSheetModal>
      </BottomSheetModalProvider>
    );
  }
);
```

Then you can render it using: 
```
 myModalRef.current?.present(someData);
<MyModal ref={editFormRef} save={onSave}/> 
```

**Comment by Saphirah** [comment]
> [@mwannags](https://github.com/mwannags) I haven't tested the code I provided here – it's just an abstract version of what I did in my library. But it should make clear what I mean. And I hope it can help someone

Helped me. Thank you! Here is a full ts hook:
```ts
export function useBottomSheetData<T>(ref?: RefObject<BottomSheetModal | null>, defaultValue?: T) {
  const modalRef = useRef<BottomSheetHandle | null>(null);
  const [data, setData] = useState<T | null>(defaultValue || null);
  useImperativeHandle(
    ref,
    () => ({
      present: data => {
        const nextEntry = data ?? defaultValue;
        setData(nextEntry || null);
        modalRef.current?.present(data);
      },
      dismiss: conf => modalRef.current?.dismiss(conf),
      snapToIndex: (index, conf) => modalRef.current?.snapToIndex(index, conf),
      snapToPosition: (position, conf) => modalRef.current?.snapToPosition(position, conf),
      expand: conf => modalRef.current?.expand(conf),
      collapse: conf => modalRef.current?.collapse(conf),
      close: conf => modalRef.current?.close(conf),
      forceClose: conf => modalRef.current?.forceClose(conf),
    }),
    [defaultValue],
  );
  return {data, setData, modalRef};
}
```

Usage: 
```ts
export default function CustomBottomSheet(props: {ref?: RefObject<BottomSheetModal | null>}) {
  const {data, setData, modalRef} = useBottomSheetData<any>(props.ref, {hello: "world"});

  return (
    <BottomSheetModal ref={modalRef}>
      <Text>{data.hello}</Text>
    </BottomSheetModal>
  );
}
```
```ts
ref.current?.present({hello: "there"});
```

**Comment by praisedavid787** [comment]
> Usage:
> 
> export default function CustomBottomSheet(props: {ref?: RefObject<BottomSheetModal | null>}) {
>   const {data, setData, modalRef} = useBottomSheetData<any>(props.ref, {hello: "world"});
> 
>   return (
>     <BottomSheetModal ref={modalRef}>
>       <Text>{data.hello}</Text>
>     </BottomSheetModal>
>   );
> }
> ref.current?.present({hello: "there"});

Beautiful, just beautiful 🤩
