### ISSUE TITLE
does not reopen using the gesture

### ISSUE THREAD

**Issue by cruzms** [gorhom/react-native-bottom-sheet#130]
# Bug

I have a list of elements, each one opens the sheet to see the details, if I touch outside or use a button to close the sheet there is no problem but when I use the gesture to close it and when I click on another of the elements in the list the sheet does not open.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0   |
| react-native                    | 0.63   Expo 39|
| react-native-reanimated         | 1.13.0   |
| react-native-gesture-handler    | 1.7.0   |

## Steps To Reproduce

As i said above, if i use the button or tap outside it works, if i close using the gesture it doesn't open again

https://user-images.githubusercontent.com/31360984/102833735-8a1a7d00-43b7-11eb-8c92-0693434c6b17.mp4

## Reproducible sample code
Page with List
``` jsx
<FlatList
        data={services2}
        keyExtractor={(item) => String(item.id)}
        renderItem={({ item }) => (
          <Card
            marker={item}
            onPress={() => { 
                sheetRef.current.snapTo(1);
                setCurrent(item); }}
          />
        )}
      />
<MyBottomSheet
        sheetRef={sheetRef}
        current={current}
      />
```
MyBottomSheet.js
``` jsx
<BottomSheet
      ref={sheetRef}
      snapPoints={[0, '70%']}
      index={-1}
      backdropComponent={BottomSheetBackdrop}
    >
      <TouchableOpacity onPress={()=>{sheetRef.current.close();}} >
          <MaterialIcons name="close" size={20} color="black" />
      </TouchableOpacity>
  <BottomSheetScrollView
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator
      >
    {item info}
</BottomSheetScrollView>
</BottomSheet>
```

**Comment by gorhom** [comment]
hi @cruzms , try to use [BottomSheetModal](https://gorhom.github.io/react-native-bottom-sheet/modal)  it will fit your use case better .
