### ISSUE TITLE
Bottom Sheet Model Stuck On Android Device

### ISSUE THREAD

**Issue by Saff-Elli-Khan** [gorhom/react-native-bottom-sheet#133]
https://user-images.githubusercontent.com/62799255/103379390-4508f000-4b07-11eb-8553-7dda31b684a5.mov

Please fix this issue ASAP :) Thanks

**Comment by gorhom** [comment]
@Saff-Elli-Khan please re-create the issue and follow the issue template

**Comment by Saff-Elli-Khan** [comment]
Actually, the problem is in react native gesture handler linking. The problem is resolved by @Akinmac002

Adding these lines of code in android/app/src/main/java/com/projectName/MainActivity.java

`import com.facebook.react.ReactActivity;
  import com.facebook.react.ReactActivityDelegate;
  import com.facebook.react.ReactRootView;
  import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

   public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
       return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }
}`
