### ISSUE TITLE
Docs: Custom Handle example in Reanimated V2

### ISSUE THREAD

**Issue by henrymoulton** [gorhom/react-native-bottom-sheet#138]
# Feature Request

Happy 2021 @gorhom! Thanks for all your contributions to RN so far :)

https://gorhom.github.io/react-native-bottom-sheet/custom-handle/ is coded in Reanimated V1. Would be useful to update to latest examples.

## Possible implementation

I'll try updating it myself and submit a PR (good excuse to learn V2).

**Comment by gorhom** [comment]
happy new year @henrymoulton  🥳

thanks for spotting this enhancement, and i agree , the documentation should provide examples with both v2 & v3 version.

feel free to submit a pr , will be more than happy to get it merged

**Comment by henrymoulton** [comment]
OK great I'll look into this, however [transformOrigin isn't in redash for reanimated v2](https://github.com/wcandillon/react-native-redash/issues/398#issuecomment-731509439).

Perhaps there's another way of implementing this animation however. I'll have a try.

**Comment by efstathiosntonas** [comment]
Hi everyone, any updates on this? transformOrigin still doesn't exist yet

**Comment by Sax-Yusuph** [comment]
Hi, any updates on this yet?
