### ISSUE TITLE
Get realtime BS animation values

### ISSUE THREAD

**Issue by ezhkov** [gorhom/react-native-bottom-sheet#147]
# Feature Request
Thank you for great component. It is so cool! 

Is there any way to get BS realtime animation values? 

## Why it is needed
Sometimes we need to create beautiful related animations between two components. E.g. if I drag my BS up or down smoothly, another component could use BS's realtime Y value to smoothly change position

## Possible implementation
![CleanShot 2021-01-04 at 14 34 05](https://user-images.githubusercontent.com/568355/103526208-ff974a80-4e99-11eb-9d14-2bc2a6daf316.gif)

**Comment by gorhom** [comment]
the library already provides this 

https://gorhom.github.io/react-native-bottom-sheet/props#animatedposition

**Comment by ezhkov** [comment]
Isn't this property using from outside BS to set its realtime position? So I need to calculate it myself, including percentage values etc.?

**Comment by ezhkov** [comment]
> the library already provides this
> 
> https://gorhom.github.io/react-native-bottom-sheet/props#animatedposition

Thank you. I didn't understand how to use it first. But now I looked into examples and now everything fell into place )

**Comment by gorhom** [comment]
no worries 👏

**Comment by ezhkov** [comment]
Okay, I noticed, that you're using `useValue` from `react-native-redash`. What if I don't want to include this library in my project? How to use `animatedPosition` in usual way?

**Comment by gorhom** [comment]
you can use `useValue` from `react-native-reanimated`
