### ISSUE TITLE
Props animatedIndex and animatedPosition causing infinite updates

### ISSUE THREAD

**Issue by tankers746** [gorhom/react-native-bottom-sheet#149]
# Bug

The animated reactions that update the animated props are causing worklets to loop infinitely.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.0.2-alpha.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.0   |
| react-native-gesture-handler    |1.9.0   |

## Steps To Reproduce

1. Run the sample
2. Move the drawer
3.  Check the console

## Reproducible sample code

```
import { AppRegistry } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const App = function App() {
    const animatedIndex = useSharedValue(0);

    useDerivedValue(() => {
        console.log(animatedIndex.value);
    });
    return (
        <BottomSheet
            index={0}
            snapPoints={[100, 500]}
            animatedIndex={animatedIndex}>
            <View style={{ backgroundColor: 'red', flex: 1 }} />
        </BottomSheet>
    );
};

AppRegistry.registerComponent('App', () => App);

```

**Comment by tankers746** [comment]
https://github.com/gorhom/react-native-bottom-sheet/pull/150

**Comment by gorhom** [comment]
thanks @tankers746 for submitting this issue and the pr ❤️
