### ISSUE TITLE
How change handle color

### ISSUE THREAD

**Issue by Piero87** [gorhom/react-native-bottom-sheet#155]
How can I change the handle color? I have tried this:

      <BottomSheet
        ref={this.bottomSheetRef}
        index={-1}
        snapPoints={[0, 255]}
        onChange={this.onChange}
        backdropComponent={BottomSheetBackdrop}
        handleComponent={() =>
          <View style={styles.closeLineContainer}>
            <View style={styles.closeLine}></View>
          </View>
        }
      >
        ...
      </BottomSheet>

styles:

```
  closeLineContainer: {
    alignSelf: 'center'
  },
  closeLine: {
    width: 40,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.lightGray,
    marginTop: 9,
  },
```
This is the result:
<img width="452" alt="Schermata 2021-01-06 alle 14 44 34" src="https://user-images.githubusercontent.com/768952/103775168-f7701400-502d-11eb-84eb-878d2db681c9.png">

As you can see there i a space in the bottom that I don't know how I can remove, instead if I remove the custom handleComponent I get this that is what I want:

<img width="435" alt="Schermata 2021-01-06 alle 14 46 20" src="https://user-images.githubusercontent.com/768952/103775228-12428880-502e-11eb-9f26-c9da78807793.png">

So my question is, how can I just change the handle color?

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0  |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.9.0   |

**Comment by gorhom** [comment]
@Piero87 thanks for spotting this bug ! i'm working on a fix 👍

**Comment by Piero87** [comment]
@gorhom Now it works! thank you very much!

**Comment by gorhom** [comment]
i will prepare a release soon

**Comment by gorhom** [comment]
this has been released with `v2.0.2`, and soon will be released on `v3.1.0`

**Comment by Piero87** [comment]
@gorhom I have tried the version 2.0.2 but there still seems to be the same problem of the bottom space with the code I use above

**Comment by gorhom** [comment]
@Piero87 try to clear the cache and try again, because it is working on my side both on v2 and v3

**Comment by Piero87** [comment]
I have tried, I removed node modules, and rebuild again all the app, but I still have the problem, instead if I remove this:

    handleComponent={() =>
      <View style={styles.closeLineContainer}>
        <View style={styles.closeLine}></View>
      </View>
    }

it works, but in this way I can't change the handler color

**Comment by Piero87** [comment]
@gorhom I have tried, I removed node modules, and rebuild again all the app, but I still have the problem, instead if I remove this:

    handleComponent={() =>
      <View style={styles.closeLineContainer}>
        <View style={styles.closeLine}></View>
      </View>
    }

it works, but in this way I can't change the handler color. What you think to expose a prop to change the color?

**Comment by Piero87** [comment]
@gorhom I found the problem, it's because I use the backgroundComponent too, if you add this:

```
        backgroundComponent={() =>
          <View style={styles.contentContainer}/>
        }
```

With styles:

```
const styles = StyleSheet.create({
  contentContainer: {
    ...StyleSheet.absoluteFillObject,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: 'red'
  }
})
```

You will see the error again

**Comment by gorhom** [comment]
i have tested your code on `2.0.3` and looks fine , try to clear cache and install the library again 👍
![simulator_screenshot_2FBD866A-408E-4D18-BD8F-50C5E1D51AF4](https://user-images.githubusercontent.com/4061838/104242338-533c0200-545f-11eb-9eda-4c419b593f7b.png)

**Comment by Piero87** [comment]
@gorhom Thank for the answer, you have to add also the custom handler:

```
 backgroundComponent={() =>
          <View style={styles.contentContainer}/>
        }
handleComponent={() =>
  <View style={styles.closeLineContainer}>
    <View style={styles.closeLine}></View>
  </View>
}
```

```
const styles = StyleSheet.create({
  contentContainer: {
    ...StyleSheet.absoluteFillObject,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: 'red'
  },
  closeLineContainer: {
    alignSelf: 'center'
  },
  closeLine: {
    width: 40,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.lightGray,
    marginTop: 9,
  },
})
```

In your image above I see that you haven't used it

**Comment by EskimoEmoji** [comment]
For the custom background, how can I get this section of code to work for the .js file? And/or is there just an easy way to change the background color. style={{ backgroundColor: "blue" }} doesn't seem to work? Is there a way to adjust the style for BottomSheet?

Thanks!

const CustomBackground = ({
  animatedIndex,
  style,
}: BottomSheetBackgroundProps) => {
  // animated variables
  const animatedBackground = useMemo(
    () =>
      interpolateColors(animatedIndex, {
        inputRange: [0, 1],
        outputColorRange: ['#fff', '#a8b5eb'],
      }),
    [animatedIndex]
  );

**Comment by soham-gadhave** [comment]
> How can I change the handle color? I have tried this:
> 
> ```
>   <BottomSheet
>     ref={this.bottomSheetRef}
>     index={-1}
>     snapPoints={[0, 255]}
>     onChange={this.onChange}
>     backdropComponent={BottomSheetBackdrop}
>     handleComponent={() =>
>       <View style={styles.closeLineContainer}>
>         <View style={styles.closeLine}></View>
>       </View>
>     }
>   >
>     ...
>   </BottomSheet>
> ```
> 
> styles:
> 
> ```
>   closeLineContainer: {
>     alignSelf: 'center'
>   },
>   closeLine: {
>     width: 40,
>     height: 6,
>     borderRadius: 3,
>     backgroundColor: Colors.lightGray,
>     marginTop: 9,
>   },
> ```
> 
> This is the result:
> <img alt="Schermata 2021-01-06 alle 14 44 34" width="452" src="https://user-images.githubusercontent.com/768952/103775168-f7701400-502d-11eb-84eb-878d2db681c9.png">
> 
> As you can see there i a space in the bottom that I don't know how I can remove, instead if I remove the custom handleComponent I get this that is what I want:
> 
> <img alt="Schermata 2021-01-06 alle 14 46 20" width="435" src="https://user-images.githubusercontent.com/768952/103775228-12428880-502e-11eb-9f26-c9da78807793.png">
> 
> So my question is, how can I just change the handle color?
> 
> Library	Version
> @gorhom/bottom-sheet	2.0.0
> react-native	0.63.3
> react-native-reanimated	1.13.2
> react-native-gesture-handler	1.9.0

How did you achieve those rounded corners on the handle without using the handleComponent prop?

**Comment by Piero87** [comment]
@soham-gadhave as you can see in the code above:

```
handleComponent={() =>
      <View style={styles.closeLineContainer}>
        <View style={styles.closeLine}></View>
      </View>
    }
```

**Comment by mdalishanali** [comment]
```
 backgroundComponent={() =>
          <View style={styles.contentContainer}/>
        }
handleComponent={() =>
  <View style={styles.closeLineContainer}>
    <View style={styles.closeLine}></View>
  </View>
}
```
````
const styles = StyleSheet.create({
  contentContainer: {
    ...StyleSheet.absoluteFillObject,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: 'red'
  },
  closeLineContainer: {
    alignSelf: 'center'
  },
  closeLine: {
    width: 40,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.lightGray,
    marginTop: 9,
  },
})`
```
My requirement is to change the bottom sheet background color. This is the best answer to solve this issue. Thank you guys
