### ISSUE TITLE
Unwanted line (white? color) on Android between Handle component and content

### ISSUE THREAD

**Issue by ferrannp** [gorhom/react-native-bottom-sheet#159]
# Bug

Not sure where it comes from but happens on Android and not iOS. See iOS vs Android:

![Screenshot 2021-01-06 at 21 05 20](https://user-images.githubusercontent.com/774577/103815094-2359bc80-5063-11eb-8a6a-1b3d45c1f0ea.png) ![Screenshot 2021-01-06 at 21 06 58](https://user-images.githubusercontent.com/774577/103815101-25bc1680-5063-11eb-9049-a02b3b5d47fa.png)

Also when moving the sheet, that line flickers.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.6.1   |

## Steps To Reproduce & Sample code

I want to change the color of the sheet so I have a custom Handle (it doesn't have style props, right?): 

<details>
  <summary>Handle code</summary>
  
  ```
  const BottomSheetHandle = () => {
  const { colors } = useTheme();

  return (
    <View
      style={[
        styles.container,
        {
          backgroundColor: colors.bottomSheetBackground,
          shadowColor: colors.bottomSheetShadow,
        },
      ]}
    >
      <View
        style={[
          styles.indicator,
          { backgroundColor: colors.bottomSheetHandle },
        ]}
      />
    </View>
  );
};

export const styles = StyleSheet.create({
  container: {
    height: 24,
    padding: 10,
    shadowOffset: {
      width: 0,
      height: -5,
    },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 16,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },

  indicator: {
    alignSelf: 'center',
    width: (7.5 * width) / 100,
    height: 4,
    borderRadius: 4,
  },
});
```
</details>

<details>
  <summary>BottomSheet code:</summary>
  
  ```
      <BottomSheet
        index={0}
        snapPoints={snapPoints}
        handleComponent={BottomSheetHandle}
        handleHeight={24}
      >
        <View
          style={[
            styles.sheetContainer,
            { backgroundColor: colors.bottomSheetBackground },
          ]}
        >
          {children}
        </View>
      </BottomSheet>
      
      
      // Styles:
        sheetContainer: {
          flex: 1,
          alignItems: 'center',
      },
```
</details>

**Comment by gorhom** [comment]
hi @ferrannp thanks for submitting this issue, this is a known issue on Android, that's why i added `backgroundComponent` prop to wrap both the handle and the content. give it a try and let me know 👍

**Comment by ferrannp** [comment]
Hey @gorhom, thanks for your prompt response! Looks like that this:

```js
        backgroundComponent={() => (
          <View
            style={{
              ...StyleSheet.absoluteFillObject,
              backgroundColor: 'black'
              borderTopLeftRadius: 14,
              borderTopRightRadius: 14,
            }}
          />
        )}
```

Makes it work on Android (need to add `borderTopLeftRadius` and `borderTopRightRadius` like the Handle). However, I need to remove `elevation` from the Handle to make it look good. Any other way to add a top shadow (Handle) on Android?

**Comment by gorhom** [comment]
i would advice to add the shadow to the background too

**Comment by ferrannp** [comment]
But shadow does not work on Android, right? (needs to be `elevation`...). Unless you use something as svg I guess? Anyway, I found a bit difficult to change the background colors of the whole sheet checking the docs 😄 . But thank you for your answers! I guess we can close the issue.
