### ISSUE TITLE
using dynamic snapPoints there is a glitch in the bottom

### ISSUE THREAD

**Issue by Piero87** [gorhom/react-native-bottom-sheet#160]
Hello again :D,
I'm trying to use dynamic snapPoints connected to a state, this is the code:

```
  constructor(props) {
    super(props);
    this.state = {
      snapPoints: [0, 310]
    };
  }
```

this is the Bottom Sheet component:

```
      <BottomSheet
        ref={this.bottomSheetRef}
        index={-1}
        snapPoints={this.state.snapPoints}
        backdropComponent={BottomSheetBackdrop}
      >
       ...
     </BottomSheet>
```

Then on the click you will see in the video attached I do this:

```
      this.setState({
        snapPoints: [0, 510]
      });
```

or this:

```
      this.setState({
        snapPoints: [0, 430]
      });
```

or this:

```
      this.setState({
        snapPoints: [0, 310]
      });
```

And when the BottomSheet move to [0, 310] snapPoints make a glitch on the bottom:

https://user-images.githubusercontent.com/768952/103819370-9155b200-506a-11eb-9ba9-d94616ed5e4a.mov

I was afraid it was a fault of some of my components so I try a more clean and do the same:

https://user-images.githubusercontent.com/768952/103819421-ad595380-506a-11eb-9ee1-a7e1bcc8daa5.mov

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0  |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.9.0   |

**Comment by gorhom** [comment]
try to set the `backgroundComponent` with `bottom: -100`

**Comment by Piero87** [comment]
@gorhom I have tried but I don't see any difference, can you give me an example?

**Comment by gorhom** [comment]
@Piero87 okay I'll prepare something later 👍

**Comment by Piero87** [comment]
thank you 🙏

**Comment by Piero87** [comment]
@gorhom have you closed because it's fixed?

**Comment by gorhom** [comment]
this should be resolved with `3.1.0` & `2.0.3` 👍

**Comment by Piero87** [comment]
@gorhom Yes it's fixed, thank you.
I take this opportunity to ask you something else about the snapPoint field, I have a button in the bottom of the sheets, that have this styles:

```
  base: {
    position: 'absolute',
    bottom: 0,
    width: Dimensions.get('window'),
    height: 80,
  },
```

And this is where I insert it:

```
      <BottomSheet
        ref={this.bottomSheetRef}
        index={-1}
        snapPoints={snapPoints}
        onChange={this.onBottomSheetChange}
        backdropComponent={BottomSheetBackdrop}
>
<ButtonFullScreen />
</BottomSheet>
```

And when I change the snapPoints from the higher to the lowest value:

https://user-images.githubusercontent.com/768952/104250777-9fdb0980-546e-11eb-961b-bcc7d0743358.mov

As you can see goes up and then return in position, you know how can I fix this?

**Comment by iamnafri** [comment]
> @gorhom Yes it's fixed, thank you. I take this opportunity to ask you something else about the snapPoint field, I have a button in the bottom of the sheets, that have this styles:
> 
> ```
>   base: {
>     position: 'absolute',
>     bottom: 0,
>     width: Dimensions.get('window'),
>     height: 80,
>   },
> ```
> 
> And this is where I insert it:
> 
> ```
>       <BottomSheet
>         ref={this.bottomSheetRef}
>         index={-1}
>         snapPoints={snapPoints}
>         onChange={this.onBottomSheetChange}
>         backdropComponent={BottomSheetBackdrop}
> >
> <ButtonFullScreen />
> </BottomSheet>
> ```
> 
> And when I change the snapPoints from the higher to the lowest value:
> Registrazione.schermo.2021-01-12.alle.00.39.02.mov
> 
> As you can see goes up and then return in position, you know how can I fix this?

@Piero87 did you find a solution regarding this?
I faced the same issue in v4.
