### ISSUE TITLE
Bottom sheet only opens sometimes

### ISSUE THREAD

**Issue by theianjohnson** [gorhom/react-native-bottom-sheet#161]
# Bug

Using with Expo 40, and just repro'd with the latest `"@gorhom/bottom-sheet": "^2.0.2"` on a real Android device using the Expo app.

I can't nail down what's causing this, but the bottom sheet will only open sometimes (see console output screenshot below). On load it's open correctly, but if I swipe down to close it, then it only opens seemingly randomly when the `onPress={openPostActions}` is pressed.

![image](https://user-images.githubusercontent.com/4634364/103841738-23e55980-5049-11eb-9e80-1993fa58ca79.png)

Method
```
const postActions = useRef<BottomSheet>(null);
const openPostActions = () => {
	console.log('openPostActions()');
	postActions.current.snapTo(1);
};
```

Bottom sheet
```
<BottomSheet
	ref={postActions}
	index={1}
	snapPoints={[0, '25%']}
	onChange={handleSheetChanges}
>
	<View style={styles.contentContainer}>
		<Text onPress={reportPost} style={styles.postActionsText}>Report Post</Text>
		<View style={{ backgroundColor: 'black', borderTop: 1, opacity: .15, height: 1,}} />
		<Text onPress={deletePost} style={[styles.postActionsText, styles.postActionsTextDanger]}>Delete Post</Text>
	</View>
</BottomSheet>
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         |2.0.2   |
| react-native                    | https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz   |
| react-native-reanimated         | 2.0.0-rc.1   |
| react-native-gesture-handler    | 1.9.0   |

**Comment by gorhom** [comment]
@theianjohnson thanks for submitting this issue, i have tried to reproduce it but it seems working fine 


https://user-images.githubusercontent.com/4061838/104104869-ea138d80-52aa-11eb-9a2b-b7ed7d24c822.mp4

**Comment by theianjohnson** [comment]
@gorhom Is there an Expo snack or something I can look at? I still can't get it to open consistently and while I'm sure it's something on my end I just cannot figure out what

**Comment by theianjohnson** [comment]
Sorry actually I think it was because I meant to be using your v3, not v2 since I was using it with Reanimated v2

**Comment by theianjohnson** [comment]
I may've found something, I downgraded to your v2 and Reanimated 1 and I can repro this. Without `useMemo` it won't open, even though in your documentation you have an example of not using it, which is what I was doing

https://gorhom.github.io/react-native-bottom-sheet/props

ie.

Does not work
```
snapPoints={[0, '25%']}
```

Does work
```
const snapPoints = useMemo(() => [0, '25%'], []);
// ...
snapPoints={snapPoints}
```

**Comment by gorhom** [comment]
good finding , i think it is important to provide a memoized variables to prevent unwanted side effects, i will need to update the docs to mention it 👍

**Comment by majirosstefan** [comment]
Still happening. I need to tap 2 times to open bottomsheet. Please see recording: 

https://github.com/gorhom/react-native-bottom-sheet/assets/44647381/0056d3d4-55f2-4711-beb5-f2b6df688c83

I am using "@gorhom/bottom-sheet": "4.5.1",  "react-native-reanimated": "~2.8.0",  "react-native": "0.68.2",  "react-native-gesture-handler": "~2.2.1".

The recording above has been created using Storybook.

The code sample has been inspired from the documentation: 

```
const SheetSample = ({title, subtitle, renderBottomSheet, ...props}: SheetProps) => {

  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  // renders
  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button
          onPress={handlePresentModalPress}
          title="Present Modal"
          color="black"
        />
        <BottomSheetModal
          ref={bottomSheetModalRef}
          index={1}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
        >
          <View style={styles.contentContainer}>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
 }

stories.add("Empty", () => {
  return (
      <SheetSample />    
  );
});
```

**Comment by roncbird** [comment]
Hi @majirosstefan, I'm pretty new to React Native and have been tasked with implementing a bottom sheet. We use Storybooks, and I'm trying to get it to show up in Storybooks, but unfortunately, I'm not able to. I suspect it is due to `GestureHandlerRootView` not being in the right place for Storybooks. I'm not sure where to put it though. I noticed in your comment above, in the video you were able to get it working. I was wondering if you wouldn't mind share an example of how you got the Bottom Sheet to show up in Storybooks?

**Comment by tstechnik** [comment]
> Still happening. I need to tap 2 times to open bottomsheet. Please see recording:
> 
>  Screen.Recording.2023-09-18.at.2.54.32.PM.mov 
> I am using "@gorhom/bottom-sheet": "4.5.1", "react-native-reanimated": "~2.8.0", "react-native": "0.68.2", "react-native-gesture-handler": "~2.2.1".
> 
> The recording above has been created using Storybook.
> 
> The code sample has been inspired from the documentation:
> 
> ```
> const SheetSample = ({title, subtitle, renderBottomSheet, ...props}: SheetProps) => {
> 
>   const bottomSheetModalRef = useRef<BottomSheetModal>(null);
> 
>   // variables
>   const snapPoints = useMemo(() => ['25%', '50%'], []);
> 
>   // callbacks
>   const handlePresentModalPress = useCallback(() => {
>     bottomSheetModalRef.current?.present();
>   }, []);
>   const handleSheetChanges = useCallback((index: number) => {
>     console.log('handleSheetChanges', index);
>   }, []);
> 
>   // renders
>   return (
>     <BottomSheetModalProvider>
>       <View style={styles.container}>
>         <Button
>           onPress={handlePresentModalPress}
>           title="Present Modal"
>           color="black"
>         />
>         <BottomSheetModal
>           ref={bottomSheetModalRef}
>           index={1}
>           snapPoints={snapPoints}
>           onChange={handleSheetChanges}
>         >
>           <View style={styles.contentContainer}>
>             <Text>Awesome 🎉</Text>
>           </View>
>         </BottomSheetModal>
>       </View>
>     </BottomSheetModalProvider>
>   );
>  }
> 
> stories.add("Empty", () => {
>   return (
>       <SheetSample />    
>   );
> });
> ```

I have the same issue, have you find a solution? Sometimes open directly but mostly i need to press multiple time.

**Comment by tstechnik** [comment]
I have the same issue, if sometimes i need press multiple time to open bottomsheet, but what i found is, if i swipe the app and open it back then the sheet popping out.

**Comment by ffkraemer** [comment]
Same problem of double click to open BottomSheet here
