### ISSUE TITLE
[v4] | [v2] Realm get closed once BottomSheet is used

### ISSUE THREAD

**Issue by Youmir** [gorhom/react-native-bottom-sheet#1642]
# Bug
Anyone faced the same issue as I do ? 
I use Realm DB as a local db for the app and when I follow instruction and I add the bottomSheet component to my page, realm db connection fails and get closed !

"Cannot access realm that has been closed."

When I remove BottomSheet, it works fine again. I can't see what's the link between the 2, tried to read the code of bottomSheet but don't see how it blocks my local db.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.5.1  |
| react-native                    | 0.65.1  |
| react-native-reanimated         | ^2.2.1  |
| react-native-gesture-handler    | 1.10.3 |
| realm  | ^10.11.0 |

.

## Steps To Reproduce

1. Follow BottomSheet Instructions
2. Add any component to your code ( realm already set and you get data in you app from the local db ) 
3. you'll get the bug

Describe what you expected to happen:

1. To get the bottomSheet work?
2.

**Comment by cyril36** [comment]
Hello @Youmir 

I am bumping into the a similar issue with useRealm() and RealmProvider. Have you find a solution?
I am sure that it was working at one point but i have done a lot of changes in the code and my libraries version that it will be hard for me to find the bug.

The error i get is :
Error: Realm context not found.  Did you call useRealm() within a <RealmProvider/>?

But the Bottomsheet should be in the RealmProvider scope. Here is my BottomSheet code : 

BottomSheet.js
```
export default BottomSheetWithRef = React.forwardRef((props, ref) => {
  const snapPoints = useMemo(() => ["25%", "50%", "75%", "100%"], []);
  const realm = useRealm() //THis works
  console.log(realm) //THis works
  const renderBackdrop = useCallback((props) => {
    return (
      <BottomSheetBackdrop
        {...props}
        disappearsOnIndex={-1}
        appearsOnIndex={0}
      />
    );
  }, []);

  const renderChildren = (data) => {
    return React.Children.map(props.children, (child, index) => {
      return React.cloneElement(child, { key: index, bottomSheetData: data });
    });
  };

  return (
    <BottomSheetModal
      backdropComponent={renderBackdrop}
      ref={ref}
      index={!Object.is(props.index, undefined) ? props.index : 2}
      snapPoints={snapPoints}
    >
      {({ data }) => {

          const realm = useRealm() //This does not works and give me above error
          console.log(realm) //This does not works  and give me above error

        return (
          
            <View style={styles.contentContainer}>{renderChildren(data)}</View>
        );
      }}
    </BottomSheetModal>
  );
});
```

App.js
```
 const bottomSheetRef = useRef(null);

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    bottomSheetRef.current?.present();
  }, []);
  const closeModal = useCallback(() => {
    bottomSheetRef.current?.dismiss();
  }, []

<RealmProvider
   ...myConfig>
  >
      <Button OnPress={handlePresentModelPress} title='open bottomsheet'/>
      <BottomSheetWithRef ref={bottomSheetRef}>
               <MyCustomView/>
      </BottomSheetWithRef>
</RealmProvider> 
```
The following does not work inside BottomSheetModal
```
          const realm = useRealm() //This does not works and give me above error
          console.log(realm) //This does not works  and give me above error
```

I dont know if I should pass something to the <BottomSheetModal/> children to let the RealmProvider context propagated to the children


Can you help?
