### ISSUE TITLE
BottomSheetModal immediately hides itself after opening

### ISSUE THREAD

**Issue by Michael-M-Judd** [gorhom/react-native-bottom-sheet#167]
# Bug
It seems that the `BottomSheetModal` does not work in the default example. I dug into the code a little but and it seems like the `doDismiss` is being called when it's initially presented:

```
if (isMinimized.current && !isForcedDismissed.current) {
        return;
      }

      const adjustedIndex = dismissOnPanDown ? _index - 1 : _index; // This is true on initial `.present()` call - which I don't think it should, which leads to it immediately being removed
      currentIndexRef.current = _index;

      if (adjustedIndex >= 0) {
        if (_providedOnChange) {
          _providedOnChange(adjustedIndex);
        }
      } else {
        doDismiss();
      }
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.2   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce
1. Simply try and present a `BottomSheetModal` given the normal setup with a provider

Describe what you expected to happen:

1. When calling `.present()` it should open

## Reproducible sample code
The bottom sheet modal example:
https://gorhom.github.io/react-native-bottom-sheet/modal/usage

**Comment by gorhom** [comment]
hi @Michael-M-Judd, i have tested the example in the usage documentation, but i couldn't reproduce the bug 

https://user-images.githubusercontent.com/4061838/104104624-9bb1bf00-52a9-11eb-912b-f74818924782.mp4

**Comment by Michael-M-Judd** [comment]
Strange - sorry. I also tested with a blank app and it worked. Perhaps it's something todo with my react-navigation setup (i'm currently putting the modal at the screen level and provider wrapped around the app)

**Comment by gorhom** [comment]
@Michael-M-Judd please let me know if it's not working with you

**Comment by Mohamed-kassim** [comment]
@gorhom i have the same bug, i calculate the sheet height on global state setting the state with the required value
so i think that state change inside the modal on opening causes it to immediately hides itself

**Comment by FRizzonelli** [comment]
@gorhom Same issue here, onDismiss is called right after calling ref.present(). Any idea on how to workaround this?

**Comment by FRizzonelli** [comment]
@gorhom @Michael-M-Judd I found the "issue", you need to set the first snapPoints equal to 0 for modal to not disappear istantly and _dismissOnPanDown_ should be set on false! Do you think is it possible to mention it inside the doc gorhom? (I really love your work tho ❤️)

**Comment by gorhom** [comment]
@FRizzonelli could you provide a reproducible sample code so i could investigate this behaviour ? thanks :)

**Comment by yolpsoftware** [comment]
Same issue here, but only on the iPhone SE device of one of my testers. You press the button that presents the modal, but the modal never appears. In the logs, I see that `onDismiss` is called immediately after the modal is presented.

On all other devices (real or simulator) we do not have this behavior.

@gorhom Any idea how to debug this? Can I somehow see the reason why `onDismiss` is being called?

**Comment by yolpsoftware** [comment]
@gorhom still a problem. On one device (the main device of one of our testers), all the bottom modals immediately disappear. It's an iPhone SE 3rd generation.

On the iPhone SE 3rd generation simulator, everything works fine. I'm trying to get my hands on a second iPhone SE 3rd generation.

I know this is a bad bug report, but maybe you have some advice on how to debug this? Is there a way to see the reason why `onDismiss` is being called?

**Comment by peterferguson** [comment]
I experience this recently but only when `detached` & `enableDynamicSizing` are both enabled at the same time

**Comment by yolpsoftware** [comment]
@peterferguson but then it was on all devices, right?

I'm puzzled as to why my test user experiences this **always**, but I have not been able to reproduce it **once**, on all my devices and simulators.

**Comment by deKadir** [comment]
I faced this issue on my physical device. I remembered that i disabled all animations on my phone. Then i turned them on and now it works fine. I think this issue occurs when animations are disabled on phone

**Comment by trizerr** [comment]
In react-native-reanimated `3.15.0` [ReducedMotionConfig](https://docs.swmansion.com/react-native-reanimated/docs/components/ReducedMotionConfig) was added.
Basically it disables reduced motion, even if user has it enabled.
It fixed the issue for me.

**Comment by yolpsoftware** [comment]
Seeing this again, but this time it's not because of Reduce Motion.

Seemingly randomly, around 1 out of 5 times I open the modal, it animates to the snappoint, and then immediately hides itself, without an animation back to 0.

**Comment by MikaelAmborn** [comment]
For us the issue was with the GestureDetector in the BottomSheetBackdropComponent, I noticed that setting the pressBehavior to 'none' made the bug go away. So our solution was to implement our own backdrop component without the GestureDetector, wrapping the children in a Pressable inside the backdrop and handling the closing of the bottom sheet from the onPress callback.

**Comment by sharanabasappadhammur** [comment]
hello

**Comment by VinhTranHuu** [comment]
Hi @gorhom ,  I'm using BottomSheet inside a provider component. When I call .present() followed by .snapToIndex(0), the bottom sheet opens but then immediately hides. How can I fix this?
