### ISSUE TITLE
Release on npmjs.com

### ISSUE THREAD

**Issue by ghost** [gorhom/react-native-bottom-sheet#17]
# Feature Request

Could this package be released on https://www.npmjs.com?

## Why it is needed

Linting in my editor isn't handling this type of package well...

**Comment by gorhom** [comment]
hi @Nico-uncinc , this package is actually published on [NPM](https://www.npmjs.com/package/@gorhom/bottom-sheet) with types embedded,, so if you could provide more details so i could help you :)
