### ISSUE TITLE
[2.0.2] Using dismissOnPanDown={false} on BottomSheetModal prevent BottomSheetBackdrop from working properly

### ISSUE THREAD

**Issue by Nevosis** [gorhom/react-native-bottom-sheet#170]
# Bug

Title, when I use dismissOnPanDown={false}, BottomSheetBackdrop become white and un-clickable. And I have the same issue as [118](https://github.com/gorhom/react-native-bottom-sheet/issues/118) when using custom backdrop.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.2   |
| react-native                    | 16.13.1   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

1. Open BottomSheetModal with dismissOnPanDown={false} using bottomSheetModalRef.current.present()
2. See white backdrop unclickable

Describe what you expected to happen:

1. Proper backdrop working

## Reproducible sample code

`
<BottomSheetModal
      backdropComponent={BottomSheetBackdrop}
      ref={bottomSheetModalRef}
      index={0}
      snapPoints={[200]}
      handleComponent={HandleComponent}
      dismissOnPanDown={false}>
{...}
    </BottomSheetModal>
`

**Comment by gorhom** [comment]
Hi @Nevosis , looking at `BottomSheetBackdrop` props and component, you will notice that it expects at least 2 snap points, however it can be override 👇

```tsx
  const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop
        appearsOnIndex={0}
        disappearsOnIndex={-1}
        {...props}
      />
    ),
    []
  );
```
