### ISSUE TITLE
TouchableOpacity from React Native Gesture Handler doesn't work inside Modal

### ISSUE THREAD

**Issue by jerryjfwang** [gorhom/react-native-bottom-sheet#173]
# Bug

Using react-native-gesture-handler's TouchableOpacity inside BottomSheetModal doesn't work. However, react-native's Button inside BottomSheetModal does work.

https://user-images.githubusercontent.com/36211796/104091363-e76b6500-52b7-11eb-8a24-579198a35196.MP4

## Environment info

| Library                                          | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet             | ^2.0.2   |
| expo                                              |~40.0.0|
| react-native                                  | https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz  |
| react-native-reanimated             | 2.0.0-rc.0  |
| react-native-gesture-handler     | ~1.8.0  |

## Steps To Reproduce

1. expo init (basic config)
2. yarn add @gorhom/bottom-sheet react-native-reanimated@2.0.0-rc.0 react-native-gesture-handler
3. Replace App.js with the code below.

Describe what you expected to happen:

1. Touchable Opacity inside the modal should register presses

## Reproducible sample code

```
import {
  BottomSheetModal,
  BottomSheetModalProvider
} from '@gorhom/bottom-sheet';
import React, { useCallback, useRef, useState } from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';
import { TouchableOpacity } from "react-native-gesture-handler";

const App = () => {
  const [count, setCount] = useState(1)

  const bottomSheetModalRef = useRef(null);

  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);

  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button
          onPress={handlePresentModalPress}
          title="Present Modal"
          color="black"
        />
        <BottomSheetModal
          ref={bottomSheetModalRef}
          snapPoints={["50%"]}
        >
          <View style={styles.contentContainer}>
            <TouchableOpacity onPress={() => setCount(p => p + 1)}><Text style={{color: "blue", fontSize: 18}}>Increase count with Touchable Opacity</Text></TouchableOpacity>
            <Button title="increase count with RN Button" onPress={() => setCount(p => p + 1)}/>
            <Text>{count}</Text>
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: 'center',
  },
});

export default App;
```

**Comment by gorhom** [comment]
https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#pressables--touchables-are-not-working-on-android

**Comment by yfunk** [comment]
@gorhom Looking at the implementation of [Touchables](https://github.com/gorhom/react-native-bottom-sheet/blob/v3/src/components/touchables) in this library it's just a wrapper that uses RNGH Touchables on Android and falls back to the RN ones for iOS. Can you give a technical explanation on why this is necessary? Does it have something to do with the iOS only `exclusive` prop of RNGH Buttons, which the Touchables are based on? 

I don't really want to use the Touchables from this library for my buttons, because I reuse them all over the app and then it would be RN Touchables everywhere on iOS, so it would be nice to understand the underlying issue 🙂

**Comment by gorhom** [comment]
@yfunk good question , the reason why is that `Touchables` need to be deeply integrated with `Gesture Handler` components.

read more about at React Native Gesture Handler website: 

https://docs.swmansion.com/react-native-gesture-handler/docs/api/components/touchables/

**Comment by yfunk** [comment]
@gorhom I have read the Gesture Handler documentation a few times, but I was wondering why Touchables behave differently on Android and iOS when used inside Sheet Modals from this library. 

On Android the Touchables from `react-native-gesture-handler` work inside Modals, but the ones from `react-native` do not work inside Modals. On iOS it's the other way around and Touchables from `react-native` work well, but the ones from `react-native-gesture-handler` do not. Can you explain the reason why it is different?

**Comment by xotahal** [comment]
@gorhom @yfunk Hey guys, any thoughts about this?

```ts
const BottomSheetContentWrapperComponent = forwardRef<
  TapGestureHandler,
  BottomSheetContentWrapperProps
>(({ children, onGestureEvent, onHandlerStateChange }, ref) => {
  return (
    <TapGestureHandler
      ref={ref}
      enabled={false} // <-- ADDED
      maxDurationMs={1000000}
      shouldCancelWhenOutside={false}
      onGestureEvent={onGestureEvent}
      onHandlerStateChange={onHandlerStateChange}
    >
      {children}
    </TapGestureHandler>
  );
});
```

See `enabled={false}`, I understand that I disabled the handler, but everything works as expected including RN touchables (`Pressable`). Just wondering what do you guys think about providing a `prop` on `BottomSheet` that would allow us to disable it.

**Comment by gorhom** [comment]
@xotahal this been suggested with a pr, but it breaks the sheet functionality https://github.com/gorhom/react-native-bottom-sheet/pull/60#issuecomment-797089004
