### ISSUE TITLE
SectionList Example flickering when dragging handle

### ISSUE THREAD

**Issue by likern** [gorhom/react-native-bottom-sheet#178]
# Bug

When I start dragging handle on opened bottom-sheet I see bottom-sheet flickering (while I'm constantly dragging down, it jumps a little bit to up). I experienced this behaviour too in my fork.

On screen record it is a barely visible, but on a real device I can clearly see it.

I think it might be related to https://github.com/software-mansion/react-native-reanimated/issues/1610.
I tested **v3** branch with latest `903ea38d18a3012005dbaf5de608926675b41616` `chore: release v3.1.0` commit.

# Environment
Android device - Xiaomi Mi 9T Pro 
Android OS - 10

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | v3.1.0   |

https://user-images.githubusercontent.com/842306/104110612-5d88bf80-52ea-11eb-887d-864229e71ea0.mp4

**Comment by gorhom** [comment]
yeah this issue is annoying , it would be in the RN sectionlist implementation of the sticky header but not i am not 100% sure 🧐

**Comment by zaghadon** [comment]
This bug was closed due to stale, have there been any fix? Workarounds? What's up?
