### ISSUE TITLE
[v3] - gesture state cancelled when textInput is pressed

### ISSUE THREAD

**Issue by mr-moto** [gorhom/react-native-bottom-sheet#179]
# Bug
introduced in 3.0.2-alpha.0
Pressing on a TextInput will result in the content gesture state to be cancelled/state 3. If modal is dismissed while in that state, `handleOnChange` will not be called ( similar to #168 and #171 ).
Closing the keyboard via system keyboard down or keyboard return key does not change state.
Only work around for the user is to tap somewhere in the modal to put it in start then end state or drag the modal down

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.1.0   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.1   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

1. simple modal example
2. add a TextInput in the modal
3. tap on the TextInput and dismiss modal ( either by pressing the dismiss modal button or adding a backdrop and tapping that ) then try presenting modal again

Describe what you expected to happen:

1. `handleOnChange` to be called so modal is dismissed properly

**Comment by MehtaManan07** [comment]
Any updates on the issue?
I am facing the same issue and already spent more than 3 hours looking for a solution
