### ISSUE TITLE
Rewrite the library in Reanimated v2

### ISSUE THREAD

**Issue by gorhom** [gorhom/react-native-bottom-sheet#18]
# Feature Request

## Why it is needed

To utilise the power of Reanimated v2, this library will need to be partially re-written.

## Possible implementation

- Re-write `useTransition.ts`
- Utilise the new native `measure` & `scrollTo`

**Comment by sa8ab** [comment]
Yes It would be super cool to make it with reanimated2, I will be glad to help with it
