### ISSUE TITLE
[v3] modal flicker and position change when keyboard is activated

### ISSUE THREAD

**Issue by mr-moto** [gorhom/react-native-bottom-sheet#180]
# Bug
Im not able to reproduce it on the examples but happens on a fresh react native init project
Flicker and modal gets pushed up slightly when pressing on a TextInput. Happens with normal `BottomSheet` aswell but no flicker, just the sheet getting pushed up slightly.
seems to happen only on android

https://user-images.githubusercontent.com/24904987/104121155-1ce07480-52f1-11eb-9cac-472a770d8517.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.0.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.1   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

1. `npx react-native init <projectName>`
2. Follow instruction on installing v3 bottomsheet
3. add modal with text input

Describe what you expected to happen:

1. no flicker and push up of modal

## Reproducible sample code
```
//App.js
import React, {useRef} from 'react';
import {View, Button, TextInput} from 'react-native';
import {
  BottomSheetModalProvider,
  BottomSheetModal,
  BottomSheetBackdrop,
} from '@gorhom/bottom-sheet';

const App = () => {
  const bottomSheetRef = useRef(null);
  return (
    <BottomSheetModalProvider>
      <View>
        <Button
          title="OPEN MODAL"
          onPress={() => bottomSheetRef.current.present()}
        />
      </View>
      <BottomSheetModal
        ref={bottomSheetRef}
        snapPoints={['80%']}
        backdropComponent={BottomSheetBackdrop}>
        <View style={{backgroundColor: 'red'}}>
          <TextInput />
        </View>
      </BottomSheetModal>
    </BottomSheetModalProvider>
  );
};

export default App;
```

**Comment by mr-moto** [comment]
Can confirm this only happens when `windowSoftInputMode` is set to `adjustResize`. which makes sense for the position adjustment of the modal. Flicker still happens on adjustment

**Comment by gorhom** [comment]
thanks @mr-moto for reporting this, i will prepare a pr this week to handle keyboard interaction

**Comment by fabcall** [comment]
@gorhom I can confirm this issue, but it only happens in v3. In v2, it's working as expected (just pointing, since you put the v2 tag as well).

**Comment by rickyplouis** [comment]
Any update? Open to helping out if need be.

**Comment by gorhom** [comment]
@rickyplouis i have created a post in discussions to plan its implementation, please have a look and feel free to share your thoughts  

#233

**Comment by hoangtrung99** [comment]
i have same issue :((

**Comment by Janak-Nirmal** [comment]
@gorhom I believe latest update resolves this issue. I have added keyboardBehavior as **none** i.e. I don't want anything to happen if keyboard is opened or closed. I upgraded to latest version 3.6.2 but somehow flicker is still there in the component when we focus on the text input. Not able to figure out what I missed here. Can you please enlighten me ?

**Comment by davidgarra** [comment]
I solved the problem, in my case I was using react-native-reanimated 2.0.0-rc.2, I simply uninstalled it and installed version 2.0.0 

Now everything is working perfectly

**Comment by gorhom** [comment]
it should be resolved with `v4` 👍
