### ISSUE TITLE
[v3] Animated.SharedValue can't be passed to animatedIndex prop in BottomSheetModal

### ISSUE THREAD

**Issue by jerryjfwang** [gorhom/react-native-bottom-sheet#181]
# Bug

Passing an Animated.SharedValue to the animatedIndex prop of BottomSheetModal results in a "No default value" error.

![IMG_22CC29D83016-1](https://user-images.githubusercontent.com/36211796/104172430-368fd200-543f-11eb-807f-aee654ece29d.jpeg)

## Environment info

| Library                                          | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet             | ^2.0.2   |
| expo                                              |~40.0.0|
| react-native                                  | https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz  |
| react-native-reanimated             | 2.0.0-rc.0  |
| react-native-gesture-handler     | ~1.8.0  |

## Steps To Reproduce

1. expo init (basic config)
2. yarn add @gorhom/bottom-sheet react-native-reanimated@2.0.0-rc.0 react-native-gesture-handler
3. Replace App.js with the code below.

Describe what you expected to happen:

1. animatedIndex prop for BottomSheetModal should be able to handle Animated.SharedValue in react-native-reanimated v2

## Reproducible sample code

```
import {
  BottomSheetModal,
  BottomSheetModalProvider
} from '@gorhom/bottom-sheet';
import React, { useCallback, useRef } from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';
import { useSharedValue } from "react-native-reanimated";

const App = () => {
  const bottomSheetModalRef = useRef(null);

  const sharedValue = useSharedValue(0);

  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);

  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button
          onPress={handlePresentModalPress}
          title="Present Modal"
          color="black"
        />
        <BottomSheetModal
          animatedIndex={sharedValue}
          ref={bottomSheetModalRef}
          snapPoints={["50%"]}
        >
          <View style={styles.contentContainer}>
            <Text>Hello World!</Text>
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: 'center',
  },
});

export default App;
```

**Comment by gorhom** [comment]
hi @jerryjfwang , you can pass `Animated.SharedValue` only with `v3`

**Comment by jerryjfwang** [comment]
Hmmm. I'm trying to pass Animated.SharedValue right now with v3 and I'm getting a "no default value" error.

Is the right way to pass it in?

```
const sharedValue = useSharedValue(0);

<BottomSheetModal 
  animatedIndex={sharedValue}
>
...
</BottomSheetModal>
```

Also happy to submit a formal bug request as well. Thanks for the help! :)

**Comment by gorhom** [comment]
> Also happy to submit a formal bug request as well.

@jerryjfwang yes please , just updated this issue with the bug template :)

**Comment by jerryjfwang** [comment]
Updated!

**Comment by gorhom** [comment]
@jerryjfwang you are using `@gorhom/bottom-sheet@^2.0.2` that runs on Reanimated v1 , you need to use `@gorhom/bottom-sheet@^3`

**Comment by jerryjfwang** [comment]
Ah. My apologies — must’ve not copied the right installation instructions. Didn’t mean to waste your time 😅

Thank you for creating and maintaining this library!

**Comment by gorhom** [comment]
@jerryjfwang no worries, I know its a bit confusing to have two versions being maintain within the same package :) 

let me know if it's still an issue

**Comment by mgcrea** [comment]
Any chance this could still happen with up-to-date versions? I'm encountering the same error following the [CustomBackground](https://gorhom.github.io/react-native-bottom-sheet/custom-background) guide:

```
▶ cat node_modules/@gorhom/bottom-sheet/package.json | jq .version
"3.4.0"
▶ cat node_modules/react-native-reanimated/package.json | jq .version
"2.0.0"
```

I'm also encountering strange TypeScript errors:

<img width="1029" alt="Screenshot 2021-03-08 at 23 23 51" src="https://user-images.githubusercontent.com/108273/110389822-5b7e7b00-8065-11eb-9c27-bfb9741573f1.png">

<img width="606" alt="Screenshot 2021-03-08 at 23 22 34" src="https://user-images.githubusercontent.com/108273/110389697-2b36dc80-8065-11eb-9dc8-21d33ab4794e.png">

---

Edit: Fixed the error by adding `.value` to the `animatedIndex`: 

```
interpolateColors(animatedIndex, {
```

becomes

```
interpolateColors(animatedIndex.value, {
```

And it works but color never changes (index does not get updated when toggling bottom-sheet positions).
