### ISSUE TITLE
[v3] OverDrag not working if we have only one snap point

### ISSUE THREAD

**Issue by chybisov** [gorhom/react-native-bottom-sheet#184]
# Bug

OverDrag feature released in v3.1.0 produce a crash on iOS and bottomSheet disappearing behavior on Android when we have **only one** snap point and try to over drag via swipe to the bottom.

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.1.0   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.0   |
| react-native-gesture-handler    | 1.9.0   |

**Comment by gorhom** [comment]
this should be resolved with v3.1.1
