### ISSUE TITLE
[v3] Unable to resolve "../bottomSheetContentWrapper" from "node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx"

### ISSUE THREAD

**Issue by theianjohnson** [gorhom/react-native-bottom-sheet#185]
# Bug

Updating the library to the 3.1.0 and when restarting Expo I get a compile error

`Unable to resolve "../bottomSheetContentWrapper" from "node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx"`

![image](https://user-images.githubusercontent.com/4634364/104235758-4640f380-540a-11eb-91f1-a397392eae75.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.1.0   |
| react-native                    | https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz   |
| react-native-reanimated         | 2.0.0-rc.0 (FYI does your library support rc.0? That's the latest version Expo supports)   |
| react-native-gesture-handler    | 1.9.0  |

## Steps To Reproduce

1. Run `expo start`
2. See compile error

Describe what you expected to happen:

1. No compile error

**Comment by gorhom** [comment]
hi @theianjohnson could you remove the library and install it again ?

**Comment by theianjohnson** [comment]
Attempting this again and still doesn't work, although there's a different error. Does your library support rc.0? That's the latest version Expo supports

I've uninstalled and reinstalled `@gorhom/bottom-sheet` and no change

The error now is 
![image](https://user-images.githubusercontent.com/4634364/110218650-bcdcf900-7e6f-11eb-9860-1f629e535b0b.png)


| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.3.3   |
| react-native                    | https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz   |
| react-native-reanimated         | 2.0.0-rc.2  |
| react-native-gesture-handler    | 1.10.3  |

**Comment by gorhom** [comment]
hmm that's weird,, try:
- remove node_modules
- reset metro cache
