### ISSUE TITLE
How do you use this with the backdrop component?

### ISSUE THREAD

**Issue by theianjohnson** [gorhom/react-native-bottom-sheet#187]
# Feature Request

It'd be really helpful if there were more examples in the docs, ie how do I use this with the `backdropComponent`? Because this doesn't seem to work 

```
<BottomSheet
	ref={postActions}
	index={0}
	snapPoints={useMemo(() => [0, '25%'], [])}
	onChange={handleSheetChanges}
	backdropComponent={<BottomSheetBackdrop />}
>
...
</BottomSheet>
```

**Comment by Johan-dutoit** [comment]
The backdrop is used like this: `backdropComponent={BottomSheetBackdrop}`.

However, there is a bug I believe.  The backdrop is capturing all events and not bubbling up.
i.e. touches are not happening.

Repro steps
- Assign a backdrop
- Try to tap on anything (i.e. the trigger for opening the bottom sheet)
- Nothing happens

I can get around this with hot reloading
- While no backdrop assigned,  open the bottom sheet
- Assign the backdrop
- All events work as expected (while opened and closed)

**Comment by gorhom** [comment]
you could look at the default `BottomSheetBackdrop` props , you can customise it base on your usage 

https://github.com/gorhom/react-native-bottom-sheet/blob/d68aea6cf38b0c45753d15d2425fb40e542d0e00/src/components/bottomSheetBackdrop/types.d.ts#L17-L49

**Comment by Johan-dutoit** [comment]
Thanks, I ended up going with this

```js
 backdropComponent={(backdropProps) => (
        <BottomSheetBackdrop {...backdropProps} enableTouchThrough={true} />
      )}
```

Perhaps `enableTouchThrough` should be true by default?
I imagine the most common use case would want to allow users to interact with whatever is below the bottom sheet while it's closed.

**Comment by gorhom** [comment]
@Johan-dutoit true , however this backdrop also used with bottom sheet modal where it should block the view 🤷‍♂️

one thing for sure, is that i need to document this better 👍

**Comment by Johan-dutoit** [comment]
Ah, more context.
Thanks for the great lib!

**Comment by mip404** [comment]
@gorhom @Johan-dutoit  Thanks for the quick reply!

When I try set the backdrop on `v3.1.0` I get the following error:

```javascript
        backdropComponent={(backdropProps) => (
          <BottomSheetBackdrop {...backdropProps} enableTouchThrough={true} />
        )}
```

I get the following error
```typescript
TypeError: this._component.setNativeProps is not a function. (In 'this._component.setNativeProps(props)', 'this._component.setNativeProps' is undefined)
```

**Comment by gorhom** [comment]
@jbowa thanks for reporting this issue, i am waiting for this pr https://github.com/software-mansion/react-native-reanimated/pull/1606 to be releases to adopt it and resolve the issue

**Comment by mip404** [comment]
@theianjohnson Are we happy to close this? @gorhom  since `react-native-reanimated` `2.0.0-rc-2`  has been released I assume this should be rectified in the next release…

**Comment by theianjohnson** [comment]
👌

**Comment by aminesghir** [comment]
@gorhom along with the opacity, is there a way to customise the backdrop and make it blurred when the bottom sheet is open ?

**Comment by devDoubleH** [comment]
@aminesghir I agree, I don't notice any change in the backdrop when the bottomsheet is opened, I think that depending on the theme of the phone, white and black backgrounds should be placed on it.

`backdropComponent={props => (
            <BottomSheetBackdrop
              {...props}
              opacity={0.5}
              enableTouchThrough={true}
            />
          )}`

**Comment by sieta1** [comment]
> @gorhom @Johan-dutoit Thanks for the quick reply!
> 
> When I try set the backdrop on `v3.1.0` I get the following error:
> 
> ```js
>         backdropComponent={(backdropProps) => (
>           <BottomSheetBackdrop {...backdropProps} enableTouchThrough={true} />
>         )}
> ```
> 
> I get the following error
> 
> ```ts
> TypeError: this._component.setNativeProps is not a function. (In 'this._component.setNativeProps(props)', 'this._component.setNativeProps' is undefined)
> ```

This worked for me

**Comment by MoFerhat** [comment]
```
<BottomSheetModal
index={0}
snapPoints={['45%']}
backdropComponent={({ style }) => (
<View style={[style, { backgroundColor: 'rgba(0, 0, 0, 0.5)' }]} />
)}
>
```

**Comment by JerryVerhoeven** [comment]
Here's how I put it all together to get it functioning on my end:
```
backdropComponent={props => (<BottomSheetBackdrop {...props}
opacity={0.5}
enableTouchThrough={false}
appearsOnIndex={0}
disappearsOnIndex={-1}
style={[{ backgroundColor: 'rgba(0, 0, 0, 1)' }, StyleSheet.absoluteFillObject]} />)}
```

**Comment by amavictor** [comment]
> Here's how I put it all together to get it functioning on my end:
> 
> ```
> backdropComponent={props => (<BottomSheetBackdrop {...props}
> opacity={0.5}
> enableTouchThrough={false}
> appearsOnIndex={0}
> disappearsOnIndex={-1}
> style={[{ backgroundColor: 'rgba(0, 0, 0, 1)' }, StyleSheet.absoluteFillObject]} />)}
> ```

I have been struggling with the same issue too but this helps a lot.

**Comment by Michaelvons** [comment]
The sample code in their docs now explains this better
[Link to Doc with Sample Code](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetbackdrop/)

**Comment by FloErwerth** [comment]
Using an custom backdrop component using react-native-reanimated could look like the following:

```
const Backdrop = ({ animatedIndex }: BottomSheetBackdropProps) => {
	const animatedStyle = useAnimatedStyle(() => ({
		backgroundColor: yourBackgroundColor,
		position: "absolute",
		width: "100%",
		height: "100%",
		opacity: interpolate(animatedIndex.value, [-1, 0], [0, yourDesiredOpacity]),
	}));

	return <Animated.View style={animatedStyle} />;
};
```

Note: Adjust the index value if you have more then one snap point. The initial index is always -1.
