### ISSUE TITLE
Making BottomSheet unvisible

### ISSUE THREAD

**Issue by Bayramito** [gorhom/react-native-bottom-sheet#188]
Hi,

I have a horizontal `FlatList` with images. And i want each item to have it's own bottomsheet (modal or regular doesnt matter). 

here is my flatlist
```
return (
	<FlatList
		data={fakeImages}
		horizontal
		decelerationRate="fast"
		snapToInterval={IMAGE_WIDTH}
		renderItem={_renderItem}
		keyExtractor={(_, index) => index.toString()}
	/>
)
```

and here is the `_renderItem` 
```
		const _renderItem = ({ item }) => (
			<View style={{ flex: 1 }}>
		                  <TouchableOpacity
					activeOpacity={0.7}
					// onPress={() =>
					// 	props.navigation.navigate("ImageShowcase", {
					// 		source: item,
					// 		id: index,
					// 	})
					// }
					onPress={handleSheet}
				>
					<SharedElement id={`item.${index}.photo`}>
						<Image
							source={{ uri: item }}
							style={styles.image}
							resizeMode="cover"
						/>
					</SharedElement>
				</TouchableOpacity>

				<BottomSheet
					ref={footer}
					index={1}
					animateOnMount={true}
					snapPoints={snapPoints}
					dismissOnPanDown={false}
					//	onChange={handleSheetChanges}
				>
					<View style={styles.contentContainer}>
						<Text>{item.title} \</Text>
					</View>
				</BottomSheet>
			</View>
		);
```

With this way each item has its own  bottomsheet.
BUT, cannot make them toggleable unfortunately.

Here is what i did try,
firstly setted my snapPoints,
then created a toggler with `useState`
	```
```
        const snapPoints = useMemo(() => [0, "25%", "50%", "100%"], []);
	const [visible, setVisible] = useState(true);
```

and here i try to tigger the toggler but it doesnt work

	```
	const handleSheet = useCallback(() => {
			setVisible(!visible);
			if (visible) {
				footer?.current?.snapTo(0);
			} else {
				footer?.current?.close();
			}
			console.log(footer);
		}, [visible]);
```

**Comment by gorhom** [comment]
hi @Bayramito could you use the issue template, so i could help ?

**Comment by gorhom** [comment]
try to look at https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android.

let me know if you want to open this issue
