### ISSUE TITLE
Cannot programmatically `dismiss` BottomSheetModal as it keeps reopening

### ISSUE THREAD

**Issue by heejongahn** [gorhom/react-native-bottom-sheet#191]
# Bug

Hi, first of all, thanks for the great lib!

I'm trying to upgrade the lib from 1.4.1 to 2.0.3, and having trouble. It works well for the most part, except when I try to call `ref.current?.dismiss()` to programmatically dismiss the modal.

I've made a simple custom hook and am using it.

```ts
import { useRef, useCallback } from 'react';

import { BottomSheetModal } from '@gorhom/bottom-sheet';

export function useBottomSheetRef() {
  const ref = useRef<BottomSheetModal>(null);

  const handlePresent = useCallback(() => {
    ref.current?.present();
  }, []);

  const handleDismiss = useCallback(() => {
    ref.current?.dismiss();
  }, []);

  return [ref, handlePresent, handleDismiss] as const;
}
```

If I pass the `ref` to bottom sheet  try to dismiss the modal by either clicking the backdrop or scrolling the handle down, it works as expected. However, when I call `handleDismiss`, It seems like the modal immediately re-opens. For below example, I'm calling `handleDismiss` on item press:

![reopens](https://user-images.githubusercontent.com/6768840/104537202-dbd3c180-565c-11eb-824f-545dfbf23aab.gif)

I've already made sure that `handlePresent` is not being called somewhere else. I think I'm not doing anything fancy here so it's bit hard to provide anymore useful info, but If there's anything you need, please let me know!

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.3   |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 1.13.1   |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce

1. present a modal
2. try calling `ref.current?.dismiss()`

Describe what you expected to happen:

1. modal closes without re-opening

**Comment by Bayramito** [comment]
can you share your snapPoints ??

**Comment by heejongahn** [comment]
@Bayramito I'm using both percentage values (e.g. `['50%', '70%]`) and absolute values (e.g. `[364]`), the issue is reproduced in both cases.

**Comment by gorhom** [comment]
hi @heejongahn , could you share a reproducible sample code :)

**Comment by Bayramito** [comment]
did you wrapped your modal with `BottomSheetModalProvider` ?

**Comment by heejongahn** [comment]
@gorhom I think I found the reproducible path.

If your handler calling `dismiss` also triggers the rerender of the bottom sheet content, this happens. You can verify this by just adding `setCount(state => state + 1);` above [this line](https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/modal/DynamicSnapPointExample.tsx#L32).

**Comment by heejongahn** [comment]
To be more precise, I'm not sure if the condition is re-render or re-layout.

**Comment by anastely** [comment]
I facing the same issue :)
try to put `handleDismiss()` in setTimeout callback and will work well with you, something like this
`setTimeout(() => handleDismiss(), 0);`

@gorhom that's what I told u in Discord ;)

**Comment by gorhom** [comment]
sorry @heejongahn , without reproducible sample code i can't help, feel free to create another issue and provide one

**Comment by heejongahn** [comment]
@gorhom As I said, it's reproducible by adding literally one line to the example app you provided. If you need me to fork this repo and add that line, I'm happy to do that.

**Comment by Bayramito** [comment]
Just delete onChange props and set index prop carefully

**Comment by heejongahn** [comment]
I've created a new issue with repro ( #204 )
