### ISSUE TITLE
console.log leftover

### ISSUE THREAD

**Issue by efstathiosntonas** [gorhom/react-native-bottom-sheet#192]
# Bug

On this line there is a console.log leftover https://github.com/gorhom/react-native-bottom-sheet/blob/e8dd7f590d987303d3d05650e6e5c76e959bdd66/src/components/bottomSheet/BottomSheet.tsx#L554

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.3   |
| react-native                    | 0.63.4   |

**Comment by gorhom** [comment]
thanks @efstathiosntonas  for reporting this , I will get it removed later today 👍
