### ISSUE TITLE
onChange not called reliably

### ISSUE THREAD

**Issue by ayalpani** [gorhom/react-native-bottom-sheet#193]
# Bug

Hi, my onChange method is not always called, when the user swipes down. This is the code I use. In 1/10 swipes (down-swipes) handleSheetChange is not called at all. Any idea why?  

```
const snapPoints = useMemo(() => [0, '30%', '100%'], []);
```

```
const handleSheetChange = useCallback(
  (index) => {
    //console.log('handleSheetChange', {index});
    if (index === 0) {
      setIsHidden(true);
    }
  },
  [setIsHidden],
);
```

```
useEffect(() => {
  console.log('useEffect', {isHidden});
  if (isHidden) {
    sheetRef.current?.snapTo(0);
  } else {
    sheetRef.current?.snapTo(1);
  }
}, [isHidden]);
```

```
<BottomSheet
  ref={sheetRef}
  index={1}
  snapPoints={snapPoints}
  animateOnMount={true}
  onAnimate={handleSheetAnimate}
  onChange={handleSheetChange}>
  <BottomSheetScrollView style={styles.ScrollView}>
    ...
  </BottomSheetScrollView>
</BottomSheet>
```
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.1.0  |
| react-native                    | 0.63.3  |
| react-native-reanimated         | 2.0.0-alpha.8   |
| react-native-gesture-handler    | 1.8.0   |

**Comment by gorhom** [comment]
hi @ayalpani , i have tested this locally , and it seems working fine .

however notice that in you provided reproducible code that you do not set `isHidden` to `false` when the sheet extends , maybe that is the issue
