### ISSUE TITLE
[v3] animateOnMount has glitches on iPhone X/11/12 Pro/Pro Max

### ISSUE THREAD

**Issue by chybisov** [gorhom/react-native-bottom-sheet#196]
# Bug

`animateOnMount` has glitches on iPhone X/11/12 (tested on real device and emulators):

1) Sometimes it is not opening at all (can't figure out what's the cause)
2) It calculates wrong layout and does not take into account iPhone X/11/12 bottom bar (dock?).

These issues all happening only with animateOnMount and first time when we show bottom sheet, all other executions of `snapTo` works fine.

Sorry I can't provide any snack. If someone has snack with bottomSheet I can test it and write more details maybe.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.1.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.0   |
| react-native-gesture-handler    | 1.9.0   |

**Comment by gorhom** [comment]
hi @chybisov , i am testing on iPhone 11 with notch at the bottom and it works fine. could you test this issue on bare project and see if you could reproduce it

**Comment by chybisov** [comment]
@gorhom  hi, thanks, I’ll try on Monday.

**Comment by chybisov** [comment]
@gorhom I checked this and it seems I have problem with `@react-navigation/bottom-tabs` integration together with `BottomSheet`. I checked this guide https://gorhom.github.io/react-native-bottom-sheet/react-navigation-integration but it's not clear what navigators you mentioned there (all of them?) and where do I need to put insets to make it all work together. I have custom bottom tabbar without `useSafeAreaInsets` hook, but wrapped in `<SafeAreaView edges={['left', 'right', 'bottom']}>`.

Could you please help with this? Maybe there are some known pitfalls not mentioned in that guide?

**Comment by gorhom** [comment]
the integration document did not cover `bottom-tabs` navigation indeed, i will update it shortly

**Comment by chybisov** [comment]
@gorhom thank you! 😃

**Comment by chybisov** [comment]
@gorhom after updating to v3.3.0 I got an issue where bottom sheet now starts from the bottom of the screen and not from the bottom tabbar as before. I fixed this by adding bottom tabbar height to my snap points, but it would be really great to not break behavior of the bottom sheet in conjunction with bottom tabbar after each update. 😄  It would be really helpful to shed some light to how properly integrate bottom sheet with bottom tabbar navigation (@react-navigation/bottom-tabs). Thank you!

**Comment by christopher-caldwell** [comment]
This may or may not be related, but I was wondering if you know how to have the bottom sheet cover the tab bar? I tried using Portal, but wasn't able to figure it out.

![Screen Shot 2021-05-11 at 6 13 03 PM](https://user-images.githubusercontent.com/62559469/117899626-bf4f3b00-b284-11eb-9166-a277b033f93f.png)

The sheet works great, just wondering if it's possible to cover the tab bar using `@react-navigation/tab`

**Edit:** Was able to achieve this by using your portal library 🙌
