### ISSUE TITLE
MaskedView / Help with Scroll

### ISSUE THREAD

**Issue by theodelebarre** [gorhom/react-native-bottom-sheet#197]
Hi,

I am using the V2 and since the update some of my elements are now getting hidden. (See the video).
In the previous version it was showing up, maybe there's now a masked view or some style that hide elements out of the sheet. 

It would be really great to have an option to toggle that, there isn't many ways I can implement what I've made and now I can't use it anymore.

And I would need help on this :
I want to be able to scroll the flatlist horizontally without having to interfere with the drag. 
If my drag is perfectly horizontal and goes a bit downwards the bottom sheet will start to drag down and the scroll resets itself.

Sadly the props enableContentPanningGesture disable everything, it would be nice to be able to disable the drag only so we can scroll peacefully and enable it once done scrolling.

Thanks in advance for you help!

https://user-images.githubusercontent.com/12496482/104764888-4a517600-5768-11eb-83f3-e50cf15aac54.mov

**Comment by gorhom** [comment]
Unfortunately, the mask layer was needed for better layout calculation, I would advice to add the circle icon to the handle container, it is not masked.

![image](https://user-images.githubusercontent.com/4061838/104812977-5f7ce200-5806-11eb-9d37-47715b6281c2.png)

Also 

> I want to be able to scroll the flatlist horizontally without having to interfere with the drag.

https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android

**Comment by theodelebarre** [comment]
Hey @gorhom,

I've been able to achieve your advice.

It is working perfectly for the Flatlist not interfering with the drag,
as for the rest though, this is what it does when I have my FlatList inside the HandleComponent -> 

https://user-images.githubusercontent.com/12496482/104939438-b2929880-59b0-11eb-88cf-f5795d759bc2.mov

If I put back the FlatList inside the content it works perfectly but the purple view with the icon inside will hide if half closed.

I would gladly need help on that.
