### ISSUE TITLE
Remove bottom sheet handle background component

### ISSUE THREAD

**Issue by mip404** [gorhom/react-native-bottom-sheet#198]
Hey @gorhom ,

When using a custom handle, we are still showing the background component for the bottom sheet handle - therefore when we use a larger border radius we can see the background component…

![Simulator Screen Shot - iPhone 11 - 2021-01-16 at 20 03 55](https://user-images.githubusercontent.com/36777651/104807861-09924500-57da-11eb-8351-4c70ff5fdb81.png)

**Comment by gorhom** [comment]
you can provide `null` to `backgroundComponent` and it will be removed 👍

**Comment by mip404** [comment]
Ah ofcourse, thanks @gorhom

**Comment by Chris1369** [comment]
<img width="160" alt="Capture d’écran 2022-03-24 à 20 50 47" src="https://user-images.githubusercontent.com/57523018/159998641-ca7b20b9-cac4-4b8f-8f06-d587ae71edfa.png">

Hi @gorhom  , do you know how can i hide this little line please ? Thankssssss

**Comment by thanggggg1** [comment]
> <img alt="Capture d’écran 2022-03-24 à 20 50 47" width="160" src="https://user-images.githubusercontent.com/57523018/159998641-ca7b20b9-cac4-4b8f-8f06-d587ae71edfa.png">
> 
> Hi @gorhom , do you know how can i hide this little line please ? Thankssssss

do you know how to do this

**Comment by grish97** [comment]
Hi everyone. 
@jbowa you can use this prop to hide that line: `handleIndicatorStyle={{ display: "none" }}`
    
```
    <BottomSheetModal
        index={0}
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
        enablePanDownToClose={true}
        handleIndicatorStyle={{ display: "none" }}
    >
        <BottomSheetView>{props.children}</BottomSheetView>
    </BottomSheetModal>
```

**Comment by a-petrenko-muse** [comment]
@thanggggg1, @Chris1369 
You can do it like this
```
const styles = StyleSheet.create({
    headerWrapper: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'flex-end',
        borderTopRightRadius: 8,
        borderTopLeftRadius: 8,
        height: 40,
    },
    headerContainer: {
        flexDirection: 'row',
        borderTopRightRadius: 8,
        borderTopLeftRadius: 8,
        width: '100%',
        height: 24,
        backgroundColor: colors.white,
    },
    headerMiddleElement: {
        width: 48,
        height: 6,
        borderRadius: 6,
        backgroundColor: colors.bottomSheetGray,
        marginBottom: 6,
    },
    transparentBackground: {
        backgroundColor: 'transparent',
    },
})

const renderHeader = () => (
    <View style={styles.headerWrapper}>
        <View style={styles.headerMiddleElement} />
        <View style={styles.headerContainer} />
    </View>



// and add props
        <BottomSheet
            handleComponent={renderHeader}
            backgroundStyle={styles.transparentBackground}
        >
            {renderContainer()}
        </BottomSheet2>
    
```

**Comment by Michaelvons** [comment]
in the recent release, the option that works is

`handleComponent={null}
`

**Comment by behruzsultonov** [comment]
> you can provide `null` to `backgroundComponent` and it will be removed 👍

But it shows transparent background.  I want to remove whole area
