### ISSUE TITLE
Error when list is empty

### ISSUE THREAD

**Issue by tankers746** [gorhom/react-native-bottom-sheet#20]
# Bug

 When using BottomSheetFlatList with an empty list you get the following error: 
`scrollToIndex out of range: requested index 0 but maximum is -1`

![IMG_0305](https://user-images.githubusercontent.com/19326459/90733893-a8844500-e2ff-11ea-8340-e54f38b16084.PNG)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 1.1.1   |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 1.12.0   |
| react-native-gesture-handler    | 1.7.0   |

## Steps To Reproduce

1. Ensure the list is empty
2. Open the bottom sheet
3. Close the bottom sheet

## Reproducible sample code

```
import { AppRegistry, LogBox } from 'react-native';
import BottomSheet, { BottomSheetFlatList } from '@gorhom/bottom-sheet';

const App = function App() {
    return (
        <BottomSheet snapPoints={[100, 600]}>
            <BottomSheetFlatList
                contentContainerStyle={{ flexGrow: 1, backgroundColor: '#fff' }}
                data={[]}
                renderItem={() => null}
            />
        </BottomSheet>
    );
};

AppRegistry.registerComponent('App', () => App);

```

**Comment by gorhom** [comment]
@tankers746  thanks for reporting this issue ! i'll look into it today
