### ISSUE TITLE
Enable default backdrop customization.

### ISSUE THREAD

**Issue by f-ricci** [gorhom/react-native-bottom-sheet#206]
# Feature Request

Enable background color customization on the default backdrop

## Why it is needed

Most cases you don't need to make anything custom other than the background color. Copying and pasting the internal solutions doesn't seem elegant.

## Possible implementation

here
https://github.com/gorhom/react-native-bottom-sheet/blob/4451d3413de5f09d406f40e885d22baccd00241b/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx#L90

you need to swap the order in the array, thus allowing the given styles to include the backgroundColor.

### Code sample

```javascript
const containerStyle = useMemo(
    () => [
      styles.container,
      style,
      {
        opacity: animatedOpacity,
      },
    ],
    [style, animatedOpacity]
  );
```

**Comment by f-ricci** [comment]
Thanks @gorhom

**Comment by gorhom** [comment]
this should be resolved with v2.0.5 & v3.2.1 🎉

**Comment by vicolsson** [comment]
Hey @gorhom, it's not changed in V3
https://github.com/gorhom/react-native-bottom-sheet/blob/v3/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx#L86

**Comment by hanselabreu** [comment]
It's as @vicolsson said. Didn't know we had an issue for this, I had opened a discussion (#431) thinking I was doing something wrong.

**Comment by hanselabreu** [comment]
Opened #448.
