### ISSUE TITLE
Regular views in bottom sheet become unresponsive to gestures after list has been scrolled

### ISSUE THREAD

**Issue by tankers746** [gorhom/react-native-bottom-sheet#21]
# Bug

Apologies for the rapid bug reports, loving the library! 

When using a BottomSheetFlatList sandwiched between two views, the two view becomes unresponsive to gestures after the BottomSheetFlatList has been scrolled down and then up. 

I've attached a gif to demonstrate, it shows 3 scenarios:
1. Open bottom sheet, gesture down from blue area (works fine)
2. Open bottom sheet, scroll list down, gesture down from blue area (works fine)
3. Open bottom sheet, scroll list down, scroll list up slightly, gesture down from blue area (no movement)

As you can see, anything outside of the BottomSheetFlatList becomes unresponsive to gestures.
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/19326459/90761631-43881980-e316-11ea-984e-d8b0d9fdf260.gif)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 1.1.1   |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 1.12.0   |
| react-native-gesture-handler    | 1.7.0   |

## Steps To Reproduce

1. Open bottom sheet
2. Scroll down bottom sheet list 
3. Scroll up bottom sheet list (not to top)
4. Attempt to swipe down to close bottom sheet

## Reproducible sample code

```
import { AppRegistry, LogBox } from 'react-native';
import BottomSheet, { BottomSheetFlatList } from '@gorhom/bottom-sheet';

const App = function App() {
    return (
        <BottomSheet snapPoints={[100, 600]} handleComponent={() => null}>
            <View style={{ height: 100, backgroundColor: 'blue' }} />
            <BottomSheetFlatList
                contentContainerStyle={{ flexGrow: 1, backgroundColor: '#fff' }}
                data={[0, 1, 2, 3, 4, 5, 6, 7, 8]}
                renderItem={() => (
                    <View style={{ backgroundColor: 'red', height: 100, marginBottom: 20 }} />
                )}
            />
            <View style={{ height: 100, backgroundColor: 'green' }} />
        </BottomSheet>
    );
};

AppRegistry.registerComponent('App', () => App);

```

**Comment by gorhom** [comment]
nice catch ! i'll investigate this issue today, meanwhile you could put these two views as `header` & `footer` for the `BottomSheetFlatList`

**Comment by tankers746** [comment]
Cheers, unfortunately I cant use header or footer as I want the views to be static, not scroll with the list and a sticky header has the same problem as a view.
