### ISSUE TITLE
Placing an element above a bottom sheet modal

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#210]
# Bug

I'm trying to place a View with an absolute position at the bottom (bottom: 0) where the bottom sheet modals appear and regardless of the zIndex I give the View, I am unable to place it above the modal. The View **does** appear above a **regular** Bottom Sheet, but not a modal. Any idea why and how to do this?

## Environment info

"@gorhom/bottom-sheet": "^2",
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
"react-native-reanimated": "~1.13.0",
"react-native-gesture-handler": "~1.8.0",

## Steps To Reproduce

Use the pseudo code I pasted

Describe what you expected to happen:

The red line (View) at the bottom should appear above the bottom sheet modal

## Reproducible sample code

Pseudo code to illustrate:

```
<View>
  <BottomSheetModal
    ref={MyModalRef}
    name="MyModal"
    index={1}
    snapPoints={MyModalSnapPoints}
    topInset={topSafeArea}
    animatedPosition={animatedModalPosition}
    handleComponent={Handle}>
    ...
  </BottomSheetModal>
  <View style={{ position: 'absolute', left: 0, right: 0, bottom: 0, zIndex: 10000000000, }}>
    <View style={{ width: '100%', height: 5, backgroundColor: 'red' }} />
  </View>
</View>
```

**Comment by gorhom** [comment]
thanks @kickbk  for submitting this issue!

as you mentioned, this would work with the `BottomSheet` but not with `BottomSheetModal`, the reason is because the modal will be teleported to the root node that contain the `BottomSheetModalProvider`. it uses [@gorhom/portal](https://github.com/gorhom/react-native-portal) internally.

this was implemented to make sure that the sheet will be presented on top of all views as a native modal would do.

**Comment by kickbk** [comment]
Gotcha. Can you think of a way I could somehow place something above it or below it? Im trying to place a loader strip right above the react navigation bottom tabs. I suppose I could somehow create the loader in react navigation and use a global state to show it, but the loader is only used on the search screen and this solution is an overkill ugly workaround.

**Comment by gorhom** [comment]
hmm sorry i didn't get what you mean,  could you provide a simple visual of what are you trying to achieve ?

**Comment by kickbk** [comment]
![bottomSheet](https://user-images.githubusercontent.com/31323376/104959721-ae9e5080-5987-11eb-918d-a06f796f9c5b.png)
See the green loader at the bottom? I'd like it to appear while loading results right above the bottom tabs and over the modals.

**Comment by gorhom** [comment]
you can add that layer to the `BottomSheetHandle` and limit the `snapPoints` to show only the handle while its loading

**Comment by kickbk** [comment]
Mo, after playing around with this for quite a while, I came up with a pretty convenient way to address positioning requirements with your repo and react navigation. I ended up wrapping each screen in a navigator with a `withModalProvider`. Since it expects a functional component with no props, I had to move the [navigation](https://reactnavigation.org/docs/navigating-without-navigation-prop/) and [route](https://reactnavigation.org/docs/use-route/) props inside the screen components (see links). Then I was able to wrap the screen component.

Note: wrapping the screens should be handled outside the navigator or it will recreate a component every time and return errors. An example of the correct way to do this:

```
const WrappedAccountScreen = withModalProvider(AccountScreen);

export default function AccountNavigator() {
  return (
    <AccountStack.Navigator>
      <AccountStack.Screen
        name="Account"
        component={WrappedAccountScreen} // << Do not place withModalProvider(AccountScreen) here directly.
      />
    ...
```
Now placing components, such as a loader, at `bottom: 0` would place them right above the nav bar.
This is also convenient when placing the bottom sheet for multiple screens, so no need to include them in every screen, just in the provider module.

I wanted to share this solution for anyone looking to do the same.

**Comment by kickbk** [comment]
Mo, sorry for reopening this. It looks like my solution requires one last fix.
Currently, when you have a bottom sheet inside a component, if you click anywhere on the component, the bottom sheet will close. 
However, my provider is as follows:
```
import { BottomSheetModalProvider } from "@gorhom/bottom-sheet";
import React, { FC } from "react";
import { Alerts } from "./Alerts";

export const withModalProvider = (Component: FC) => () => {
  return (
    <BottomSheetModalProvider>
      <Component />
      <Alerts />
    </BottomSheetModalProvider>
  );
};
```
The `Alerts` component contains a bottom sheet. I open it by setting a global state variable which opens the sheet. Easy.
However, since the bottom sheet is not technically inside the component, but below it, it does not automatically close when one clicks outside of it.

Could you please suggest a possible solution/workaround? Maybe a an event listener attached to `BottomSheetModalProvider` which updates the global state, which in turn dismisses the sheet?

**Comment by mihkuno** [comment]
> Mo, after playing around with this for quite a while, I came up with a pretty convenient way to address positioning requirements with your repo and react navigation. I ended up wrapping each screen in a navigator with a `withModalProvider`. Since it expects a functional component with no props, I had to move the [navigation](https://reactnavigation.org/docs/navigating-without-navigation-prop/) and [route](https://reactnavigation.org/docs/use-route/) props inside the screen components (see links). Then I was able to wrap the screen component.
> 
> Note: wrapping the screens should be handled outside the navigator or it will recreate a component every time and return errors. An example of the correct way to do this:
> 
> ```
> const WrappedAccountScreen = withModalProvider(AccountScreen);
> 
> export default function AccountNavigator() {
>   return (
>     <AccountStack.Navigator>
>       <AccountStack.Screen
>         name="Account"
>         component={WrappedAccountScreen} // << Do not place withModalProvider(AccountScreen) here directly.
>       />
>     ...
> ```
> 
> Now placing components, such as a loader, at `bottom: 0` would place them right above the nav bar. This is also convenient when placing the bottom sheet for multiple screens, so no need to include them in every screen, just in the provider module.
> 
> I wanted to share this solution for anyone looking to do the same.



> Mo, after playing around with this for quite a while, I came up with a pretty convenient way to address positioning requirements with your repo and react navigation. I ended up wrapping each screen in a navigator with a `withModalProvider`. Since it expects a functional component with no props, I had to move the [navigation](https://reactnavigation.org/docs/navigating-without-navigation-prop/) and [route](https://reactnavigation.org/docs/use-route/) props inside the screen components (see links). Then I was able to wrap the screen component.
> 
> Note: wrapping the screens should be handled outside the navigator or it will recreate a component every time and return errors. An example of the correct way to do this:
> 
> ```
> const WrappedAccountScreen = withModalProvider(AccountScreen);
> 
> export default function AccountNavigator() {
>   return (
>     <AccountStack.Navigator>
>       <AccountStack.Screen
>         name="Account"
>         component={WrappedAccountScreen} // << Do not place withModalProvider(AccountScreen) here directly.
>       />
>     ...
> ```
> 
> Now placing components, such as a loader, at `bottom: 0` would place them right above the nav bar. This is also convenient when placing the bottom sheet for multiple screens, so no need to include them in every screen, just in the provider module.
> 
> I wanted to share this solution for anyone looking to do the same.

Apparently, this works if the screen switches without transition

**Comment by rebirthtobi** [comment]
@kickbk @gorhom How do we place items above the bottom sheet and make it behave like Google map bottom sheet.
