### ISSUE TITLE
TypeError: (0, _reactNativeReanimated.useSharedValue) is not a function. (In '(0, _reactNativeReanimated.useSharedValue)(0)', '(0, _reactNativeReanimated.useSharedValue)' is undefined)

### ISSUE THREAD

**Issue by herenickname** [gorhom/react-native-bottom-sheet#213]
# Bug
Running application on iPhone 12 Pro Max.

TypeError: (0, _reactNativeReanimated.useSharedValue) is not a function. (In '(0, _reactNativeReanimated.useSharedValue)(0)', '(0, _reactNativeReanimated.useSharedValue)' is undefined)

This error is located at:
    in ForwardRef
    in ForwardRef (at App.tsx:93)
    in RCTView (at View.js:34)
    in View (at App.tsx:43)
    in App (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in DevAppContainer (at AppContainer.js:121)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^3  |
| react-native                    | sdk-40.0.1  |
| react-native-reanimated         | ^2.0.0-rc.2  |
| react-native-gesture-handler    | ~1.8.0   |

## Steps To Reproduce

I tried to run example code from https://gorhom.github.io/react-native-bottom-sheet/usage

## Reproducible sample code

Just build the project based on the example code.

**Comment by herenickname** [comment]
Tested with react-native-reanimated@2.0.0-rc.1, nothing has changed.

**Comment by herenickname** [comment]
Tried to install v2, then

```
Failed building JavaScript bundle.
Unable to resolve "./hooks/useBottomSheetSpringConfigs" from "node_modules/@gorhom/bottom-sheet/src/index.ts"
```

Upd: fixed with purging the expo cache.

**Comment by tgreco** [comment]
Same error, no solution.

**Comment by gbasalo03** [comment]
same error, can't find a solution.

**Comment by gbasalo03** [comment]
![314351475_6028589137159900_4782109480969968892_n](https://user-images.githubusercontent.com/106594038/201805891-047c5dd9-87f0-4a01-a654-dc732783a9ff.jpg)

**Comment by MikePendo** [comment]
Same error
