### ISSUE TITLE
Switch inside Modal doesn't work.

### ISSUE THREAD

**Issue by sahejmaharjan** [gorhom/react-native-bottom-sheet#218]
# Bug

Switch doesn't work as expected inside BottomSheetModal maybe because of enableContentPanningGesture. I tried disabling enableContentPanningGesture and Switch kinda worked when dragging the switch button but doesn't work when pressed.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         "^2.0.4" 
| react-native                   "0.63.3"
| react-native-reanimated       "^1.13.2"
| react-native-gesture-handler   "^1.8.0"

## Steps To Reproduce
1. Create a BottomSheetModal.
2. Add Switch as a children of BottomSheetModal.
3. disable enableContentPanningGesture( which makes Switch inside BottomSheetModal work only on dragging the button doesn't work on tapping the Swtich button )

Expected:

1. Switch Button to work even on tap as well as dragging the button.

## Reproducible sample code
```
 <BottomSheetModal
        ref={bottomSheetModalRef}
        index={2}
        snapPoints={snapPoints}
        // enableContentPanningGesture={false}
        backgroundComponent={() => <View style={styles.background} />}
        onChange={() => console.log('onchange')}
        onDismiss={() => setOpenModal(false)}>
       <Switch
          trackColor={{false: '#767577', true: '#81b0ff'}}
          thumbColor={isEnabled ? '#f5dd4b' : '#f4f3f4'}
          ios_backgroundColor="#3e3e3e"
          onValueChange={toggleSwitch}
          value={isEnabled}
        />
      </BottomSheetModal>
      ```

**Comment by alessiocancian** [comment]
Use Switch from react-native-gesture-handler

**Comment by gorhom** [comment]
@sahejmaharjan please follow @alessiocancian suggestion for now, i am working on another fix but will be released later 👍

thanks @alessiocancian for helping out :)
