### ISSUE TITLE
Scrolling content makes the bottomsheet close / snap 

### ISSUE THREAD

**Issue by sandan10** [gorhom/react-native-bottom-sheet#220]
# Bug

I add a `BottomSheet` with the snapPoints [20, "50%", "90%"]. Then wrap my content in `BottomSheetScrollView`.
I expand the BottomSheet to 90% scroll the content, but when I start to scroll the content back to top the BottomSheet "closes" or snaps to closest point (it looks like.)

I was able to reproduce this in both my own code and in the example for ScrollView.
I'm not sure, but it looks like it only happens if you drag the content for a longer distance, not "short" scrolls.

It happens on Android and iOS.

https://user-images.githubusercontent.com/1405227/105365539-a8fe7000-5bfe-11eb-82af-5b57be194648.mov

## Environment info

In my app:

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.4   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.0   |
| react-native-gesture-handler    | 1.9.0   |

From example-app in repo:

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.4   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce
1. Run code or use ScrollView-example
2. Expand BottomSheet
3. Scroll content 
4. Scroll back up in a single drag-event

## Reproducible sample code

```
import React from 'react'
import { View } from 'react-native'
import BottomSheet, {
    BottomSheetScrollView,
} from '@gorhom/bottom-sheet'

const C = () => {
    return (
        <View style={{ flex: 1 }}>
            <BottomSheet snapPoints={[20, '50%', '90%']} index={1}>
                <BottomSheetScrollView>
                    <View style={{ flex: 1 }}>
                        {Array(50)
                            .fill('x')
                            .map((_, i) => {
                                return (
                                    <View
                                        key={String(i)}
                                        style={{
                                            marginBottom: 40,
                                            backgroundColor: '#cecece',
                                            height: 60,
                                        }}
                                    />
                                )
                            })}
                    </View>
                </BottomSheetScrollView>
            </BottomSheet>
        </View>
    )
}
```

**Comment by gorhom** [comment]
thanks @sandan10 for spotting and submit this issue :)

**Comment by gorhom** [comment]
this should be resolved with v2.0.5 🎉

**Comment by sandan10** [comment]
Thanks, looks like the scrolling is working now!

It also seems like there is some debug-logging going on when scrolling. Snippet of output:
```
 e {"_dispatchInstances": {"_debugHookTypes": null, "_debugID": 3444, "_debugIsCurrentlyTiming": false, 
 "_debugNeedsRemount": false, "_debugOwner": {"_debugHookTypes": null, "_debugID": 3442, "_debugIsCurrentlyTiming": 
 false, "_debugNeedsRemount": false, "_debugOwner": [FiberNode], "_debugSource": [Object], "actualDuration": 41, 
 "actualStartTime": 4773, "alternate": [FiberNode], "child": [Circular],
 ....
 ```

**Comment by gorhom** [comment]
@sandan10 i have checked the codebase , there is no left over debugging logs.

please check again and let me know.. thanks for the coffee 😇

**Comment by sandan10** [comment]
Sorry, my bad.
I had some logging on `BottomSheetScrollView#onScroll(event)` from yesterday while testing 2.0.4, but this wasn't logging anything before i updated to 2.0.5.
