### ISSUE TITLE
No default value

### ISSUE THREAD

**Issue by ghost** [gorhom/react-native-bottom-sheet#221]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.2.0  |
| react-native                    | expo 40.0.1  |
| react-native-reanimated         | 2.0.0 rc 0   |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce
I have written my code for gorhom/bottom-sheet 2.0 with reanimated 2 rc0.
I've triied to upgrade to gorhom 3.2.0 without any changes and I get errors.

First error : 
No default value 
```bash
TypeError: No default value

This error is located at:
    in CustomBackground (at BottomSheetBackgroundContainer.tsx:17)
    in BottomSheetBackgroundContainerComponent
    in BottomSheetBackgroundContainerComponent (at BottomSheet.tsx:615)
----

TypeError: undefined is not an object (evaluating 'this.map.setNativeProps')
- node_modules/react-native/Libraries/LogBox/LogBox.js:148:8 in registerError
- node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
- node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
```

Do you jave any idea ?
Thanks for your work !

**Comment by MaganAnkur** [comment]
any idea on this pls?
