### ISSUE TITLE
Upgrade 2 to 3

### ISSUE THREAD

**Issue by ghost** [gorhom/react-native-bottom-sheet#222]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.2.0  |
| react-native                    | expo 40.0.1  |
| react-native-reanimated         | 2.0.0 rc 0   |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce
I have written my code for gorhom/bottom-sheet 2.0 with reanimated 2 rc0.
I've triied to upgrade to gorhom 3.2.0 without any changes and I get errors.

First error : 
No default value 
```bash
TypeError: No default value

This error is located at:
    in CustomBackground (at BottomSheetBackgroundContainer.tsx:17)
    in BottomSheetBackgroundContainerComponent
    in BottomSheetBackgroundContainerComponent (at BottomSheet.tsx:615)
----

TypeError: undefined is not an object (evaluating 'this.map.setNativeProps')
- node_modules/react-native/Libraries/LogBox/LogBox.js:148:8 in registerError
- node_modules/react-native/Libraries/LogBox/LogBox.js:59:8 in errorImpl
- node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
```

Do you jave any idea ?
Thanks for your work !

## Reproducible sample code
```javascript
<BottomSheet
        ref={sheetRef}
        index={1}
        snapPoints={snapPoints}
        backgroundComponent={CustomBackground}
        handleComponent={Handle}
      >
        <ScrollView
          contentContainerStyle={styles.containerView}
          showsVerticalScrollIndicator={false}
        >
          <Comp />
        </ScrollView>
      </BottomSheet>
```

**Comment by gorhom** [comment]
hi @rwanito , thanks for submitting this issue.

looking at the error message `this.map.setNativeProps` the ref map does not exists on this library , could you check this out ?

**Comment by ghost** [comment]
Thanks for your reply !
I've triied with your basic example.

```javascript 
<BottomSheet ref={sheetRef} index={1} snapPoints={snapPoints}>
        <View>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
```

Now I have this : Tried to synchronously call function error
Like : 
https://github.com/software-mansion/react-native-reanimated/discussions/1571

**Comment by gorhom** [comment]
i would advice to do clean install , and check if it happens again ?

all `v3` animated methods are worklets. and it works fine on bare `/example`

**Comment by ghost** [comment]
Now, I have simply a crash without any feedback.
Maybe, it's the fact I'm using reanimated 2 rc 0 but not the last release ?

**Comment by gorhom** [comment]
@rwanito not sure, but try to update to rc2 and try again

**Comment by gorhom** [comment]
let me know if you need to re-open it
