### ISSUE TITLE
iPad/Tablet support

### ISSUE THREAD

**Issue by thupi** [gorhom/react-native-bottom-sheet#226]
# Feature Request

  This is a great package, especially due to the great support React Navigation and high performence. However, one missing feature seems to be the abilitiy to configure the BottomSheet to behave native-like on tablets and big screen devices. 
  
With native-like i mean like the following:

![image](https://user-images.githubusercontent.com/16625262/105488624-3353dc00-5cb2-11eb-8e6c-849e38eac9ed.png)

## Why it is needed

We need this feature in order to deliver a native-like experience on big screen devices. This package seems to get a lot of thing right but would benefit from having the option to configure the sheet to be contained, more like the native implementations such as in the AppStore as shown above :-)

## Possible implementation

I imagine that we could add an option to define the maxWidth and height of the sheet. That way the sheet wouldn't go all the way to the edges but stay centered. The last part would be to have some way of telling the sheet to open to the centered state. Could be achived by either just keep using the % definition or support a new method that would open the sheet to the full size.

### Code sample

Looking forward to hear what you guys think of the idea :-)

**Comment by gorhom** [comment]
duplicated #227

**Comment by SimpleCreations** [comment]
Is there any update on this? Both #226 and #227 are closed, and there seems to be nothing in the docs about iPad support.

**Comment by egorderg** [comment]
I've used this example https://gorhom.github.io/react-native-bottom-sheet/detach-modal and created a dynamic marginHorizontal value based on the layout width.

**Comment by Hesowcharov** [comment]
@egorderg  yeah me too... currently it looks like a single way to cut the width of the bottom sheet container and align it horizontally by left and right margin.

**Comment by vjanssens** [comment]
A workaround inspired by @egorderg's comment:

```ts
import { SCREEN_WIDTH } from "@gorhom/bottom-sheet";

export default function MyComponent() {
  const styles = makeStyle();

  return (
    <BottomSheet containerStyle={styles.bottomSheetContainerStyle}>
    </BottomSheet>
  );
}


const makeStyle = () => {
  let horizontalMarginBottomSheet = 0;
  if (SCREEN_WIDTH > 500) {
    horizontalMarginBottomSheet = (SCREEN_WIDTH - 500) / 2;
  }

  return StyleSheet.create({
    bottomSheetContainerStyle: {
      marginHorizontal: horizontalMarginBottomSheet,
    }
  });
};
```
