### ISSUE TITLE
iPad/Tablet - contained layout for bigger screen devices

### ISSUE THREAD

**Issue by thupi** [gorhom/react-native-bottom-sheet#227]
# Feature Request

  This is a great package, especially due to the great support React Navigation and high performence. However, one missing feature seems to be the abilitiy to configure the BottomSheet to behave native-like on tablets and big screen devices. 
  
With native-like i mean like the following:

![image](https://user-images.githubusercontent.com/16625262/105488624-3353dc00-5cb2-11eb-8e6c-849e38eac9ed.png)

## Why it is needed

We need this feature in order to deliver a native-like experience on big screen devices. This package seems to get a lot of thing right but would benefit from having the option to configure the sheet to be contained, more like the native implementations such as in the AppStore as shown above :-)

## Possible implementation

I imagine that we could add an option to define the maxWidth and height of the sheet. That way the sheet wouldn't go all the way to the edges but stay centered. The last part would be to have some way of telling the sheet to open to the centered state. Could be achived by either just keep using the % definition or support a new method that would open the sheet to the full size.

### Code sample

Not really sure which changes would be needed to achive something like this yet.

Looking forward to hear what you guys think of the idea :-)

**Comment by gorhom** [comment]
thanks @thupi for submitting this feature request ! this is indeed something we need to implement here.

currently i am busy with the keyboard handling #203 , but i would like to see others to get involve with this too
