### ISSUE TITLE
I need help with snapPoints

### ISSUE THREAD

**Issue by Bayramito** [gorhom/react-native-bottom-sheet#228]
### BUG

**Environment Info**

Library | Version
-- | --
@gorhom/bottom-sheet | 2.2.0
"react-native": "0.63.4",
react-native-reanimated | 1.13.1
react-native-gesture-handler | 1.8.0

Hi,

I need a little bit help for responsive placement of the elements.
I cannot get the same result within the different devices.

here are my snap points:

	const snapPoints = useMemo(() => [32, height / 4, height / 2, height], []);

And here is the entire bottomsheet:
### Reproducible Sample Code

                         	<BottomSheet
					ref={bottomSheet}
					index={1}
					animateOnMount={true}
					snapPoints={snapPoints}
					dismissOnPanDown={false}
					backgroundComponent={(props) => (
						<View style={{ backgroundColor: "transparent" }} />
					)}
					handleComponent={(props) => (
						<Animated.View
							onLayout={(e) => console.log(e.nativeEvent.layout)}
							style={[styles().handle, { opacity }]}
						>
							<Separator {...props} width={width / 5} />
						</Animated.View>
					)}
				>
					<Animated.View style={[styles().contentContainer, { opacity }]}>
						{/* <GoTopButton
									activeIndex={activeIndex}
									styles={styles().goTop}
									bottomSheet={bottomSheet}
								/> */}
						<BottomSheetTop item={item} navigation={navigation} />
						<BottomSheetMiddle
							item={item}
							modal={setModal}
							text={setModalText}
						/>
						<BottomSheetProductColor item={item} variant={setSelectedVariant} />
					</Animated.View>
				</BottomSheet>

i measured the handle component its 32 units.

So what I want to achieve is, to make the handle visible always then `25%`, `50%` and `100%` of height of the screen.

`height` variable comes from window height.

BUT, look what is the result at first two snap points in different devices. in IOS handle is not even visible
<img width="1533" alt="Ekran Resmi 2021-01-22 14 22 49" src="https://user-images.githubusercontent.com/44513402/105490411-68196080-5cbd-11eb-9545-e536dd045c29.png">

And this is the second snap point which is at 25% of height
<img width="1532" alt="Ekran Resmi 2021-01-22 14 06 20" src="https://user-images.githubusercontent.com/44513402/105490456-7798a980-5cbd-11eb-9664-04019deea08d.png">

**Comment by gorhom** [comment]
Hi @Bayramito , thanks for submitting this issue,

could you try to provide the `topInset` from `react-native-safe-context` and check again ?

https://gorhom.github.io/react-native-bottom-sheet/props#topinset

**Comment by Bayramito** [comment]
> Hi @Bayramito , thanks for submitting this issue,
> 
> could you try to provide the `topInset` from `react-native-safe-context` and check again ?
> 
> https://gorhom.github.io/react-native-bottom-sheet/props#topinset

thank you for response but `useSafeArea` looks deprecated. 
Tried with `useSafeAreaInsets` but got this error below..
<img width="340" alt="Ekran Resmi 2021-01-23 15 39 46" src="https://user-images.githubusercontent.com/44513402/105579776-3ffb3180-5d91-11eb-97d5-3ffa7fbbee60.png">


EDIT: I actually findout different method.  this may help you to improve the library.

1. Wrapped each level(snapPoint) with a `View` component in the bottom sheet.
2. Got `height` size `onLayout`  each of them and stored in the state with different values e.g. level1 , level2 and so on.
3. and used these values in the states to create snapPoints e.g. 
`const snapPoints = [1, level1 + 32, level1 + level2 + 3 .... ...]`

32 -> height of the handle

with that way, i managed to calculate snapPoints dynamically  based on content's height in the bottom sheeet.

### Example Code
                             //LEVEL 1
	                     	        <View
						onLayout={(event) =>
							setButtonLayout(event.nativeEvent.layout.height)
						}
					>
						<BottomSheetTop item={item} navigation={navigation} />
					</View>
                            //LEVEL 2
					<View
						onLayout={(event) =>
							setButtonLayout2(event.nativeEvent.layout.height)
						}
					>
						<BottomSheetMiddle
							item={item}
							modal={setModal}
							text={setModalText}
						/>
						<BottomSheetProductColor item={item} variant={setSelectedVariant} />
					</View>


**States**

	const [buttonLayout, setButtonLayout] = useState(0);
	const [buttonLayout2, setButtonLayout2] = useState(0);
	const bottomSheet = useRef(null);
	const snapPoints = [
		1,
		buttonLayout + 20,
		buttonLayout + buttonLayout2 + 20,
		height,
	];
