### ISSUE TITLE
Null backgroundComponent blocks ScrollView in the screen

### ISSUE THREAD

**Issue by mskri** [gorhom/react-native-bottom-sheet#232]
# Bug

Reported similar issue (#217) where `backdropComponent={BottomSheetBackdrop}` was blocking ScrollView in the screen. After updating to 3.2.1 where that issue was fixed noticed that if you have `backgroundComponent={null}` similar problem appears. Some invisible view seems to be blocking touch events to the screen.

There was no problem when using iOS simulator but testing on a real device the screen was blocked by something and ScrollView in the screen does not work.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.2.1   |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 2.0.0-rc.2   |
| react-native-gesture-handler    | 1.9.0  |

### Bottom sheet not displaying properly

When using following props bottom sheet displays nothing when it is expanded

```
<ScrollView>
    <Button title="Expand" onPress={() => ref.current?.expand()} />
    ...
</ScrollView>
<BottomSheet
    ref={ref}
    index={0}
    snapPoints={[0, '50%']}
    backgroundComponent={null}>
        <Text>test<Text>
</BottomSheet>
```

1. Create a bottom sheet without background component by using `backgroundComponent={null}`
2. You cannot scroll the`ScrollView` in the screen. Seems like there is some invisible view blocking touch events to the screen.

Describe what you expected to happen:

Bottom sheet does not prevent use of ScrollView in the screen.

## Reproducible sample code

See above section for the used props.

**Comment by gorhom** [comment]
hi @mskri , thanks for submitting this issue.

I have tried to reproduce the issue, but i couldn't 



https://user-images.githubusercontent.com/4061838/105749678-09194d00-5f44-11eb-9cfc-19a85344e4ff.mp4

**Comment by gorhom** [comment]
let me know if the issue still exists

**Comment by jparkrr** [comment]
No action needed, but in case it helps someone else:

A similar thing was happening to me, including the fact that it worked fine on the simulator, but not a real ios device. The sheet could only be expanded using the handle, but not by dragging a BottomSheetScrollView. It was fixed when I upgraded to expo sdk 42 (therefore upgrading reanimated and gesture-handler).

**Comment by praisedavid787** [comment]
Still very much exists guys. On the screen where I have it rendered, there's a ScrollView and when I render the backdrop component it blocks touch events on the ScrollView.

```javascript
   <BottomSheet
      // backdropComponent={renderBackdrop}
      onChange={handleSheetChanges}
      ...
```
Commenting it out restores response.
Experienced on Android Emulator

"@gorhom/bottom-sheet": "^4.4.5",
"react-native-gesture-handler": "^2.8.0",
"react-native-reanimated": "^2.13.0",
