### ISSUE TITLE
BottomSheetModalProvider crashing in some circumstances when dismissing a modal

### ISSUE THREAD

**Issue by alessiocancian** [gorhom/react-native-bottom-sheet#240]
# Bug

`null is not an object (evaluating 'sheetsQueueRef.current[sheetsQueueRef.current.length - 1].ref.current.restore')` when calling `bottomSheetModalRef.dismiss()`.
It happens when the modal is somehow unmounted before the animation ends (in my case because the page is unmounted from the stack of react-navigation), so 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.5   |
| react-native                    | 0.63.4  |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

To reproduce the bug you need to unmount the page containing the modal before the animation ends, so that ModalProvider will use a null ref.
I tried to add a setTimeout of 1 second (so the animation ends) before unmounting the page (before calling `navigation.goBack()`) and everything works fine, so I think that the modal gets removed from sheetsQueue only when animation ends.

I tested with ref.dismiss() and dismiss and dismissAll from `useSheetModal()` and it always crashes in the same way:
1. open the modal
2. dismiss the modal and unmount the page containing it (navigation.goBack) before animation ends
3. open another modal
4. when trying to dismiss it (even with drag down) I get the error because bottomSheetModalProvider tries to restore the modal which was unmounted in step 2

## Reproducible sample code

I can't provide it right now but I will add it later if you really need it

**Comment by gorhom** [comment]
this should be resolved with #205

**Comment by alessiocancian** [comment]
Thanks for the quick response, I tested the pr but it crashes on `.minimize()` when opening the modal at step 3 now.

**Comment by gorhom** [comment]
this should be fixed with `v2.0.7` 🎉
