### ISSUE TITLE
[V2] Bottomsheet close on outside clicks 

### ISSUE THREAD

**Issue by rosshabe** [gorhom/react-native-bottom-sheet#243]
Hi @gorhom  how to prevent the bottom sheet from closing every time if press on Backdrop or outside the Bottom Sheet 
Will appreciate the advice thanks

**Comment by gorhom** [comment]
@codeGoogle have a look at `BottomSheetBackdrop` props, you will need to pass `closeOnPress` as `false` to prevent it from closing 👍

https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetBackdrop/types.d.ts

**Comment by rosshabe** [comment]
Thanks for the quick response

**Comment by Rc85** [comment]
Pressing on backdrop doesn't dismiss the BottomSheetModal for me, any idea why? Using version 2.1.0 with 1.13.2 reanimated.

My backdrop component.

```
import React, { useEffect, useMemo, useState } from 'react';
import PropTypes from 'prop-types';
import { useSelector } from 'react-redux';
import { ReduxState } from '../../types/ReduxState';
import Animated, { Extrapolate, interpolate } from 'react-native-reanimated';
import { theme } from '../../theme';
import { BottomSheetBackdropProps } from '@gorhom/bottom-sheet';
import { Pressable } from 'react-native';

export const Backdrop = (props: BottomSheetBackdropProps) => {
  const themeName = useSelector((state: ReduxState) => state.Theme.theme);

  const animatedOpacity = useMemo(
    () =>
      interpolate(props.animatedIndex, {
        inputRange: [0, 0.5],
        outputRange: [0, 0.5],
        extrapolate: Extrapolate.CLAMP
      }),
    [props.animatedIndex]
  );

  const containerStyle = useMemo(
    () => [
      props.style,
      {
        backgroundColor: theme[themeName].color.black,
        opacity: animatedOpacity
      }
    ],
    []
  );

  return <Animated.View style={containerStyle} />;
};

Backdrop.propTypes = {};

export default Backdrop;
```
Tried using BottomSheetDefaultBackdropProps as well.

I had to wrap the Animated.View with Pressable and call a dismiss props to dismiss the modal.

**Comment by achan** [comment]
@Rc85 Since you're creating your own backdrop component, you'll be responsible for dismissing the modal yourself.

If you're looking for a backdrop that'll darken the views behind it, you can use the [backdrop provided by the library](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx), which supports dismissing on tap.

**Comment by rosshabe** [comment]
@Rc85  @achan    Thanks for the attention  I have  got that one sorted out I have got another issue when I am trying to close the bottom sheet from the class  which is called the inside function component which triggers another function inside the function component the bottom sheet does not respond 
eg

const SearchBottomSheet = forwardRef((props,ref) =>{
  useImperativeHandle(ref,() => ({
  openSheet:() => {
        console.log("clicked");
  },
  closeSheet:()=>{
  bottomSheetRef.current.close();
  messageBoxSheetModal.current.close();
  console.log("Close Bottom Sheet");
  },
  afterSelectAdress:()=>{
   console.log("clicked");
   closeSearch();
  }
        }),
    )

**Comment by Vednus** [comment]
@codeGoogle it might be easier to just pass a close function to the custom sheet: 

`backdropComponent={(props) => <CustomBackdrop {...props} close={() => bottomSheetRef.current.close()} />}`

**Comment by juzerdhinoj-dimiour** [comment]
Code snippet to implement:

```
import {
  BottomSheetBackdrop,
} from "@gorhom/bottom-sheet";
...
const renderBackdrop = useCallback(
    (props) => <BottomSheetBackdrop {...props} />,
    []
  );
...
<BottomSheetModal
          ref={bottomSheetModalRef}
          index={1}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
          backdropComponent={renderBackdrop}
        >

```

> @Rc85 Since you're creating your own backdrop component, you'll be responsible for dismissing the modal yourself.
> 
> If you're looking for a backdrop that'll darken the views behind it, you can use the [backdrop provided by the library](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx), which supports dismissing on tap.

**Comment by lahfir** [comment]
**Version of Bottom Sheet Package**
"@gorhom/bottom-sheet": "4"

```
  const renderBackdrop = useCallback(
    (props) => <BottomSheetBackdrop {...props} pressBehavior={"collapse"} />,
    []
  );
```
I've used the pressBehaviour prop to collapse the bottom sheet instead of closing it

**Comment by abiblair** [comment]
I found the following worked best for me: 

```typescript
const renderBackdrop = useCallback(
    (props) => <BottomSheetBackdrop {...props} 
      disappearsOnIndex={-1}
      appearsOnIndex={0}
      onPress={hideBottomSheet}
    />,
    []
  );
``` 

This brings up the semi opaque background and allowed me to link the on press hide with my own global bottom sheet store.

**Comment by SidVermaS** [comment]
You can set pressBehavior to "none" in the BottomSheetBackdrop component.

```
 const renderBackdrop = React.useCallback(
    (props: BottomSheetBackdropProps) => (
      <BottomSheetBackdrop
        {...props}
        opacity={0.9}
        pressBehavior={feedbackBottomModalState?.pressBehavior ?? 'none'}
        appearsOnIndex={0}
        disappearsOnIndex={-1}
      />
    ),
    [],
  );
```

**Comment by MariuzM** [comment]
Looks like this works 
```
        backdropComponent={(props) => (
            <BottomSheetBackdrop {...props} onPress={() => bottomSheetRef.current?.close()} />
          )}
```
