### ISSUE TITLE
Bottomsheet [v2] i need help on how to pass props on a bottomsheet inside a class and how to call it 

### ISSUE THREAD

**Issue by rosshabe** [gorhom/react-native-bottom-sheet#245]
When i pass props gives me some errors

**Comment by rosshabe** [comment]
Hi @gorhom  First of all YOUR Components are so clean they make apps look simple and very creative that why I like using them and we make plans to ask you to help us creating custome components on near future  but i am not Senior so i am having little troubles on implementing them hence i am using straight .js an not .tsx

### **How to pass props on BackdropComponent 
and how to call a custom background inside a class**   
Eg.
               <BottomSheet
         ref={this.actionSheet}
         index={0}
         enableHandlePanningGesture={this.state.isDraggable}
         enableContentPanningGesture={true}

        >

When I call it that way it gives me errors hence I am using class


### **How to call a bottomsheet inside a class**

eg.
import BottomSheet, { BottomSheetBackdrop ,BottomSheetModal,BottomSheetBackground }  from '@gorhom/bottom-sheet';


export default class Homescreen extends Component {

   constructor(props) {
        super(props);
        this.actionSheet = React.createRef();
               }


HOW I CALL IT INSIDE FUNCTION  OF A CLASS 
this.actionSheet.current?.expand();

BUT it doesn't respond:

KIndly i need your support thanks

**Comment by gorhom** [comment]
you can use the below example 
```tsx
import React, { Component, Ref, RefObject } from 'react';
import { Button, Text, View } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const snapPoints = [0, '50%'];

class App extends Component {
  bottomSheetRef: RefObject<BottomSheet>;
  constructor(props) {
    super(props);
    this.bottomSheetRef = React.createRef();
  }

  handleOnExpandPress = () => {
    if (this.bottomSheetRef.current) {
      this.bottomSheetRef.current.expand();
    }
  };

  render() {
    return (
      <View
        style={{ flex: 1, justifyContent: 'center', alignContent: 'center' }}
      >
        <Button title="Mount" onPress={() => this.handleOnExpandPress()} />
        <BottomSheet ref={this.bottomSheetRef} snapPoints={snapPoints}>
          <Text>Class</Text>
        </BottomSheet>
      </View>
    );
  }
}

export default App;

```
