### ISSUE TITLE
[v3] Example app crashing

### ISSUE THREAD

**Issue by allenan** [gorhom/react-native-bottom-sheet#247]
# Bug

First off, thanks for building this! This is the best-looking bottom sheet library I've come across so far. I'm trying to run the v3 example app, but after building, when I select any of the examples, I get a crash with the following error:

```
Error: Requiring module "src/screens/basic/BasicExamples.tsx", which threw an exception: ReferenceError: Can't find variable: _setGlobalConsole
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.2.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.2   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

1. clone `gorham/react-native-bottom-sheet`
2. `cd example`
3.  `yarn install && npx pod-install && react-native run-ios`
4.  select "Basic Example" from the available examples
5. the app crashes

Describe what you expected to happen:

1. I'd expect to see the basic example

## Reproducible sample code

This refers to the example app included within this repo.

**Comment by gorhom** [comment]
it is a cache issue, look at https://github.com/software-mansion/react-native-reanimated/issues/1640#issuecomment-766713089
