### ISSUE TITLE
[v3] Opening bottom sheet prevents touch events

### ISSUE THREAD

**Issue by allenan** [gorhom/react-native-bottom-sheet#248]
# Bug

After opening the bottom sheet, touch events within the scrollview or flatlist do not register. Scrolling to the bottom of the sheet restores touch event functionality.

https://user-images.githubusercontent.com/792845/106369382-c4a3fd80-6305-11eb-8c89-b3a98d26d342.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.2.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.2   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

1. clone and run example app
2. select the map example
3. open the bottom sheet to its expanded position
4. tap any of the list items, the tap will not be registered
5. scroll to the bottom
6. taps will be registered again

Describe what you expected to happen:

1. Interacting with the main bottom sheet component shouldn't affect tap gestures within the sheet

## Reproducible sample code

It can be reproduced in the example app within the repo

**Comment by ArturoTorresMartinez** [comment]
I've the same problem but with outside touch events. 
Also using a map like on your last screen but cannot manipulate it.

**Comment by gorhom** [comment]
@allenan i found the bug, and it seems to be `Reanimated` one, i work on it later today

**Comment by ArturoTorresMartinez** [comment]
That would be amazing!
Thanks

**Comment by allenan** [comment]
@gorhom that's great, much appreciated 🙏

**Comment by gorhom** [comment]
this issue and the pr already been submitted to `Reanimated` repository

issue: https://github.com/software-mansion/react-native-reanimated/issues/1701 
pr: https://github.com/software-mansion/react-native-reanimated/pull/1702

**Comment by gorhom** [comment]
hi @allenan , the issue may take time to be merged in reanimated repo. so i created this patch 

create `react-native-reanimated+2.0.0-rc.3.patch` file in `patches` folder then run `npx patch-package`

```
diff --git a/node_modules/react-native-reanimated/ios/native/NativeMethods.mm b/node_modules/react-native-reanimated/ios/native/NativeMethods.mm
index 58f1e20..505dd43 100644
--- a/node_modules/react-native-reanimated/ios/native/NativeMethods.mm
+++ b/node_modules/react-native-reanimated/ios/native/NativeMethods.mm
@@ -37,14 +37,10 @@
 }
 
 
-NSString *eventDispatcherKey = @"eventDispatcher";
 void scrollTo(int scrollViewTag, RCTUIManager *uiManager, double x, double y, bool animated) {
   UIView *view = [uiManager viewForReactTag:@(scrollViewTag)];
   RCTScrollView *scrollView = (RCTScrollView *) view;
-  RCTEventDispatcher* oldEventDispatcher = [scrollView valueForKey:eventDispatcherKey];
-  [scrollView setValue:nil forKey:eventDispatcherKey];
   [scrollView scrollToOffset:(CGPoint){(CGFloat)x, (CGFloat)y} animated:animated];
-  [scrollView setValue:oldEventDispatcher forKey:eventDispatcherKey];
 }
 
 }

```

**Comment by WJimmyCook** [comment]
I tested out those changes (I was seeing the same errors) and everything works perfect now. You're a legend @gorhom

**Comment by gorhom** [comment]
@WJimmyCook glad to hear it works with yea :)

**Comment by allenan** [comment]
@gorhom working great in the example repo now! Thanks for the fix. I'm going to try updating our app from v2 to v3 now that this is fixed 👍

**Comment by gorhom** [comment]
[the pr](https://github.com/software-mansion/react-native-reanimated/pull/1702) is merged 🎉

with the next release of Reanimated, you won't have to apply the patch 👏

**Comment by gorhom** [comment]
this issue resolved with the stable release of Reanimated v2 🎉

**Comment by pynner** [comment]
Make sure to run a `pod install` after updating to Reanimated 2.0.0!
