### ISSUE TITLE
Display bottom sheet above react navigation bottom tab bar

### ISSUE THREAD

**Issue by bo3hm** [gorhom/react-native-bottom-sheet#249]
## Ask your Question

First of all thanks for the great package, I really appreciate your work. I'm currently trying to implement it in our app, and it works great on screens without a bottom tab bar, i.e the bottom tab bar of React Navigation created with `createBottomTabNavigator`.  Unfortunately on screens with the tab bar it looks like this: 

![actual](https://user-images.githubusercontent.com/5023759/106452774-a1ee2200-6488-11eb-8caa-f8b9b17aa79b.png)

Ideally the bottom sheet should be stacked above the navigation, like this.

![expected](https://user-images.githubusercontent.com/5023759/106452791-a6b2d600-6488-11eb-9bf1-8d43dabbacc9.png)

Is this currently possible or do you have any hints how to easily do this?

Sorry, if this question already came up and I've missed it, but any help would be appreciated

**Comment by ferrannp** [comment]
@bo3hm you can use https://github.com/gorhom/react-native-portal to achieve it. I did it myself too and it works.

**Comment by bo3hm** [comment]
> @bo3hm you can use https://github.com/gorhom/react-native-portal to achieve it. I did it myself too and it works.

Interesting. Thanks, I'll give it a try.

**Comment by shwetsolanki** [comment]
@ferrannp do you have any example for usage? 

FYI: I am using react-native-navigation

**Comment by gorhom** [comment]
@bo3hm you will need to use `BottomSheetModal` and add its provider to the root component of you application 👍

**Comment by mrmarktyy** [comment]
> @bo3hm you will need to use `BottomSheetModal` and add its provider to the root component of you application 👍

Would you mind provide some snippet code to solve this issue by using BottomSheetModalProvider? thank you

**Comment by kickbk** [comment]
> root component of you application

I am still unable to do this with react-navigation. The bottom tab bar is created within `<Navigation />` component which is typically placed in App.js. If you surround this component with a `BottomSheetModalProvider`, then the modal will appear from the bottom of the window, which is "below" the tab bar (not below but same point, so it covers it).
Next, you create a `<Stack.Navigator>` which contains a `<BottomTab.Navigator>`, which in turn contains `<BottomTab.Screen>` components. surrounding these with a any component is very tricky, but it's possible via a custom `tabBar` option in the `<BottomTab.Navigator>`. However, it will still have no effect since the height of the window is still 100% from the bottom.
The only point where the window height of 100% is the actual **SCREEN** height is within the `BottomTab.Screen`. There, indeed, you can surround the content with a `<BottomSheetModalProvider>`.

The problem is that you cannot share **THE SAME** `BottomSheetModal` with several screens. If you create a BottomSheet component and place it inside each screen, it will generate a new modal for each screen.
This becomes a problem when you want to trigger showing a common `BottomSheetModal` via state change, because doing something like the code below will trigger each one of the BottomSheet components:
```
useEffect(() => {
  if (alert) {
    ref.current?.present();
  }
}, [alert, ref]);
```
I experimented with adjusting the `handleOnContainerMeasureHeight` callback by passing `tabBarHeight` as an option to  `<BottomSheetModalProvider tabBarHeight={tabBarHeight}>` after [fetching it with `useBottomTabBarHeight`](https://reactnavigation.org/docs/bottom-tab-navigator/), and storing in state.
It's obviously not a great solution.

@gorhom, can think of a way to surround all screens in react navigation with a provider which will emerge from above the tab bar, or some other solution? Maybe making `BottomSheetModalProviderWrapper` aware of the bottom tab bar?

**Comment by SylarRuby** [comment]
It's an issue for me, too. To get it to work, I have to create a state for the BottomSheet then pass a renderedItem, through state, to achieve it but it's def not ideal as I'd like to use the BottomSheen component in my chosen screen.

**Comment by SylarRuby** [comment]
I get. So in your App.js you'd wrap your main stack around `BottomSheetModalProvider` then `BottomSheetModal` anywhere in your app:

App.js:

```js
[..]
<NavigationContainer>
  <BottomSheetModalProvider>
      <RootStack />   
  </BottomSheetModalProvider>
</NavigationContainer>
```

**Comment by edmondso006** [comment]
I wrote a blog post about this. Here is the link if you are interested.  
https://dev.to/edmondso006/react-native-custom-bottombar-navigation-with-bottomsheet-1ep9

**Comment by AkshayAdiga1997** [comment]
> I get. So in your App.js you'd wrap your main stack around `BottomSheetModalProvider` then `BottomSheetModal` anywhere in your app:
> 
> App.js:
> 
> ```js
> [..]
> <NavigationContainer>
>   <BottomSheetModalProvider>
>       <RootStack />   
>   </BottomSheetModalProvider>
> </NavigationContainer>
> ```

This did not work for me.

**Comment by RemyMachado** [comment]
For those of you who are still struggling, here's a concrete example without using react-native-portal, as the author of the lib stated:


> @bo3hm you will need to use `BottomSheetModal` and add its provider to the root component of you application

First, the provider:

```javascript
// App.jsx
import { BottomSheetModalProvider } from '@gorhom/bottom-sheet'


const App = () => {
  return (
    <BottomSheetModalProvider>
      <Navigation /> // this is my app entry component (react-navigation Navigator), use yours
    </BottomSheetModalProvider>
  )
}
```
```javascript
// Home.jsx
// inside any descendant component (e.g. App > BottomSheetModalProvider > Navigation > ** > Home)

import React, { useCallback, useMemo, useRef } from 'react'
import { BottomSheetModal } from '@gorhom/bottom-sheet'
import { View, Button, StyleSheet, Text } from 'react-native'

const Home = () => {
  const bottomSheetModalRef = useRef<BottomSheetModal>(null)

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], [])

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present()
  }, [])
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index)
  }, [])

  return (
    <View>
        <Button onPress={handlePresentModalPress} title="Present Modal" color="black" />
        <BottomSheetModal ref={bottomSheetModalRef} index={1} snapPoints={snapPoints} onChange={handleSheetChanges}>
          <View style={styles.contentContainer}>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});
```

The documentation needed:
- author comment: https://github.com/gorhom/react-native-bottom-sheet/issues/249#issuecomment-776284053
- API: https://gorhom.github.io/react-native-bottom-sheet/modal/usage

I'm using v4 (alpha).

**Comment by tungduonghgg123** [comment]
For those of you who expects the modal to appear right away with `index={1}` like it works with `BottomSheet`:
It won't, you have to implement: `bottomSheetModalRef.current?.present()` like that of https://github.com/gorhom/react-native-bottom-sheet/issues/249#issuecomment-906535858

**Comment by 0xknon** [comment]
> I wrote a blog post about this. Here is the link if you are interested. https://dev.to/edmondso006/react-native-custom-bottombar-navigation-with-bottomsheet-1ep9

I followed this and this solve most of the use cases. 

However, if the I need to use `useNavigation`, or other navigator depending functions or hook, inside the bottom sheet, I need the Portal under the navigator.

**Comment by nielpattin** [comment]
> I get. So in your App.js you'd wrap your main stack around `BottomSheetModalProvider` then `BottomSheetModal` anywhere in your app:
> 
> App.js:
> 
> ```js
> [..]
> <NavigationContainer>
>   <BottomSheetModalProvider>
>       <RootStack />   
>   </BottomSheetModalProvider>
> </NavigationContainer>
> ```

umm, why this have 2 unlike react ? I try this and it worked ?

**Comment by ghost** [comment]
news?

**Comment by TSB1999** [comment]
> ## Ask your Question
> First of all thanks for the great package, I really appreciate your work. I'm currently trying to implement it in our app, and it works great on screens without a bottom tab bar, i.e the bottom tab bar of React Navigation created with `createBottomTabNavigator`. Unfortunately on screens with the tab bar it looks like this:
> 
> ![actual](https://user-images.githubusercontent.com/5023759/106452774-a1ee2200-6488-11eb-8caa-f8b9b17aa79b.png)
> 
> Ideally the bottom sheet should be stacked above the navigation, like this.
> 
> ![expected](https://user-images.githubusercontent.com/5023759/106452791-a6b2d600-6488-11eb-9bf1-8d43dabbacc9.png)
> 
> Is this currently possible or do you have any hints how to easily do this?
> 
> Sorry, if this question already came up and I've missed it, but any help would be appreciated

Use higher order components on your screens

**Comment by sachin3973** [comment]
I've followed along and wrap my navigation with `<BotttomSheetModalProvider>` its showing up like it should but now it's not snapping back to bottom like it should.

**Comment by yunesuk** [comment]
> I've followed along and wrap my navigation with `<BotttomSheetModalProvider>` its showing up like it should but now it's not snapping back to bottom like it should.

same here , any solutions ??

**Comment by rizkhal** [comment]
you have any solution @YunsGeek ?

**Comment by yunesuk** [comment]
> you have any solution @YunsGeek ?

not yet :(

**Comment by bmartinezg** [comment]
My problem was that with `<BotttomSheetModalProvider>` i was using `<BottomSheet>` instead of `    <BottomSheetModal>`.

### My code working:
**App.tsx**
````
  <BottomSheetModalProvider>
      <NavigationContainer>
          <MainBottomTabs />
      </NavigationContainer>
    </BottomSheetModalProvider>
````

**Screen.tsx**
````
  <>
    <SafeAreaView style={customTheme.safeArea}>
      <Layout style={eva.style.screen}>
        <View style={eva.style.labelWrapper}>
        </View>
      </Layout>
    </SafeAreaView>
    <BottomSheetModal
      detached
      ref={bottomSheetModalRef}
      index={1}
      snapPoints={[60, "50%"]}
      onChange={handleSheetChanges}
    >
      <></>
    </BottomSheetModal>
 </>
````

**Comment by safaiyeh** [comment]
> @ferrannp do you have any example for usage?
> 
> FYI: I am using react-native-navigation

Has anyone solved this for RNN? Would the BotttomSheetModalProvider fix apply here as well?

**Comment by netojose** [comment]
> > I get. So in your App.js you'd wrap your main stack around `BottomSheetModalProvider` then `BottomSheetModal` anywhere in your app:
> > App.js:
> > ```js
> > [..]
> > <NavigationContainer>
> >   <BottomSheetModalProvider>
> >       <RootStack />   
> >   </BottomSheetModalProvider>
> > </NavigationContainer>
> > ```
> 
> umm, why this have 2 unlike react ? I try this and it worked ?

I also dont'know why this has unlikes, because this solves the problem, and this is the reason behind the bug

**Comment by ayusintyaadewi** [comment]
`<BottomSheetModalProvider>
    <Tab.Navigator>
             {/* your screen */}
    </Tab.Navigator>
</BottomSheetModalProvider>`

You should put the code like that. It works for me

**Comment by ayusintyaadewi** [comment]
`<BottomSheetModalProvider>`
    `<Tab.Navigator>`
        `{/* your tab screen */}`
    `</Tab.Navigator>`
`</BottomSheetModalProvider>`

**Comment by ayusintyaadewi** [comment]
```
</BottomSheetModalProvider>
</BottomSheetModalProvider>
```

**Comment by ayusintyaadewi** [comment]
If you combine stack and tab navigation, you can wrap `<Tab.Navigator>` with `<BottomSheetModalProvider>` like this. It works for me.

```<BottomSheetModalProvider>
    <Tab.Navigator>
        {/* your tab screen */}
    </Tab.Navigator>
</BottomSheetModalProvider>```

**Comment by ayusintyaadewi** [comment]
If you combine stack and tab navigation, you should wrap `<Tab.Navigator>` with `<BottomSheetModalProvider>` like this. It works for me.

```
<BottomSheetModalProvider>
    <Tab.Navigator>
        {/* your tab screen */}
    </Tab.Navigator>
</BottomSheetModalProvider>
```

**Comment by windcloudit** [comment]
Why close this issue? Im still stuck here. Any new solution for now? BottomSheetModalProvider not working in my case.

**Comment by windcloudit** [comment]
I got this error when I wrap "BottomSheetModalProvider" out of "NavigationContainer"

`useNavigation.tsx:19 Uncaught Error: Couldn't find a navigation object. Is your component inside NavigationContainer?`

```
 <BottomSheetModalProvider>
      <NavigationContainer>
          <MainBottomTabs />
      </NavigationContainer>
    </BottomSheetModalProvider>
```

**Comment by sanaarshed** [comment]
@bo3hm can you please tell me how you achieved it?

**Comment by faerylay** [comment]
> @bo3hm you will need to use `BottomSheetModal` and add its provider to the root component of you application 👍

Really Thanks bro

**Comment by dydent** [comment]
Is there a solution for this that does not require an "additional" navigator for the full screen modals?

**Comment by tt-mp** [comment]
> > @ferrannp do you have any example for usage?
> > FYI: I am using react-native-navigation
> 
> Has anyone solved this for RNN? Would the BotttomSheetModalProvider fix apply here as well?

Also interested in this.

**Comment by gustavosantaella** [comment]
> > > @ferrannp do you have any example for usage?
> > > FYI: I am using react-native-navigation
> > 
> > 
> > Has anyone solved this for RNN? Would the BotttomSheetModalProvider fix apply here as well?
> 
> Also interested in this.

You just to wrap your application inside provider
![image](https://user-images.githubusercontent.com/51528255/215253272-342f4356-a681-4f63-8f82-e5d96ccc50a1.png)

**Comment by kylkrie** [comment]
if I import `BottomSheetModal` like this
```import BottomSheetModal from '@gorhom/bottom-sheet';```
the bottom sheet shows below my bottom tab bar
changing the import to this
```import {BottomSheetModal} from '@gorhom/bottom-sheet';```
it shows above the bottom tab bar

**Comment by tanishapatel-zymr** [comment]
> if I import `BottomSheetModal` like this `import BottomSheetModal from '@gorhom/bottom-sheet';` the bottom sheet shows below my bottom tab bar changing the import to this `import {BottomSheetModal} from '@gorhom/bottom-sheet';` it shows above the bottom tab bar

if I import like import BottomSheetModal from '@gorhom/bottom-sheet'; 
my bottomsheet open immediately does any one know why?

**Comment by LasithaOffice** [comment]
> @bo3hm you can use https://github.com/gorhom/react-native-portal to achieve it. I did it myself too and it works.

Worked perfectly. Thanks

**Comment by jamalsoueidan** [comment]
Didnt work with BottomSheetModalProvider i played it at the root layout, at the tabs layout,everywhere, no change.

**Comment by abdrhxyii** [comment]
Why did you all closed this issue? Still couldn't find a way to fix it.!!! it gonna be 2025 in 4 days.

**Comment by bmitioglov** [comment]
you can set property called **bottomInset** on the BottomSheet or BottomSheetModal, I've set it to my bottomTab menu height and it works

<BottomSheetModal
      ref={bottomSheetRef}
      index={-1}
      snapPoints={snapPoints}
      bottomInset={bottomMenuHeight}
      onChange={(index) => console.log('BottomSheet index:', index)}
    >

**Comment by showy-arjun** [comment]
@kickbk https://stackdev.space/questions/issue-with-hamburger-button-not-functioning-properly-to-open-navigationui-navigation-drawer-in-android-devices

**Comment by enesuur** [comment]
I know this issue closed, but i come across with the same issue.
Here is how it worked for me.

import { BottomSheetModal, BottomSheetView } from '@gorhom/bottom-sheet';


     <BottomSheetModal
        ref={bottomSheetModalRef}
        index={0}
        snapPoints={snapPoints}
        enablePanDownToClose={true}
        backgroundStyle={styles.bottomSheetBackground}
      >
        <BottomSheetView style={styles.bottomSheetContent}>
          <BottomSheetView style={styles.bottomSheetContent}>
              <Text>Your content goes here...</Text>
        </BottomSheetView>
      </BottomSheetModal>

Also wrap your RootStack with BottomSheetModalProvider

You can export with the following statement:
import { BottomSheetModalProvider } from '@gorhom/bottom-sheet';

**Comment by rozhkovs** [comment]
I have issues where some screens need to be above the `ModalBottomSheet` itself. I can't place the `BottomSheetModalProvider` at the very root of the project, but it was positioned above the tab navigator. It worked quite well, but this still happens on Android 9. I'm currently thinking about how to fix this in an easy way.

**Comment by rozhkovs** [comment]
I fixed this issue with the following code:

<img width="566" alt="Image" src="https://github.com/user-attachments/assets/8e74a5c7-ab22-4249-a5f8-7b6a089a4872" />

**Comment by MrKinq** [comment]
I have the same issue using wix/react-native-navigation, already wrapped with BottomSheetModalProvider, but wix navigation works different... any solution?

**Comment by alexdieudonne** [comment]
wrapping with react native portal fixed my issue with Expo tabs router
