### ISSUE TITLE
[v3] BottomSheetBackdrop flashes on mounting

### ISSUE THREAD

**Issue by ferrannp** [gorhom/react-native-bottom-sheet#250]
# Bug

In some ocsasions (not sure if because of `react-navigation` or not), `BottomSheetBackdrop` flashes (black to transparent) the whole screen.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.2.1  |
| react-native                    | 0.63.4  |
| react-native-reanimated         | 2.0.0-rc.2   |
| react-native-gesture-handler    | 1.9.0  |

## Steps To Reproduce

Clone https://github.com/ferrannp/bottom-sheet-playground.

1. Open the app
2. She the flash
3. Reload JS
4. See the flash
5. Comment out `backdropComponent={BottomSheetBackdrop}`
6. Reload JS
7. You will not see the flash

Describe what you expected to happen:

1. `BottomSheetBackdrop` not to flash when mounting

## Reproducible sample code

https://github.com/ferrannp/bottom-sheet-playground

**Comment by gorhom** [comment]
this issue is the same as https://github.com/gorhom/react-native-bottom-sheet/pull/239 ( v2 ), working on a fix 👍

**Comment by gorhom** [comment]
could you test `v3.3.1` 👍

**Comment by sergeylaptev** [comment]
I use 3.3.1. Shadow still flickers on mount:)

**Comment by sandergo90** [comment]
+1

**Comment by Sexual** [comment]
Any update on this issue?

**Comment by gorhom** [comment]
this should be fixed with `v4` 👍
