### ISSUE TITLE
Animate on mount causing hard crash when container height changes on Android

### ISSUE THREAD

**Issue by tankers746** [gorhom/react-native-bottom-sheet#251]
# Bug

There is an issue when using the animateOnMount prop on Android. Changes to the container height cause the app to crash with a SIGABRT Abort Program. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.2.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.2   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

1. Run the example
2. Tap the "Decrease container height" button
3. App crashes

## Reproducible sample code

```
import BottomSheet from '@gorhom/bottom-sheet';
import React, { useState } from 'react';
import { AppRegistry, TouchableOpacity, Text, Dimensions } from 'react-native';

const App = function App() {
    const [containerHeight, setContainerHeight] = useState(Dimensions.get('window').height);
    return (
        <BottomSheet
            index={0}
            snapPoints={[100, 500]}
            animateOnMount
            containerHeight={containerHeight}>
            <TouchableOpacity onPress={() => setContainerHeight(height => height - 100)}>
                <Text>Decrease container height</Text>
            </TouchableOpacity>
        </BottomSheet>
    );
};

AppRegistry.registerComponent('App', () => App);

```

Cheers,
Tom

**Comment by harveyconnor** [comment]
This occurs on v2 as well
