### ISSUE TITLE
Bottom sheet stops showing when setting state in onDismiss

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#252]
# Bug

@gorhom I think I found another bug. I may be missing something, but I can't think what that may be.
I see the bottom sheet stop showing when introducing a setState in its `onDismiss` callback.

## Environment info

Using snack

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.7  |
| react-native                    | *  |
| react-native-reanimated         | ~1.13.0   |
| react-native-gesture-handler    | ~1.8.0  |

## Steps To Reproduce

Check out [this snack](https://snack.expo.io/@kickbk/bottomsheetmodal-state-issue)

Test it first. It will work just as you expect:
1. Click "Set alert state and show"
2. The bottom sheet will show
3. Minimize the bottomSheet
4. Click "Set alert state and show"
5. The bottom sheet will show again

Now, uncomment the lines I marked with `// << UNCOMMENT ME`
This will simply add a state object which will be set whenever the bottom sheet is dismissed.
Test it again.

1. Click "Set alert state and show"
2. The bottom sheet will show
3. Minimize the bottomSheet
4. Click "Set alert state and show"
**5. The bottom sheet will not show again**

## Reproducible sample code

Check out [this snack](https://snack.expo.io/@kickbk/bottomsheetmodal-state-issue)

**Comment by gorhom** [comment]
thanks @kickbk to submitting this issue, going to submit a pr shortly :)
