### ISSUE TITLE
Can't open sheet when we closed it many times

### ISSUE THREAD

**Issue by benhartouz** [gorhom/react-native-bottom-sheet#255]
# Bug - Hotfix 

Can't open sheet when we closed it many times, 

## Steps To Reproduce

https://user-images.githubusercontent.com/15239702/106518884-ca9f0780-64da-11eb-8b09-358355f4112a.mov

**Comment by jerearaujo03** [comment]
Did you solved it? I have the same problem

**Comment by benhartouz** [comment]
@jerearaujo03 yes it's fixed in the v2.1.0

**Comment by benhartouz** [comment]
@jerearaujo03 https://github.com/gorhom/react-native-bottom-sheet/pull/257
