### ISSUE TITLE
Why Are RNGH Props V3 Only

### ISSUE THREAD

**Issue by zachgibson** [gorhom/react-native-bottom-sheet#258]
## Ask your Question

Just wondering why the React Native Gesture Handler props like `waitFor` are only in version 3 as of right now? I can't use RNGH buttons because I need `waitFor`. Also this lib keeps getting better and better, good work!

**Comment by gorhom** [comment]
hi @zachgibson , actually this could be easily implemented in `v2`, and would do so once i get free or someone could help :)

**Comment by zachgibson** [comment]
I'm down to contribute this change. Just need to figure out where it goes/what it looks like. 🙂

**Comment by chybisov** [comment]
@gorhom btw these types are broken in v3. I assume they shouldn't be required.
![image](https://user-images.githubusercontent.com/18644653/107357770-2a993d80-6adb-11eb-989f-884756625aee.png)
