### ISSUE TITLE
How to use BottomSheet in a Provider wrapping the entire app

### ISSUE THREAD

**Issue by aonawale** [gorhom/react-native-bottom-sheet#259]
## Ask your Question

Firstly, thanks for this library, easy to use, and nice APIs.

I tested the BottomSheet following the example on [this page](https://gorhom.github.io/react-native-bottom-sheet/usage) and it works fine.

To avoid duplicating the BottomSheet UI code everywhere I need it and to create a common interface app-wide I created a context and provider component that wraps the BottomSheet and exposes functions to control it via a custom hook.

The bottom sheet does not work properly using the setup. There are a bunch of issues ranging from animation, wrong dynamic content size calculation amongst others.

Here is my code.

```
// App.js
const App = () => (
          <BottomSheetProvider>
              <AddPhotoScreen />
          </BottomSheetProvider>
)
```

```
// BottomSheetContext.ts
export interface BottomSheetContextValue {
  expand: (options: BottomSheetProps) => void;
  collapse: () => void;
}

export const BottomSheetContext = createContext<BottomSheetContextValue | undefined>(undefined);
```

```
// BottomSheetProvider.ts
const DEFAULT_OPTIONS: BottomSheetProps = {
  snapPoints: [0],
  index: -1,
  renderContent: () => null,
};

export const BottomSheetProvider = ({ children }: BottomSheetProviderProps) => {
  const bottomSheetRef = useRef<BottomSheet>(null);
  const [options, setOptions] = useState<BottomSheetProps>({ ...DEFAULT_OPTIONS });
  const snapPoints = useMemo(() => options.snapPoints || [], [options]);

  const collapseBottomSheet = useCallback(() => {
    bottomSheetRef.current?.collapse();
    setOptions({ ...DEFAULT_OPTIONS });
  }, []);

  const bottomSheetContext: BottomSheetContextValue = useMemo(
    () => ({
      expand: (opts: BottomSheetProps) => {
        bottomSheetRef.current?.expand();
        setOptions({ ...DEFAULT_OPTIONS, ...opts });
      },
      collapse: collapseBottomSheet,
    }),
    [collapseBottomSheet],
  );

  return (
    <BottomSheetContext.Provider value={bottomSheetContext}>
        {children} // rest of app UI
        <BottomSheet
          index={-1}
          snapPoints={snapPoints}
          ref={bottomSheetRef}
          backdropComponent={BottomSheetBackdrop}
        >
          {options.renderContent()}
        </BottomSheet>
    </BottomSheetContext.Provider>
  );
};
```

```
// useBottomSheet.js Hook
export const useBottomSheet = () => {
  const context = useContext(BottomSheetContext);
  if (context === undefined) {
    throw new Error('useBottomSheet must be used within a BottomSheetContext');
  }
  return context;
};
```

```
// AddPhotoScreen.tsx
const bottomSheet = useBottomSheet();
const [contentHeight, setContentHeight] = useState(0);
const snapPoints = useMemo(() => [0, contentHeight], [contentHeight]);

const handleOnLayout = useCallback(({ nativeEvent: { layout: { height } } }) => {
    setContentHeight(height);
  }, []);

const content = useMemo(
    () => (
      <View onLayout={handleOnLayout}>
        <Padding all={spacing[20]}>
          <Headline>Title</Headline>
          <SizedBox height={spacing[32]} />
           <Button mode="contained" title='Foo' />
           <SizedBox height={spacing[8]} />
        </Padding>
      </View>
    ),
    [handleOnLayout],
  );

const showOptions = () => bottomSheet.expand({
          renderContent: () => content,
          snapPoints: snapPoints,
        });
```

### Result - When placed in the provider

https://user-images.githubusercontent.com/10553988/106536355-90dcf980-64f8-11eb-8b40-93a1b1a34668.mov

### Result - When placed in the component, like the example in the doc.

https://user-images.githubusercontent.com/10553988/106536397-a520f680-64f8-11eb-810a-198229ca6d4f.mov

So my question is: am I doing something wrong? or the BottomSheet must be placed in every component file that wants to show it?

**Comment by SteliosKornelakis** [comment]
I was about to ask the same thing.
I use BottomSheet inside each Card Item of a Flat List. I consider this should be somewhere outside and triggered through a custom hook provided any required props. What is the correct approach?

**Comment by aonawale** [comment]
I managed to get this working by expanding the bottom sheet after rendering it. I realized I was expanding it before it gets a chance to be rendered in the UI.

Code:

```
export const BottomSheetProvider = ({ children }: BottomSheetProviderProps) => {
  const bottomSheetRef = useRef<BottomSheet>(null);
  const [options, setOptions] = useState<BottomSheetProps | null>(null);
  const snapPoints = useMemo(() => options?.snapPoints || [0], [options]);

  useEffect(() => {
    if (options) {
      bottomSheetRef.current?.expand();
    } else {
      bottomSheetRef.current?.collapse();
    }
  }, [options]);

  const collapseBottomSheet = useCallback(() => setOptions(null), []);

  const handleSheetChanges = useCallback(
    (index: number) => {
      if (index === 0) {
        collapseBottomSheet();
      }
    },
    [collapseBottomSheet],
  );

  const bottomSheetContext: BottomSheetContextValue = useMemo(
    () => ({
      expand: setOptions,
      collapse: collapseBottomSheet,
    }),
    [collapseBottomSheet],
  );

  return (
    <BottomSheetContext.Provider value={bottomSheetContext}>
      {children}

      {options && (
        <BottomSheet
          index={-1}
          snapPoints={snapPoints}
          ref={bottomSheetRef}
          handleComponent={View}
          backdropComponent={BottomSheetBackdrop}
          onChange={handleSheetChanges}
        >
          {options.children}
        </BottomSheet>
      )}
    </BottomSheetContext.Provider>
  );
};
```

**Comment by victoriomolina** [comment]
I thought exactly the same thing. I made something really similar to your first code, but cannot make it work.

The logic I am following is:

  1. Provide a method to expand the bottom sheet, which just sets a state with callback (useStateWithCallback). So, when the options of the bottom sheet are provided to the .expand method as arguments, it will open the bottom sheet with all these options previously  setted.
  2. When the bottom sheet is closed (via gesture or with the .collapse() method) set the Context provider stateful options to undefined.
 
 
But, for some reasons, this doesn’t work as expected: no transition when opening, and cannot close the bottom sheet the second time.

Also, I am checking your second solution, but think something will cause issues. You are closing the bottom sheet in a useEffect, after setting the options to undefined when closing it. Doesn’t this cause UI problems to you?

**Comment by Derewith** [comment]
The second solution pointed out by @aonawale is working but not correctly and always , sometimes it just won't open the bottom sheet. 
Does anyone has a better approach ? I was trying to handle the bottom sheet as a screen in the end and seems to be the only correct solution as [react-navigation-bottom-sheet](https://github.com/th3rdwave/react-navigation-bottom-sheet)

**Comment by noctivityinc** [comment]
@aonawale thanks for the code, but can you show the complete code including the imports?  I cant believe something like this isnt standard in the library, which is great but should allow for a single bottom sheet with dynamic content like you are doing.
