### ISSUE TITLE
BottomSheet inside a FlatList

### ISSUE THREAD

**Issue by Patrioot** [gorhom/react-native-bottom-sheet#260]
I am trying to do a horizontal  FlatList or (Carousel) that contain 3 Bottomsheets , so the user can swipe left and right bottomsheet, however whenever i try to swipe left or right the bottomsheet seems to block the gesture, and i can't swipe anymore  . Is there anyway to do this ? 

![Feb-02-2021 15-55-39](https://user-images.githubusercontent.com/72344148/106603269-231fe480-656f-11eb-9ade-64d5ed18624f.gif)

**Comment by ahmadqwer** [comment]
@Patrioot Hello, 
Did you find a solution for this?
I have a similar layout and i have the same issue.

**Comment by AMITHATHAMPY** [comment]
@Patrioot @ahmadqwer Hi,
Did you find any fix?

**Comment by ahmadqwer** [comment]
@AMITHATHAMPY Unfortunately, no.
I ended up removing the flatlists from the bottom sheets :(
