### ISSUE TITLE
Bug with adding shadow behind the botton-sheet on android 

### ISSUE THREAD

**Issue by raulk07** [gorhom/react-native-bottom-sheet#263]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.7  |
| react-native                    | 0.63.4 |
| react-native-reanimated         | 2.0.0-rc.2 |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce

1. added this shadow properties to the bottom-sheet:

`shadowColor: "#000", 
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,`

Describe what you expected to happen:

1. shadow should apply correctly behind the bottom sheet

## Reproducible sample code screenshot
![screenshot](https://user-images.githubusercontent.com/75887921/106926621-8fd2e480-6711-11eb-96a4-d856b0b5de5b.jpg)

**Comment by Karthik-B-06** [comment]
@gorhom  Facing this issue in android.

Using the bottom sheet as toast with a shadow like this

``` 
toastShadow: {
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: -20,
    },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: Platform.OS === 'ios' ? 10 : 0,
  }
```

While adding elevation to the bottom sheet, the sheet moves 10px above from the bottom of the screen. Without the elevation, there is no way to differentiate between the sheet and the rest of the screen. 
 
(https://files.slack.com/files-pri/T024FNSN4-F01PBM0KBU2/img_20210225_182034.jpg)

(https://files.slack.com/files-pri/T024FNSN4-F01PHRX27GU/img_20210225_182027.jpg)
