### ISSUE TITLE
scroll not working for nested BottomSheetFlatList in BottomSheet

### ISSUE THREAD

**Issue by t08-apporio** [gorhom/react-native-bottom-sheet#266]
# Bug
scroll not working for nested BottomSheetFlatList in BottomSheet

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.7   |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.7.0   |

## Steps To Reproduce
1.BottomSheet contains a horizontal BottomSheetFlatList
2.Each BottomSheetFlatList item contains a Pressable which contains a BottomSheetView which in-turn wraps another BottomSheetFlatList

Describe what you expected to happen:
1.The nested BottomSheetFlatList should scroll 

## Reproducible sample code
```
<BottomSheet>
   <BottomSheetFlatList
      data={data}
      renderItem={({index, item}) => <Pressable item={item}/>
      horizontal
   />
</BottomSheet>
```
```
<Pressable>
   other components...
   <BottomSheetView>
      <BottomSheetFlatList
         data={items}
         renderItem={({item}) => <Text>{item.text}</Text>}
      />
   </BottomSheetView>
</Pressable>
```

**Comment by gorhom** [comment]
hmm , could you provide a reproduce sample code that can run from `/exmple` folder ?

**Comment by t08-apporio** [comment]
@gorhom flatlist from gesture handler did the trick. Although there is another issue I've run into. Will create another issue for it. Thanks for this awesome package!!!

**Comment by Dajust** [comment]
Thanks for the gesture-handler flatlist tip @t08-apporio, worked for me too.

For me, Bottomsheet FlatList didn't even render anything because I needed it multiple levels down the BottomSheet tree: `BottomSheet > View > View > BottomSheetFlatList`. It works if rendered as a direct child, but the scrolling was really bad.

- @gorhom/bottom-sheet 2.3.0
- Expo Go

**Comment by sebastian-nowak** [comment]
Hey @Dajust, did you by any chance manage to get `BottomSheetFlatList` to work if it's not a direct child of a `BottomSheet`?

**Comment by B-Manitas** [comment]
I encountered the same issue where the scroll was not working for a nested BottomSheetFlatList inside a BottomSheet. I found that setting overdragResistanceFactor={0} resolves the problem in my case.

**Comment by shuhat36** [comment]
If you have a <BottomSheetModal> wrapper on it, please make sure `enableContentPanningGesture` remains `true`
