### ISSUE TITLE
[v3] BottomSheetScrollView not working with dynamic snapPoints

### ISSUE THREAD

**Issue by bogoslavskiy** [gorhom/react-native-bottom-sheet#270]
# Bug
Any dynamic `snapPoint` change not working with `BottomSheetScrollView`, 
During scrolling `BottomSheetModal` disappears immediately

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^3   |
| react-native                    | 0.63   |
| react-native-reanimated         | 2.0.0-rc.2   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

1. Set dynamic `snapPoints`
2. Wrap content in `BottomSheetScrollView`

Describe what you expected to happen:

1. Content height can be longer than screen height
2. If content height < screen height, `BottomSheet` must be equal to the content height

## Reproducible sample code

```js
const [contentHeight, setContentHeight] = React.useState(0);
const snapPoints = React.useMemo(() => [contentHeight], [contentHeight]);

const handleOnLayout = React.useCallback(({ nativeEvent }: LayoutChangeEvent) => {
  const { height } = nativeEvent.layout;
  setContentHeight(height);
}, []);

<BottomSheetModal 
  ref={bottomSheetRef}
  snapPoints={snapPoints}
>
  <View onLayout={handleOnLayout}>
    <BottomSheetScrollView>
      <View 
        style={{
          height: 800,
          backgroundColor: 'red'
        }}
      />
    </BottomSheetScrollView>
  </View>
</BottomSheetModal>
```

**Comment by selimxsuha** [comment]
any solution?

**Comment by cltsang** [comment]
> any solution?

https://gorhom.github.io/react-native-bottom-sheet/hooks/#usebottomsheetdynamicsnappoints

**Comment by quicksilverr** [comment]
This doesn't answer the question @cltsang

**Comment by cltsang** [comment]
It does answer the question.
Just need to follow the example closely, and replace `BottomSheetView` with `BottomSheetScrollView`.

**Comment by Hopefulee** [comment]
@cltsang  - thanks heaps. It does what i need
