### ISSUE TITLE
Bottom sheet youtube style

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-bottom-sheet#271]
# Feature Request

https://user-images.githubusercontent.com/20476002/107353181-0b93af00-6acd-11eb-8f70-bf9c0a175eca.mp4

Hi @gorhom ,

it would be possible to have an example like what you see in the video how does youtube.

1) The possibility that the bottom sheet opens under a certain component (video player).
2) The possibility of being able to scroll, if it contains elements not visible for its entire height.
3) The possibility that if I am in the scrolling part and I make a movement from top to bottom, the bottom sheet will try to close.
4) The possibility if instead I make a movement from bottom to top, by pressing in the part of the description or where the x (close) is located, it allows me to open the bottom scheet to 100% (in the meantime you can see that the color becomes darker than the one in the video part), if instead the opposite is done it becomes lighter gradually.

## Why it is needed

It would be very useful to have a similar example for future implementation.

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by gorhom** [comment]
you could implement this by yourself, i don't see it as an enhancement to add. look at the themed example https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/advanced/CustomThemeExample.tsx
