### ISSUE TITLE
How To Collapse or Snap Bottom sheet from Class component using forwardRef

### ISSUE THREAD

**Issue by rosshabe** [gorhom/react-native-bottom-sheet#272]
Hi @gorhom working on derlivery app  I am trying to call bottomsheet from class component to function component the function I have passed through  forwardRef give me longs on click but bottom sheet wont collapse of snap 

function component 
const SearchBottomSheet = forwardRef((props,ref) =>{
const bottomSheetRef = useRef(null);
.....

 useImperativeHandle(ref,() => ({
  openSheet:() => {
        console.log("clicked");
        
  },
  closeSheet:()=>{
  bottomSheetRef.current.close();
        console.log("clicked");

  },
  afterSelectAdress:()=>{
   console.log("clicked");
   closeSearch();
   
  }
        }),
    )
}

Class ref to child bottom sheet function component 
   constructor(props) {
        super(props);
           this.child = React.createRef();
                 ...

Class component function 
 selectBottomSheetClose(){
              this.child.current.closeSheet();

          }

Event when I try to call the snap event within the function component call back if I have other instruction it doest work 
if the snap event its alone  works 

eg .
  const  navigateToPickupData = React.useCallback((destinationPlaceId, destinationName, descName, pred) =>{     
                props.navigatePickup(destinationPlaceId, destinationName, descName, pred);
                setChooseRide(true)
 bottomSheetRef.current?.snapTo(1); 
               }, []);   

That don't work  below works 

  const  navigateToPickupData = React.useCallback((destinationPlaceId, destinationName, descName, pred) =>{     
               bottomSheetRef.current?.snapTo(1); 
               }, [bottomSheetRef]);   

Any ideas

**Comment by nurcinozer** [comment]
any updates on this?
