### ISSUE TITLE
Content panning gesture not working on latest version of RNGH 1.10.0

### ISSUE THREAD

**Issue by eugenemlee** [gorhom/react-native-bottom-sheet#274]
# Bug

`enableContentPanningGesture` has no effect after upgrading `react-native-gesture-handler` from `1.9.0` to `1.10.0`

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.0   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.10.0   |

## Steps To Reproduce

1. Upgrade to latest version of `react-native-gesture-handler@1.10.0` 
2. When Bottom Sheet is open, scroll content up.
3. Bottom sheet does not expand

Describe what you expected to happen:

- On content scroll, the bottom sheet should expand up

**Comment by saransh-malik** [comment]
This is actually happening with the new version of RNGH  the scroll is completely not working. Tried the base example in documentation as well.

**Comment by efstathiosntonas** [comment]
Same here on 2.2.0 @gorhom, `react native gesture handler 1.1.10`

**Comment by gorhom** [comment]
thanks @eugenemlee for submitting this issue, i will look into it later today 👍

**Comment by gorhom** [comment]
this commit https://github.com/software-mansion/react-native-gesture-handler/commit/8d679249604f0b6f69d3d3933a6383145fb7617a caused this issue ! i will need more time to investigate it 😓

**Comment by gorhom** [comment]
issue been reported to React Native Gesture Handler repo https://github.com/software-mansion/react-native-gesture-handler/issues/1354

**Comment by gorhom** [comment]
the issue should be resolved with `react-native-gesture-handler` `v1.10.1` 👏
