### ISSUE TITLE
Drag threshold or friction of drag gesture

### ISSUE THREAD

**Issue by Saranshmalik** [gorhom/react-native-bottom-sheet#277]
## Ask your Question

Currently if the user is trying to drag the drawer to an open state and doesn't do with adequate velocity or enough drag the drawer shows friction and doesn't open. Is there a way to actually configure this and decide the friction value or velocity somehow in v2?

**Comment by saransh-malik** [comment]
@gorhom Hey, was looking if there is a prop to handle this somehow?
