### ISSUE TITLE
Add ability to place something below bottom sheet

### ISSUE THREAD

**Issue by chybisov** [gorhom/react-native-bottom-sheet#281]
## Ask your Question

It's not clear now how to address these issue (especially on v3):

1. Integrate with something that needs to be below bottom sheet (e.g. @react-navigation/bottom-tabs).
2. On iPhone X/11/12 we have bottom line and bottom sheet should have the ability to take into account its height.

I'm not sure where this should be done - on lib side or our own, but tips to this would be so much helpful. Thank you!

Maybe related #196  #237

**Comment by zhigang1992** [comment]
For us we wanted to place a "Next Button" at the bottom the screen, that stays there and regardless of where the bottom-sheet snapped to. like this

```
  const testStyle = useAnimatedStyle(() => ({
    position: 'absolute',
    left: 0,
    width: 100,
    height: 100,
    backgroundColor: 'red',
    bottom: animatedPOIListPosition.value - topSafeArea,
  }));
```
https://github.com/zhigang1992/react-native-bottom-sheet/tree/bug/dragissue

https://user-images.githubusercontent.com/1057756/112707556-45870c00-8ee7-11eb-89e1-3aa78f49e488.mp4

it works really well when we are dragging the scroll view, but if we drag the handler or let go of the scroll view and have it spring to snap point. then there is a glitch.

https://user-images.githubusercontent.com/1057756/112707640-c80fcb80-8ee7-11eb-8a08-674a33183809.mp4

not sure if it's an issue with reanimated-2. any ideas? cc @gorhom

**Comment by gorhom** [comment]
@zhigang1992 hmm that's weird .. but i would think of introducing a new prop `footerComponent` which will stick to the bottom of the sheet. but there other priorities iam working on for now.

**Comment by RedkoVO** [comment]
I found a solution.

https://ui.gorhom.dev/components/bottom-sheet/custom-footer/
