### ISSUE TITLE
How I can put handle component inside ScrollView?

### ISSUE THREAD

**Issue by romadryud** [gorhom/react-native-bottom-sheet#284]
## Ask your Question

How I can put handle component inside ScrollView?

**Comment by gorhom** [comment]
sorry @romadryud, the bot seems not detecting question template it correctly

**Comment by romadryud** [comment]
@gorhom Don't worry. Can you please explain how can I do this?

**Comment by gorhom** [comment]
Hi @romadryud , there are two to achieve it:

- by providing a `handleComponent` prop https://gorhom.github.io/react-native-bottom-sheet/props#handlecomponent 
- setting `ScrollView` sticky header https://reactnative.dev/docs/scrollview#stickyheadercomponent

**Comment by romadryud** [comment]
Hi @gorhom . I try but the handler doesn't scroll at all he stays above the panel. Can you please provide a small example?

**Comment by romadryud** [comment]
@gorhom  Providing `handleComponent` does not put handle inside a Scroll View. About the sticky header, it does not seem to put inside scroll view it makes a sticky handle not to put inside scroll view. Thank you.

**Comment by gorhom** [comment]
@romadryud  if you are talking about the bottom sheet handle, so it **should not** be inside the scrollview but on top of it. Maybe you could provide a visual of what are you trying to achieve so i could understand better.

**Comment by romadryud** [comment]
@gorhom For example if I have a long content and my snap points are `["5%", "100%"]`. And when I try to scroll content inside Scroll View my handler doesn't hide and scroll with the content. He just stays in top position even if I scrolling content. I need handler scrolled with content

**Comment by gorhom** [comment]
could you provide a reproducible sample code ?

**Comment by romadryud** [comment]
```
<Settings for list of news />
<BottomSheet
	ref={sheetRef}
	index={1}
	snapPoints={snapPoints}
	onChange={handleSheetChange}
	enableOverDrag={false}
	enableContentPanningGesture={false}
	handleComponent={({ animatedIndex, animatedPosition }) =>
		This handle i want inside BottomSheetScrollView
	}
>
		<BottomSheetScrollView>Long list of news</BottomSheetScrollView>
</BottomSheet>
```

**Comment by romadryud** [comment]
@gorhom `index={1}` means that the Bottom Sheet must be opened by default(my snap points: `["5%", "100%"]`) and I just handle down and look settings for a list and handle up to open a long list of news and when I scrolling I want to handle component scroll out too with content.
