### ISSUE TITLE
Touchables not working in BottomSheetModal?

### ISSUE THREAD

**Issue by bekatd** [gorhom/react-native-bottom-sheet#285]
I am using standard `TouchableOpacity` from `react-native` inside my bottom sheet modal, but unfortunately it does not work (`onPress` event does not fire when pressed).

Only workaround is to use `TouchableOpacity` from `react-native-gesture-handler`

So question: Am I forced to use Touchable from rn-gesture-handler or there is something I am doing wrong?

**Comment by xubmuajkub** [comment]
This really save my day. Thanks @bekatd .
