### ISSUE TITLE
List freeze on dynamic items [v2]

### ISSUE THREAD

**Issue by saransh-malik** [gorhom/react-native-bottom-sheet#286]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2   |
| react-native                    | 0.63.0   |
| react-native-reanimated         | 1.9.0   |
| react-native-gesture-handler    | 1.6.1   |

## Steps To Reproduce

1. Use a flatlist component
2. Render a scrollable list, go to the bottom come back up
3. Somehow change the list items to 0 or max 1

Describe what you expected to happen:

1. The drawer should still be draggable

## Reproducible sample code
*** data here is sample array of objects

```javascript
renderItem = ({ item }) => {
    return (
      <View style={{ padding: 50 }}>
        <MmcText>{item.name}</MmcText>
      </View>
    )
  }

  onSearchTest = (text) => {
    const filtered = data?.filter((item) => item.name === text)
    this.setState({
      data: filtered,
    })
  }

  renderHeader = () => {
    return (
      <SearchBar
        value={this.state.searchText}
        onChangeText={this.onSearchTest}
        viewStyle={styles.searchBar}
      />
    )
  }

<BottomSheet
        ref={this.sheetRef}
        snapPoints={[200, Dimensions.get('window').height]}>
        <BottomSheetFlatList
          data={this.state.data}
          keyExtractor={(i) => i}
          ListHeaderComponent={this.renderHeader()}
          renderItem={this.renderItem}
          contentContainerStyle={styles.contentContainer}
        />
      </BottomSheet>
```
https://user-images.githubusercontent.com/56735972/107796249-a4e9ec00-6d7f-11eb-9d0b-6fd7c2c1a32a.mov

**Comment by saransh-malik** [comment]
@gorhom Any help/guidance here? Even if you could point me in right direction, I can try debug this out. Thanks :)

**Comment by gorhom** [comment]
@saransh-malik thanks for submitting this issue, ill look into it later today 👍
