### ISSUE TITLE
put a bottom sheet in a component

### ISSUE THREAD

**Issue by ahmetkuslular** [gorhom/react-native-bottom-sheet#287]
## Ask your Question

I want to put a bottom sheet in a single component and run it on the whole screen?
_for example_ I have a selection input. When I click I want to open the modal and make a selection. I don't want to display the bottom sheet every time. It will take place in input and will work on the whole screen when it works. Currently, it only detects the component inside.

**Comment by kashif-valuefy** [comment]
If you are using BottomSheetModal for displaying the BottomSheet
Just wrap your root component(App.js) with BottomSheetModalProvider. It should work

**Comment by kashif-sk** [comment]
If you are using BottomSheetModal for displaying the BottomSheet
Just wrap your root component(in App.js) with BottomSheetModalProvider. It should work

**Comment by FilipSavic95** [comment]
Anyone coming here, just re-start your coding process and you'll figure out the mistake :D
In my case, i was using modal provider buy just the `BottomSheet from "@gorhom/bottom-sheet";` 
(instead of `{BottomSheetModal} from from "@gorhom/bottom-sheet";`)
