### ISSUE TITLE
react-native-gesture-handler's RectButton onPress callback on iOS

### ISSUE THREAD

**Issue by sibest19** [gorhom/react-native-bottom-sheet#302]
# Bug

I use `RectButton` from react-native-gesture-handler.
The onPress callback is not invoked on iOS when I insert a RectButton in a `BottomSheet`.

![Registrazione schermo 2021-02-21 alle 15 42 14](https://user-images.githubusercontent.com/6689226/108628711-afca0e00-745c-11eb-9ebd-0140fedde2d6.gif)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.2   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.10.1   |

## Steps To Reproduce

1. Add a `BottomSheet`
2. Add a `RectButton` as a child with an onPress callback
3. Press the button
4. on Android the callback gets called, on iOS it doesn't.

Describe what you expected to happen:

1. I expected the callback was invoked both on iOS and Android

## Reproducible sample code

Snack available [here](https://snack.expo.io/@sibest/lonely-macaroni-and-cheese), [attached source code zip](https://github.com/gorhom/react-native-bottom-sheet/files/6017875/lonely-macaroni-and-cheese.zip)

**Comment by JClackett** [comment]
also, have the same thing, on V2 in iOS, no TouchableOpacity's seem to work

**Comment by Vednus** [comment]
Yeah, it seems like you have to go with react-native's touchables for iOS and gesture-handler's touchables for android. Kinda annoying.

**Comment by gorhom** [comment]
@sibest19 @JClackett @Vednus  , to enable any `react-native-gesture-handler` buttons you will need to add `disallowInterruption={true}` to its props 👍

let me know if it works

**Comment by sibest19** [comment]
It works! I had to dive deep down into [Objective-C source code for RNNativeViewHandler](https://github.com/software-mansion/react-native-gesture-handler/blob/e6f11644de4becc72570561fc35f445fa535d684/ios/Handlers/RNNativeViewHandler.m#L89) to actually understand what that prop was actually doing.

So this definitely adresses the issue for **v1**.
Thank you, I appreciate your support.
