### ISSUE TITLE
How to expand the bottom sheet to max height?

### ISSUE THREAD

**Issue by romadryud** [gorhom/react-native-bottom-sheet#303]
If i have snap points `["5%","100%"]`. And I want to when I open the screen I have already expanded the bottom-sheet. I set `index={1}`, but when I open the screen I have "loading" and after a few s I have opened bottom-sheet

**Comment by t08-apporio** [comment]
@romadryud put index={0}. snapPoints is an array, array indices start from 0

**Comment by romadryud** [comment]
@t08-apporio I need to expand its mean 100% height, its first position in my snap points so it is 100%. You propose to expand only by 5%.

**Comment by t08-apporio** [comment]
@romadryud try setting the initial index to 0 and see if it takes the same amount of time to show up. Bottom sheet must be taking some time to initialise. My usage displays the bottom sheet instantly. In any case some code snippets would be helpful.
