### ISSUE TITLE
Detect when bottom-sheet-modal is focused

### ISSUE THREAD

**Issue by fabcall** [gorhom/react-native-bottom-sheet#306]
# Feature Request

Similarly to how onFocusEffect / isFocused available in react-navigation, we could have an alternative to detect if a bottom-sheet-modal is currently presented (and on top).

## Why it is needed

On screens where we have more than one bottom-sheet-modal and we need to fire specific handlers in those modals, this could be a great improvement. There's a ton of use cases for this, e.g. loading some data only when bottom-sheet is indeed presented, but an interesting one would be handling onBackPress to dismiss the top bottom-sheet. Even though bottom-sheet-modal provides an onAnimate mode (and we could use it for set a flag when toIndex > 0), if there's more than one bottom-sheet presented, this may be not enough for such use cases.

## Possible implementation

Perhaps, give the dev a possibility to provide bottom-sheet a name, then, when bottom-sheet's present method is called, update an array on Context, where every opened bottom-sheet's name is stored. Then, provide a function isBottomSheetPresented (or even a custom hook) which accepts the bottom-sheet name as param and returns if it's on top of the array (e.g., index === 0). Something like this, on parent component:

### Code sample

```
const SIGN_IN_BOTTOM_SHEET = 'SIGN_IN_BOTTOM_SHEET'
const SIGN_UP_BOTTOM_SHEET = 'SIGN_UP_BOTTOM_SHEET'

function Landing() {
  const signInRef = useRef()
  const signUpRef = useRef()
  return (
    <View>
      <Text>Hey there, potato</Text>
      <SignInBottomSheet ref={signInRef} />
      <SignUpBottomSheet ref={signUpRef} />
    </View>
  )
}

const SignInBottomSheet = forwardRef(props, forwardedRef) => {
  const {isBottomSheetModalPresented} = useBottomSheetModal()
  const isSignInPresented = isBottomSheetModalPresented(SIGN_IN_BOTTOM_SHEET)

  useEffect(() => {
    if (isSignInPresented) {
      alert('lets fry these potatos')
    }
  }, [isSignInPresented])

  return (
    <BottomSheetModal name={SIGN_IN_BOTTOM_SHEET} ref={forwardRef} snapPoints={[...]}>
      <View />
    </BottomSheetModal>
  )
}
```

**Comment by Kaveh-ap** [comment]
I've also faced a similar problem, and this feature could be beneficial in my situation as well.

**Comment by danver0921** [comment]
I agree. we need it.

**Comment by dgreasi** [comment]
+1
