### ISSUE TITLE
Allow defining bounces, decelerationRate and overScrollMode scrollable props

### ISSUE THREAD

**Issue by NelsonBrandao** [gorhom/react-native-bottom-sheet#308]
# Feature Request

Currently there is no way to override `bounces`, `decelerationRate` and `overScrollMode` on `FlatList` and `SectionList`. 

## Why it is needed

This is needed to better simulate native lists on iOS devices. Since `bounces` and `overScrollMode` are the default behaviour on iOS.

## Possible implementation

It looks like changing the order prop other [here](https://github.com/gorhom/react-native-bottom-sheet/blob/a47c3006ff90c7b0d1b75fa7c35b9277d3e9d97f/src/components/flatList/FlatList.tsx#L74-L76
) might resolve this problem. Although I'm not sure if it will cause others problems.

### Code sample

```js
import { BottomSheetFlatList } from '@gorhom/bottom-sheet';

<BottomSheetFlatList {...props} bounces overScrollMode="auto" />
```

**Comment by gorhom** [comment]
hi @NelsonBrandao ,

`bounces` & `overScrollMode` are complex to implement, especially with sheet panning interaction. luckily both of them are overridable and supported with `v3` and on progress for `v2`  🤞

`decelerationRate` is a bit tricky, currently i am manipulating this variable to prevent momentum event on scrollables, we could override the default value with provided value sometime in the future , or if someone wants to contribute to get done ❤️
