### ISSUE TITLE
Unexpected token at index.ts

### ISSUE THREAD

**Issue by Drzaln** [gorhom/react-native-bottom-sheet#31]
# Bug

![Screenshot from 2020-09-16 14-46-26](https://user-images.githubusercontent.com/33492469/93307842-abedec00-f82b-11ea-96ce-e9645cb74436.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 1.2.2   |
| react-native                    | 0.61.4   |
| react-native-reanimated         | 1.13.0   |
| react-native-gesture-handler    | 1.8.0   |

i got this error when i want to run the app. I'm using JS not TS

**Comment by gorhom** [comment]
what version is your `metro-react-native-babel-preset` dependency ?

**Comment by Drzaln** [comment]
0.63.0 the latest

**Comment by gorhom** [comment]
could you add `typescript` as dev dependency

**Comment by Drzaln** [comment]
i've installed typescript but nothing changes 🤔

**Comment by gorhom** [comment]
hi @Drzaln i tried to reproduce this issue with no luck, would you mind create reproducible repo ?

**Comment by Drzaln** [comment]
hi @gorhom, i think i already find the issue. I change the node to latest version and it works, maybe i can close this issue. Thank you

**Comment by umar-abdullahi** [comment]
I'm using expo and I;m having the same issue currently.

@gorhom/bottom-sheet = `2.0.0`
react-native-reanimated = `1.9.0`
react-native-gesture-handler = `1.8.0`

**Comment by skeie** [comment]
Make sure you're using at least these versions of babel core and babel runtime

```
"@babel/core": "^7.9.0",
"@babel/runtime": "^7.9.2",
```

**Comment by tamdao** [comment]
the same issue
