### ISSUE TITLE
Integrating with react-native-snap-carousel

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#311]
## Ask your Question

I'm using https://github.com/meliorence/react-native-snap-carousel inside a BottomSheet.
It's working fine on iOS and when used outside a BottomSheet, but it doesn't scroll on Android when inside a BottomSheet.

I imagine it's because the carousel loads React Native's `ScrollView` - https://github.com/meliorence/react-native-snap-carousel/blob/4.0.0-beta.x/src/carousel/Carousel.tsx

What would you do in this case?

**Comment by gorhom** [comment]
@kickbk what bottom sheet version are you using ?

**Comment by kickbk** [comment]
@gorhom I'm using v.2 for now.
I created a [snack](https://snack.expo.io/@kickbk/bottom-sheet-containing-carousel---carousel-not-scrolling-on-android).
Open in ios. Scroll the carousel - works. Try android - doesn't scroll.

**Comment by gorhom** [comment]
hi @kickbk , i checked your snack and its simple to fix, you just need to wrap your `carousel` component with 

```tsx
<NativeViewGestureHandler disallowInterruption={true}>
   {...}
</NativeViewGestureHandler>
```

**Comment by kickbk** [comment]
Nice. Thanks!. Trying to figure this out. Getting a warning when wrapping the carousel:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `NativeViewGestureHandler`.
    in ResultsCarousel (at SearchScreen.tsx:602)
    in NativeViewGestureHandler (at SearchScreen.tsx:601)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:240)
  ```

**Comment by gorhom** [comment]
try to update your `react-native-gesture-handler`

**Comment by kickbk** [comment]
> try to update your `react-native-gesture-handler`

Upgraded. Still the same weird error. Thought it may be the carousel component inside the `NativeViewGestureHandler`, so I tried the below code, but it's still giving the error:
```
<BottomSheet
  ref={resultsCarouselRef}
  index={0}
  snapPoints={resultsCarouselSnapPoints}
  topInset={topSafeArea}
  animatedPosition={animatedModalPosition}
  handleComponent={() => <View />}
  backgroundComponent={null}
  onChange={(snapPoint: number) => {
    if (snapPoint === 0 && currentSearchModalSnapPoint !== 2 && !alert) {
      searchModalRef.current?.snapTo(1);
    }
  }}>
  <NativeViewGestureHandler>
    <View>
      <Text>Hello!</Text>
    </View>
  </NativeViewGestureHandler>
</BottomSheet>
```
        
Any ideas?

**Comment by kickbk** [comment]
@gorhom I updated the snack with the latest version of `react-native-gesture-handler` and added the `NativeViewGestureHandler` wrapper. When running on my phone and trying to touch the screen, expo crashes.

**Comment by gorhom** [comment]
i think the safest `react-native-gesture-handler` version with Expo would be `1.9.0`

**Comment by kickbk** [comment]
> i think the safest `react-native-gesture-handler` version with Expo would be `1.9.0`

Updated to that version. Still crashing Expo on the snack and giving the same error locally 🤕

**Comment by kickbk** [comment]
Interestingly enough, running ios or android on snack, and not on my own iphone, does work. But check out how Android behaves - choppy.try dragging back and forth. Strange.

**Comment by kickbk** [comment]
OK, I was running to some issues unrelated to the library. It's working perfectly with `NativeViewGestureHandler`. Thanks!
