### ISSUE TITLE
How change draggable icon's color

### ISSUE THREAD

**Issue by Martirosyan21** [gorhom/react-native-bottom-sheet#313]
## Ask your Question

How change draggable icon's color 

https://user-images.githubusercontent.com/51718597/109429212-02cf3280-7a14-11eb-8af4-8c4d75d89996.jpg

**Comment by filiptronicek** [comment]
@Vahe21 may I ask how you handled this problem? I haven't found anything in the docs

**Comment by psyzz** [comment]
did anyone succeed ?

**Comment by mxmtsk** [comment]
You can change the style by adding the following prop

```
<BottomSheet
  handleIndicatorStyle={{backgroundColor: 'red'}}
  ....
/>
```
