### ISSUE TITLE
Getting scaling effect when moving bottom sheet up and down

### ISSUE THREAD

**Issue by helgahjartar** [gorhom/react-native-bottom-sheet#314]
## Ask your Question

Hello,

I've switched to using your bottom sheet from the react-native-scroll-bottom-sheet. I'm wondering if you know how to get the same effect as displayed here: https://www.npmjs.com/package/react-native-scroll-bottom-sheet - where the card scales down as you move the bottom sheet up. In react-native-scroll-bottom-sheet it was using `animatedPosition` in combination with features from react reanimated v2, but it seems to have a different functionality with your bottom sheet.
Trying to use this now: 

```
import { Extrapolate, interpolateNode, useSharedValue } from 'react-native-reanimated';
........
   
  const animatedPosition = useSharedValue<number>(0);
   const animatedIndex = useSharedValue<number>(0);
   const cardScale = interpolateNode(animatedPosition.value, {
      inputRange: [0, 0.6, 1],
      outputRange: [1, 0.9, 0.7],
      extrapolate: Extrapolate.CLAMP,
   });
```

where cardScale ends up here - this is the image I'm trying to scale: 

```
const CardView: FunctionComponent<CardViewProps> = ({ source, cardScale }) => {
   return (
      <View style={styles.container}>
         <Animated.Image
            source={source}
            style={[styles.imageStyle, { transform: [{ scale: cardScale }] }]}
         />
      </View>
   );
};
```

and the BottomSheet looks like so: 
```
 <BottomSheet
     handleComponent={() => <Handle />}
     ref={sheetRef}
     index={0}
     waitFor
     simultaneousHandlers
     snapPoints={snapPoints}
     animatedPosition={animatedPosition}
     animatedIndex={animatedIndex}
     backgroundComponent={() => <View style={styles.contentContainer} />}>
     <BottomSheetScrollView
        scrollEnabled={false}
        contentContainerStyle={styles.contentContainer}>
        {overlay}
     </BottomSheetScrollView>
  </BottomSheet>
```

I'm wondering what I'm missing here. If the screen re-renders, the card suddenly scales down, but nothing happens as you move the bottom sheet up and down.

**Comment by helgahjartar** [comment]
I've also been looking into your examples, I see there is a scaling effect on the temperature in the Map example, however it doesn't seem to work anymore when I switch to v3 branch (I'm using version 3). Could there be some regression here?

**Comment by gorhom** [comment]
hi @helgifeiti , thanks for pointing out that weather scaling is not working at map example, i'll push a fix later this week.

looking at your provided code, you should interpolate the `animatedIndex` instead` animatedPosition`

**Comment by helgahjartar** [comment]
Thanks for the reply @gorhom. I had actually tried using the `animatedIndex` instead of `animatedPosition`, but no luck. It just doesn't seem to detect the moving of the sheet. But I'll maybe wait and see how your map example ends up looking after your fix is in and try to follow that.
It shouldn't matter that I'm using `BottomSheet` whereas there you're using `BottomSheetModal`?

**Comment by gorhom** [comment]
no it shouldn't , i have fixed the map example for v3 , have a look at it 👍

**Comment by helgahjartar** [comment]
Hey @gorhom, just wanted to let you know I managed to get this working by wrapping the `animatedIndex`  inside a `useDerivedValue` function like a saw you were doing, and using `interpolate` instead of `interpolateNode`, along with moving it into a `useAnimatedStyle` applied directly to the component I was trying to scale, like I saw you did in your example. 
So thanks for all your help!

**Comment by mgcrea** [comment]
@helgifeiti any chance you could share a working code snippet? Looks like the docs [CustomBackground](https://gorhom.github.io/react-native-bottom-sheet/custom-background) guide is currently broken for v3 and I'm looking for a way to fix it (not getting any animatedIndex update).

**Comment by joseito-terence** [comment]
@helgifeiti 
> Hey @gorhom, just wanted to let you know I managed to get this working by wrapping the `animatedIndex` inside a `useDerivedValue` function like a saw you were doing, and using `interpolate` instead of `interpolateNode`, along with moving it into a `useAnimatedStyle` applied directly to the component I was trying to scale, like I saw you did in your example. So thanks for all your help!

Can you please point me towards this example that you've mentioned?
