### ISSUE TITLE
scroll down to close bottom sheet in scrollview doesnt work in ios

### ISSUE THREAD

**Issue by casysj** [gorhom/react-native-bottom-sheet#316]
# Bug

Hello
I have a simple problem but can not handle it.

```
const data = useMemo(
    () =>
      Array(50)
        .fill(0)
        .map((_, index) => index),
    []
  );

  // render
  const renderItem = useCallback(
    (item) => (
      <View key={item}>
        <Text>{item}</Text>
      </View>
    ),
    []
  );
<BottomSheet
          ref={bottomSheetRef}
          index={0}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
          style={styles.sheetContainer}
        >
          <BottomSheetScrollView>{data.map(renderItem)}</BottomSheetScrollView>
        </BottomSheet>
```

this is how my codes look like.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.2   |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.7.0   |

## Steps To Reproduce

1. i open bottomsheet with a button
2. scroll the view inside.
3. scroll down to the top of contents and trying to keep scrolling down so that bottom sheet can be scrolled down and closed
4. but bottom sheet is not scrolled down in ios. in android it works

Describe what you expected to happen:

1. i want bottom sheet can be closed with scrolling down in ios too
2.

**Comment by casysj** [comment]
if i tap around 3-4 times very fast and scroll down at last tap, then i can close bottom sheet.
but it doesnt work so far as expected

**Comment by moseffect21** [comment]
Same problem. Found some solution?

**Comment by carissacks** [comment]
Hi, try changing your snapPoint to something like this
```jsx
const snapPoints = [0, '50%', '100%'];
```
works well for me!
Related PR: #322

**Comment by carissacks** [comment]
Hi @casysj @moseffect21 , try adding `0` to your snapPoint. Looks something like this
```jsx
const snapPoints = [0, '50%', '100%'];
```
hope it works well
Related PR: #322

**Comment by RomanSuvorov** [comment]
I have the same problem

**Comment by BerkeAras** [comment]
Same issue

**Comment by BerkeAras** [comment]
Any updates?

**Comment by zouarimustafa** [comment]
use  enablePanDownToClose
