### ISSUE TITLE
BottomSheetModal Handler 

### ISSUE THREAD

**Issue by michaelbayday** [gorhom/react-native-bottom-sheet#317]
# Bug

Android Handler for BottomSheetModal has some styling that is not overridable

iOS
![image](https://user-images.githubusercontent.com/35093298/109748906-83b23980-7b8e-11eb-80c8-405fdbd70187.png)

Android
![image](https://user-images.githubusercontent.com/35093298/109748814-59607c00-7b8e-11eb-8bbf-a2820e391b5b.png)

## Environment info
Android on PIxel 4 Simulator

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.2   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.9.0   |

## Steps To Reproduce

```ts

const StyledHandle = styled.View`
  height: 15px;
  border-top-left-radius: 30px;
  border-top-right-radius: 30px;
  background-color: ${({ theme }) => theme.BACKGROUND};
`;

<BottomSheetModal
      ref={modalRef}
      snapPoints={['75%']}
      backdropComponent={StyledOverlay}
      handleComponent={() => <StyledHandle />}
    >
```
Describe what you expected to happen:

1. Expecting to not see these weird borders on android like ios
2.

**Comment by gorhom** [comment]
hi @michaelbayday , you should set the background colour and top border radius on the `backgroundComponent` instead 👍
