### ISSUE TITLE
Backdrop prop causes BottomSheet to slide off the bottom of the screen when calling collapse()

### ISSUE THREAD

**Issue by tankers746** [gorhom/react-native-bottom-sheet#318]
# Bug

Setting `backdropComponent={BottomSheetBackdrop}` then calling `ref.collapse()` will close the bottom sheet.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.3.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0-rc.3   |
| react-native-gesture-handler    | 1.10.2   |

## Steps To Reproduce

1. Run the example app
2. Choose Advanced > Backdrop
3. Expand the sheet to 50%
4. Tap Collapse

https://user-images.githubusercontent.com/19326459/109780123-a94c4b00-7c41-11eb-8b24-7285453f8408.MP4

Cheers,
Tom

**Comment by gorhom** [comment]
Hi @tankers746, thanks for submitting this issue,

This is actually not an issue, this is an expected behaviour. You tapped on the backdrop not the collapse button 👍
