### ISSUE TITLE
[v2] null is not an object (evaluating 'sheetsQueueRef.current[sheetsQueueRef.current.length - 1].ref.current.minimize')

### ISSUE THREAD

**Issue by Yonom** [gorhom/react-native-bottom-sheet#323]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.2   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Add BottomSheetModalProvider to the root App component.
2. Use BottomSheetModal on some screen in the app.
3. Go to that screen and present/dismiss BottomSheetModal a couple of times, then go back to previous screen and return back to screen with BottomSheetModal and it crashes.

Same as #292 

Describe what you expected to happen:

1. No crash

## Reproducible sample code

```js
<BottomSheetModal
  ref={ref}
  snapPoints={[500]}
  backgroundComponent={() => <View />}
  backdropComponent={BottomSheetBackdrop}
  handleComponent={() => <View />}
  index={0}
  onChange={() => {}}
  onDismiss={() => {}}
>
  // ...
</BottomSheetModal>
```

**Comment by braincore** [comment]
Just tried this library today and immediately ran into this issue as well. My setup is almost identical to yours. A simple reproduction is to simply have two modals mounted at the same time.

I'm guessing that there's an issue with the `StackBehavior` logic which the docs say isn't implemented for v2 (though what the v2 behavior should be is unclear).

**Comment by braincore** [comment]
While I haven't thoroughly tested, just wanted to verify that moving to v3.3.3 appears to solve the immediate problem.

**Comment by Yonom** [comment]
I am not able to upgrade to v3 yet, since it requires a prerelease library (reanimated 2)

**Comment by gorhom** [comment]
this should be fixed with `v2.2.4`

**Comment by Yonom** [comment]
@gorhom Originally, this issue appeared only on Android and since the fix on v2.2.4, we have stopped seeing this issue among our Android userbase

Unfortunately, the same issue has popped up on iOS now:

`null is not an object (evaluating 'currentMountedSheet.ref.current.minimize')`

It seems like a weird race condition of some sort...

> Reproduction steps

on iOS navigate to a screen with bottom sheet, open it, close it, go back and repeat several times

> Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.4   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.10.3   |

**Comment by anthowm** [comment]
I get this error in android by the moment



Library | Version
-- | --
@gorhom/bottom-sheet | 2.3.0
react-native | 0.64.0
react-native-reanimated | 1.13.3
react-native-gesture-handler | 1.10.3

**Comment by chintanbawa** [comment]
Hi @Yonom, Did you able to fix the iOS?

**Comment by chintanbawa** [comment]
Hi @Yonom, Did you fix this issue for iOS?
