### ISSUE TITLE
Top part of bottomsheet slightly visible even the initial index value is -1

### ISSUE THREAD

**Issue by tomybudiman** [gorhom/react-native-bottom-sheet#328]
# Bug
The top part of bottomsheet (Handle component) slightly visible on screen mount even i already set the initial index value to -1. But when i close it from ref methods `.close()` it closed perferctly without any top part being visible. The issue only happen on the devices like Samsung S20.

![](https://i.ibb.co/Zdzg4jL/Screenshot-20210306-131641-Hangry.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^2 |
| react-native                    | 0.63.4 |
| react-native-reanimated         | ^1.9.0 |
| react-native-gesture-handler    | ^1.5.6 |

## Reproducible sample code

```javascript
const [contentHeight, setContentHeight] = useState(0);
const snapPoints = useMemo(() => [0, contentHeight], [contentHeight]);
const easing = Easing.out(Easing.bezier(0.78, -0.4, 0.32, 1.6));
// Methods
const onLayoutSheetContainer = ({nativeEvent}) => {
  const layoutHeight = get(nativeEvent, 'layout.height', 0);
  setContentHeight(layoutHeight);
};
// Render
return (
  <BottomSheet
    index={-1}
    snapPoints={snapPoints}
    animationDuration={750}
    animationEasing={easing}
    handleComponent={HandleComponent}
    backdropComponent={BottomSheetBackdrop}
    backgroundComponent={BackgroundComponent}>
    <View
      style={styles.autoResizeContainer}
      onLayout={onLayoutSheetContainer}>
      {props.children}
    </View>
  </BottomSheet>
);
```

**Comment by danarchos** [comment]
Did you ever find a fix for this @tomybudiman , getting this issue too
