### ISSUE TITLE
Possibility to disable gestures

### ISSUE THREAD

**Issue by iremlopsum** [gorhom/react-native-bottom-sheet#33]
# Feature Request

Hey, I've been loving this library, great work! I've been missing an option to disable gestures on the bottomsheet so the user wouldn't be able to swipe it away

## Why it is needed

In case you want to put something important in the bottomsheet, and want the user to not accidentally close it by swipining/scrolling around

**Comment by gorhom** [comment]
thanks @iremlopsum for submitting this feature request, i'll work on it as soon as i get free 👍

**Comment by gorhom** [comment]
released with [v1.3.0](https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v1.3.0)

**Comment by a-eid** [comment]
@gorhom was this removed on v3 ?

**Comment by gorhom** [comment]
@a-eid https://gorhom.github.io/react-native-bottom-sheet/props#enablecontentpanninggesture
