### ISSUE TITLE
BottomSheetModal doesn't slide up when opening keyboard on iOS

### ISSUE THREAD

**Issue by theianjohnson** [gorhom/react-native-bottom-sheet#330]
# Bug

See https://snack.expo.io/@setjetters/excited-french-fries

On Android the BottomSheetModal slides up correctly when the keyboard opens

On iOS it doesn't and the keyboard ends up covering the `<TextInput>`

## Environment info

v2
| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.2   |
| react-native                    | Expo 40 (so react-native 0.63)   |
| react-native-reanimated         | 1.13.0   |
| react-native-gesture-handler    | 1.8.0   |

v3
| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.0.0   |
| react-native                    | Expo 40 (so react-native 0.63)   |
| react-native-reanimated         | 2.0.0-rc.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Open Expo Snack https://snack.expo.io/@setjetters/excited-french-fries in iOS
2. Click "Open" button at top
3. Click into the TextInput in the BottomSheetModal at the bottom

Describe what you expected to happen:

1. The BottomSheetModal should slide up with the keyboard

## Reproducible sample code

https://snack.expo.io/@setjetters/excited-french-fries

**Comment by gorhom** [comment]
keyboard handling will be release soon for v3, please have a look https://github.com/gorhom/react-native-bottom-sheet/discussions/233, but not sure for v2 ,, at least for now

**Comment by theianjohnson** [comment]
I've got v3 working so that'd be great, how is it only bugged on iOS? ie on Android the whole bottom sheet slides up to accommodate the keyboard fine

**Comment by theianjohnson** [comment]
Ah is there any way this could be patched into the 3.0.0 release? Since that's the last Expo 40 can use

**Comment by gorhom** [comment]
@theianjohnson you could fork `feature/keyboard-handling` and downgrade to `rc.0` and see how it goes .. i think there will be fewer changes to be made to get it working
