### ISSUE TITLE
[v3] Unable to resolve "./useReactiveValue" from "node_modules/@gorhom/bottom-sheet/src/hooks/index.ts"

### ISSUE THREAD

**Issue by theianjohnson** [gorhom/react-native-bottom-sheet#332]
# Bug

Ok opening a _third_ issue since your auto close is a little overzealous, https://github.com/gorhom/react-native-bottom-sheet/issues/331

Doesn't look like we can reopen issues so creating a new one from https://github.com/gorhom/react-native-bottom-sheet/issues/185

Attempting this again and still doesn't work, although there's a different error. Does your library support rc.0? That's the latest version Expo supports

I've uninstalled and reinstalled @gorhom/bottom-sheet and no change

![image](https://user-images.githubusercontent.com/4634364/110218829-a2efe600-7e70-11eb-9aad-cd28fc41c31d.png)

`useReactiveSharedValue` maybe?
![image](https://user-images.githubusercontent.com/4634364/110218794-75a33800-7e70-11eb-9fa9-021758bf8879.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.3.3   |
| react-native                    | https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz   |
| react-native-reanimated         | 2.0.0-rc.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Run expo start
2. See compile error

Describe what you expected to happen:

1. No compile error

**Comment by gorhom** [comment]
hi @theianjohnson, unfortunately you will need to use `v3.0.0`, because `Expo v40` is only support `Reanimated v2.rc0`.

or wait till `Expo v41` https://blog.swmansion.com/reanimated-2-0-stable-release-is-out-564c9c910891?source=social.tw

**Comment by theianjohnson** [comment]
@gorhom same error

Looks like this https://github.com/gorhom/react-native-bottom-sheet/blob/fdf8c4c7bab67865bc2b9575ef13aecc45de1690/src/hooks/index.ts is the commit for 3.0.0 yeah? Not seeing it in there

**Comment by gorhom** [comment]
the hook `useReactiveValue` was released with `v3.3.0` ,, there must be a problem with your node_modules or cache

**Comment by theianjohnson** [comment]
Got it 👌  Cleared the cache with `expo r -c` and using `"@gorhom/bottom-sheet": "3.0.0"` and `"react-native-reanimated": "^2.0.0-rc.0"` it works again
