### ISSUE TITLE
Prevent content behind bottom sheet from being interacted with.

### ISSUE THREAD

**Issue by dochonglo** [gorhom/react-native-bottom-sheet#339]
## Ask your Question

Hello!

Is it possible to prevent content from being interacted with when the bottom sheet is present. From my understanding, the bottom sheet is positioned over the view. How come I'm able to tap on buttons in the view instead of the modal actually dismissing itself?

Thanks in advance! :)

**Comment by kickbk** [comment]
Hi @ismaelbarry, try adding a `backdropComponent` to your BottomSheet. If you prefer it to be transparent, you can customize it, but regardless, when you add it, it will go on top of your other content and prevent taps those taps.
