### ISSUE TITLE
BottomSheetScrollView gets stuck when sheet is expanded

### ISSUE THREAD

**Issue by rkrueger11** [gorhom/react-native-bottom-sheet#34]
# Bug

When switching between BottomSheetScrollViews, if the sheet is in an expanded view then it gets stuck and the content won't scroll until you minimize the sheet and then expand it again. I'm using the focus hook from react navigation, and it's still not working.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         |1.2.2   |
| react-native                    | 0.63.2   |
| react-native-reanimated         |1.13.0  |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce

1. Have one bottom sheet, with two children views and <BottomSheetScrollView> as the top parent of each
2. Switch from one to another while the sheet is expanded
3. Attempt to scroll in the body

Describe what you expected to happen:

1. Scrolling doesn't work, but should

## Reproducible sample code
In progress

**Comment by gorhom** [comment]
@rkrueger11 thanks for submitting this bug, i'll look into it later today 👍

**Comment by gorhom** [comment]
@rkrueger11 i tried from my side, seems working, but i would appreciate if you could provide a reproducible sample code :)

**Comment by rkrueger11** [comment]
Thanks @gorhom. I'll get some sample code posted tomorrow. Sorry was hoping to get there today. Great work on this package though!

**Comment by gorhom** [comment]
hi @rkrueger11, could you try again with v1.4 release, it should provide more stability :)

**Comment by rkrueger11** [comment]
@gorhom Tried with 1.4.1 release and still having the issue, though I think it's probably with my `react-navigation` wrapper around it, so this can be closed.

**Comment by Gnative** [comment]
Hi @rkrueger11  I'm having this same issue, did you find the cause to this ? Thanks.

**Comment by gorhom** [comment]
hi @Gnative would mind provide reproducible sample code ?

**Comment by Gnative** [comment]
Sure. I'll try my best. Still working on it being my misunderstanding on how to implement the BottomSheetScrollView

**Comment by Gnative** [comment]
@gorhom So for me this is the code (below) that causes the non responsive BottomSheetScrollView when the panel reaches max snap point. In usage I am able get the BottomSheetScrollView responsive again my pulling down a little on the BottomSheet and letting it re-snap to the max snap point.

Basically setting state from with in the handleSheetChange callback can cause this problem

This code can be use with in the `BasicExamples.tsx` Line 29 or file attached
[BasicExamples.tsx.txt](https://github.com/gorhom/react-native-bottom-sheet/files/5378885/BasicExamples.tsx.txt)

```
    const [stateItem, setStateItem] = useState(0)

    // callbacks
    const handleSheetChange = useCallback(index => {
      console.log('handleSheetChange', index);
      setStateItem(index)
    }, []);

```

And thanks - its a really nice component.

**Comment by gorhom** [comment]
thanks for the sample ,,, i'll look into it today and i'll make sure to get it fix asap :)

**Comment by maxckelly** [comment]
Hey, amazing package. Thank you for your hard work. 

I'm also experiencing this on Android with BottomSheetFlatList, but iOS works great.

**Comment by tankers746** [comment]
I believe this is the same issue I'm experiencing. https://github.com/gorhom/react-native-bottom-sheet/issues/51
