### ISSUE TITLE
Failed building javascript bundle

### ISSUE THREAD

**Issue by mrsilph** [gorhom/react-native-bottom-sheet#342]
# Bug

Hi! I'm having this error in my app react native app with expo. This is the error tray:

Failed building JavaScript bundle.
Unable to resolve module ./hooks/useBottomSheetSpringConfigs from D:\development\ReactProjects\cat-reminders\node_modules\@gorhom\bottom-sheet\src\index.ts:

None of these files exist:
  * node_modules\@gorhom\bottom-sheet\src\hooks\useBottomSheetSpringConfigs(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * node_modules\@gorhom\bottom-sheet\src\hooks\useBottomSheetSpringConfigs\index(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  
> 1 | export { default } from './components/bottomSheet';
  2 |
  3 | // scrollables
  4 | export { default as BottomSheetFlatList } from './components/flatList';

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^2.2.4   |
| react-native                    | 0.63.2   |
| react-native-reanimated         | ~1.13.0  |
| react-native-gesture-handler    | ~1.8.0   |

## Steps To Reproduce

1. npm i @gorhom/bottom-sheet
2. write some code importing the library
3. run in android with expo

Describe what you expected to happen:

1. Run without errors

## Reproducible sample code

Here is my code with this library.

--------------------------------------------------

import React, { useEffect } from "react";
// native components
import { StyleSheet } from "react-native";
// ui components
import { View, Text } from "react-native-ui-lib";
import BottomSheet from "@gorhom/bottom-sheet";
// styles
import { Colors } from "./styles";

const AvatarsBottomSheet = ({ visible }: Props) => {
  // sheet ref
  const sheet = React.createRef<BottomSheet>();

  // sheet content
  const renderContent = () => {
    return (
      <View style={styles.panel}>
        <View>
          <Text>HI</Text>
        </View>
      </View>
    );
  };

  return (
    <BottomSheet
      ref={sheet}
      index={1}
      snapPoints={[-1, "60%"]}
      children={renderContent}
    />
  );
};

const styles = StyleSheet.create({
  header: {
    height: 40,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: Colors.SECONDARY,
  },
  slot: {
    width: 40,
    height: 8,
    borderRadius: 4,
    marginBottom: 10,
    backgroundColor: Colors.PRIMARY,
  },
  panel: {
    backgroundColor: Colors.SECONDARY,
  },
});

interface Props {
  visible: boolean;
}

export default AvatarsBottomSheet;

**Comment by gorhom** [comment]
hi @darmane , `useBottomSheetSpringConfigs` is only available for `v3` ! please remove the library and install it again and make sure to clear metro cache
