### ISSUE TITLE
Cannot reopen modal

### ISSUE THREAD

**Issue by Dallas62** [gorhom/react-native-bottom-sheet#343]
# Bug

When we have 2 bottom sheet modals in replace-mode, and you try to close both at the same time.
The first modal cannot be reopened.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.3.3   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.0.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Implement 2 bottom sheet modal
 - `modal1` must open `modal2`
 - The action on `modal2` is to close both `modal1` and `modal2`
2. Open `modal1`
3. Open `modal2`
4. Close both `modal1` and `modal2` from `modal2`
5. Try to open `modal1` (cannot be opened).

Describe what you expected to happen:

1. `modal1` should open

## Reproducible sample code

```jsx
import React, { useRef } from 'react';
import { TouchableOpacity, Text } from 'react-native';
import { BottomSheetModal } from '@gorhom/bottom-sheet';

const snap_points = ['20%'];

function MyComp() {
  const bottom_sheet_modal1_ref = useRef(null);
  const bottom_sheet_modal2_ref = useRef(null);

  const open_modal1 = () => {
    bottom_sheet_modal1_ref.current.present();
  };

  const open_modal2 = () => {
    bottom_sheet_modal2_ref.current.present();
  };

  const close_both_modals = () => {
    bottom_sheet_modal2_ref.current.dismiss();
    bottom_sheet_modal1_ref.current.dismiss();
  };

  return (
    <>
        <TouchableOpacity onPress={open_modal1}><Text>Open modal1</Text></TouchableOpacity>
        <BottomSheetModal ref={bottom_sheet_modal1_ref} snapPoints={snap_points}>
          <TouchableOpacity onPress={open_modal2}><Text>Open modal2</Text></TouchableOpacity>
        </BottomSheetModal>
        <BottomSheetModal ref={bottom_sheet_modal2_ref} snapPoints={snap_points}>
          <TouchableOpacity onPress={close_both_modals}><Text>Close both modal</Text></TouchableOpacity>
        </BottomSheetModal>
    </>
  );
}
```

- Click on `Open modal1`
- Then, click on `Open modal2`
- Then, click on `Close both modal`
- Then, click on `Open modal1` nothing happen

**NOTE: It's working if we inverse the closing order inside `close_both_modals` by:**
```js
  const close_both_modals = () => {
    bottom_sheet_modal1_ref.current.dismiss();
    bottom_sheet_modal2_ref.current.dismiss();
  };
```

**Comment by gorhom** [comment]
Try to use ‘dismissAll’

**Comment by Dallas62** [comment]
Hi @gorhom 

It's probably working with `dismissAll`, but in this particular case it's not working.
The order of the dismiss influence the result (like my final note).
I suppose there is a boolean which is in the wrong state.

This may lead to other issues.

In my case, I made it work but it's still a bug in my opinion.

Regards,

**Comment by gorhom** [comment]
okay i will look into it

**Comment by gorhom** [comment]
this should be fixed with `v3.4.1`

**Comment by Dallas62** [comment]
Thanks a lot for your reactivity ! 👍

**Comment by gorhom** [comment]
no problem :)
