### ISSUE TITLE
BottomSheetBackdrop: customize behavior on press

### ISSUE THREAD

**Issue by jsamr** [gorhom/react-native-bottom-sheet#344]
# Feature Request

Provide a new prop for `BottomSheetBackdrop` component, `pressBehavior`, which can have the following values:

| Press Behavior | Description                                                                    |
| -------------- | ------------------------------------------------------------------------------ |
| `'none'`       | Pressing the backdrop does nothing. Equivalent to `closeOnPress=false`.        |
| `'close'`      | Pressing the backdrop closes the sheet. Equivalent to `closeOnPress=true`.     |
| `'collapse'`   | Pressing the backdrop collapses the sheet (snap to `disappearsOnIndex` index). |
| number         | Pressing the backdrop snaps to the provided index.                             |

## Why it is needed

Currently, the only customization is via `closeOnPress`, which causes the sheet to be completely closed when the user presses the backdrop. I believe it is a very frequent scenario when the library consumer wants the sheet to be collapsed instead.

## Possible implementation

```tsx
const BottomSheetBackdropComponent = ({
  disappearsOnIndex = DEFAULT_DISAPPEARS_ON_INDEX,
  pressBehavior = DEFAULT_PRESS_BEHAVIOR
}) => {
  const { collapse, snapTo, close } = useBottomSheet();
  //...
  const handleOnPress = useCallback(() => {
    if (pressBehavior === 'close') {
      close()
    } else if (pressBehavior === 'collapse') {
      snapTo(disappearsOnIndex)
    } else if (typeof pressBehavior === 'number') {
      snapTo(pressBehavior)
    }
  }, [close, snapTo, disappearsOnIndex]);
  // ...
}
```

### Code sample

```tsx
const Backdrop = (props: BottomSheetBackdropProps) => <BottomSheetBackdrop pressBehavior="collapse" {...props} />
```

### Remarks

1. ~~I wonder if `'collapse'` should snaps to zero instead... not sure what's the best.~~ I do favor the proposed implementation, since the consumer can still use a numbered index (`0`) for the desired behavior.
2. `closeOnPress` would be deprecated by this new prop. While these props coexist, I believe it would be sensible that `pressBehavior` takes precedence over `closeOnPress` when both are defined. We could also print a warning.

**Comment by gorhom** [comment]
@jsamr thanks for submitting this well detailed enhancement ❤️ 

This should be implemented for both `v2` & `v3`, I added `help wanted` tag, but if not picked up i will work on it

**Comment by jsamr** [comment]
@gorhom You're welcome, your library is beautiful :heart:  Not sure I'll have the bandwidth to do that soon, but if I do I'll let you know before starting!

**Comment by jsamr** [comment]
@gorhom I'm plannig to take a shot very soon! I'll post one PR on master, and one on v3 branch.

**Comment by gorhom** [comment]
thanks @jsamr for the amazing work you've done! 

this feature is now available for `v3` & `v2`  🎉

**Comment by jsamr** [comment]
@gorhom my pleasure!
