### ISSUE TITLE
TextInput "steals" the gesture from Bottom Sheet on android

### ISSUE THREAD

**Issue by krakz999** [gorhom/react-native-bottom-sheet#349]
## Ask your Question

I have a search field in my bottom sheet's header. On iOS I'm able to pull up the bottom sheet by tapping and dragging the TextInput in the header, however on android the input field seems to steal the gesture and the bottom sheet can not be pulled up with it. Wondering if there is a trick that I'm missing to make this work?

**Comment by JenyaIII** [comment]
> ## Ask your Question
> I have a search field in my bottom sheet's header. On iOS I'm able to pull up the bottom sheet by tapping and dragging the TextInput in the header, however on android the input field seems to steal the gesture and the bottom sheet can not be pulled up with it. Wondering if there is a trick that I'm missing to make this work?

Try wrapping it in a BottomSheetView. I had a similar problem with buttons wrapped in TouchableOpacity, then I imported the TouchableOpacity component from this library (gorhom/react-native-bottom-sheet) and everything worked. Same situation with FlatList ScrollView SectionList. You can also try importing TextInput from gorham/react-native-bottom-sheet

**Comment by krakz999** [comment]
@JenyaIII doesn't seem to work. Yeah had the same issue with buttons and I'm already using the gesture-handler alternatives for those. For the TextInput I can't seem to find a solution on android, even the gesture-handler variant steals the gesture from the sheet.

**Comment by JenyaIII** [comment]
> @JenyaIII doesn't seem to work. Yeah had the same issue with buttons and I'm already using the gesture-handler alternatives for those. For the TextInput I can't seem to find a solution on android, even the gesture-handler variant steals the gesture from the sheet.

god damn ((((

**Comment by krakz999** [comment]
Fixed by patching `shouldHandlerBeCancelledBy` method and `RootViewGestureHandler` class  react-native-gesture-handler

```
diff --git a/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerOrchestrator.java b/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerOrchestrator.java
index f08713b..7b9a03b 100644
--- a/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerOrchestrator.java
+++ b/node_modules/react-native-gesture-handler/android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerOrchestrator.java
@@ -2,6 +2,7 @@ package com.swmansion.gesturehandler;
 
 import android.graphics.Matrix;
 import android.graphics.PointF;
+import android.util.Log;
 import android.view.MotionEvent;
 import android.view.View;
 import android.view.ViewGroup;
@@ -13,6 +14,8 @@ import java.util.Comparator;
 
 import androidx.annotation.Nullable;
 
+import com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper;
+
 public class GestureHandlerOrchestrator {
 
   // The limit doesn't necessarily need to exists, it was just simpler to implement it that way
@@ -533,6 +536,9 @@ public class GestureHandlerOrchestrator {
       // state, we delegate the decision to the implementation of GestureHandler#shouldBeCancelledBy
       return handler.shouldBeCancelledBy(other);
     }
+    if (other instanceof RNGestureHandlerRootHelper.RootViewGestureHandler && handler instanceof PanGestureHandler) {
+      return false;
+    }
     return true;
   }
 
diff --git a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.java b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.java
index 9bf0c8f..8d4e58c 100644
--- a/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.java
+++ b/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.java
@@ -81,7 +81,7 @@ public class RNGestureHandlerRootHelper {
     return mRootView;
   }
 
-  private class RootViewGestureHandler extends GestureHandler {
+  public class RootViewGestureHandler extends GestureHandler {
     @Override
     protected void onHandle(MotionEvent event) {
       int currentState = getState();
```
