### ISSUE TITLE
onDrag callback to determine when user dragging/pulling drawer.

### ISSUE THREAD

**Issue by MidasCE** [gorhom/react-native-bottom-sheet#351]
# Feature Request

Hi, Could we have a callback to determine state when user longPress and start to drag the handler? (Example: onDragHandler, which return start index)

## Why it is needed

Currently, It seems like we only have 2 callback which is (onChange, onAnimate) which only triggered once user release their finger. It would be great to able to detect that user are pressing and dragging the drawer.

### Code sample

```
const onDrag = (fromIndex: number, (maybe other params to determine position) => {
   ......
}
...
onDragHandler={onDrag}
```

Let me know what's your thought

**Comment by fukemy** [comment]
hi any update? It's really what I want to do

**Comment by alexeyvax** [comment]
If you need to simulate onDrag logic you can use `animatedPosition` prop

```
import { useSharedValue } from "react-native-reanimated";

const currentPosition = useSharedValue(0);

<BottomSheetPanel
    ...
    animatedPosition={currentPosition}
    ...
/>
```

any details on this comment
https://github.com/gorhom/react-native-bottom-sheet/issues/423#issuecomment-1102691451
