### ISSUE TITLE
snapTo in v2.2.4 stopped working

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#352]
# Bug

I believe there may be a bug in the latest release of v2.2.4.
`snapTo` is not working for me.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.4   |

## Steps To Reproduce

Go to https://snack.expo.io/@kickbk/bottomsheetmodal-224-snapto-issue. Click on "Show modal" and then on "Snap to 1"
It will fail.
Now, go to package.json and change BottomSheet to v. 2.2.3. Try again - it will work this time.
## Reproducible sample code

https://snack.expo.io/@kickbk/bottomsheetmodal-224-snapto-issue

**Comment by gorhom** [comment]
thanks @kickbk for reporting this bug, it should be resolved with `v2.2.5` 👏
