### ISSUE TITLE
dismissOnPanDown={false} interrupts .present() on modals

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#353]
## Ask your Question

Is `dismissOnPanDown={false}` supposed to interrupt `.present()` on modals?
Have a look at https://snack.expo.io/@kickbk/bottomsheet-switching-modals
Run it and click the buttons - everything works as it should, it keeps switching between the modals.
Now, uncomment `dismissOnPanDown={false}` in BottomSheetModal A and try clicking the buttons. Once modal B fires `present();` **after modal A ran `.present()`**, modal A will no longer show.

**Comment by kickbk** [comment]
I think it's a bug. Doesn't happen with v.2.2.3

**Comment by gorhom** [comment]
this should be fixed with `v2.2.6`
