### ISSUE TITLE
Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?

### ISSUE THREAD

**Issue by faustoct1** [gorhom/react-native-bottom-sheet#354]
# Bug
running `yarn ios` got `Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?`

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^3   |
| react-native                    | ~0.63.4  |
| react-native-reanimated         | ^2.0.0   |
| react-native-gesture-handler    | ^1.10.3   |

## Steps To Reproduce

`yarn ios`

## Package.json
`````
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^3",
    "@react-native-async-storage/async-storage": "^1.14.1",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-firebase/analytics": "^10.8.1",
    "@react-native-firebase/app": "^10.8.1",
    "@react-native-firebase/auth": "^10.8.1",
    "@react-native-firebase/database": "^10.8.1",
    "@react-native-firebase/firestore": "^10.8.1",
    "@react-native-firebase/functions": "^10.8.1",
    "@react-native-firebase/messaging": "^10.8.1",
    "@react-native-firebase/remote-config": "^10.8.1",
    "@react-native-firebase/storage": "^10.8.1",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "expo": "~40.0.0",
    "expo-ads-admob": "^9.0.0",
    "expo-image-picker": "^10.0.0",
    "expo-notifications": "^0.9.0",
    "expo-splash-screen": "~0.8.0",
    "expo-status-bar": "~1.0.3",
    "expo-updates": "~0.4.0",
    "geofire-common": "^5.2.0",
    "moment": "^2.29.1",
    "native-base": "^2.15.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-cheerio": "^1.0.0-rc.4",
    "react-native-device-settings": "^1.2.0",
    "react-native-emoji": "^1.8.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-gps-state": "^2.0.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-share": "^5.1.4",
    "react-native-unimodules": "~0.12.0",
    "react-native-web": "~0.13.12",
    "react-native-webview": "^11.2.3"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
`````

**Comment by anujraghuvanshi** [comment]
Anybody with solution of this ?

**Comment by blazk0** [comment]
having the same issue as well

**Comment by gorhom** [comment]
@Anuj-Raghuvanshi , @blazk0 https://docs.swmansion.com/react-native-reanimated/docs/installation#babel-plugin

**Comment by faustoct1** [comment]
It's been caused by react-navigation 5 or prior.. I moved to react-navigation 6! **Which works**

**Comment by sameer-kumar-jain** [comment]
For me yarn start --reset-cache works

**Comment by DeniferSantiago** [comment]
@faustoct I tried it and it did not work for me, when I get to a view with a BottomSheet it throws me the same error

**Comment by carsonxw** [comment]
I ran `yarn add react-native-reanimated@next`. It worked for me.

**Comment by DeniferSantiago** [comment]
My problem was that I wasn't using the reanimated2 plugin correctly

```javascript
module.exports = {
    presets: ["module:metro-react-native-babel-preset"],
    env: {
        production: {
            plugins: ["react-native-paper/babel", "react-native-reanimated/plugin"]
        }
    }
};
```
I changed it to:
```javascript
module.exports = {
    presets: ["module:metro-react-native-babel-preset"],
    plugins: ["react-native-reanimated/plugin"],
    env: {
        production: {
            plugins: ["react-native-paper/babel"]
        }
    }
};

```

**Comment by burak4ydin** [comment]
> My problem was that I wasn't using the reanimated2 plugin correctly
> 
> ```js
> module.exports = {
>     presets: ["module:metro-react-native-babel-preset"],
>     env: {
>         production: {
>             plugins: ["react-native-paper/babel", "react-native-reanimated/plugin"]
>         }
>     }
> };
> ```
> 
> I changed it to:
> 
> ```js
> module.exports = {
>     presets: ["module:metro-react-native-babel-preset"],
>     plugins: ["react-native-reanimated/plugin"],
>     env: {
>         production: {
>             plugins: ["react-native-paper/babel"]
>         }
>     }
> };
> ```

Congratulations! It worked for me 🥳

**Comment by cyrusbowman** [comment]
Clearing metro bundler cache worked for me.

`expo start -c`

**Comment by aurelienlouvel** [comment]
U need to disable eslint : https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-non-null-assertion.md
