### ISSUE TITLE
Cannot drag bottomsheet when on top of TextInput

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#360]
## Ask your Question
Hi @gorhom 
Have a look at https://snack.expo.io/@kickbk/android-text-input-cannot-drag
Test on iOS and android.
Click modal A
Drag the bottom sheet up by dragging on the TextInput.
iOS works. Android not.
How do I solve this?

**Comment by zhigang1992** [comment]
Try TextInput from the react-native-gesture-handler package?

**Comment by kickbk** [comment]
@zhigang1992 tried both using a `TextInput` from the `react-native-gesture-handler`, as well as wrapping with `<NativeViewGestureHandler disallowInterruption>` but that didn't help. @gorhom any suggestions?

**Comment by kickbk** [comment]
Many hours of tests later and I found out that my issue was caused by `BottomSheetFlatList`.
I believe it was extending past its visual bounding. Does that make sense? Let me give an example - the issue of not being able to drag the bottom sheet up was random, which is strange already.
My bottom sheet is as follows:
```
<BottomSheetModal
  ref={searchModalRef}
  ...
  >
  <SearchField />
  <View style={{ flex: 1 }}>
    {
      !someCondition ? (
        <SearchCategories // This is in fact another 'BottomSheetFlatList' which was causing the bottom sheet not to open. Changing it to FlatList solved the issue />
      ) : (
        <BottomSheetFlatList // Replaced this one with FlatList as well.
          ref={listRef}
          data={data}
          keyExtractor={(item: { id: string }) => `row-${item.id}`}
          renderItem={({ item }: { item: Item }) => <ListRow {...item} />}
          onEndReached={() => loadMore()}
        />
      )
    }
  </View>
</BottomSheetModal>
```
Replacing the `SearchCategories` component, which is a `BottomSheetFlatList` with a `FlatList` from `react-native-gesture-handler` solved the dragging issue.

Next - when the bottom sheet would open with `ListRow` `BottomSheetFlatList` and I would scroll a little, I would have to drag down from the top the distance I scrolled down on the list before the bottom sheet would start moving down.

Anyway, for now this issue is resolved by using FlatList. @gorhom if you want to debug this further, let me know.

**Comment by kickbk** [comment]
Oh, and the issue with not being able to drag the BottomSheet when on a `TextInput` is still not resolved. Tried importing from `react-native-gesture-handler`, but that didn't help.

**Comment by kickbk** [comment]
@gorhom I had to revert back to `BottomSheetFlatList` to be able to drag the bottom sheet down when dragging the FlatList. So this issue is back. Can we please resolve it?

**Comment by gorhom** [comment]
@kickbk it seems that it is an issue `react-native-gesture-handler`, you can apply @osdnk's patch to solve it https://github.com/software-mansion/react-native-gesture-handler/issues/668#issuecomment-733004914
