### ISSUE TITLE
Android TextInput onFocus snapTo not working correctly

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#362]
# Bug

When clicking inside a TextInput and running a function `onFocus` to snap a bottom sheet to a specific snap point doesn't always run with Android (Works on iOS).

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.6  |

## Steps To Reproduce
Go to [this snack](https://snack.expo.io/@kickbk/android-text-input-cannot-drag)
1. Open Modal A
2. Click inside the TextInput
3. Modal should snap to point 2 ('100%'), but doesn't always.
4. If it does work, then open Modal B, dismiss the keyboard by clicking the search icon. Open modal A and try again

This happens on the simulator as well as actual devices (old and new)

You can see the modal collapses to snap point 0 and you can see it also in the console log.

iOS works as it should.

![androidSnap](https://user-images.githubusercontent.com/31323376/112034292-8bb12980-8afb-11eb-886a-a087447cff65.gif)

## Reproducible sample code

Code on [this snack](https://snack.expo.io/@kickbk/android-text-input-cannot-drag)

**Comment by kickbk** [comment]
@gorhom could you please have a quick glance at this? Is there a solution or should I just wait for Expo to update to reanimated 2 and then wait for the upcoming keyboard handling of v3?

**Comment by ryanliszewski** [comment]
I'm also seeing this same behavior on Android on the latest V3 version: 

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.3   |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 2.0.1   |
| react-native-gesture-handler    | 1.10.3   |

**Comment by fcandi** [comment]
Thx, I experience exactly the same problem. Would love to upgrade to v3, but reAnimated v2 not yet working properly in my context due to a critical open bug (the one with "failed to create a worklet")

**Comment by gorhom** [comment]
@ryanliszewski , @kickbk  could you provide a reproducible sample code for `v3` ? thanks

@fcandi you may need to install `Reanimated` babel plugin https://docs.swmansion.com/react-native-reanimated/docs/installation#babel-plugin

**Comment by kickbk** [comment]
@gorhom please have a look at https://snack.expo.io/@kickbk/android-text-input-cannot-drag and run on android.

**Comment by fcandi** [comment]
> @fcandi you may need to install `Reanimated` babel plugin https://docs.swmansion.com/react-native-reanimated/docs/installation#babel-plugin

Thanks @gorhom Last time I tried some weeks ago.. So I tried to install reanimated again and now it works :D Don't ask me what I did different.

> @ryanliszewski , @kickbk could you provide a reproducible sample code for `v3` ? thanks

Still, now using 3.6.4, I have the same problem like @kickbk It seems like there is an android logic that fiddles with the bottom sheet on its own when the keyboard appears. It will then override the snapTo. At least its my theory..?

**Comment by fcandi** [comment]
Hey @kickbk I have one more problem and wanted to ask you first before opening an issue: My BottomSheet is not accepting PanGestures on the TextInput (or BottomSheetTextInput). It only react on the handle and on the rest of the View. Its working on OS, though. 

Do you have the same problem or do I need to look at some other sources of my problem? Thx :)

**Comment by gorhom** [comment]
@fcandi you need to apply this patch https://github.com/gorhom/react-native-bottom-sheet/blob/v4/example/patches/react-native-gesture-handler%2B1.10.3.patch 👍

**Comment by fcandi** [comment]
@gorhom Thanks the Patch working great :)

@kickbk I also head the problem only on Android that there was a automatic keyboard handling that interfered with the Bottom Sheet snap points. That is, because I had a configuration in AndroidManifest.xml in "activity" :  "android:windowSoftInputMode". There are several options, I now use "android:windowSoftInputMode="adjustPan" and its working great.
