### ISSUE TITLE
Is BottomSheet FlatList still using getNode()

### ISSUE THREAD

**Issue by MagnusEklof** [gorhom/react-native-bottom-sheet#364]
## Ask your Question

I am using the latest version of flatlist but with newer version of react-native and I get a warning that "FlatList: Calling getNode() on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release."

Can you confirm? And if so can you fix this?

**Comment by RealDyllon** [comment]
I'm getting the same warning as well, on React Native 0.64.0

**Comment by oneji** [comment]
Can u please accept the PR to solve this warning? Or as I can see this repo isn't maintaned anymore... @vonovak @richkeenan @thgh @olliebrennan @grifotv

**Comment by rrebase** [comment]
@oneji I highly recommend https://github.com/ds300/patch-package for these types of quick fixes.

This repo is definitely in active development and @gorhom is doing a fantastic job 👏. Considering the popularity of the library and amount of use cases it just takes time to address all of them while building new features.
