### ISSUE TITLE
Best way to access the currently displayed modal?

### ISSUE THREAD

**Issue by rkrueger11** [gorhom/react-native-bottom-sheet#365]
## Ask your Question

Hey there, I have a button (not a part of any bottom sheet) that needs to dynamically hide/show depending on which bottom sheet modal is currently being displayed. Is there a way to currently do that? Seems like maybe this would need to be a new exported hook?

**Comment by gorhom** [comment]
you could use `onChange`, when the sheet gets close, it will fire with `index: -1`

hope this answers your question

**Comment by rkrueger11** [comment]
Ah, awesome. Great idea.
