### ISSUE TITLE
Dismissing keyboard as sheet is closing

### ISSUE THREAD

**Issue by jb4e** [gorhom/react-native-bottom-sheet#368]
## Ask your Question

I'm just starting with this library and it seems great so far. Thank you! I'm stuck on one thing. 

I have a bottom sheet with 2 snap points (0 and 80%) that displays a text input at the top. My question is this: 
How can I dismiss the keyboard as a user begins to pull the handle down to dismiss the sheet? I'm currently using the onChange event, but it fires after the sheet is no longer visible, leading to an awkward sequence. 

Is there a different event I can use, or is there special keyboard handling? 

Thanks in advance!

**Comment by kickbk** [comment]
related to my question as well https://github.com/gorhom/react-native-bottom-sheet/issues/356

**Comment by zhigang1992** [comment]
Maybe this could be a part of https://github.com/gorhom/react-native-bottom-sheet/discussions/233

Maybe one way to do it is to pass down a animationIndex like the map example.

The derive its change, runInJs to dismiss the keyboard?

**Comment by carissacks** [comment]
Any update on this question?

**Comment by amjadbouhouch** [comment]
I'm facing this right now, Any update?

**Comment by gorhom** [comment]
hi @jb4e , this should be handled by the pan gesture here https://github.com/gorhom/react-native-bottom-sheet/blob/43ece449ea57578f697d8b49c9825dd28d238b37/src/hooks/useInteractivePanGestureHandler.ts#L110-L120

if user pan down the sheet more than the `KEYBOARD_DISMISS_THRESHOLD` which is 12.5 pixels than it will dismiss the keyboard.

**Comment by carissacks** [comment]
Hi, @jb4e maybe you can take a look at the latest v4. The alpha version has `enablePanDownToClose` prop which might fit yours

**Comment by gorhom** [comment]
this should be resolved on `v4` https://github.com/gorhom/react-native-bottom-sheet/commit/8f34990436f8cc8c1ec1c545488d77db5845166c
