### ISSUE TITLE
Crashing when changing snapPoints

### ISSUE THREAD

**Issue by rkrueger11** [gorhom/react-native-bottom-sheet#370]
# Bug

When changing the snapPoints of a mounted sheet, if the sheet is currently at a higher snap point than one provided in the new props, it crashes.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.4.1   |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 2.0.0   |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1. Mount a sheet and move it to the top most snap point
2. Update the sheet's props removing the top most snap point (via a button or timer)
3. When the sheet's props are updated, it crashes

Describe what you expected to happen:

1. The sheet should move down to the top most snap point of the new provided array
2. It seemingly works well for when the sheet is at a low snap point and it is removed; the sheet moves up to the lowest snap point of the new array.

A real world example of needing the ability to update the snapPoints is when having a search bar w/o results vs w/ results. If there are results, I want to prevent the sheet from being collapsed so that the search results are not visibile, but if there are results, I'm okay with the sheet only being open enough to show the search bar.

## Reproducible sample code
Expo isn't on reanimated v2 yet, so I don't think I can create a snack of this issue.

**Comment by gorhom** [comment]
thanks @rkrueger11 for reporting this bug, it should be resolved with `v3.5.1`
