### ISSUE TITLE
@react-native-community/slider interaction failure with enableContentPanningGesture

### ISSUE THREAD

**Issue by jsamr** [gorhom/react-native-bottom-sheet#372]
# Bug

When the `BottomSheet` component has a `Slider` child from `@react-native-community/slider` and `enableContentPanningGesture` is set to `true`, the pan horizontal gesture fails to move the slider handle.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.2.6  |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 1.13.0   |
| react-native-gesture-handler    | 1.8.0   |
| @react-native-community/slider | 3.0.3 |

## Steps To Reproduce

**Steps to reproduce**

Pan the slider in the BottomSheet

**Expected behavior**

The handle moves.

**Observed behavior**

The handle stays still.

```jsx
import * as React from 'react';
import { View, StyleSheet } from 'react-native';
import Slider from '@react-native-community/slider';
import BottomSheet from '@gorhom/bottom-sheet';

const snapPoints=[200]

export default function App() {
  return (
    <View style={styles.container}>
      <BottomSheet enableContentPanningGesture={true} index={0} snapPoints={snapPoints}>
        <View style={{flexGrow:1}}>
          <Slider />
        </View>
      </BottomSheet>
    </View>
  );
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```

## Reproducible sample code

https://snack.expo.io/@jsamr/bottomsheet-slider-bug

## Ideas for a fix

I wonder if it is possible to setup the pan gesture handler to only capture gestures on the vertical axis?

**Comment by gorhom** [comment]
@jsamr this could be solve with `NativeViewGestureHandler` from `react-native-gesture-handler` 

```tsx
<NativeViewGestureHandler disallowInterruption={true}>
   <Slider />
</NativeViewGestureHandler>
```

**Comment by gorhom** [comment]
or on `v3` you could use `activeOffsetY` & `failOffsetX` like in the view pager example

https://github.com/gorhom/react-native-bottom-sheet/blob/fa7ce6338f336b97475b27461bd18af1f5ed85a3/example/src/screens/advanced/ViewPagerExample.tsx#L14-L15

https://gorhom.github.io/react-native-bottom-sheet/props#gesture-configuration

**Comment by jsamr** [comment]
> <NativeViewGestureHandler disallowInterruption={true}>

Fantastic! Thanks for the tip. Closing but that would be worth mentioning in the docs!

**Comment by Aryk** [comment]
> @jsamr this could be solve with `NativeViewGestureHandler` from `react-native-gesture-handler`
> 
> ```tsx
> <NativeViewGestureHandler disallowInterruption={true}>
>    <Slider />
> </NativeViewGestureHandler>
> ```


I'm on 4.4.3 and this didn't work. Tweaking activeOffsetY and failOffsetX seems to have helped. 

Curious if NativeViewGestureHandler worked for anyone on Android?

**Comment by obasille** [comment]
@Aryk same here, using NativeViewGestureHandler doesn't help when running on my Android phone
