### ISSUE TITLE
[v3] Backdrop not always appearing

### ISSUE THREAD

**Issue by Johan-dutoit** [gorhom/react-native-bottom-sheet#375]
The backdrop isn't always appearing, I tested this with the example app too (I disabled the alert to make it easier to see the difference)

https://user-images.githubusercontent.com/1611055/112805394-d2f86680-9075-11eb-8d56-98b7ce44894d.mov

**Comment by gorhom** [comment]
thanks @Johan-dutoit for reporting this bug and test the pr 👏 , it should be resolved with `v3.6.2`

**Comment by mistenkt** [comment]
Still seems to be an issue with 3.6.3. on BottomSheetModal with included BottomSheetBackdrop:


https://user-images.githubusercontent.com/76615/115599975-78e96a80-a2dc-11eb-896d-d5bfee6c8545.mov
