### ISSUE TITLE
Can a FlatList be scrollable within a BottomSheet?

### ISSUE THREAD

**Issue by cymen** [gorhom/react-native-bottom-sheet#377]
## Ask your Question

I wanted something similar to the map view in the examples except with a BottomSheet that only opens at most 1/2 of the screen height. I got this to work just fine however the FlatList within the bottom sheet is not scrollable (although I could get the "pull from top" to refresh action to happen on Android).

I think looked closer at the map example and observed the list is only scrollable when the modal BottomSheet is fully expanded. I updated my usage to be like the map example w/ the modal variant of BottomSheet and I do see that working when the list is fully expanded (I changed mine so a "whole screen" snap point was present).

I thought perhaps this was a simultaneous gestures issue so I tried doing that but it didn't seem to help. I also tried switching to the FlatList from this module and that didn't seem to make a difference either.

I was left wondering if I was "doing it wrong" and that just isn't how it works. If that is the case, that is fine just was confused. I'm tried up to version 3.6.0 (I am on reanimated v2). I'll try 3.6.1 but wanted to ask in case I should change my approach.

**Comment by gorhom** [comment]
are you using `BottomSheetFlatList` ? 

https://gorhom.github.io/react-native-bottom-sheet/scrollables#bottomsheetflatlist

**Comment by mechaadi** [comment]
Hey, I am also trying to implement scrollview inside the bottom sheet but for some reasons it's not working as it should because I am not able to scroll, no matter what.

Here's how the page looks like: https://prnt.sc/1103qgs
And here's the code of my homepage: https://pastebin.com/CG3QQLSb 

Please help me.

**Comment by gorhom** [comment]
@mechaadi look at the docs https://gorhom.github.io/react-native-bottom-sheet/scrollables/#bottomsheetflatlist

**Comment by mechaadi** [comment]
Hey, ofcourse I've tried all four scrollables but none of them are working. I am unable to scroll in the drawer with any of the four scrollables given in the docs.

**Comment by mechaadi** [comment]
Okay so update, I tried using the bottom sheet directly on app.js file and it worked but when I use it on other pages of my app like the home page then it is not scrolling. I am using a stack navigator with a bottom navigation bar, is that something to do with the scroll issues?

 I am attaching both app.js file and home.js file. The app.js file contains the navigator and home.js file contains the bottom sheet.
 
 App.js: https://pastebin.com/uyFsBTLA
 Home.js: https://pastebin.com/vvQwnNbA

**Comment by BlameFelix** [comment]
@mechaadi it looks like you're trying to import ScrollView from 'react-native'. As stated in the docs you're supposed to use the one from 'react-native-gesture-handler'

`import {
  ScrollView,
  FlatList
} from 'react-native-gesture-handler';`

see [this](https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android)

**Comment by mechaadi** [comment]
@BlameFelix It worked, thank you so much. I didn't notice, my bad.

Anyways, thanks for this great library, cheers. :)

**Comment by cymen** [comment]
I've still got some odd behavior but I think the root cause of my problem was missing this step (I'm using `@react-navigation/native` along with `@react-navigation/bottom-tabs`):

https://docs.swmansion.com/react-native-gesture-handler/docs/#with-wixreact-native-navigation

The odd thing was it was working for a while without that but I probably upgraded a module or multiple modules and broke it without realizing the cause. I'm going to close this as I think the root cause is clear (mistake on my end).

**Comment by jorgegvallejo** [comment]
> @mechaadi it looks like you're trying to import ScrollView from 'react-native'. As stated in the docs you're supposed to use the one from 'react-native-gesture-handler'
> 
> `import { ScrollView, FlatList } from 'react-native-gesture-handler';`
> 
> see [this](https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android)

This worked. Also, anybody looking to implement a SectionList see how to do it [here](https://github.com/software-mansion/react-native-gesture-handler/pull/447)

**Comment by TowhidKashem** [comment]
> @mechaadi it looks like you're trying to import ScrollView from 'react-native'. As stated in the docs you're supposed to use the one from 'react-native-gesture-handler'
> 
> `import { ScrollView, FlatList } from 'react-native-gesture-handler';`
> 
> see [this](https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android)

This is confushing, so don't use the `BottomSheetFlatList` component from `@gorhom/bottom-sheet` and use the `FlatList` from gesture handler?

Using the one from gesture handler fixed the not being able to scroll issue for me but I thought we should be using all the scrollable components from here:

https://ui.gorhom.dev/components/bottom-sheet/scrollables

hey @gorhom sorry to tag you but could you confirm that the above is the way to go or are we missing something here?

**Comment by brianwachira** [comment]
> > @mechaadi it looks like you're trying to import ScrollView from 'react-native'. As stated in the docs you're supposed to use the one from 'react-native-gesture-handler'
> > `import { ScrollView, FlatList } from 'react-native-gesture-handler';`
> > see [this](https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android)
> 
> This is confushing, so don't use the `BottomSheetFlatList` component from `@gorhom/bottom-sheet` and use the `FlatList` from gesture handler?
> 
> Using the one from gesture handler fixed the not being able to scroll issue for me but I thought we should be using all the scrollable components from here:
> 
> https://ui.gorhom.dev/components/bottom-sheet/scrollables
> 
> hey @gorhom sorry to tag you but could you confirm that the above is the way to go or are we missing something here?

Yes, it is very strange. Importing FlatList from react-native-gesture-handler fixes the issue.

**Comment by mgulfam0722** [comment]
> [@mechaadi](https://github.com/mechaadi) it looks like you're trying to import ScrollView from 'react-native'. As stated in the docs you're supposed to use the one from 'react-native-gesture-handler'
> 
> `import { ScrollView, FlatList } from 'react-native-gesture-handler';`
> 
> see [this](https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android)

Thank you so much.

**Comment by therealtgd** [comment]
I tried using ScrollView and FlatList from `react-native-gesture-handler` and I still can't get it to work.
If I use `BottomSheetFlatList` by itself it doesn't work, but if I wrap it with `BottomSheetScrollView` it works although I get an error: `VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.`.

The documentation is really confusing since it states that we should use the BottomSheet scrollable components, but they clearly don't work.

**Comment by Gurinder-saini** [comment]
@therealtgd did you find any solution?

**Comment by jdvplus** [comment]
> I tried using ScrollView and FlatList from `react-native-gesture-handler` and I still can't get it to work. If I use `BottomSheetFlatList` by itself it doesn't work, but if I wrap it with `BottomSheetScrollView` it works although I get an error: `VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.`.
> 
> The documentation is really confusing since it states that we should use the BottomSheet scrollable components, but they clearly don't work.

having the same exact issues.

**Comment by DrWenz** [comment]
having the same issue. A ScrollView inside BottomSheetView is not working, i am not able to scroll down, i always sticks at the top element after i release the pointer.

**Comment by navarroaxel** [comment]
hi @gorhom I notice you have changed the `FlashListExample.tsx` to use the `useBottomSheetScrollableCreator` hook. Is the hook usage the new standard instead of `BottomSheetFlashList`?

**Comment by gorhom** [comment]
@navarroaxel yes! it was a mistake to try to load third party library directly from this package. so i created this hook to extract all the integration needed for the consumer to compose when needed. This allow the library to support LegendList or any upcoming list library.

**Comment by AdiCahyaSaputra** [comment]
> I tried using ScrollView and FlatList from `react-native-gesture-handler` and I still can't get it to work. If I use `BottomSheetFlatList` by itself it doesn't work, but if I wrap it with `BottomSheetScrollView` it works although I get an error: `VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.`.
> 
> The documentation is really confusing since it states that we should use the BottomSheet scrollable components, but they clearly don't work.

i'm experiencing the same issue here

**Comment by t0ma5h** [comment]
I have the same issue with version 5.2.7

**Comment by rochagbr** [comment]
I have the same issue
