### ISSUE TITLE
Doesn't handle clicks in InputAccessoryView

### ISSUE THREAD

**Issue by dev-chief** [gorhom/react-native-bottom-sheet#379]
# Bug

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 1 |
| react-native                    | 0.63.4  |
| react-native-reanimated         |  1.20   |
| react-native-gesture-handler    | 1.10.2   |

## Steps To Reproduce
1) Focus TextInput
2)There will be a view above the keyboard
3) Any click on the accessory will close the keyboard
CODE: 
https://snack.expo.io/@dev_effect/bold-cereal

**Comment by ajp8164** [comment]
This is still not working.
