### ISSUE TITLE
Bottomsheet stuck after close

### ISSUE THREAD

**Issue by Bernard996** [gorhom/react-native-bottom-sheet#383]
# Bug
I've installed BottomSheet 3.6.2 because I read that the after closing stuck problem was fixed, but I still have it. Is there a way to fix it? It appears pretty randomly

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.2   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Open it
2. Close it a random number of times

Describe what you expected to happen:

1. It should always open
2. Sometimes it doesn't

**Comment by Dhanraj-Naik** [comment]
same issue with v2 version.
The method bottomSheetRef.current.expand() no more works if bottomsheet is closed using bottomSheetRef.current.close() to 0%

**Comment by gorhom** [comment]
@Bernard996 thanks for submitting this issue , i have already created a pr to fix it https://github.com/gorhom/react-native-bottom-sheet/pull/389

**Comment by Bernard996** [comment]
> @Bernard996 thanks for submitting this issue , i have already created a pr to fix it https://github.com/gorhom/react-native-bottom-sheet/pull/389

Hi, thank you, I'll try it asap 🙂

**Comment by danielkrux** [comment]
Hey! Any news on this? Currently experiencing the same problem. Version `2.2.3` seems to work fine, but would like to update to V3

**Comment by Bernard996** [comment]
> Hey! Any news on this? Currently experiencing the same problem. Version `2.2.3` seems to work fine, but would like to update to V3

Yes, I've tried it this afternoon and it works perfectly

**Comment by danielkrux** [comment]
Doesn't seem like the PR is merged yet right (#389)? Or am I missing something?

**Comment by gorhom** [comment]
this should be fixed with `v3.6.3` 👏
