### ISSUE TITLE
Bottom sheet not expand again

### ISSUE THREAD

**Issue by haianh130799** [gorhom/react-native-bottom-sheet#384]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.1   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | ^2.0.0   |
| react-native-gesture-handler    | ^1.9.0  |

## Steps To Reproduce

1.Focus to text input of bottom sheet in map screen (i use BottomSheetTextInput)
2.Navigate to another screen
3. Back to the map cannot see bottom sheet any more
-Here is my code 
![bottomSheet](https://user-images.githubusercontent.com/44061072/113376945-2849b600-939d-11eb-96ff-b49281a8de27.png)
-My SearchHandle component
![search-handle](https://user-images.githubusercontent.com/44061072/113376974-41526700-939d-11eb-941b-964738f70b57.png)

**Comment by haianh130799** [comment]
@gorhom please help me

**Comment by gorhom** [comment]
thanks @haianh130799 for submitting this bug, i will look into it later today 👍

**Comment by gorhom** [comment]
@haianh130799 could you please provide a reproducible sample so i could debug it faster ? thanks

**Comment by haianh130799** [comment]
@gorhom i can’t reproduce on snack but i can record screen for you

**Comment by haianh130799** [comment]
-Here is my video
https://user-images.githubusercontent.com/44061072/113651206-c8644f80-96bb-11eb-9fe2-f6dfc893400a.mp4

**Comment by haianh130799** [comment]
on ios works fine on android does not

**Comment by zpv** [comment]
I'm experiencing this issue too, but I noticed it works fine on reanimated v1.

**Comment by ghost** [comment]
Same here.

**Comment by Takuya-H23** [comment]
I'm experiencing this issue with v1

**Comment by gorhom** [comment]
could someone create a reproducible sample code based on this template https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template
