### ISSUE TITLE
Backdrop component doesn't allow to press anything else

### ISSUE THREAD

**Issue by Bernard996** [gorhom/react-native-bottom-sheet#391]
# Bug
When you provide the customBackdrop prop, using the BottomSheetBackdrop component, it overlays everything else and doesn't allow you to press anything, even when BottomSheet is closed

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.2 with stuck on close fix   |
| react-native                    | 0.63.4  |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. use BottomSheet with customBackdrop prop set to BottomSheetBrìackdrop
2. run your app
3. try to touch something, nothing happens

Describe what you expected to happen:

1. When BottomSheet is closed, you should be able to use the rest of the interface

## Reproducible sample code
```
import React, {useState, useEffect, useRef} from 'react';
import { Text, View, TouchableOpacity} from 'react-native';
import BottomSheet, {BottomSheetView, BottomSheetBackdrop} from '@gorhom/bottom-sheet'  //versione 3

const Home = (props) => {

return (	
	<View style={styles.container}>
		<TouchableOpacity style={{width: 800, height: 400, backgoundColor: 'red'}} onPress={()=>{console.log('TouchableOpacity')}}></TouchableOpacity>
		<BottomSheet
			snapPoints={[0,500]}
			index={-1}
			backdropComponent={BottomSheetBackdrop}
			>
			<BottomSheetView>
          <Text>Swipe down to close</Text>
			</BottomSheetView>
		</BottomSheet>
		
	</View>
);
	
export default Home;



```

**Comment by gorhom** [comment]
this should be fixed with `v3.6.3` 👏

**Comment by Jalson1982** [comment]
@gorhom this does not work with the latest version. I just update to 3.6.3 and used backdrop component from example and I do not have any touches.

**Comment by Bernard996** [comment]
> @gorhom this does not work with the latest version. I just update to 3.6.3 and used backdrop component from example and I do not have any touches.

Mine works, just updated to 3.6.3

**Comment by Echelpoel** [comment]
Also experienced this issue with BottomSheetBackdrop when using BottomSheetModal. When using BottomSheet it works as expected.

**Comment by bryanprimus** [comment]
still happen in `v4.4.5`
