### ISSUE TITLE
Have sheet fully close even if handle not dragged fully to bottom of device?

### ISSUE THREAD

**Issue by davemurphysf** [gorhom/react-native-bottom-sheet#393]
## Ask your Question

I have a `BottomSheetModal` setup with only 2 snappoints: [-1, '100%']. Unless I drag the handle beyond the bottom of the screen, it does not close fully.  How can I have the sheet close fully even if not dragged full to the bottom?

**Screenshots**

- Full drag to bottom of screen

![bottom_sheet_closes](https://user-images.githubusercontent.com/408705/113930348-02aa1b80-97a6-11eb-832e-3709fd405771.gif)

- Drag part-way down screen and then released

![bottom_sheet_doesnt_close](https://user-images.githubusercontent.com/408705/113930370-0b9aed00-97a6-11eb-90d8-f18ba4f32f7e.gif)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.2   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Drag handle only part-way down and then release before reaching bottom of device

Describe what you expected to happen:

1. Same behavior as when handle is dragged all the way down the screen; handle disappears post-animation

## Relevant code
(There is a `BottomSheetModalProvider` further up the tree from this component)
```javascript
import React, {
    useCallback,
    useEffect,
    useMemo,
    useRef,
    useState,
} from 'react';
import { BottomSheetModal } from '@gorhom/bottom-sheet';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const giphySDKKey = '...'; 
const gifsToLoad = 25;
const gifRating = 'pg-13';
const maxGifsToLoad = 200;

const GiphyPicker = ({
    onGifSelected,
    buttonVisible,
}: {
    onGifSelected: (gif: IGif) => void;
    buttonVisible: boolean;
}) => {
    const [gifs, setGifs] = useState<Array<IGif>>([]);
    const bottomSheetModalRef = useRef<BottomSheetModal | null>(null);

    const snapPoints = useMemo(() => [-1, '100%'], []);
    const insets = useSafeAreaInsets();

    const handlePresentModalPress = useCallback(() => {
        bottomSheetModalRef.current?.present();
    }, []);

    const handleGiphySearchFocus = useCallback(() => {
        bottomSheetModalRef.current?.expand();
    }, []);

    const handleGifClicked = (gif: IGif) => {
        bottomSheetModalRef.current?.close();
        onGifSelected(gif);
    };

    return (
        <View style={styles.container}>
            {buttonVisible && (
                <Pressable onPress={handlePresentModalPress}>
                    <Giphy />
                </Pressable>
            )}
            <BottomSheetModal
                ref={bottomSheetModalRef}
                index={1}
                snapPoints={snapPoints}
                topInset={insets.top}
            >
                <View style={styles.contentContainer}>
                    <GiphySearchAndGrid
                        onGifClicked={handleGifClicked}
                        onSearchFocus={handleGiphySearchFocus}
                        gifsToLoad={gifsToLoad}
                        gifRating={gifRating}
                        initialGifs={gifs}
                        maxGifsToLoad={maxGifsToLoad}
                    />
                </View>
            </BottomSheetModal>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    contentContainer: {
        flex: 1,
        alignItems: 'center',
    },
    giphyButton: {
        flexShrink: 1,
        maxWidth: '50%',
    },
    buttonPadding: {
        margin: 5,
    },
});

export default GiphyPicker;
```

**Comment by gorhom** [comment]
hi @davemurphysf could you update this issue and follow the template please https://github.com/gorhom/react-native-bottom-sheet/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by baronha** [comment]
> ## Ask your Question
> I have a `BottomSheetModal` setup with only 2 snappoints: [-1, '100%']. Unless I drag the handle beyond the bottom of the screen, it does not close fully. How can I have the sheet close fully even if not dragged full to the bottom?
> 
> **Screenshots**
> 
> * Full drag to bottom of screen
> 
> ![bottom_sheet_closes](https://user-images.githubusercontent.com/408705/113930348-02aa1b80-97a6-11eb-832e-3709fd405771.gif)
> 
> * Drag part-way down screen and then released
> 
> ![bottom_sheet_doesnt_close](https://user-images.githubusercontent.com/408705/113930370-0b9aed00-97a6-11eb-90d8-f18ba4f32f7e.gif)
> 
> ## Environment info
> Library	Version
> @gorhom/bottom-sheet	3.6.2
> react-native	0.63.4
> react-native-reanimated	2.1.0
> react-native-gesture-handler	1.10.3
> ## Steps To Reproduce
> 1. Drag handle only part-way down and then release before reaching bottom of device
> 
> Describe what you expected to happen:
> 
> 1. Same behavior as when handle is dragged all the way down the screen; handle disappears post-animation
> 
> ## Relevant code
> (There is a `BottomSheetModalProvider` further up the tree from this component)
> 
> ```js
> import React, {
>     useCallback,
>     useEffect,
>     useMemo,
>     useRef,
>     useState,
> } from 'react';
> import { BottomSheetModal } from '@gorhom/bottom-sheet';
> import { useSafeAreaInsets } from 'react-native-safe-area-context';
> 
> const giphySDKKey = '...'; 
> const gifsToLoad = 25;
> const gifRating = 'pg-13';
> const maxGifsToLoad = 200;
> 
> const GiphyPicker = ({
>     onGifSelected,
>     buttonVisible,
> }: {
>     onGifSelected: (gif: IGif) => void;
>     buttonVisible: boolean;
> }) => {
>     const [gifs, setGifs] = useState<Array<IGif>>([]);
>     const bottomSheetModalRef = useRef<BottomSheetModal | null>(null);
> 
>     const snapPoints = useMemo(() => [-1, '100%'], []);
>     const insets = useSafeAreaInsets();
> 
>     const handlePresentModalPress = useCallback(() => {
>         bottomSheetModalRef.current?.present();
>     }, []);
> 
>     const handleGiphySearchFocus = useCallback(() => {
>         bottomSheetModalRef.current?.expand();
>     }, []);
> 
>     const handleGifClicked = (gif: IGif) => {
>         bottomSheetModalRef.current?.close();
>         onGifSelected(gif);
>     };
> 
>     return (
>         <View style={styles.container}>
>             {buttonVisible && (
>                 <Pressable onPress={handlePresentModalPress}>
>                     <Giphy />
>                 </Pressable>
>             )}
>             <BottomSheetModal
>                 ref={bottomSheetModalRef}
>                 index={1}
>                 snapPoints={snapPoints}
>                 topInset={insets.top}
>             >
>                 <View style={styles.contentContainer}>
>                     <GiphySearchAndGrid
>                         onGifClicked={handleGifClicked}
>                         onSearchFocus={handleGiphySearchFocus}
>                         gifsToLoad={gifsToLoad}
>                         gifRating={gifRating}
>                         initialGifs={gifs}
>                         maxGifsToLoad={maxGifsToLoad}
>                     />
>                 </View>
>             </BottomSheetModal>
>         </View>
>     );
> };
> 
> const styles = StyleSheet.create({
>     container: {
>         flex: 1,
>         justifyContent: 'center',
>         alignItems: 'center',
>     },
>     contentContainer: {
>         flex: 1,
>         alignItems: 'center',
>     },
>     giphyButton: {
>         flexShrink: 1,
>         maxWidth: '50%',
>     },
>     buttonPadding: {
>         margin: 5,
>     },
> });
> 
> export default GiphyPicker;
> ```

Hi.
Probably not very relevant but I'm curious about your GIPHY image visualizer. too smooth. Can you guide me?
