### ISSUE TITLE
could not run example

### ISSUE THREAD

**Issue by KingAmo** [gorhom/react-native-bottom-sheet#399]
# Bug
```
error Cannot find module 'metro-config/src/defaults/blacklist'
```

![image](https://user-images.githubusercontent.com/29938227/114332874-a49c8000-9b79-11eb-9b83-5d614f816d2c.png)

**Comment by JanithaR** [comment]
Hi, did you find a solution to this?

**Comment by KingAmo** [comment]
@JanithaR  do not open `example` folder, open root folder instead

**Comment by JanithaR** [comment]
Is there another way to run the example app instead of doing `cd example` and `yarn android`? Because doing that throws the same error.

**Comment by KingAmo** [comment]
> Is there another way to run the example app instead of doing `cd example` and `yarn android`? Because doing that throws the same error.

check the `script` field in root `package.json`

**Comment by tluber** [comment]
> > Is there another way to run the example app instead of doing `cd example` and `yarn android`? Because doing that throws the same error.
> 
> check the `script` field in root `package.json`

Still throwing error

**Comment by tluber** [comment]
In root folder:

1. `yarn install`
2. `yarn run example`
3. `cd example/ && yarn android`

**Comment by CavalcanteLeo** [comment]
still not working?
