### ISSUE TITLE
Is it possible to do Reddit like bottom sheet embedded in stack navigator?

### ISSUE THREAD

**Issue by shekharskamble** [gorhom/react-native-bottom-sheet#40]
# Bug

![WhatsApp Image 2020-10-03 at 12 46 09 PM](https://user-images.githubusercontent.com/8002785/94983688-b7ede380-0577-11eb-8d0d-f66975034158.jpeg)
Is it possible to implement something like what reddit does? main screen of stack navigator will be a bottom sheet which will subsequently call other stack screens. Could you please point me to as how we can achieve this?  

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^1.4.1   |
| react-native                    | 0.62.2   |
| react-native-reanimated         | ^1.8.0   |
| react-native-gesture-handler    | ^1.6.1   |

## Steps To Reproduce

1. Click on one of the tab from Tab navigator (Each tab will have its own stack navigator)
2. First screen on stack navigator is bottom sheet
3. Open bottom sheet, Currently it opens and covers entire screen 

Describe what you expected to happen:

1. Click on one of the tab from Tab navigator (Each tab will have its own stack navigator)
2. First screen on stack navigator is bottom sheet
3. Open bottom sheet (refer to attached screen)

**Comment by gorhom** [comment]
hi @shekharskamble , you can achieve this many ways, the easiest will be to wrap the `NavigationContainer` with `BottomSheetModalProvider`, then customise you tab bar and add custom button to trigger the sheet modal 👍

**Comment by shekharskamble** [comment]
Thanks @gorhom
