### ISSUE TITLE
Pull BottomSheet down when at the top of a FlatList

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#403]
## Ask your Question

As long as BottomSheet is not at the top snap point, a `BottomSheetFlatList` inside it is not scrollable. Scrolling it will push the BottomSheet up or down - makes sense in most cases.

In my case, I would like the `FlatList` to be scrollable inside the BottomSheet, until you reach the top of the FlatList. Then when you keep scrolling down, instead of the FlatList showing you you're at the top with that elastic visual behavior, I would like to enable the pull **down** of the BottomSheet. Or in other words, I would like to be able to pull the BottomSheet down when I reach the top of the FlatList.

Could you please suggest a way to do this when using a regular FlatList?

**Comment by jfbn** [comment]
Are you using [BottomSheetFlatList](https://gorhom.github.io/react-native-bottom-sheet/scrollables#bottomsheetflatlist)?

**Comment by kickbk** [comment]
No, as I wrote above I am using a `FlatList` since I need the list to be scrollable in a middle snap point. I'm looking to add the "drag down when you reach the top of the list" functionality of `BottomSheetFlatList`

**Comment by mertuner** [comment]
How to implement this behaviour when using BottomSheetFlatList @jfbn ?

**Comment by jfbn** [comment]
> How to implement this behaviour when using BottomSheetFlatList @jfbn ?

It worked out the box for me, I just followed the documentation from the link I sent above.
