### ISSUE TITLE
Bug with animatedIndex prop of Backdrop Component in BottomSheetModal

### ISSUE THREAD

**Issue by theMasix** [gorhom/react-native-bottom-sheet#407]
## Bug: `animatedIndex` prop of Backdrop Component in BottomSheetModal doesn't work as expected

I think the `animatedIndex` in BottomSheetModal has not correct type and can't be animated using interpolate function of reanimated library.
If I use BottomSheet instead of BottomSheetModal, it works properly, but in BottomSheetModal, `animatedIndex` doesn't work properly

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.3 |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 1.9.0   |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1. Create a BottomSheetModal
2. Provide Custom Backdrop Component
3. Try to animate the Backdrop using `animatedIndex`

Describe what you expected to happen:

1. I expected `animatedIndex` to be an animated value

**Comment by gorhom** [comment]
please provide a reproducible sample code so i could help you, thanks

**Comment by theMasix** [comment]
Main BottomSheetModal Component:
```
<BottomSheetModal
      ref={ref}
      index={1}
      snapPoints={snapPoints}
      onChange={handleSheetChanges}
      bottomInset={0}
      backdropComponent={(props) => <CustomBackdrop {...props} />}
      {...rest}
    >
    ...
```

and this is my CustomBackdrop:
```
import React, { useMemo } from 'react';
import PropTypes from 'prop-types';
import Animated, { Extrapolate, interpolate } from 'react-native-reanimated';

const CustomBackdrop = ({ animatedIndex, style }) => {
  const animatedOpacity = useMemo(
    () =>
      interpolate(animatedIndex, {
        inputRange: [0, 1],
        outputRange: [0, 1],
        extrapolate: Extrapolate.CLAMP,
      }),
    // eslint-disable-next-line
    [animatedIndex],
  );

  const containerStyle = useMemo(
    () => [
      style,
      {
        backgroundColor: '#a8b5eb',
        opacity: animatedOpacity,
      },
    ],
    [style, animatedOpacity],
  );

  return <Animated.View style={containerStyle} />;
};
```

As I said before, If I use BottomSheet instead of BottomSheetModal, the opacity of Backdrop will change by animatedIndex, but in BottomSheetModal, it doesn't.
And another thing, If I provide default BottomSheetBackdrop to BottomSheet, it's opacity changes and everything is good. But if I pass this default component to BottomSheetModal, background is fixed and has no opacity change effect.

Thanks for your response.

**Comment by theMasix** [comment]
Or even this code doesn't work and Backdrop doesn't have any animation.
```
<BottomSheetModal
      ref={ref}
      index={1}
      snapPoints={snapPoints}
      onChange={handleSheetChanges}
      bottomInset={0}
      onDismiss={() => {
        console.log('dismissed');
      }}
      backdropComponent={(props) => (
        <BottomSheetBackdrop {...props} pressBehavior="close" />
      )}
      {...rest}
    >
      // content
</BottomSheetModal>
```

But if I only replace `BottomSheetModal` with `BottomSheet` then backdrop animates!
@gorhom

**Comment by theMasix** [comment]
Issue resolved! It was all about `snapPoints`.

my previous `snapPoints` was
```
  const snapPoints = useMemo(() => [0, contentHeight], [contentHeight]);

```
and I updated them to
```
  const snapPoints = useMemo(() => [contentHeight], [contentHeight]);
```

Now the `animatedIndex` and animations works as expected. I don't know why my previous `snapPoints` worked with `BottomSheet` properly.
It would be great if you can provide more information about `snapPoints` and how they works in the doc. So no one will have any issue same as mine.

@gorhom

**Comment by andreibahachenka** [comment]
i have the same issue, but the solution for me is not suitable

my snappoints are     
const snapPoints = useMemo(() => ['65%', '65%'], [])

**Comment by andreibahachenka** [comment]
described here: https://github.com/gorhom/react-native-bottom-sheet/issues/846
