### ISSUE TITLE
useBottomSheet not returning anything

### ISSUE THREAD

**Issue by ricbermo** [gorhom/react-native-bottom-sheet#408]
# Bug

Use the following snippet:
```javascript
const Component = React.memo(function Component(props) {
  const hooks = useBottomSheet();
  return <Component {...props} />;
});
```

Trying to access any of the methods included in `hooks` would result in an error like `undefined is not an object (evaluating 'hooks.<method>` where `method` is just either expand, collapse, etc.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.3   |
| react-native                    | 0.64.0  |
| react-native-reanimated         | 2.0.1   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Create a custom component
```javascript
const snapPoints = [-1, '100%'];
const ReportAttatchmentsPicker = React.memo(
  function ReportAttatchmentsPicker() {
    const bottomSheetRef = useRef();

    return (
      <NativeViewGestureHandler disallowInterruption={true}>
        <View style={styles.container}>
          <BottomSheet ref={bottomSheetRef} snapPoints={snapPoints}>
            <View style={styles.contentContainer}>
              <Text>Awesome 🎉</Text>
            </View>
          </BottomSheet>
        </View>
      </NativeViewGestureHandler>
    );
  },
);

// use it somewhere
<ReportAttatchmentsPicker />
```
2. Import `useBottomSheet` and use it, like this
```javascript
const Component = React.memo(function Component(props) {
  const hooks = useBottomSheet();
  return <Component {...props} />;
});
```
3. Try to access any of the methods that should be within `hook`, like this `onPress={() => hooks.collapse()`

Describe what you expected to happen:

1. `hooks` should contain the methods. Right now it's just undefined.

## Reproducible sample code

Will add later if this doesn't turn out to be some misconfiguration or something like that.

**Comment by gorhom** [comment]
@ricbermo https://gorhom.github.io/react-native-bottom-sheet/hooks#usebottomsheet

> This hook works at any component inside the `BottomSheet`.

**Comment by ricbermo** [comment]
@gorhom makes sense. TY. I'd that to the docs, tho.
