### ISSUE TITLE
[Question] Is there a way to close the sheet when pressing outside of it?

### ISSUE THREAD

**Issue by mryechkin** [gorhom/react-native-bottom-sheet#41]
# Question

I'm wondering if there is a way to close the sheet (basic) when pressing outside of it? Is there an event handler that I could utilize?

Thanks for your great work, by the way!

**Comment by mryechkin** [comment]
So I think this works.. 🤔 

```js
<BottomSheet
  ...
  backgroundComponent={() => (
    <View style={styles.container} onTouchEnd={() => handleClosePress()} />
  )}
>
```
where `onTouchEnd` is basically my "blur" handler. Only thing is - now when I specify `backgroundComponent` this way, the snap points don't seem to work as expected. For example, the below is using `'100%'`:

<img width="429" alt="Screen Shot 2020-10-03 at 10 48 54 PM" src="https://user-images.githubusercontent.com/5657181/95005830-eba62900-05ca-11eb-9506-3f0ff44546c2.png">

**Comment by gorhom** [comment]
hi @mryechkin, this was intentionally left out of the bottom sheet `static` because it is considered out of the scope.

the only problem with setting this logic on the `backgroundComponent`, that it is wrapped with two views that sets the height to be fixed. 

I would suggest to look at the `OverlayExample` in `example/src/screens/advanced/OverlayExample.tsx`, it should provide a bit of help to achieve that. However, it deserve to be added in the examples to provide best practices 👍

**Comment by mryechkin** [comment]
Thanks for the details @gorhom! Appreciate it. I'll check out the `Overlay` example as you suggest.

Are there any other major concerns with using the `backgroundComponent` approach? I'm still fairly new to React Native world (coming from web), so just want to make sure I'm not trying something completely stupid 😅

Thanks again for your help

**Comment by gorhom** [comment]
>Are there any other major concerns with using the backgroundComponent approach? I'm still fairly new to React Native world (coming from web), so just want to make sure I'm not trying something completely stupid 😅

yeah, the only problem with setting this logic on the backgroundComponent, that it is wrapped with two views that sets the height to be fixed and the background will be moving along with the sheet, so it won't work as expected.

```tsx
<ContentWrapper // < this view sets the height to be fixed
          ref={rootTapGestureRef}
          initialMaxDeltaY={snapPoints[Math.max(initialSnapIndex, 0)]}
          style={containerStyle}
          {...tapGestureHandler}
        >
          <Animated.View style={contentContainerStyle}> // < this view sets the height to be fixed
            {BackgroundComponent && (
              <BackgroundComponent pointerEvents="none" />
            )}
```

**Comment by Angelk90** [comment]
@gorhom , @mryechkin : Are there any news?

P.s.
Can you tell me how I can change the color of the bottom-sheet the upper part together with the arrow, so to speak the white part of the image.

<img width="427" alt="Schermata 2020-11-18 alle 20 01 14" src="https://user-images.githubusercontent.com/20476002/99575856-80c57b80-29d9-11eb-86f6-9a9bd50cda69.png">

**Comment by avet-m** [comment]
@Angelk90 you can use your own component. please have a look at [handlecomponent](https://github.com/gorhom/react-native-bottom-sheet#handlecomponent)  prop

**Comment by Angelk90** [comment]
@avet-m : #74

**Comment by gorhom** [comment]
this should be doable with `backdropComponent`, [read more about it ](https://gorhom.github.io/react-native-bottom-sheet/custom-backdrop)
