### ISSUE TITLE
BottomSheetFlatList ref.current.scrollToIndex not scrolling

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#414]
# Bug

I seems to be unable to make a `BottomSheetFlatList` scroll to a specific index with `restaurantListRef.current?.scrollToIndex({index});`. It does work with a `FlatList` from `react-native` or `react-native-gesture-handler`.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3   |
| expo                   | 41.0.1   |

## Steps To Reproduce

Try to make a flat list inside a BottomSheetModal animate to any index.

## Reproducible sample code

I would share a snack with sdk 41, but they just recently upgraded the sdk and it's hanging on "loading". However, this one should be easy to reproduce. A simple bottomsheet modal containing a BottomSheetFlatList with a few results. Then try with a button click to animate to some index. Test with regular FlatList as well.

**Comment by gorhom** [comment]
Hi @kickbk , you will only be able to any `scroll` method when the sheet is extended, otherwise it will conflict with continues panning gesture.

**Comment by aminerol** [comment]
i was able to get around this with wrapping `scroll` inside `setTimeout` with a `0` timeout value, not sure if this a good solution but it does work for me right now

```js
setTimeout(() => {
            scrollRef.current?.scrollToIndex({
                index: index,
                animated: true,
            });
        }, 0);
```

**Comment by alexanderblackh** [comment]
Hi, is there any plan to reverse this? I don't understand why calling a method manually would interfere with the panning gesture. As far as I can see, calling it manually should help alleviate those concerns because `scrollToIndex` would be fired instead of a scroll gesture.

**Comment by daniel-xyz** [comment]
I'm also stuck at this issue. I display a map above the bottom sheet and want to call "scrollToIndex" after the user clicked a map marker. Would be nice to have support for that.

**Comment by lmeier** [comment]
+1

Trying to implement the exact same behavior @daniel-xyz is attempting, and having no luck.

**Comment by BliiTzZ** [comment]
Have you found a solution for defining a scrollToIndex or an initialScroll? @lmeier @aminerol @alexanderblackh @daniel-xyz

**Comment by kylealwyn** [comment]
> you will only be able to any scroll method when the sheet is extended, otherwise it will conflict with continues panning gesture.

@gorhom why would this be the case?

**Comment by danger9224** [comment]
@gorhom Is it possible to disable this lock-in manually? Eg. my use case would be a horizontal flatlist inside a bottomsheet that serves as a view pager - I don't really see that gesture conflicting with the vertical gestures for showing/hiding, and even if it would, I'd still want to be able to programatically scroll so that eg. it can expand and scroll to the next page at the same time.

**Comment by santirodriguezaffonso** [comment]
Use `FlatList` from `'react-native-gesture-handler'` or `FlashList` and then pass `renderScrollComponent={ScrollView}` from `'react-native-gesture-handler'` for Android OS (fix scrolling behavior)
