### ISSUE TITLE
Seamless scrolling between  bottom sheet and scrollable

### ISSUE THREAD

**Issue by mertuner** [gorhom/react-native-bottom-sheet#415]
## Ask your Question

No matter what I tried I can't achieve something like this.  Even If I use the suggested BottomSheetFlatList,  I can only scroll the inner FlatList. There is no way to interact with BottomSheet except for the handler.  Is there any way to implement a seamless transition when FlatList is on top I can start collapsing BottomSheet.
![ios](https://user-images.githubusercontent.com/27824729/115955012-ff52a780-a4a8-11eb-9d65-4cd18360890e.gif)

**Comment by LucidTechInc** [comment]
Hello were you able to get this to work, am having the same issue but with the scrollview

**Comment by RomanSuvorov** [comment]
Same trouble

**Comment by benkeegan98** [comment]
Anyone have a solution to this?
