### ISSUE TITLE
How to display bottom sheet on top of flatlist?

### ISSUE THREAD

**Issue by tsvetann** [gorhom/react-native-bottom-sheet#418]
## Ask your Question

I have a FlatList with lots of items. Each item has a menu icon. When I click on one of the menu icons I would like to show the bottom sheet with some options. Currently the bottom sheet just does not display at all on top of the flat list. Any ideas or examples I can look at? 

`"@gorhom/bottom-sheet": "2"`
`"react-native-reanimated": "1"`

Thanks

**Comment by ezhkov** [comment]
Could you please provide component layout? I think it could look like this:

```javascript
<View>
  <FlatList />
  <BottomSheet>...</BottomSheet>
</View>
```

**Comment by tsvetann** [comment]
@ezhkov here is what i have:

```js
<ScreenBody>
      <StatusBar backgroundColor={Colors.white} />
      <AddPost />
      <Button onPress={handlePresentPress}>Present Modal</Button>
      <Button onPress={handleDismissPress}>Dismiss Modal</Button>
      <Button onPress={handleExpandPress}>Expand</Button>
      <Button onPress={handleCollapsePress}>Collapse</Button>
      <FlatList
        horizontal={false}
        showsHorizontalScrollIndicator={false}
        data={data?.getFeed}
        renderItem={renderItem}
        keyExtractor={keyExtractor}
        refreshing={networkStatus === 4}
        onRefresh={() => refetch()}
        keyboardShouldPersistTaps="always"
        keyboardDismissMode="on-drag"
        windowSize={10}
      />
      <View style={styles.container}>
          <BottomSheet
            ref={bottomSheetRef}
            type="FlatList"
            index={1}
            snapPoints={snapPoints}
            onChange={handleSheetChanges}>
            <View style={styles.contentContainer}>
              <Text>Awesome 🎉</Text>
            </View>
          </BottomSheet>
        </View>
</ScreenBody>

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    backgroundColor: 'white',
  },
  itemContainer: {
    padding: 6,
    margin: 6,
    backgroundColor: '#eee',
  },
});
```

If I remove the FlatList component all works. When I put it back the BottomSheet never appears and i get no errors. I only added the buttons on top for testing purposes

Thanks for your help

**Comment by ezhkov** [comment]
@tsvetann BottomSheet is expanding at full parent height. His parent has `flex: 1`, but it means that parent should stretch or fit HIS parent. So RN decided to collapse height of <View style={{ flex: 1 }}/>. 

I think you should move BS out of View and put it next to FlatList

**Comment by tsvetann** [comment]
@ezhkov works now. Many thanks for your help
