### ISSUE TITLE
Cannot convert undefined value to object

### ISSUE THREAD

**Issue by Chasty** [gorhom/react-native-bottom-sheet#42]
# Bug

I've tried to add the library two times and follow all the necessary instructions to make it run but I always got `Cannot convert undefined value to object`

What I did:

-   yarn add @gorhom/bottom-sheet@2.0.0-alpha.0
-   yarn add react-native-reanimated@alpha
-   yarn add react-native-gesture-handler
- project.ext.react = [
     enableHermes: true,  // clean and rebuild if changing
]
- import com.facebook.react.bridge.JSIModulePackage;
- import com.swmansion.reanimated.ReanimatedJSIModulePackage;
- @Override
         protected JSIModulePackage getJSIModulePackage() {
          return new ReanimatedJSIModulePackage(); // <- add
       }

<img width="652" alt="Captura de Pantalla 2020-10-05 a la(s) 09 51 39" src="https://user-images.githubusercontent.com/18494040/95095254-6fa60100-06f0-11eb-9b41-47386e2e9615.png">

**Comment by gorhom** [comment]
hi @Chasty , in order to help you with your issue, please recreate the issue and follow the issue template.
