### ISSUE TITLE
Touchables not styleable, can't be used with ref and press event bubbles. - Android

### ISSUE THREAD

**Issue by kenshinman** [gorhom/react-native-bottom-sheet#420]
# Bug
This bug is only on Android. Works well on iOS

I imported TouchableOPacity from this library so I can use it within the BottomSheet. Works well but I have the following issues
- styling the dimensions (width/height) does not work when you use percentages e.g `width='30%'`
- trying to use ref on the Touchable in TypeScript e.g. buttonRef= useRef<TouchableOpacity>(null) gives this error `'TouchableOpacity' refers to a value but is being used as a type here. Did you mean 'typeof TouchableOpacity'?`
- Lastly, I noticed that press event bubbles when you nest the TouchableOpacity in 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.3.0  |
| react-native                    | ~0.63.4  |
| react-native-reanimated         | ~1.13.0 |
| react-native-gesture-handler    | ~1.8.0   |

## Steps To Reproduce

1. Use the `TouchableOpacity` component and style as `<TouchableOpcity style={{width: '40%'}} />
2. for ref bug, see second bullet point above
3.   
    ``` 
          <TouchableOpaity onPress={() => console.log('a')}> 
                 <TouchableOpaity onPress={() => console.log('b')}>Click B<T/ouchableOpaity>
           <T/ouchableOpaity>
           when B is pressed, it logs a and b
    ```

Describe what you expected to happen:

1. 
2.

## Reproducible sample code

```
    import { TouchableOpacity } from '@gorhom/bottom-sheet';

...

    const triggerRef = useRef<View>(null);
...
    const getPositions = () => {
        triggerRef.current?.measure((x, y, w, h, xAbs, yAbs) => {
          handlePosition(yAbs, xAbs, h, w);
        });
       };
...
    <TouchableOpacity
        ref={triggerRef as any}
        activeOpacity={0.6}
        onPress={() => {
          getPositions();
        }}
      >
        {triggerElement}
      </TouchableOpacity>
```

**Comment by ezhkov** [comment]
@kenshinman I think, it's not BottomSheet issue. It's react-native-gesture-handler does something wrong:

https://snack.expo.io/@ezhkov/rngh-nested-touchable-android-bug
