### ISSUE TITLE
How to attach a component to move with the bottom sheet?

### ISSUE THREAD

**Issue by karimcambridge** [gorhom/react-native-bottom-sheet#423]
## Ask your Question

Hi, for example, think Uber or Lyft, or any rideshare app, there is a location icon above the bottom sheet that moves with the sheet,

how can I achieve this?

**Comment by ezhkov** [comment]
@karimcambridge You can do this using `animatedPosition` prop.

```javascript
import Animated, {
  Extrapolate,
  useValue,
  interpolate,
} from 'react-native-reanimated';

const App = () => {
  const snapPoints = [100, 200, 500];
  const currentPosition = useValue(0);
  const elementTranslateY = useMemo(() => interpolate({
    inputRange: [100, 300],
    outputRange: [0, 200],
    extrapolate: Extrapolate.CLAMP,
  }), [snapPoints]);

  return (
    <View>
      <Animated.View style={{ transform: [{translateY: elementTranslateY}]}}>
        <SomeContent/>
      </Animated.View>
      <BottomSheet
        snapPoints={snapPoints}
        animatedPosition={currentPosition}
        index={0}
      >
      ...
      </BottomSheet>
    </View>
  )
}

```

**Comment by karimcambridge** [comment]
@ezhkov wow thank you, is that for reanimated 2.1.0 though? I'm getting errors like `TypeError: undefined is not an object (evaluating 'input.length')`

the `interpolate` function seems to require more arguments

Figured it out, the `interpolate` function just removed the object and uses more arguments now, but I don't know what I should put for the first argument.

**Comment by ezhkov** [comment]
@karimcambridge Nope, it's for BS v2 and Reanimated v1. But I see, I made a mistake. You should pass `currentPosition` as first argument to `interpolate`:

```javascript
const elementTranslateY = useMemo(() => interpolate(currentPosition, {
    inputRange: [100, 300],
    outputRange: [0, 200],
    extrapolate: Extrapolate.CLAMP,
  }), [snapPoints]);
```

If you want to use Reanimated v2 with BS v3, you probably should write something like this:

```javascript
import Animated, {
  Extrapolate,
  useSharedValue,
  interpolateNode,
} from 'react-native-reanimated';

const App = () => {
  const snapPoints = [100, 200, 500];
  const currentPosition = useSharedValue(0);
  const elementTranslateY = useMemo(() => interpolateNode(currentPosition.value, {
    inputRange: [100, 300],
    outputRange: [0, 200],
    extrapolate: Extrapolate.CLAMP,
  }), [snapPoints]);

  return (
    <View>
      <Animated.View style={{ transform: [{translateY: elementTranslateY}]}}>
        <SomeContent/>
      </Animated.View>
      <BottomSheet
        snapPoints={snapPoints}
        animatedPosition={currentPosition}
        index={0}
      >
      ...
      </BottomSheet>
    </View>
  )
}
```

**Comment by karimcambridge** [comment]
@ezhkov Hmm, when I print `currentPosition` it returns an empty array.

Not really that knowledgable in this reanimated stuff, I'll try to do some research on how to get the correct `currentPosition` value

I think `animatedPosition` might be bugged in bottom-sheet v3 as related to #376

**Comment by ezhkov** [comment]
@karimcambridge Bad news are that you cannot debug `reanimated` values as usual.

I noticed that animatedPosition in v3 differs from the same in v2. It kinda mirrored. If I use v2 I can write code as in example above. But in v3 it seems that animatedPosition = 0 complied to the most top snapPoint (window height)

**Comment by karimcambridge** [comment]
Damn,. Yea something is up with animatedPosition, seems I have to wait cause it might be a bug with the repo currently.

Thank you so much ;\

**Comment by willerrodrigo** [comment]
@karimcambridge Did you try with animatedIndex?

**Comment by karimcambridge** [comment]
> @karimcambridge Did you try with animatedIndex?

No, I don't know how.

**Comment by willerrodrigo** [comment]
> @karimcambridge Nope, it's for BS v2 and Reanimated v1. But I see, I made a mistake. You should pass `currentPosition` as first argument to `interpolate`:
> 
> ```js
> const elementTranslateY = useMemo(() => interpolate(currentPosition, {
>     inputRange: [100, 300],
>     outputRange: [0, 200],
>     extrapolate: Extrapolate.CLAMP,
>   }), [snapPoints]);
> ```
> 
> If you want to use Reanimated v2 with BS v3, you probably should write something like this:
> 
> ```js
> import Animated, {
>   Extrapolate,
>   useSharedValue,
>   interpolateNode,
> } from 'react-native-reanimated';
> 
> const App = () => {
>   const snapPoints = [100, 200, 500];
>   const currentPosition = useSharedValue(0);
>   const elementTranslateY = useMemo(() => interpolateNode(currentPosition.value, {
>     inputRange: [100, 300],
>     outputRange: [0, 200],
>     extrapolate: Extrapolate.CLAMP,
>   }), [snapPoints]);
> 
>   return (
>     <View>
>       <Animated.View style={{ transform: [{translateY: elementTranslateY}]}}>
>         <SomeContent/>
>       </Animated.View>
>       <BottomSheet
>         snapPoints={snapPoints}
>         animatedPosition={currentPosition}
>         index={0}
>       >
>       ...
>       </BottomSheet>
>     </View>
>   )
> }
> ```

@karimcambridge It is the same, but with BottomSheet animatedIndex prop instead animatedPosition.

**Comment by TeyimPila** [comment]
Has anyone been able to solve this? The Animated element is fixed and not moving with the bottom sheet as it is supposed to

**Comment by TeyimPila** [comment]
I got this to work, in case you're struggling with this too...

The code has some hacks but the main idea works and can be improved. 

It is worth noting that this only works when you pull to snapPoints and isn't moving WHILE you're moving (dragging) the bottom sheet. Aside from that, it works great. 

```JavaScript
import React, {
  createRef, useCallback, useMemo, useState,
} from 'react';
import {
  Dimensions, Text, View,
} from 'react-native';

import { Icon } from 'native-base';
import BottomSheet from '@gorhom/bottom-sheet';
import Animated, {
  Extrapolate,
  interpolateNode,
} from 'react-native-reanimated';

const windowHeight = Dimensions.get('window').height;

const Container = () => {

  const [toPos, setToPos] = useState(0);

  const bottomSheetRef = createRef();

  // variables
  const snapPoints = useMemo(() => [0, windowHeight / 4, windowHeight / 2, windowHeight], []);

  const handleSheetAnimate = useCallback((from, to) => {
    setToPos(snapPoints[to]);
    console.log('handleSheetAnimate', { from, to });
  }, [snapPoints]);

  const elementTranslateY = interpolateNode(toPos + 20, {
    inputRange: [0, 500],
    outputRange: [0, -500],
    extrapolate: Extrapolate.CLAMP,
  });

  return (
    <View>

      <Animated.View style={{ transform: [{ translateY: elementTranslateY }] }}>
          <Icon name="ios-close" size={10} color="#01a699" />
      </Animated.View>
      <BottomSheet
        style={{ backgroundColor: '#fff' }}
        ref={bottomSheetRef}
        index={-1}
        snapPoints={snapPoints}
        onAnimate={handleSheetAnimate}
      >
        <View>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
};

export default Container;
```

**Comment by gorbypark** [comment]
It's a complete hack, but I was able to implement a component moving with the bottom sheet by absolutely positioning the component inside the customBackground component
```js
<BottomSheet
  backgroundComponent={props => <CustomBackground {...props} />}
  ...
>
  ...
</BottomSheet>
```

```js
  const CustomBackground = ({style}) => {
    return (
      <>
        <View
          style={[
            {...style},
          ]}
        />
        <View style={{position: 'absolute', top: -45, right: 0}}>
          <CustomMovingElementGoesHere />
        </View>
      </>
    );
  };
```
The only issue I have is that Android is not receiving onPress events if `<CustomMovingElementGoesHere />` is a pressable/touchable.  I've tried importing touchables from both react-native and react-native-gesture-handler, and they both just don't work on Android (but work great on iOS).  If anyone has any ideas how to get Android working I'd be all ears!  Although it's a bit hacky, it seems like a more elegant solution than listening to `animatedPosition` and re-animating something based on that..

**Comment by karimcambridge** [comment]
> It's a complete hack, but I was able to implement a component moving with the bottom sheet by absolutely positioning the component inside the customBackground component
> 
> ```js
> <BottomSheet
>   backgroundComponent={props => <CustomBackground {...props} />}
>   ...
> >
>   ...
> </BottomSheet>
> ```
> 
> ```js
>   const CustomBackground = ({style}) => {
>     return (
>       <>
>         <View
>           style={[
>             {...style},
>           ]}
>         />
>         <View style={{position: 'absolute', top: -45, right: 0}}>
>           <CustomMovingElementGoesHere />
>         </View>
>       </>
>     );
>   };
> ```
> 
> The only issue I have is that Android is not receiving onPress events if `<CustomMovingElementGoesHere />` is a pressable/touchable. I've tried importing touchables from both react-native and react-native-gesture-handler, and they both just don't work on Android (but work great on iOS). If anyone has any ideas how to get Android working I'd be all ears! Although it's a bit hacky, it seems like a more elegant solution than listening to `animatedPosition` and re-animating something based on that..

Will v4 have a way to easily implement this?

Think, lyft or uber where their bottom sheet has a location icon attached and moving with it.

**Comment by knxlab** [comment]
Hey

In case someone is looking for the solution : 
"@gorhom/bottom-sheet": "^4",
"react-native-reanimated": "^2.4.1",

You should use a shared value (useSharedValue), and create a style with "useAnimatedStyle"

Here is a full working example.


```typescript
import React from 'react';
import Animated, {
  useSharedValue,
  interpolate,
  useAnimatedStyle,
} from 'react-native-reanimated';
import BottomSheet from '@gorhom/bottom-sheet';
import { StyleSheet, View } from 'react-native';

const App = () => {
  const snapPoints = [100, 200, 500];
  const currentPosition = useSharedValue(0);

  const animatedStyles = useAnimatedStyle(() => {
    const scale = interpolate(currentPosition.value, [100, 500], [1, 2]);

    return {
      transform: [{ scale }],
    };
  });

  return (
    <View style={styles.container}>
      <Animated.View
        style={[
          {
            position: 'absolute',
            top: 100,
            width: 200,
            height: 200,
            backgroundColor: 'blue',
            zIndex: 100000,
          },
          animatedStyles,
        ]}
      />
      <BottomSheet
        snapPoints={snapPoints}
        animatedPosition={currentPosition}
        index={0}>
        <View
          style={{
            width: '100%',
            height: '100%',
            backgroundColor: 'green',
          }}></View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
  },
});

```

**Comment by abazudosen** [comment]
> 

doesnt work!! the component doesnt move as I drag the bottom sheet

**Comment by abazudosen** [comment]
> Hey
> 
> In case someone is looking for the solution : "@gorhom/bottom-sheet": "^4", "react-native-reanimated": "^2.4.1",
> 
> You should use a shared value (useSharedValue), and create a style with "useAnimatedStyle"
> 
> Here is a full working example.
> 
> ```ts
> import React from 'react';
> import Animated, {
>   useSharedValue,
>   interpolate,
>   useAnimatedStyle,
> } from 'react-native-reanimated';
> import BottomSheet from '@gorhom/bottom-sheet';
> import { StyleSheet, View } from 'react-native';
> 
> const App = () => {
>   const snapPoints = [100, 200, 500];
>   const currentPosition = useSharedValue(0);
> 
>   const animatedStyles = useAnimatedStyle(() => {
>     const scale = interpolate(currentPosition.value, [100, 500], [1, 2]);
> 
>     return {
>       transform: [{ scale }],
>     };
>   });
> 
>   return (
>     <View style={styles.container}>
>       <Animated.View
>         style={[
>           {
>             position: 'absolute',
>             top: 100,
>             width: 200,
>             height: 200,
>             backgroundColor: 'blue',
>             zIndex: 100000,
>           },
>           animatedStyles,
>         ]}
>       />
>       <BottomSheet
>         snapPoints={snapPoints}
>         animatedPosition={currentPosition}
>         index={0}>
>         <View
>           style={{
>             width: '100%',
>             height: '100%',
>             backgroundColor: 'green',
>           }}></View>
>       </BottomSheet>
>     </View>
>   );
> };
> 
> const styles = StyleSheet.create({
>   container: {
>     width: '100%',
>     height: '100%',
>     backgroundColor: 'white',
>   },
> });
> ```

doesnt work!! the component doesnt move as I drag the bottom sheet

**Comment by larbizard** [comment]
> It's a complete hack, but I was able to implement a component moving with the bottom sheet by absolutely positioning the component inside the customBackground component
> 
> ```js
> <BottomSheet
>   backgroundComponent={props => <CustomBackground {...props} />}
>   ...
> >
>   ...
> </BottomSheet>
> ```
> 
> ```js
>   const CustomBackground = ({style}) => {
>     return (
>       <>
>         <View
>           style={[
>             {...style},
>           ]}
>         />
>         <View style={{position: 'absolute', top: -45, right: 0}}>
>           <CustomMovingElementGoesHere />
>         </View>
>       </>
>     );
>   };
> ```
> 
> The only issue I have is that Android is not receiving onPress events if `<CustomMovingElementGoesHere />` is a pressable/touchable. I've tried importing touchables from both react-native and react-native-gesture-handler, and they both just don't work on Android (but work great on iOS). If anyone has any ideas how to get Android working I'd be all ears! Although it's a bit hacky, it seems like a more elegant solution than listening to `animatedPosition` and re-animating something based on that..

Did you manage to make the component clickable ? Thank you for your help

**Comment by gorbypark** [comment]
> > It's a complete hack, but I was able to implement a component moving with the bottom sheet by absolutely positioning the component inside the customBackground component
> > ```js
> > <BottomSheet
> >   backgroundComponent={props => <CustomBackground {...props} />}
> >   ...
> > >
> >   ...
> > </BottomSheet>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> >   const CustomBackground = ({style}) => {
> >     return (
> >       <>
> >         <View
> >           style={[
> >             {...style},
> >           ]}
> >         />
> >         <View style={{position: 'absolute', top: -45, right: 0}}>
> >           <CustomMovingElementGoesHere />
> >         </View>
> >       </>
> >     );
> >   };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The only issue I have is that Android is not receiving onPress events if `<CustomMovingElementGoesHere />` is a pressable/touchable. I've tried importing touchables from both react-native and react-native-gesture-handler, and they both just don't work on Android (but work great on iOS). If anyone has any ideas how to get Android working I'd be all ears! Although it's a bit hacky, it seems like a more elegant solution than listening to `animatedPosition` and re-animating something based on that..
> 
> Did you manage to make the component clickable ? Thank you for your help

I ended up using the other solution posted above, using the `animatedPosition` prop and `useSharedValue` to track the position of the bottom sheet, then use an reanimated style to translate the button based on that animatedPosition.  It works well, for me.

**Comment by larbizard** [comment]
> > > It's a complete hack, but I was able to implement a component moving with the bottom sheet by absolutely positioning the component inside the customBackground component
> > > ```js
> > > <BottomSheet
> > >   backgroundComponent={props => <CustomBackground {...props} />}
> > >   ...
> > > >
> > >   ...
> > > </BottomSheet>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```js
> > >   const CustomBackground = ({style}) => {
> > >     return (
> > >       <>
> > >         <View
> > >           style={[
> > >             {...style},
> > >           ]}
> > >         />
> > >         <View style={{position: 'absolute', top: -45, right: 0}}>
> > >           <CustomMovingElementGoesHere />
> > >         </View>
> > >       </>
> > >     );
> > >   };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The only issue I have is that Android is not receiving onPress events if `<CustomMovingElementGoesHere />` is a pressable/touchable. I've tried importing touchables from both react-native and react-native-gesture-handler, and they both just don't work on Android (but work great on iOS). If anyone has any ideas how to get Android working I'd be all ears! Although it's a bit hacky, it seems like a more elegant solution than listening to `animatedPosition` and re-animating something based on that..
> > 
> > 
> > Did you manage to make the component clickable ? Thank you for your help
> 
> I ended up using the other solution posted above, using the `animatedPosition={currentPosition}` prop to track the position of the bottom sheet, then use an animated style to translate the button based on that position. It works well, for me.

I will try this thank you !

**Comment by larbizard** [comment]
> > > > It's a complete hack, but I was able to implement a component moving with the bottom sheet by absolutely positioning the component inside the customBackground component
> > > > ```js
> > > > <BottomSheet
> > > >   backgroundComponent={props => <CustomBackground {...props} />}
> > > >   ...
> > > > >
> > > >   ...
> > > > </BottomSheet>
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```js
> > > >   const CustomBackground = ({style}) => {
> > > >     return (
> > > >       <>
> > > >         <View
> > > >           style={[
> > > >             {...style},
> > > >           ]}
> > > >         />
> > > >         <View style={{position: 'absolute', top: -45, right: 0}}>
> > > >           <CustomMovingElementGoesHere />
> > > >         </View>
> > > >       </>
> > > >     );
> > > >   };
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > The only issue I have is that Android is not receiving onPress events if `<CustomMovingElementGoesHere />` is a pressable/touchable. I've tried importing touchables from both react-native and react-native-gesture-handler, and they both just don't work on Android (but work great on iOS). If anyone has any ideas how to get Android working I'd be all ears! Although it's a bit hacky, it seems like a more elegant solution than listening to `animatedPosition` and re-animating something based on that..
> > > 
> > > 
> > > Did you manage to make the component clickable ? Thank you for your help
> > 
> > 
> > I ended up using the other solution posted above, using the `animatedPosition={currentPosition}` prop to track the position of the bottom sheet, then use an animated style to translate the button based on that position. It works well, for me.
> 
> I will try this thank you !

It's working like a charm !
