### ISSUE TITLE
Expo web Can't find file Touchables.js

### ISSUE THREAD

**Issue by zifahm** [gorhom/react-native-bottom-sheet#424]
Using bottom-sheet with Expo web
Working fine on mobile 

```Module not found: Can't resolve './Touchables' in 'project/project-name/node_modules/@gorhom/bottom-sheet/lib/module/components/touchables'```

Any Idea how to solve this?

**Comment by fikretsefa** [comment]
Hi, did you find any solution ?

**Comment by zifahm** [comment]
Nope.
I checked and its seems like the Touchable files are only defined for ios and android and index.js files for the web, maybe renaming it to index.web.js could work! or Touchable.web.js.
