### ISSUE TITLE
Unable to close the bottom sheet completely v3

### ISSUE THREAD

**Issue by kaisiant** [gorhom/react-native-bottom-sheet#429]
# Bug
Based on the docs,  `provide -1 to initiate bottom sheet in closed state.` But it is not working.
```
 const snapPoints = useMemo(
    () => [
      -1,
      Platform.OS === 'ios' ? height - 113 : height - 95,
    ],
    []
  )
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         |^3 |
| react-native                    | https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz   |
| react-native-reanimated         | ~2.1.0  |
| react-native-gesture-handler    | ~1.10.2  |

## Steps To Reproduce

https://user-images.githubusercontent.com/26655111/117109273-fb7f2900-adb6-11eb-8e93-82948b26e1ee.mov

1. Drag down the bottom sheet to close

Describe what you expected to happen:

1. The bottom sheet closed completely

**Comment by kickbk** [comment]
Have you tried adding `height` to your dependency array?
```
 const snapPoints = useMemo(
    () => [
      -1,
      Platform.OS === 'ios' ? height - 113 : height - 95,
    ],
    [height]
  )
  ```

**Comment by kaisiant** [comment]
> Have you tried adding `height` to your dependency array?
> 
> ```
>  const snapPoints = useMemo(
>     () => [
>       -1,
>       Platform.OS === 'ios' ? height - 113 : height - 95,
>     ],
>     [height]
>   )
> ```



> Have you tried adding `height` to your dependency array?
> 
> ```
>  const snapPoints = useMemo(
>     () => [
>       -1,
>       Platform.OS === 'ios' ? height - 113 : height - 95,
>     ],
>     [height]
>   )
> ```

Still unable to close it completely. :(

**Comment by kickbk** [comment]
Could you please reproduce on snack and share a link?

**Comment by kaisiant** [comment]
https://snack.expo.io/@kaisian97/crabby-kiwi

> Could you please reproduce on snack and share a link?

1. Click open
2. Drag down the modal slowly

**Comment by dparrelli** [comment]
Have you tried only having one value in the snapPoints array instead of two, and then setting the BottomSheetModal index prop value to 0?

ie. 
```
const snapPoints = useMemo(
  () => [
    Platform.OS === 'ios' ? height - 113 : height - 95,
  ],
  []
)

...

<BottomSheetModal
  index={0}
>
```

**Comment by gorhom** [comment]
@kaisian97 could you test on `v4` ? #427

**Comment by kaisiant** [comment]
> #427

Works fine on v4.
