### ISSUE TITLE
Can't resolve './Touchables' 

### ISSUE THREAD

**Issue by AppLetico** [gorhom/react-native-bottom-sheet#434]
Failed to compile.
/Users/xxxx/workspace/nextga/xxx-test-app/node_modules/xxx-ui-components/node_modules/@gorhom/bottom-sheet/lib/module/components/touchables/index.js
Module not found: Can't resolve './Touchables' in '/Users/xxx/workspace/nextga/xxx-app/node_modules/xxx-ui-components/node_modules/@gorhom/bottom-sheet/lib/module/components/touchables'

Tested on expo web. @gorhom/bottom-sheet@^3

**Comment by GitYu2016** [comment]
Ohno I have the same issue.

**Comment by tuliosciotta** [comment]
Same issue here.
