### ISSUE TITLE
Multiple Bottom Sheets in a ScrollView

### ISSUE THREAD

**Issue by ahmadqwer** [gorhom/react-native-bottom-sheet#435]
## Ask your Question

Hello,

I would like to know if is possible to implement the below using this library.
![k](https://user-images.githubusercontent.com/9438475/117653587-40330780-b19d-11eb-9308-6759eddc6244.png)

As you see this is the homescreen (the blue one), and over it there are multiple bottom sheets that i can scroll between them Horizontally and each of which can be extended on scrolling and can close and then show the Home screen (the blue one).

Is it possible with this library?

Thank you.

**Comment by gorhom** [comment]
hi @ahmadqwer , yes you can achieve this with static `BottomSheet` , look at the view pager example https://github.com/gorhom/react-native-bottom-sheet/blob/v3/example/src/screens/integrations/ViewPagerExample.tsx

**Comment by ahmadqwer** [comment]
@gorhom Thank you, i was able to make it, 

Just one question.

https://user-images.githubusercontent.com/9438475/118518351-b5c04a00-b740-11eb-82f7-27cc66f3a9b3.mp4

Is there a way I can make the 3 bottom sheets drag and move together? if i want to drag one of them i want the others move with it and snap together.

Thanks again :)
