### ISSUE TITLE
Different content - snap points?

### ISSUE THREAD

**Issue by marcibk** [gorhom/react-native-bottom-sheet#439]
Hi there :)
I´am planning to switch to react-native-bottom-sheet for the current project.
I would like to have a different content for different snapPoints. E.g when it´s opened at 25% I have a "swipe up for more content" animation/content with a headline. When the user swipes up (e.g. 80% snap point) other data/images etc. should be displayed.

The problem at the moment is, that onChange only triggers when the Panel is snapping to the next value, so I have "white screen" until the user moves the panel to the top/snaps to the new value. I want to change the content directly when the snapPoint is not at 25% anymore. Is that possible somehow?

And one other thing I couldn´t figure out yet, is that when I have an image at the top, there is still the header with the gray "slider thing" and the white bar. Is it somehow possible to make it transparent? When I try to set the image to absolute position it´s not showing anymore.

Thank you so much for your time & help!

Kind regards

**Comment by gorhom** [comment]
hi @traingethermarc 👋

you could achieve this with `animatedIndex` prop https://gorhom.github.io/react-native-bottom-sheet/props#animatedindex, where you will need to react to this value and animate your contents.

>And one other thing I couldn´t figure out yet, is that when I have an image at the top, there is still the header with the gray "slider thing" and the white bar. Is it somehow possible to make it transparent? When I try to set the image to absolute position it´s not showing anymore.

you need to set a minimal height to the handle

**Comment by marcibk** [comment]
Hi @gorhom thanks for your reply! `animatedIndex` is no callback, so I don´t have the possibility to react to the value? I tried it with useSharedValue but also no results... 

You mean the prop handleHeight from `BottomSheetModal`? When I set it to 0 or sth. else it doesn´t change anything.. 

Thank you for your time & the amazing work :)

**Comment by yafetHamouda** [comment]
@traingethermarc did you find a solution ?
