### ISSUE TITLE
function components cannot have string refs. we recommend using useref() instead

### ISSUE THREAD

**Issue by akzone** [gorhom/react-native-bottom-sheet#44]
How to fix this?

**Comment by sa8ab** [comment]
Try removing the Type of ref from default code that you copied

**Comment by gorhom** [comment]
please follow the bug report template. so we could help you

**Comment by jvence** [comment]
Same problem

**Comment by Killian-Smith** [comment]
In case anyone comes across this and has the same problem, here is the fix.

```
-  const bottomSheetRef = useRef<BottomSheet>(null);
+  const bottomSheetRef = useRef(null);
```

The reason you might need to do this is because the code in the example is typescript, whilst you may be using plain javascript!
