### ISSUE TITLE
Property "React" does not exists

### ISSUE THREAD

**Issue by tarikfp** [gorhom/react-native-bottom-sheet#440]
## Property React Does not Exists

Hi. I am using typescript in the project. I installed the app and tried basic usage code. from [here](https://gorhom.github.io/react-native-bottom-sheet/usage)  But faced error below.

![reactdoesnotexist](https://user-images.githubusercontent.com/61876765/118197081-eb221a80-b456-11eb-8d53-cecfbc862886.jpg)

I did some research and ended up with this issue https://github.com/facebook/metro/issues/646 

Even though I tried all of the possible solutions that mentioned in issue above, error still remains..

metro.config.js file below, metro version=> **_metro "^0.59.0"_**

![image](https://user-images.githubusercontent.com/61876765/118197570-e27e1400-b457-11eb-915d-eabc39e033f9.png)

.babelrc file below, babel version=>  **_"@babel/core": "^7.8.4",_**

![image](https://user-images.githubusercontent.com/61876765/118197525-ce3a1700-b457-11eb-8311-5604c6415df6.png)

The way I import react in every file on the project is => **import * as React from 'react'**

The way I imported bottom sheet, 

![image](https://user-images.githubusercontent.com/61876765/118198349-5c62cd00-b459-11eb-97e5-bca9f14bd54f.png)

**Comment by tarikpnr** [comment]
Ok. It can be closed. It resolved.
