### ISSUE TITLE
access to useBottomSheetInternal

### ISSUE THREAD

**Issue by branikclimbs** [gorhom/react-native-bottom-sheet#444]
## Ask your Question

Is there a way to access useBottomSheetInternal hook? So I can use it in my custom form elements?
https://github.com/gorhom/react-native-bottom-sheet/blob/v3/src/components/bottomSheetTextInput/BottomSheetTextInput.tsx

**Comment by vonovak** [comment]
hello, have you tried importing it? :)

`import useBottomSheetInternal from '@gorhom/bottom-sheet/src/hooks/useBottomSheetInternal'`

**Comment by gorhom** [comment]
@branislaav , @vonovak  i added this as an improvement to `v4` 👍
