### ISSUE TITLE
Can't drag bottomsheet or bottomsheet modal in android device or emulator

### ISSUE THREAD

**Issue by iarmankhan** [gorhom/react-native-bottom-sheet#450]
# Bug

I am using this library in react-native-cli project and I can't drag the bottom sheet to any snap point in any android device or emulator. everything works fine on IOS device. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.3.0   |
| react-native                    | 0.64.0  |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Add following libraries in react-native-cli project
2. Create a bottom sheet using example from documentation
3. Run on android

Describe what you expected to happen:

1. It should be draggable on android

## Reproducible sample code

`<BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>`

**Comment by iarmankhan** [comment]
Sorry my bad. react native gesture handler was not installed properly. Thank you.

**Comment by PadovaY** [comment]
@iarmankhan I'm having the same issue, can you elaborate on the solution? 🙏

**Comment by iarmankhan** [comment]
Hi, as I stated in other comment it was my issue in setup, I forgot to add native code related to react native gesture handler and react native reanimated 2.

**Comment by tungduonghgg123** [comment]
I can drag it on BottomSheet but unable to drag on BottomSheetModal. Turns out I haven't set up react-native-gesture-handler fully for Android
https://docs.swmansion.com/react-native-gesture-handler/docs/#with-wixreact-native-navigation
