### ISSUE TITLE
[V4.alpha3] Bottom Sheet Modal issue with keyboard and backdrop

### ISSUE THREAD

**Issue by elgorditosalsero** [gorhom/react-native-bottom-sheet#454]
# Bug

When opening a `BottomSheetModal` with `keyboardBehavior={'interactive'}` that contains a `BottomSheetScrollView` it has issues with height calculation on **Android**; in **iOS** it has issues with the _ScrollableView_

Another issue is that's there is no backdrop using a custom component passed as prop: `backdropComponent={Backdrop}`

On version 3.6.5 those things works "fine" with a patch to the source code inspired by [this](https://github.com/gorhom/react-native-bottom-sheet/issues/405) issue.

The patch is: 
```
export const useKeyboard = () => {
   //#region variables
-  const shouldHandleKeyboardEvents = useSharedValue(false);
+  const shouldHandleKeyboardEvents = useSharedValue(true);
   const keyboardState = useSharedValue<KEYBOARD_STATE>(
     KEYBOARD_STATE.UNDETERMINED
   );
```

https://user-images.githubusercontent.com/65770455/119354037-e275e380-bca3-11eb-9da8-823338b4c1dd.MP4

https://user-images.githubusercontent.com/65770455/119354065-e86bc480-bca3-11eb-809f-cfb2cec432a0.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         |4.0.0.alpha3   |
| react-native                    | 0.64.1  |
| react-native-reanimated         | ^2.1.0  |
| react-native-gesture-handler    | ^1.10.3   |

## Steps To Reproduce

1. Install the new alpha
2. Wrap a `BottomSheetScrollView` into a `BottomSheetModal` with `keyboardBehavior={'interactive'}`
3. Open the BS
4. Open the keyboard

Describe what you expected to happen:

1. When opening the keyboard the height should be calculated correctly (Android) | When opening the keyboard the scrollable view should be scrollable (iOS)

## Reproducible sample code

```javascript
<BottomSheetModal
   backdropComponent={Backdrop}
   enableHandlePanningGesture={false}
   enableContentPanningGesture={false}
   name={props?.name ?? 'sheet'}
   ref={ref}
   snapPoints={props.snapPoints}
   keyboardBehavior={'interactive'}
>
  <BottomSheetScrollView>
    {/* Your long component */}
  </BottomSheetScrollView>
</BottomSheetModal>
```

**Comment by gorhom** [comment]
hi @elgorditosalsero , i have teste the alpha build with keyboard handling , and it works just fine  🤔

it is maybe some of your implementation that caused the issue! 

https://user-images.githubusercontent.com/4061838/119395738-ddc52580-bccb-11eb-939c-950b4391d193.mp4

**Comment by elgorditosalsero** [comment]
Thx @gorhom, can confirm is my fault!

Bad config and the patch I was talking was applied but not needed!
