### ISSUE TITLE
Different swiping speed when starting pan gesture on handle vs on content

### ISSUE THREAD

**Issue by mateuszmazurek** [gorhom/react-native-bottom-sheet#456]
## Ask your Question

When I start swiping up/down by touching handle - sheet follows my finger 1:1 (which is ok for me), but starting gesture on content make this movement slower. Is it a feature? How can I achieve handle-like behavior even when swiping content? If there's no public API for this - where should i look in library code for this implementation?

https://user-images.githubusercontent.com/5048182/119482589-52dc3d80-bd54-11eb-984a-76898819217d.mov

```typescript
import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const App = () => {
  // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  // renders
  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;
```

**Comment by davidskaarup** [comment]
I have the same issue - dragging on the content should not be have extra drag compared to the handle. @mateuszmazurek did you find a solution?

**Comment by davidskaarup** [comment]
This is apparently only an issue on the ios simulator - when I run it on my iphone it works as expected. I have the same issue with another component so I think this is and issue with Reanimated 2.

**Comment by mateuszmazurek** [comment]
@davidskaarup sorry, I didn't notice your previous comment. No, I didn't find a solution, but if you tell that it works ok on physical devices - I'll try it. Thanks :)

**Comment by gorhom** [comment]
@mateuszmazurek are you using M1 Mac ?

**Comment by mateuszmazurek** [comment]
@gorhom nope, last x86 (i7) Macbook Pro 13"
