### ISSUE TITLE
v4 BottomSheetSectionList scrollToLocation stopped working

### ISSUE THREAD

**Issue by tumski** [gorhom/react-native-bottom-sheet#459]
Hi.

I just gave it a go in my app, v4 runs smooth in all usecases other than than scrollToLocation on BottomSheetSectionList, it simply does nothing, while I have not changed anything (working fine on v3)
Just wanted to ask if that is intended behavior in alpha, or maybe it has been overlooked.

**Comment by gorhom** [comment]
hi @tumski i have tested `BottomSheetSectionList` on `v4` and it works just fine!

make sure the sheet is extended in order to allow you to scroll

**Comment by tumski** [comment]
> hi @tumski i have tested `BottomSheetSectionList` on `v4` and it works just fine!
> 
> make sure the sheet is extended in order to allow you to scroll

Indeed, I checked again, it was still not working but when I wrapped the call for scrollToLocation() in setTimeout() it began working just fine. Will investigate it further but most likely there is something wrong with my setup. Thanks a lot for looking into this, seems that v4 is working great!
