### ISSUE TITLE
BottomSheetFlatList is scrollable only when the bottomSheet is on the top level

### ISSUE THREAD

**Issue by Maoravitan** [gorhom/react-native-bottom-sheet#46]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^1.4.1  |
| react-native                    | "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz"  |
| react-native-gesture-handler    | ~1.7.0   |

## Steps To Reproduce

1.scrolling up the bottomSheet  
2.scroll horizontally images
3. scroll down 50% the bottomSheet  
4.scroll horizontally images -> cannot.

Describe what you expected to happen:

1.i would like to be able to scroll the images horizontally also when the bottomSheet   is not on the top level.

## Reproducible sample code

```
import { BottomSheetFlatList } from '@gorhom/bottom-sheet'
import React from 'react'
import {View, Text, TouchableOpacity, Image, StyleSheet } from 'react-native'
import { ImagesSliderProps } from './ImagesSlider.d'

const ImagesSlider: React.FC<ImagesSliderProps> = ({title, images}) => {
  
 const renderImage = (itemData:any) => {  
  return (
      <TouchableOpacity activeOpacity={0.8} onPress={()=> console.log(itemData.item)}>
        <Image style={styles.image} source={{uri:itemData.item.key}}/>
      </TouchableOpacity>
    )
  }

  return (
   <View style={{flex:1}}>
    <Text>{title}</Text>
    <BottomSheetFlatList 
            showsHorizontalScrollIndicator={true} 
            initialNumToRender={2} 
            keyExtractor={(item, index) => index.toString()} 
            horizontal={true} 
            data={images} 
            renderItem={renderImage}/>
   </View>
 )
}

const styles = StyleSheet.create({
  image: {
    marginHorizontal: 5,
    width:200,
    height:150,
    resizeMode: 'stretch'
  }
})

export default ImagesSlider;
```

![cannotscroll](https://user-images.githubusercontent.com/46298560/95989963-9d4b2280-0e33-11eb-9b27-4550647cb8e7.jpg)
![scrollable](https://user-images.githubusercontent.com/46298560/95989967-9e7c4f80-0e33-11eb-8020-f4bb8693c625.jpg)

**Comment by gorhom** [comment]
you should use `FlatList` from `react-native-gesture-handler`

```tax
import { FlatList } from 'react-native-gesture-handler';
```

**Comment by gorhom** [comment]
`BottomSheetFlatList` meant to be for vertical sheet content. I think I'll need to update docs to mention this clearly

**Comment by Maoravitan** [comment]
perfect, using FlatList solved the problem.
thank you.

**Comment by mikehuebner** [comment]
Just a heads up, on Android this works fine, but on iOS you cannot swipe down on a horizontal FlatList to move the sheet.

**Comment by konradgalczynski07** [comment]
@gorhom You should definitely add this to the docs. It would save me a few hours 👍

**Comment by gorhom** [comment]
@konradgalczynski07 it is already there 
https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android

**Comment by vladimirevstratov** [comment]
> you should use `FlatList` from `react-native-gesture-handler`
> 
> ```
> import { FlatList } from 'react-native-gesture-handler';
> ```

It works, thanks

**Comment by abdullahkhan70** [comment]
But what about if there are nested Flatlist...

**Comment by dlombardi** [comment]
using the gesture library FlatList does not enable horizontal scrolling for me

**Comment by dimpram** [comment]
> using the gesture library FlatList does not enable horizontal scrolling for me

@dlombardi  For me it did work after I changed from using the modal bottom sheet to just the plain one. Of course I also changed to the gesture handler FlatList.

**Comment by ahmedam55** [comment]
I have a problem with children components that I can't change their implementation to other types of FlatList or ScrollView from react native gesture handler
