### ISSUE TITLE
'0%' is not a valid percentage snap point! expected percentage snap point must be only numbers and '%'. e.g. '50%'

### ISSUE THREAD

**Issue by ajstokar** [gorhom/react-native-bottom-sheet#464]
# Bug

My app is throwing Invariant Violation: '0%' is not a valid percentage snap point! expected percentage snap point must be only numbers and '%'. e.g. '50%'

upgraded to v3 and the following unchanged code no longer works.  I am now getting the Invariant Violation error.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.5   |
| react-native                    | 0.63.3  |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce

<img width="728" alt="Screen Shot 2021-05-28 at 3 16 03 PM" src="https://user-images.githubusercontent.com/1800186/120032202-d3ef3b00-bfc7-11eb-8459-6aae48188d64.png">
<img width="558" alt="Screen Shot 2021-05-28 at 3 16 20 PM" src="https://user-images.githubusercontent.com/1800186/120032205-d782c200-bfc7-11eb-8f96-0d35e1ac2e73.png">

Describe what you expected to happen:

The Bottom Sheet to work as usual

## Reproducible sample code

See above

**Comment by sinxwal** [comment]
Use just 0 number

**Comment by ajstokar** [comment]
I tried that as well, same error.

**Comment by sinxwal** [comment]
I guess you are facing another error.
In my project `const snapPoints = [0, '30%'];` works as expected.

**Comment by gorhom** [comment]
@ajstokar could you test on `v4` ?

```bash
yarn add @gorhom/bottom-sheet@4.0.0-alpha.7
```

**Comment by ajstokar** [comment]
I ended up sticking with the older version.  Going to close for now as it may have been some other issue with my packages.  Thanks!

**Comment by vi07** [comment]
Using 'zero' without quotes as: `const snapPoints = [0, '50%']` solved my issue.
