### ISSUE TITLE
What to do about components that should work regardless of BottomSheet?

### ISSUE THREAD

**Issue by gioragutt** [gorhom/react-native-bottom-sheet#466]
## Ask your Question

I have a feature for which I wanted to add BottomSheet into my app.

I wanted to create a small Form and show it in a `BottomSheet`.

I wanted to use the same form code to show another form in a simple RN Modal.

However, this library forces you to use the custom components (`View`, `ScrollView`, `TouchableOpacity`), and when you try to use it when you're not under a `BottomSheet`, your code/design/behavior breaks.

I'm using V2 (problem with moving to reanimated v2).

What are the guidelines for not having such compatibility issues?

**Comment by nandorojo** [comment]
Isn't this only the case with scrollable components? https://gorhom.github.io/react-native-bottom-sheet/scrollables unless you're using a react-navigation stack inside of the bottom sheet? (I'm not certain, but I thought this was the case)

**Comment by gioragutt** [comment]
As far as I've seen, all the components use the internal context, in one way or another, and don't handle the case it simply isn't provided.
