### ISSUE TITLE
No shadow applied with handleComponent = null

### ISSUE THREAD

**Issue by RohovDmytro** [gorhom/react-native-bottom-sheet#468]
# Bug

1. Set `handleComponent = null`
2. Add shadow via `style` prop.

Bug:
No shadow is applied.

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.5   |

## Reproducible sample code

````
<BottomSheet
  snapPoints={[BOTTOM_NEXT_BUTTON_HEIGHT]}
  handleComponent={null}
  keyboardBehavior={'interactive'}
  keyboardBlurBehavior={'restore'}
  style={{
    ...getShadow(2),
    zIndex: 9999999,
  }}
>
{children}
</BottomSheet>
````

**Comment by RohovDmytro** [comment]
@gorhom , the issue should be crystal clear here.

**Comment by gorhom** [comment]
hi @RohovDmytro , could you provide a reproducible sample code ? make sure it is runnable with `/example` project , thanks
