### ISSUE TITLE
`onChange` is called on initial render in iOS

### ISSUE THREAD

**Issue by diyorbek** [gorhom/react-native-bottom-sheet#47]
First of all thanks for creating this awesome library!

# Bug

I have noticed that on iOS `<BottomSheet/>`'s `onChange` prop is being called when the component is mounted. I suspect this behavior also exists in `useBottomSheetModal`. 

On Android, it is working as expected though. I am not sure, maybe I am doing something wrong.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^1.4.1   |
| react-native                    | ~0.62.2   |
| react-native-reanimated         |~1.9.0   |
| react-native-gesture-handler    | ~1.6.0   |

## Steps To Reproduce

I wanted to have 2 `BottomSheet`s which I could "navigate" between them. When the second one is closed, the first one should be opened. But when I open the app on iPhone it expands the first `BottomSheet` immediately. 

Initially,  I used `<BottomSheet/>` (first one)  and `useBottomSheetModal`(for the second one), but it didn't work as I expected, probably because of the same reason.

## Reproducible sample code

```tsx
export function HomeScreen() {
  const [isButtonVisible, setIsButtonVisible] = useState(true);
  const bottomSheetRef1 = useRef<BottomSheet>(null);
  const bottomSheetRef2 = useRef<BottomSheet>(null);

  return (
    <>
      <BottomSheet
        ref={bottomSheetRef1}
        snapPoints={["20%", "60%"]}
        onChange={() => {
          // For checking
          console.log("onChange is called in first BottomSheet");
        }}
      >
        <MyComponent1 />
      </BottomSheet>

      <BottomSheet
        ref={bottomSheetRef2}
        snapPoints={[0, "20%", "60%"]}
        onChange={(index) => {
          // For checking
          console.log("onChange is called in second BottomSheet");

          if (index === 0) {
            bottomSheetRef1.current?.expand();
            setIsButtonVisible(true);
          }
        }}
      >
        <MyComponent2 />
      </BottomSheet>

      {isButtonVisible && (
        <View>
          <Button
            onPress={() => {
              bottomSheetRef1.current?.close();
              bottomSheetRef2.current?.expand();
              setIsButtonVisible(false);
            }}
          >
            Open Second
          </Button>
        </View>
      )}
    </>
  );
}

/*  console output:

    onChange is called in second BottomSheet
    onChange is called in second BottomSheet
    onChange is called in first BottomSheet
*/
```

**Comment by gorhom** [comment]
hi @Diyorbek thanks for submitting this issue, i have look into your `Reproducible sample code` and run it locally , and it seems it's working fine https://streamable.com/rkg8pc

and looking on the functionality you wanna achieve, i would recommend you to use `BottomSheetModal` instead, look at [stack sheets example](https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/modal/StackExample.tsx)

**Comment by diyorbek** [comment]
@gorhom thanks for the reply!
I tried upgrading my dependencies and reinstall the pods. Now everything is working.

| Library                         | Version |
| ------------------------------- | ------- |
| react-native-reanimated         | ~1.9.0 => ~1.13.0   |
| react-native-gesture-handler    | ~1.6.0 => ~1.7.0  |
