### ISSUE TITLE
Disable closing the sheet on Swipe Down

### ISSUE THREAD

**Issue by ajstokar** [gorhom/react-native-bottom-sheet#474]
## Ask your Question

Is there a prop / setting to disable closing the sheet when swiping down?  I only want it to close when you drag down the handle, not the content of the sheet.  Thanks!

**Comment by gorhom** [comment]
yeah, this been added for `v4` https://github.com/gorhom/react-native-bottom-sheet/discussions/427 `enablePanDownToClose`.

**Comment by ajstokar** [comment]
For v2, when I swipe down, the sheet closes.  Are you saying that I can set enablePanDownToClose={false} in v4 so that the user can't swipe down to close?

Also, I've been installing libraries with npm vs. yarn.  Could that cause any issues?  

Thanks for the help and the great library!

- Adam

**Comment by gorhom** [comment]
>For v2, when I swipe down, the sheet closes. Are you saying that I can set enablePanDownToClose={false} in v4 so that the user can't swipe down to close?

if you are using `BottomSheetModal` on `v2` look here https://gorhom.github.io/react-native-bottom-sheet/modal/props#dismissonpandown

for `v4`, `enablePanDownToClose` will allow user to close the sheet, if you do not want this behaviour, just do not set it .

>Also, I've been installing libraries with npm vs. yarn. Could that cause any issues?

you could use any 👍
