### ISSUE TITLE
Get the y Bottom-sheet position

### ISSUE THREAD

**Issue by DonDes17** [gorhom/react-native-bottom-sheet#479]
## Ask your Question

Hi! 

I use the Bottom-sheet V2 in a child component 

 ```
<View style={{ flex: 1, padding: 24 }}>
      <BottomSheet
        ref={bottomSheetRef}
        index={0}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
        <View style={{ flex: 1, alignItems: 'center' }}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
```
I need to animate a text on my parent component when the bottom-sheet goes up /goes down
So I would like to know how get the y position of the bottom-sheet ? ( like with a native event, onLayout( ) or something like that ...)

Thank you :)

PS: Ok I did this with **onAnimate** and **handleSheetAnimate**, and it's perfect sorry for the question ^^

**Comment by yafetHamouda** [comment]
@DonDes17 Could he assist me how you done it ?

**Comment by alexeyvax** [comment]
If anyone is interested in the solution for version ^5.0.6
https://github.com/gorhom/react-native-bottom-sheet/issues/423#issuecomment-1102691451
