### ISSUE TITLE
Used context in bottom sheet in not updated on Android

### ISSUE THREAD

**Issue by mlecoq** [gorhom/react-native-bottom-sheet#48]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 1.4.1   |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 1.13.1   |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce

I have created a context for filter options (filtering is selected in bottom sheet)

```
import React from 'react';

export type FilterContextValue = {
  filter?: 'DATE' | 'NAME';
  setFilter: (filter: FilterContextValue['filter']) => void;
};

export default React.createContext<FilterContextValue>({
  setFilter: () => {},
});

```

```
const FilterProvider = ({children}: {children: React.ReactNode}) => {
  const [filter, setFilter] = useState<FilterContextValue['filter']>();

  const value = useMemo(() => ({filter, setFilter}), [filter, setFilter]);

  return <FilterContext.Provider value={value}>{children}</FilterContext.Provider>;
};

export default FilterProvider;
```

```

 import {TouchableWithoutFeedback} from '@gorhom/bottom-sheet';

 ...

  const {setFilter} = useContext(FilterCtx);


  <BottomSheetView>
          <TouchableWithoutFeedback
            onPress={() => {
              setFilter('NAME');
            }}>
            <Text>By name</Text>
          </TouchableWithoutFeedback>
          <TouchableWithoutFeedback onPress={() => setFilter('NAME')}>
            <Text>By date</Text>
          </TouchableWithoutFeedback>
        </BottomSheetView>
``` 

Describe what you expected to happen:

I expect that pressing `By name` and `By date`, the `setFilter` method created in FilterProvider would be called. In fact, it is the default method (in React.createContext which is called) 

I have tried to use setFilter elsewhere and it works fine (that's why I think it is related to bottom-sheets)

## Reproducible sample code

I will create one later

**Comment by mlecoq** [comment]
I have made a small example 

https://github.com/mlecoq/BottomSheetContextIssue

**Comment by gorhom** [comment]
thanks @mlecoq , i will look into it asap :)

**Comment by gorhom** [comment]
hi @mlecoq , i have clone and run your example ,, and it seems working fine 🤔

https://streamable.com/gjgoga

**Comment by mlecoq** [comment]
@gorhom I have checked again and I reproduce it on Android but not on iOS (I work mainly with android emulator)

**Comment by mlecoq** [comment]
https://streamable.com/bi5puo

**Comment by gorhom** [comment]
could you try to use `Touchables` from the library instead. look at (https://github.com/gorhom/react-native-bottom-sheet/blob/master/docs/touchables.md)

**Comment by mlecoq** [comment]
With Touchables it works fine in the example. But It was not working in my project (where I was already using Touchables from the library). In fact, it was a basic mistake (I details it if someone encounters the same issue): 

I added the **`<BottomSheetModalProvider>`** higher in the component tree than the **`<Provider>`** of my context, so logically the **`<BottomSheetView>`** (even if it was under the **`<Provider>`** of my context) was not notified of context changes.


@gorhom , Thank you very much for helping me going through this

**Comment by gorhom** [comment]
glad that you managed to resolve the issue :)
