### ISSUE TITLE
Scrollable Items not rendering

### ISSUE THREAD

**Issue by h-kumbi** [gorhom/react-native-bottom-sheet#480]
# Bug
Trying to have a scrollview render items is not working. Ive tried scrollable components FlatList and ScrollView from your library, react native and react-native-gesture-handler. None have worked. I can tell the component does render(using borderwidth style), the width is changeable but the height is not. Other components do render i'm only having a problem with scrollable components. Im testing it on expo using the xcode iphone simulator and a physical iphone.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.5  |
| react-native                    | 0.63.2  |
| react-native-reanimated         |2.1.0   |
| react-native-gesture-handler    | 1.10.2   |

## Steps To Reproduce

1. Nest a scrollable component within the bottom sheet
2.
3. 

Describe what you expected to happen:

1. Scrollable component to render items
2.

## Reproducible sample code
import React, { useRef } from 'react';
import { View, Text, useWindowDimensions } from 'react-native';
import {PanGestureHandler, ScrollView, FlatList} from 'react-native-gesture-handler';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import BottomSheet, { BottomSheetFlatList, BottomSheetView, BottomSheetScrollView } from '@gorhom/bottom-sheet';

const BottomSheetOption = () => {
  const sheetRef = useRef();
  const { width, height } = useWindowDimensions();
  const insets = useSafeAreaInsets();
  const modalHeight = height*0.8;

  return(
    <View style={{height, width, position:'absolute', paddingTop:insets.top, paddingBottom: insets.bottom}}>
        <BottomSheet
          animateOnMount
          index={1}
          snapPoints={[0, modalHeight]}
          ref={sheetRef}
          style={[{height:modalHeight, backgroundColor:'#fff', borderTopRightRadius: width*0.05, borderTopLeftRadius: width*0.05}]}
        >
            <FlatList
              data={[1,2,3]}
              renderItem={() => <View style={{height: 100, width, backgroundColor:'blue'}}/>}
              keyExtractor={(item, index) => index.toString()}
              style={{height:height*0.4, width, borderWidth: 1}}
              contentContainerStyle={{flex: 1}}
            />
        </BottomSheet>

    </View>
  )
}

export default BottomSheetOption;

**Comment by oguzturker8** [comment]
same

**Comment by lpmsh** [comment]
This is similar to what I mentioned in https://github.com/gorhom/react-native-bottom-sheet/issues/1156#issuecomment-2279330611. Not sure if I'm doing something wrong but I'm still encountering these same issues. @gorhom
