### ISSUE TITLE
Have any method or something to check bottom sheet is present?

### ISSUE THREAD

**Issue by kingdark1234** [gorhom/react-native-bottom-sheet#482]
Have any method or something to check bottom sheet is present?

I have to follow the document page but not find any method to bottom sheet is on present have any idea?

Thanks

**Comment by gorhom** [comment]
@kingdark1234 you can provide `onChange` and follow it's check the incoming index, or provide a shared value variable to `animatedIndex` 👍

**Comment by kingdark1234** [comment]
> @kingdark1234 you can provide `onChange` and follow it's check the incoming index, or provide a shared value variable to `animatedIndex` 👍

Cool, Thanks you.
