### ISSUE TITLE
jest mock for sheet.

### ISSUE THREAD

**Issue by ajturpei** [gorhom/react-native-bottom-sheet#483]
# Feature Request

Would be nice to have a mock file ready for the sheet since there are lots of issues with jest tests when certain actions are performed inside the sheet. (V4 alpha does not work with jest either yet)

## Why it is needed

easier mocking and testability of bottom sheet content

**Comment by donatoaguirre24** [comment]
I agree it would be nice to have a ready-to-use mock. Meanwhile the following mock works for me:

```js
require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();

// Silence the warning: Animated: `useNativeDriver` is not supported
jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper');

jest.mock('@gorhom/bottom-sheet', () => {
  const RN = require('react-native');
  
  return {
    __esModule: true,
    default: RN.View,
    namedExport: {
      ...require('react-native-reanimated/mock'),
      ...jest.requireActual('@gorhom/bottom-sheet'),
    },
  };
});
```

I'm using:

```
"@gorhom/bottom-sheet": "^3.6.5",    
"react-native": "0.64.2",
"react-native-reanimated": "^2.2.0",
```

**Comment by princefishthrower** [comment]
@donatoaguirre24 - That mock doesn't fully mock the bottom sheet including the methods like `close()` and `expand()`. My tests are failing with the following:

```
TypeError: _sheetRef$current.close is not a function

    > 44 |       sheetRef.current?.close()

```

I'll report back once I figure out how to properly mock these.

**Comment by akinyele** [comment]
Did you figure out how to properly mock this?

**Comment by Ekaanth** [comment]
Any update on this issue?

**Comment by lcrodrigues** [comment]
same problem here @princefishthrower

**Comment by pvinis** [comment]
for others that might search how to do the jest, mock
```
import mockBottomSheet from '@gorhom/bottom-sheet/mock';
jest.mock('@gorhom/bottom-sheet', () => mockBottomSheet);
```

**Comment by jahnagoldman** [comment]
Does anyone know how you might test that the `present` function is called in this case?

**Comment by LCseniordev** [comment]
Hey, does anyone knows how to make sure Footer component is rendered in the tests? Getting 'Unable to find an element' error
