### ISSUE TITLE
Overdrag does not work when dragging up on the content

### ISSUE THREAD

**Issue by davidskaarup** [gorhom/react-native-bottom-sheet#485]
# Bug

Overdrag past the top snappoint does not work when dragging up on the sheet content (View), but it works when dragging on the handle component. When dragging down past the bottom snappoint it works both on the handle and the content.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.5   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.8.0   |

## Reproducible sample code

```
<BottomSheet
  snapPoints={["25%", "75%"]}
  enableOverDrag={true}
  overDragResistanceFactor={4}
>
  {children}
</BottomSheet>
```

**Comment by danieloi** [comment]
same problem

**Comment by danieloi** [comment]
Short solution is to set the handleStyle's opacity to 0 

```
          handleStyle={{ opacity: 0 }}
