### ISSUE TITLE
Listening scroll events in BottomSheetModal

### ISSUE THREAD

**Issue by ndrkltsk** [gorhom/react-native-bottom-sheet#488]
## Ask your Question

Hi,

I'm trying to use the onScroll with the BottomSheetModal component

```
                <BottomSheetFlatList
                    ...
                    onScroll={(event): void => {
                        scrollOffset.value = event.nativeEvent.contentOffset.y
                    }}
                    ...
                />
```

it doesn't seem to work.
I am missing something?

Thanks in advance

**Comment by gorbypark** [comment]
I am trying to use the onScroll prop with `BottomSheetScrollView` and it doesn't work either.  I came across PR https://github.com/gorhom/react-native-bottom-sheet/pull/225 and it seems like it was removed (for BottomSheetScrollView..), so maybe BottomSheetFlatList is similarly intentionally lacking the function

**Comment by fcandi** [comment]
Thx, I also try to use the events (in my case onMomentumScrollEnd) and it doesn't work. Maybe, there is another way of listening to these events?

**Comment by fcandi** [comment]
@ndrkltsk @gorbypark I just tried ScrollView from react-native-gesture-handler as mentioned here:
https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android

It seems to work nicely now, events included. The horizontal Flatlist is even part of a vertical BottomSheetFlatlist and its behavior including closing the bottom sheet with vertical gestures on the horizontal Flatlist also just works. Latest versions of all components.

**Comment by gorbypark** [comment]
> @ndrkltsk @gorbypark I just tried ScrollView from react-native-gesture-handler as mentioned here:
> https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android
> 
> It seems to work nicely now, events included. The horizontal Flatlist is even part of a vertical BottomSheetFlatlist and its behavior including closing the bottom sheet with vertical gestures on the horizontal Flatlist also just works. Latest versions of all components.

Does closing the BottomSheet using gestures and the vertical ScrollView component from react-native-gesture-handler work for you?  It doesn't for me.  Kinda of makes sense it works on a horizontal one since the horizontal one wouldn't be listening for vertical gestures as well..

**Comment by fcandi** [comment]
Hi @gorbypark yes for me it is working. But I use BottomSheetFlatList for the vertical ScrollView and inside I use the ScrollView component from react-native-gesture-handler for the horizontal Image slider. See video:

https://user-images.githubusercontent.com/153574/124245795-9cbcfe00-db20-11eb-8f4b-3acdca6c38a0.mov
