### ISSUE TITLE
Bottom sheet gets obscured by the keyboard if `snapPoints` change while the text input is focused

### ISSUE THREAD

**Issue by SimpleCreations** [gorhom/react-native-bottom-sheet#489]
# Bug

https://user-images.githubusercontent.com/12449725/122297446-302ce700-cf04-11eb-9b2c-2d674db22f6e.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 4.0.0-alpha.13, 3.6.5  |
| react-native                    | 0.64.1   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Use the dynamic snap point example.
2. Add `keyboardBehavior="interactive"` and a `BottomSheetTextInput`.
3. Make the height of the content change when entering text into the text input.

Describe what you expected to happen:

The bottom sheet stays in place and does not slide under the keyboard.

## Reproducible sample code

```typescript
import React, {useCallback, useEffect, useMemo, useRef, useState} from 'react';
import {LayoutChangeEvent, StyleSheet, Text, View} from 'react-native';
import {BottomSheetModal, BottomSheetModalProvider, BottomSheetTextInput, BottomSheetView} from '@gorhom/bottom-sheet';
import {useSafeAreaInsets, SafeAreaProvider} from 'react-native-safe-area-context';

const Screen = () => {
  const [contentHeight, setContentHeight] = useState(0);
  const snapPoints = useMemo(() => [contentHeight], [contentHeight]);

  const {bottom} = useSafeAreaInsets();
  const handleLayout = useCallback(({nativeEvent: {layout: {height}}}: LayoutChangeEvent) => {
      setContentHeight(height + bottom + 24);
  }, [bottom]);

  const bottomSheetModalRef = useRef<BottomSheetModal>(null);
  useEffect(() => bottomSheetModalRef.current?.present(), []);

  const [text, setText] = useState('');

  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <BottomSheetModal
          ref={bottomSheetModalRef}
          snapPoints={snapPoints}
          keyboardBehavior="interactive">
          <BottomSheetView onLayout={handleLayout}>
            <BottomSheetTextInput
              style={styles.textInput}
              value={text}
              onChangeText={setText}
              placeholder="Type something here..."
            />
            <Text style={styles.valueText}>{text}</Text>
            {new Array(18).fill(null).map((_, i) => (
              <Text key={i}>Lorem ipsum</Text>
            ))}
          </BottomSheetView>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

const App = () => {
  return (
    <SafeAreaProvider>
      <Screen />
    </SafeAreaProvider>
  );
};

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#CCC'},
  textInput: {padding: 12, backgroundColor: '#EEE', fontSize: 17},
  valueText: {color: '#F33'},
});

export default App;
```

**Comment by ahmetuysal** [comment]
I am having the same problem. Did you manage to find a workaround? @SimpleCreations

**Comment by gorhom** [comment]
@SimpleCreations thanks for spotting this issue, i have created a pr that should resolve it 👍

could you please test this pr, thanks
https://github.com/gorhom/react-native-bottom-sheet/pull/497

**Comment by SimpleCreations** [comment]
@gorhom thank you so much for taking the time to fix the issue! I've tried the PR, it works as expected now

**Comment by SimpleCreations** [comment]
@gorhom although I tried the example from my other issue while using this PR (`#fix/489-improve-keyboard-handling`) and `keyboardBlurBehavior="restore"` and it gives the following error:

https://user-images.githubusercontent.com/12449725/122761698-307f0680-d2a5-11eb-87cd-24a6b627de60.mp4

There is no such error on `4.0.0-alpha.13`.

**Comment by SimpleCreations** [comment]
And I think I've found another regression. It is possible to drag the bottom sheet under the keyboard which wasn't possible before.

https://user-images.githubusercontent.com/12449725/122765958-af763e00-d2a9-11eb-840e-46a87df71fa4.mp4

**Comment by gorhom** [comment]
@SimpleCreations thanks for spotting this issue 😅

could you please install latest pr version and try again , thanks

**Comment by SimpleCreations** [comment]
@gorhom the error that happened when blurring the text input programmatically is gone. Also, I can't drag the sheet under the keyboard anymore.
However, after adding `keyboardBlurBehavior="restore"` to the example in the current issue (with dynamic snap points), I get an error when panning down the bottom sheet while the keyboard is open

https://user-images.githubusercontent.com/12449725/123105632-9fdd2d80-d440-11eb-8e42-e5a8def60a02.mp4

**Comment by gorhom** [comment]
hi @SimpleCreations thanks for spotting this issue too, i have updated the code base, it should work fine 👍
