### ISSUE TITLE
Question: Have you had success using TextInput inside the bottom sheet?

### ISSUE THREAD

**Issue by jonesaustindev** [gorhom/react-native-bottom-sheet#49]
I'm able to get it working on iOS, but Android it isn't selectable or usable. Curious if there is an example somewhere I could look at if it has been done before. Thanks for the **awesome** library!

**Comment by gorhom** [comment]
hi @jonesaustindev , have you tried to load `TextInput` from `react-native-gesture-handler` ?

[look at map example search header ](https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/components/searchHandle/SearchHandle.tsx#L10)

**Comment by jonesaustindev** [comment]
@gorhom yes I have! No luck unfortunately. I'm using v1 btw I should have mentioned that earlier.
EDIT:
Looking at the map example you linked. Maybe because it isn't in the header component? I'll make sure it uses gesture-handler's TextInput as well.

**Comment by gorhom** [comment]
alright i'll look into it, thanks for submitting this :)

**Comment by jonesaustindev** [comment]
@gorhom wanted to let you know, just ran that example locally on Android and the `TextInput` works as expected. Seems like it is my implementation somewhere. Appreciate the response!

**Comment by gorhom** [comment]
glad to hear that :)
