### ISSUE TITLE
Blurring `BottomSheetTextInput` programmatically does not remove the space reserved for the keyboard

### ISSUE THREAD

**Issue by SimpleCreations** [gorhom/react-native-bottom-sheet#490]
# Bug

https://user-images.githubusercontent.com/12449725/122301230-0de99800-cf09-11eb-93d7-8a369690c457.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 4.0.0-alpha.13, 3.6.5  |
| react-native                    | 0.64.1   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Use some example.
2. Add `keyboardBehavior="interactive"` and a `BottomSheetTextInput`.
3. Add a way to `.blur()` the text input.

Describe what you expected to happen:

No extra space is left at the bottom of the bottom sheet after the keyboard has closed.

## Reproducible sample code

```typescript
import React, {useCallback, useEffect, useMemo, useRef} from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import {BottomSheetModal, BottomSheetModalProvider, BottomSheetTextInput, BottomSheetView} from '@gorhom/bottom-sheet';

const App = () => {
  const snapPoints = useMemo(() => ['50%'], []);

  const bottomSheetModalRef = useRef<BottomSheetModal>(null);
  useEffect(() => bottomSheetModalRef.current?.present(), []);

  const textInputRef = useRef<typeof BottomSheetTextInput>(null);
  const handleBlurButtonPress = useCallback(() => {
    // @ts-ignore
    textInputRef.current?.blur();
  }, []);

  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <BottomSheetModal
          ref={bottomSheetModalRef}
          snapPoints={snapPoints}
          keyboardBehavior="interactive">
          <BottomSheetView>
            <BottomSheetTextInput
              // @ts-ignore
              ref={textInputRef}
              style={styles.textInput}
              placeholder="Type something here..." />
            <Button title="Blur it!" onPress={handleBlurButtonPress} />
            {new Array(18).fill(null).map((_, i) => (
              <Text key={i}>Lorem ipsum</Text>
            ))}
          </BottomSheetView>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: '#CCC'},
  textInput: {padding: 12, backgroundColor: '#EEE', fontSize: 17},
});

export default App;
```

**Comment by gorhom** [comment]
have you tried `keyboardBlurBehavior ` ?
https://gorhom.github.io/react-native-bottom-sheet/props#keyboardblurbehavior

**Comment by SimpleCreations** [comment]
The example works as expected with `keyboardBlurBehavior="restore"` on `4.0.0-alpha.13`. Thank you for pointing it out, somehow I missed this prop, I guess I assumed it would work like that by default. Sorry for the trouble

**Comment by StackTraceYo** [comment]
What if there are multiple text inputs?
