### ISSUE TITLE
When BottomSheetTextInput has the focus, BottomSheet cannot trigger the onChange event

### ISSUE THREAD

**Issue by deng-yc** [gorhom/react-native-bottom-sheet#492]
# Bug
When BottomSheetTextInput has the focus, BottomSheet cannot trigger the onChange event

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         |^3.6.5，^4.0.0-alpha.13   |
| react-native                    |^0.64.0   |
| react-native-reanimated         |^2.2.0   |
| react-native-gesture-handler    | ^1.10.3  |

## Steps To Reproduce

https://user-images.githubusercontent.com/12589538/122504774-88133d00-d02d-11eb-9722-79faa5c2478e.mp4

1. click the textinput
2. close keyboard
3. change bottom sheet

Describe what you expected to happen:

1. Trigger onchange event

## Reproducible sample code
```
import BottomSheet, { BottomSheetTextInput } from '@gorhom/bottom-sheet';
import React from 'react';
import { useState } from 'react';
import { View, Text } from 'react-native';

interface IProps {}

export const IndexScreen: React.FC<IProps> = (props: IProps) => {
  const [value, setValue] = useState('');

  const [index, setIndex] = useState(0);

  return (
    <View style={{ flex: 1, backgroundColor: '#dddddd', alignItems: 'center', paddingTop: 100 }}>
      <Text>CurrentIndex:{index}</Text>
      <BottomSheet snapPoints={[100, 500]} onChange={setIndex} keyboardBehavior="extend" keyboardBlurBehavior="restore">
        <BottomSheetTextInput style={{ backgroundColor: '#dddddd' }} value={value} onChangeText={setValue} />
      </BottomSheet>
    </View>
  );
};

export default IndexScreen;

```

**Comment by gorbypark** [comment]
I am experiencing the same issue. It only (for me) happens on Android, and not iOS.  The same undesired behavior happens with `TextInput` imported from react-native as well, so I don't think it's a specific `BottomSheetTextInput` issue.

| Library | Version |
| ------------- | ------------- |
| @gorhom/bottom-sheet: | ^3 |
 | react-native: | 0.64.2 |
| react-native-gesture-handler: | ^1.10.3 |
| react-native-reanimated :| ^2.2.0 |

**Comment by gorhom** [comment]
hi @gorbypark , @deng-yc  could you test it on `v4` #427 ? thanks

**Comment by gorbypark** [comment]
> hi @gorbypark , @deng-yc could you test it on `v4` #427 ? thanks

Good timing!  I just tried on `4.0.0-alpha.12` a couple hours ago and it works as intended.  I was about 5 minutes away from adding a comment saying so!

**Comment by gorhom** [comment]
@gorbypark thanks for testing it ❤️
