### ISSUE TITLE
Can't scroll a webview inside of bottom sheet on Android

### ISSUE THREAD

**Issue by thanhnvpk01168** [gorhom/react-native-bottom-sheet#494]
# Bug

What I'm noticing is that the scrolling inside of the Web View doesn't work on Android, even though it works totally fine on iOS.
Quick help would be appreciated because I'm under a very tight timeline!

@gorhom/bottom-sheet: "^3",
react-native: "0.63.4",
react-native-reanimated: "^2.1.0",
react-native-gesture-handler: "^1.6.1",

my code:
    <SafeAreaView style={{ flex: 1, backgroundColor: 'rgba(255, 165, 0,1)' }}>
      <Header navigation={navigation} title={'animation 8'} />
      <BottomSheet
        style={{ zIndex: 100, marginTop: 100, paddingBottom: 10 }}
        // index={-1}
        ref={sheetRef}
        snapPoints={snapPoints}
        backdropComponent={BottomSheetBackdrop}
        onChange={handleSheetChange}
      >
        <WebView
          source={{ uri: 'https://www.youtube.com/' }}
          style={{
            width: Dimensions.get('screen').width,
            minHeight: Dimensions.get('screen').height / 1.5,
            maxHeight: Dimensions.get('screen').height / 1.5
          }} />
      </BottomSheet>
    </SafeAreaView>

https://user-images.githubusercontent.com/58645779/122638281-7d37d580-d11d-11eb-9454-bfc604d233ea.mov

**Comment by gorhom** [comment]
https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#my-component-gesture-interaction-gets-conflicted-with-bottom-sheet-interactions-

**Comment by dsteinbach** [comment]
Wrapping in `NativeViewGestureHandler` does not fix.

**Comment by dsteinbach** [comment]
Others have the same problem:
https://github.com/software-mansion/react-native-gesture-handler/issues/648

**Comment by gabpaet** [comment]
I am also having this issue, I can't scroll inside the webview but adding the `NativeViewGestureHandler` works with the interactivity, its just that it doesn't fix the scrolling issue.

**Comment by mmoonn2** [comment]
```


<BottomSheetModalProvider >
    <BottomSheetModal
        ref={(ref) => { this.bottomSheetModalRef = ref }}
        backdropComponent={Backdrop}
        snapPoints={[230, '90%']}
        enableContentPanningGesture={false}
        handleStyle={{height: 30, alignContent: 'center', borderBottomWidth: 0.5, borderBottomColor: ThemeStore.default.colors.border}}
        backgroundStyle={{ backgroundColor: ThemeStore.default.navigation.colors.background }}
    >

        <View style={styles.contentContainer}>
      
            <NativeViewGestureHandler disallowInterruption={true}>
                <View style={{ flex: 1 }}>
                    {this.state.url ? <Webview style={{ width: '100%', height: '100%' }} url={`https://images.google.com/searchbyimage?image_url=${decodeURIComponent(this.state.url)}`}></Webview> : null}
                </View>
            </NativeViewGestureHandler>
        </View>
    </BottomSheetModal >
</BottomSheetModalProvider>
```
```
        enableContentPanningGesture={false}
```

It works

**Comment by ekam1400** [comment]
Tried the exact solution @nullmu0 mentioned. BottomSheet doesn't even pop up.
Would really appreciate some work-around for the same.

**Comment by tomgiam** [comment]
I have the same issue.  The scrolling sort of works on iOS (it doesn't scrolls all the way down and it bounces back) On Android it does not work at all (it scrolls the sheet, instead of the WebView content). NativeViewGestureHandler did not fix the issue, but it did make it a little better on Android (it made it stop scrolling the sheet). So NativeViewGestureHandler could fix some situations with scrolling content, but not this one.

**Comment by soo9028** [comment]
@nullmu0  worked for me. Thanks!

**Comment by Fgabz** [comment]
@mmoonn2 it's working, don't forget `enableContentPanningGesture={false}`

**Comment by baesumin** [comment]
Is this still valid? It doesn't seem to apply at the moment.
