### ISSUE TITLE
BottomSheetScrollView cannot scroll when used with Dynamic Snap Point

### ISSUE THREAD

**Issue by tsugitta** [gorhom/react-native-bottom-sheet#496]
# Bug

It seems `BottomSheetScrollView` cannot be used with dynamic snap points.
it's necessary in a case where the content of the bottom sheet can be small and can be larger than the bottom sheet's maximum height.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | v4.0.0-alpha.13   |
| react-native                    | 0.64.1   |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.3 |

## Steps To Reproduce

Use [`/example/src/screens/modal/DynamicSnapPointExample.tsx`](https://github.com/gorhom/react-native-bottom-sheet/blob/49e4772819e14b5d74b8104bfe4e95501e975a07/example/src/screens/advanced/DynamicSnapPointExample.tsx)

1. Change the code `BottomSheetView` to `BottomSheetScrollView`
2. Press `Yes` button several times.
3. The scroll view cannot scroll.

https://user-images.githubusercontent.com/8144911/122670411-e5111d80-d1fc-11eb-8be6-49c50d95411a.mov

Describe what you expected to happen:

1. The content can be scrolled when the content height is bigger than the bottom-sheet's rendered area.

## Reproducible sample code

The example code is used.

**Comment by gorhom** [comment]
@tsugitta this is an expected behaviour, the react native scroll view expect a height or `flex: 1` to be able to scroll its content. in your case the content size stretched the `BottomSheetScrollView`  height too.

i would advice to give the `BottomSheetScrollView` the initial measured content height, then let it be fixed, and content can grow and be scrollable 👏

**Comment by tsugitta** [comment]
@gorhom 
thanks for your reply. I understand your suggestion is to keep the height of the bottom sheet at its original height, and do not modify it (also do not modify snapPoints). if so, there's a problem in a case where the initial height is already bigger than the screen height..

If we can get the maximum bottom sheet height that can be calculated in react-native-bottom-sheet, setting it to ScrollView's maxHeight seems to resolve the problem. Is this practical?

Or, isn't it practical that BottomSheet determines its height by something like `min(props.contentHeight, bottomSheetMaxHeight)` ?

**Comment by mohandere** [comment]
> i would advice to give the BottomSheetScrollView the initial measured content height, then let it be fixed, and content can grow and be scrollable 👏

Hey @gorhom I didn’t understood this comment, could you please provide a small example code?

Thank you so much for amazing library.

**Comment by SMhdAsadi** [comment]
Try using maxHeight style on BottomSheetScrollView.
```jsx
<BottomSheetScrollView
    onLayout={handleContentLayout}
    style={{
        maxHeight: Dimensions.get('window').height,
    }}
>
        ...
</BottomSheetScrollView>
```

**Comment by bryanprimus** [comment]
> Try using maxHeight style on BottomSheetScrollView.
> 
> ```js
> <BottomSheetScrollView
>     onLayout={handleContentLayout}
>     style={{
>         maxHeight: Dimensions.get('window').height,
>     }}
> >
>         ...
> </BottomSheetScrollView>
> ```

tried setting maxHeight with `BottomSheetFlatList` but it didn't behave well.

**Comment by Lewitje** [comment]
> Try using maxHeight style on BottomSheetScrollView.
> 
> ```js
> <BottomSheetScrollView
>     onLayout={handleContentLayout}
>     style={{
>         maxHeight: Dimensions.get('window').height,
>     }}
> >
>         ...
> </BottomSheetScrollView>
> ```

This fixed the issue for me

**Comment by benjamin-luupli** [comment]
> Try using maxHeight style on BottomSheetScrollView.
> 
> ```js
> <BottomSheetScrollView
>     onLayout={handleContentLayout}
>     style={{
>         maxHeight: Dimensions.get('window').height,
>     }}
> >
>         ...
> </BottomSheetScrollView>
> ```

where you able to achieve scrolling at different snappoint?
