### ISSUE TITLE
Content is not intractable when providing one snap point

### ISSUE THREAD

**Issue by nyazid** [gorhom/react-native-bottom-sheet#50]
# Bug

  The bug appears for more than 1 spnap points.
  Suppose you have a button on the sheet with a onPress event handler. The onPress event works only for the last snap point. 
  otherwise, it wont.  

## Environment info

  Version V1

## Reproducible sample code

 `
<BottomSheet>
  ...
  <Button onPress={() => { alert();} }></Button>
  ...
<BottomSheet/>
`

**Comment by shekharskamble** [comment]
Facing same issue in my case it only happens on android... @nyazid how did you fix it? using only last snap point?

**Comment by nyazid** [comment]
Sorry, no solutions yet.

**Comment by sviperm** [comment]
I checked, this bug happens on android only. I think that this bug is on framework side. Currently i handle this with Pressable, onPressOut event and managing click state.

My Example.

```
import React, { useState } from "react";
import { Pressable, StyleSheet, Platform } from "react-native";

import { useDidUpdateEffect } from "~/core/hooks";
import BottomSheetHeader from "~/ui/BottomSheetHeader";
import Plus from "~/assets/svg/icons8-plus.svg";
import colors from "~/constants/colors";

export default ({ onAdd, title = "" }) => {
    const [isPress, setIsPress] = useState(false);
    const [isPressOut, setIsPressOut] = useState(false);
    const [isLongPress, setIsLongPress] = useState(false);

    const _onAdd = () => {
        if (onAdd) onAdd();
    };

    useDidUpdateEffect(() => {
        console.log(isPress, isLongPress, isPressOut);
        if (isPress && !isPressOut) {
            _onAdd();
        } else if (isPress && isPressOut) {
            setIsPress(false);
            setIsPressOut(false);
        } else if (!isPress && !isLongPress && isPressOut) {
            _onAdd();
            setIsPressOut(false);
        } else if (!isPress && isLongPress && isPressOut) {
            setIsLongPress(false);
            setIsPressOut(false);
        }
    }, [isPress, isPressOut, isLongPress]);

    const onPressHandler = () => {
        // if (Platform.OS !== "android") {
        // _onAdd();
        // } else {
        setIsPress(true);
        // }
    };

    const onPressOutHandler = () => {
        // if (Platform.OS === "android") {
        setIsPressOut(true);
        // }
    };

    const onLongPressHandler = () => {
        // if (Platform.OS === "android") {
        setIsLongPress(true);
        // }
    };

    return (
        <BottomSheetHeader title={title}>
            <Pressable
                style={styles.addButton}
                onPress={onPressHandler}
                onLongPress={onLongPressHandler}
                onPressOut={onPressOutHandler}
            >
                <Plus fill={colors.mainColor} height={40} width={40} />
            </Pressable>
        </BottomSheetHeader>
    );
};
```

This solution works for all platforms. If you want to ignore _state logic_, just uncomment `Platform.OS` lines

bonus:
```
export const useDidUpdateEffect = (fun, inputs) => {
    const isMounted = useRef(false);
    useEffect(() => {
        if (!isMounted.current) {
            isMounted.current = true;
        } else {
            fun();
        }
    }, inputs);
};
```

**Comment by minuitagency** [comment]
We also have this issue, if anybody has a solution.

**Comment by gorhom** [comment]
will look into it later 👍

**Comment by minuitagency** [comment]
Thank you so much, we are in the middle of a big launch and your library is paramount to the project.

**Comment by gorhom** [comment]
I just pushed an alpha release for v2 that includes this issue fix, please try it and let me know !

also check out the [new documents website ( still in progress )](https://gorhom.github.io/react-native-bottom-sheet/) 🎉

```ts
yarn add @gorhom/bottom-sheet@2.0.0-alpha.3
```

**Comment by minuitagency** [comment]
Hi @gorhom thank you so much! I hate to disturb you again but when updating my BottomSheet to the latest beta, it doesn't appear anymore, if flickers briefly and disappears... 

I read your doc, did I miss something?

`  <BottomSheet
        ref={bottomSheetRef}
        initialSnapIndex={0}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
        handleComponent={HandleBar}>
        {!opened ? (
          <BottomSheetView
            style={{
              backgroundColor: colors.orange,
              paddingHorizontal: gutters,
            }}>
            <Image...`

**Comment by minuitagency** [comment]
Nevermind, it works, thenk you so much!
