### ISSUE TITLE
Android: Cannot drag Bottom Sheet up after collapsing with Keyboard.dismiss

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#500]
# Bug

On Android, when using `android_keyboardInputMode="adjustResize"` on a Bottom sheet, after closing the Keyboard which will make the BS collapse, the BottomSheet cannot be dragged upward anymore. It will snap back to the bottom.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 4.0.0-alpha.12  |

## Steps To Reproduce

1. Go to https://snack.expo.io/@kickbk/search-with-mo-2
2. Click inside the search BSTextInput
3. Click one of the category images. It will call `Keyboard.dismiss();`
4. The Keyboard will close and the BS will collapse (not very elegantly, but it will). The BottomSheet will collapse to the bottom.
5. Try to drag the BottomSheet upward. It will snap back to the bottom

## Reproducible sample code

https://snack.expo.io/@kickbk/search-with-mo-2

**Comment by kickbk** [comment]
Correction. Getting this behavior whether using `android_keyboardInputMode="adjustResize"` or not. Perhaps it's related to `keyboardBehavior="interactive"`
`keyboardBehavior="extend"` seems to not have this issue.

**Comment by cuongnm2301** [comment]
same issue with v2
