### ISSUE TITLE
Updating snap point on Android when BottomSheet expands because TextInput is focused

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#501]
## Ask your Question

When focusing into a `BottomSheetTextInput`, the BottomSheet snaps to the top. On iOS, the BottomSheet's snap point updates, but not on Android.
I suppose we could listen to Keyboard events (keyboardDidShow and keyboardDidHide) and update, but ideally, the BottomSheet should do it on Android similarly to iOS. What do you think?

**Comment by kickbk** [comment]
Tried to use Keyboard event listeners, however, the main issue that it cannot resolve is that after the Keyboard is dismissed, the BottomSheet's `onChange` event doesn't fire when **closing** the BottomSheet. Dragging it to a higher snap point **does** work.

**Comment by JoyCood** [comment]
i meet the same bug, use v4
