### ISSUE TITLE
backdropComponent doesn't overlap Navigation header

### ISSUE THREAD

**Issue by mtoninelli** [gorhom/react-native-bottom-sheet#502]
## Ask your Question

"react-native": 0.64.0,
"@gorhom/bottom-sheet": ^3,
"@react-navigation/native": "^5.9.4",

The backdrop doesn't overlap the react navigation header. The results is that the header is still visible and only above that starts the backdrop with opacity. 

Is there a way to prevent this and let the backdrop going above the header?

Thank you in advance!

PS: I've seen this but the example link doesn't work (https://gorhom.github.io/react-native-bottom-sheet/react-navigation-integration)

**Comment by kickbk** [comment]
You can pass style props to the backdrop component like so:
```
<BottomSheetBackdrop
  ...
  style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 49 }}
/>
```

**Comment by mtoninelli** [comment]
Thank you @kickbk. I've tried your suggestion. But I have the same result. Here is the structure:

navigation
```
<NavigationContainer>
    <TabNav />
</NavigationContainer>
```

bottom-tabs navigation
```
export const TabNav = props => (
  <Tab.Navigator>
    <Stack.Screen component={HomeScreen} />
  </Tab.Navigator>
);
```

```
<View style={{flex: 1}}>
...
   <BottomSheet
      {...props}
      ref={ref}
      index={0}
      snapPoints={snapPoints}
      onChange={handleSheetChanges}
      backdropComponent={backdropProps => (
        <BottomSheetBackdrop
          {...backdropProps}
          enableTouchThrough={true}
          style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0}}
        />
      )}
      enabledContentGestureInteraction={false}>
      <BottomSheetView>
        ...
      </BottomSheetView>
   </BottomSheet>
</View>
```

Am I missing something?

Thank you

**Comment by kickbk** [comment]
If you are trying to offset the backdrop component so it's higher or lower (it's hard to understand from your original post), then apply a value to `bottom` or `top`. In the example you posted above you set both to 0, so obviously it will cover the entire screen.

**Comment by timedtext** [comment]
@mtoninelli   
Have you tried setting the `safeAreaInsets` 
``` ts
  const screenOptions = React.useMemo<StackNavigationOptions>(
    () => ({
      ...TransitionPresets.SlideFromRightIOS,
      safeAreaInsets: { top: 0 },
    }),
    [],
  );
```

**Comment by mtoninelli** [comment]
Thank you @nightwind2020 

I've tried safeAreaInsets and what it does is making the navigation header disappear like setting headerShown: false

Original behaviour.
<img width="265" alt="Screenshot 2021-06-28 at 10 58 58" src="https://user-images.githubusercontent.com/1280525/123620097-c2d15e00-d801-11eb-9061-580d07dc954a.png">

With safeAreaInsets {top: 0} the react header navigation disappears and doesn't overly the StatusBar.
<img width="264" alt="Screenshot 2021-06-28 at 10 59 36" src="https://user-images.githubusercontent.com/1280525/123620078-bfd66d80-d801-11eb-9084-271abb71dda0.png">

Using headerShown: false. This is the visual behaviour I want to reach. But in this case I used a dummy custom header in the screen that animates with the screen and not as a default header.
<img width="258" alt="Screenshot 2021-06-28 at 11 58 04" src="https://user-images.githubusercontent.com/1280525/123625864-1e064f00-d808-11eb-9cea-e27b3b8e4d04.png">

Any Idea how to do it keeping the react navigation header?

**Comment by SimpleCreations** [comment]
@mtoninelli 
The `BottomSheetModal` is rendered inside the nearest `BottomSheetModalProvider`.
So, the solution is to put `BottomSheetModalProvider` higher in your component tree, e.g. wrap it around `StackNavigator.Container`.
(If you're not using `BottomSheetModal` already, you'll need to replace `BottomSheet` with `BottomSheelModal` and add `BottomSheetModalProvider` as I've suggested.)

**Comment by mtoninelli** [comment]
Hi @SimpleCreations, thanks for your help.
I've done as you suggested and it covered the header as aspected. That's great but unfortunately doesn't dismiss properly the BottomSheetBackdrop. 

Once clicked the backdrop the bottomSheet flips down but the gray backdrop doesn't disappear. Like this:
<img width="211" alt="Screenshot 2021-07-01 at 16 49 09" src="https://user-images.githubusercontent.com/1280525/124153390-44d4b780-da8c-11eb-9b8a-e7d46273651b.png">

Any ideas?

**Comment by SimpleCreations** [comment]
@mtoninelli it's hard to tell without seeing the full code. It worked fine for me out of the box (even on v3), so I can suggest trying to remove any extra logic that you have (like complex snap points, non-required props, etc.) to see what causes this.

**Comment by mtoninelli** [comment]
@SimpleCreations yes, I'm trying :)
The code is the same as posted before replacing BottomSheet with BottomSheetModal and wrap all with the  BottomSheetModalProvider.

It's a weird behavior :/

**Comment by sarazeaiter1** [comment]
Does anyone have an idea of how to handle this?

**Comment by mydesweb** [comment]
just use something like this in your App or index file:

```
<View style={{ flex: 1 }}>
      <NavigationContainer ref={navigationRef}>{/* ... */}</NavigationContainer>
      <BottomSheet ref={sheetRef} />
</View>
```

**Comment by ramisalem** [comment]
@mydesweb  your suggestion won't work in all cases, for example when you want to show the sheet from anywhere in the app

**Comment by mydesweb** [comment]
@ramisalem Actually you can. In my example BottomSheet is wrapping (it is a high order component) the BottomSheet from this lib and has it's own state and own methods, I can change dynamically the content and hide/show the bottom sheet from anywhere using an imperative API. If you use forwardRef and useImperativeHandle hook you can do whatever you want. The last thing you have to do is to export and then import in your components the bottomSheetRef. Just follow this pattern [https://reactnavigation.org/docs/navigating-without-navigation-prop](https://reactnavigation.org/docs/navigating-without-navigation-prop)

**Comment by gorhom** [comment]
to allow the bottom sheet to overlap all views in screen, please use `BottomSheetModal` and make sure that your `BottomSheetModalProvider` is at the root component 👍

**Comment by dwwr** [comment]
In my case, I needed my backdrop to fully overlap the system status bar on IOS and Android.

 I used react-native `StatusBar` component to get height and set the negative of that as top offset on my backdrop. Works great for android, but`StatusBar.currentHeight` isn't available on IOS (I'm passing a hard number for now):  
```
const statusBarOffset = -(StatusBar.currentHeight ? StatusBar.currentHeight : 50)
const backdropStyles = { position: "absolute", top: statusBarOffset, width: "100%", height: "100%" }
```
then:
`<BottomSheetBackdrop {...props} style={backdropStyles} />`

**Comment by jzxchiang1** [comment]
> to allow the bottom sheet to overlap all views in screen, please use `BottomSheetModal` and make sure that your `BottomSheetModalProvider` is at the root component 👍

Make sure you wrap your entire <App /> in a <GestureHandlerRootView style={{flex: 1}} /> in order for you to be able to interact with the modal.

https://github.com/gorhom/react-native-bottom-sheet/issues/661#issuecomment-929279648

**Comment by mohandere** [comment]
Setting status bar to Translucent along with BackgroundColor can help may be for Andriod.

```
StatusBar.setTranslucent(true);
StatusBar.setBackgroundColor('transparent');
StatusBar.setBarStyle('dark-content');
```

Thanks!

**Comment by Poojaauma** [comment]
@mohandere 

The above code works, but there is a slight delay in the transition of the Status Bar background color

**Comment by kot-ezhva** [comment]
I think it happens because you use js react-navigation like me. I fixed this issue with zIndex'es :)

<img width="978" height="600" alt="Image" src="https://github.com/user-attachments/assets/a2524ad6-2f4a-46ae-ad64-e10174827bd1" />

**Comment by alexandrecoura96** [comment]
If you are facing this in expo router, you should wrap your main file, per example, the _layout with the BottomSheetModalProvider and inside your Bottom Sheet component, import the BottomSheetModal instead using that default import and put the index={0}.

So your code will be similar like this:

**Main File**
```
export default function Layout() {

  return (
    <GestureHandlerRootView>
      <BottomSheetModalProvider>
          <SafeAreaProvider>
            <StatusBar style="light" />
            <Stack screenOptions={{ headerShadowVisible: false }}>
              <Stack.Screen
                name={StackRouteNames.Splash}
              />
              <Stack.Screen
                name={StackRouteNames.Login}
              />
            </Stack>
            <ToastContainer />
          </SafeAreaProvider>
      </BottomSheetModalProvider>
    </GestureHandlerRootView>
  );
}
```

Your Bottom Sheet:

```
import {
  BottomSheetBackdrop,
  BottomSheetBackdropProps,
  BottomSheetModal,
} from "@gorhom/bottom-sheet";

    const renderBackdrop = useCallback(
      (props: BottomSheetBackdropProps) => (
        <BottomSheetBackdrop
          {...props}
          appearsOnIndex={0}
          disappearsOnIndex={-1}
        />
      ),
      []
    );

      <BottomSheetModal
        {...props}
        ref={ref}
        index={0}
        backdropComponent={renderBackdrop}
        enablePanDownToClose>
       {content}
      </BottomSheetModal>
```
