### ISSUE TITLE
BottomSheet goes nuts when loaded right away - V4

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#505]
# Bug

When a `BottomSheet` is expanded on init, it goes crazy and moves all over the screen. Adding a delay of 150 milliseconds stops it from happening.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 4.0.0-alpha.12  |

## Steps To Reproduce

Go to https://snack.expo.io/@kickbk/issue-with-v4 and try it - it will work just fine since it's V3. Now change BS to V4 alpha 12 and try again.

## Reproducible sample code

See snack

**Comment by jparkrr** [comment]
I'm seeing this issue in 4.0.0-alpha.14 as well


https://user-images.githubusercontent.com/872456/124133224-9e6ac100-da4f-11eb-8b75-34b2769a7763.mp4

**Comment by gorhom** [comment]
could you test alpha 18, thanks 

```
yarn add @gorhom/bottom-sheet@4.0.0-alpha.18
```

**Comment by jparkrr** [comment]
Looks to me like it's fixed! Thanks
