### ISSUE TITLE
Capture index change when interrupted

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#506]
## Ask your Question

If we open a `BottomSheet` `onAnimate` is fired with "from" and "to" indexes - awesome.
If we wait for the `BottomSheet` to open, the `onChange` will fire with the index - awesome.
If we then close the `BottomSheet` and we want to do something when that happens, then we can enter code to the `onChange` or even `onAnimate` if we want to perform it before it even closes - awesome.

Unfortunately, if we open the `BottomShet` and while it's climbing up we click anywhere to make it close, then neither `onAnimate` nor `onChange` will fire. So we cannot count on knowing when `BottomSheet` closes. At least not entirely.

However, obviously, the `BottomSheet` knows it needs to close when we click on the screen. At that moment, even if no change was made to the current position, I believe it may be a good thing to update the "from" and "to" indexes and the `onAnimate` and `onChange` events (and other events, like `onDismiss`) should fire..

Any recommendations?

**Comment by eliasrenman** [comment]
Hi!
Just for clarification @kickbk when the bottom sheet is interrupted what exactly happens? Neither `onAnimate` nor `onChange` fires but does the bottom sheet close successfully? 
I think i've had similar experiences where the bottom sheet sometimes closes but not always.

**Comment by kickbk** [comment]
Sorry for the insanely late response @eliasrenman but yes, the BS closes successfully. The callback functions just don't fire. This is a problem especially when you open one BS depending on the toIndex/fromIndex of another BS.
For example:
BS A opens BS B via onAnimate like so: `if(toIndex === 0){BS_B.current.snapToIndex(1)}`.
You open BS A so toIndex is 1, but before it gets there you pull it back down. You expect BS B to open, but onAnimate never runs so it remains closed.

**Comment by guidodipaolo** [comment]
Happening the same here, any solutions ?

**Comment by Bliqui** [comment]
Bump
