### ISSUE TITLE
Can't scroll BottomSheetScrollView within BottomSheet for Android

### ISSUE THREAD

**Issue by reinaldonetof** [gorhom/react-native-bottom-sheet#508]
## Ask your Question
Hi, I'm facing an issue that I can't scroll the `BottomSheetScrollView` within the `BottomSheet` using Android, but I can do this in iOS. So, reading the troubleshooting and some issues, is explain to us to use the `ScrollView` from `react-native-gesture-handler` and it's scrolling properly, but now I can't drag `BottomSheet` together with the `ScrollView`. Beside that, I'm using the `<NativeViewGestureHandler disallowInterruption>` too

So, I did a workaround and with iOS I'm using `<BottomSheet> <BottomSheetScrollView> ...` and I can drag both. But for Android I'm using ` <BottomSheet> <ScrollView> ... `, however, I can't drag both. Can something else I'm missing? Because I really want the drag action.

I'm using:

"react-native-gesture-handler": "^1.10.3",
"react-native-reanimated": "^2.2.0",
"@gorhom/bottom-sheet": "^3",
"react-native": "0.63.2",

**Comment by RafaelPena31** [comment]
I have the same problem on Android

**Comment by sanjib-suna** [comment]
Anyone got solution for this???

**Comment by colaquecez** [comment]
i have the same problem on android.. anyone?

**Comment by gorhom** [comment]
Could you test on ‘v4’ ?

**Comment by colaquecez** [comment]
<img width="407" alt="Screen Shot 2021-07-19 at 09 32 54" src="https://user-images.githubusercontent.com/38195454/126160234-b36abe77-a892-400d-b067-3343bfbd8fe1.png">

I tested the new alpha version, the bottomsheet doesn`t appear :(

**Comment by gorhom** [comment]
Could you provide a reproducible sample using this template https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by colaquecez** [comment]
<img width="373" alt="Screen Shot 2021-07-19 at 10 10 20" src="https://user-images.githubusercontent.com/38195454/126164863-59a38da6-8029-4d82-bd88-01cba57c2b8f.png">
Im using the same way that example, but the bottom sheet doesn`t appear :(
I used a wrapper containing same styles

**Comment by sahilbalodi** [comment]
Any fix for this issue ?

**Comment by sahilbalodi** [comment]
@gorhom  please refer to the template.
https://snack.expo.dev/@sahilbalodi/bottom-sheet-v4-reproducible-issue-template

scroll doesn't seem to work when keyboard is opened or closed on android.

**Comment by gorhom** [comment]
@sahilbalodi  i have tested on the stable release of `v4` and it works fine, please try again and create new issue if the issue still exist
