### ISSUE TITLE
How to change border radius of BottomSheetModal ?

### ISSUE THREAD

**Issue by TransLover** [gorhom/react-native-bottom-sheet#511]
## Ask your Question
I have read the docs and know that you style the container by using the normal `style` property, however when trying to change the border radius of the sheet, it does not work either with custom or default handle, I attach an example of how it looks like when using the styling prop (I added border width and color using the style prop)
![Uploading IMG_E0492.JPG…]()

![IMG_E0493](https://user-images.githubusercontent.com/80780293/123733355-30a47680-d850-11eb-9c7d-3e93b217678f.JPG)

**Comment by gorbypark** [comment]
You need to set a custom background component using the backgroundComponent prop and set the borderRadius there. 
```js
<BottomSheet backgroundComponent={props => <BottomSheetBackground {...props} />}>
```
and then the BottomSheetBackground component should be something like this
```js
const BottomSheetBackground = ({style}) => {
  return (
    <View
      style={[
        {
          backgroundColor: 'white',
          borderRadius: 12,
        },
        {...style},
      ]}
    />
  );
};
```

**Comment by TransLover** [comment]
> You need to set a custom background component using the backgroundComponent prop and set the borderRadius there.
> 
> ```js
> <BottomSheet backgroundComponent={props => <BottomSheetBackground {...props} />}>
> ```
> 
> and then the BottomSheetBackground component should be something like this
> 
> ```js
> const BottomSheetBackground = ({style}) => {
>   return (
>     <View
>       style={[
>         {
>           backgroundColor: 'white',
>           borderRadius: 12,
>         },
>         {...style},
>       ]}
>     />
>   );
> };
> ```

That works perfectly! thank you so much!, one last q, is there any way to set the custom BottomSheetBackground for ALL sheets globally ? or will I have to go one by one adding the custom background ?

**Comment by SimpleCreations** [comment]
> That works perfectly! thank you so much!, one last q, is there any way to set the custom BottomSheetBackground for ALL sheets globally ? or will I have to go one by one adding the custom background ?

You can create a custom wrapper component around `BottomSheet` and use it for all the sheets in your app.

```javascript
// CustomBottomSheet.js
export default function CustomBottomSheet(props) {
  return (
    <BottomSheet
      backgroundComponent={props => <BottomSheetBackground {...props} />}
      {...props} />
  );
}
```

**Comment by TransLover** [comment]
> > That works perfectly! thank you so much!, one last q, is there any way to set the custom BottomSheetBackground for ALL sheets globally ? or will I have to go one by one adding the custom background ?
> 
> You can create a custom wrapper component around `BottomSheet` and use it for all the sheets in your app.
> 
> ```js
> // CustomBottomSheet.js
> export default function CustomBottomSheet(props) {
>   return (
>     <BottomSheet
>       backgroundComponent={props => <BottomSheetBackground {...props} />}
>       {...props} />
>   );
> }
> ```

Thank you!!

**Comment by monkeedev** [comment]
well, also you can set `{ overflow: 'hidden' }` for the main `style` prop

example given down below:
```js
<BottomSheet
      ref={bottomSheetRef}
      snapPoints={snapPoints}
      enablePanDownToClose
      animateOnMount={false}
      backdropComponent={Backdrop}
      containerStyle={{ borderTopLeftRadius: 40 }}
      style={{ borderRadius: 40, overflow: 'hidden' }}
>
      ...
</BottomSheet>
```

what it looks like:
![image](https://user-images.githubusercontent.com/32853537/205268785-324514ed-b872-48d5-a730-2773c8db9532.png)

**Comment by lklima** [comment]
@MonkeeAlert on ios `overflow: 'hidden'` remove shadow.

**Comment by ice-cap0** [comment]
look no further: `backgroundStyle={{ borderRadius: 0 }}`

**Comment by ExoticCoder16** [comment]
> look no further: `backgroundStyle={{ borderRadius: 0 }}`

Someone please pin this, simple solution 👍
