### ISSUE TITLE
Bottom sheet opens on rotation

### ISSUE THREAD

**Issue by Mookiies** [gorhom/react-native-bottom-sheet#516]
# Bug

The bottom sheet opens when it should be closed after rotation. Additionally, if the device is rotated with sheet open, the `onChange` is not called until the device is rotated back again. What is odd is this appears to only happen when snap points are `[0%, 100%]` (or very close to those numbers). 

## Environment info
| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.3.0   |
| react-native                    | 0.63.2 |
| react-native-reanimated         | 1.13.3  |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Open sheet
2. Rotate device
3. Close sheet
4. Rotate device

Describe what you expected to happen:

1. Sheet expected to remain closed
2. Callback `onChange` to have been called when sheet was closed 
3. Callback `onChange` to **not** be called with incorrect snapPoint after rotation.

Video of issue:
`  const snapPoints = useMemo(() => ["0%", '100%'], []);`

https://user-images.githubusercontent.com/22333355/124296997-9599ee00-db28-11eb-898a-3a85736a42cb.mov

Video where only change is not using maxed snapPoints showing expected behavior.
`  const snapPoints = useMemo(() => ["20%", '100%'], []);`

https://user-images.githubusercontent.com/22333355/124297138-bf531500-db28-11eb-80cd-0145172a8b49.mov

## Reproducible sample code
Snack: https://snack.expo.io/@mookiies/github.com-mookiies-bottom-sheet-snap-point-demo (have to run on your device)
Repo: https://github.com/Mookiies/bottom-sheet-snap-point-demo

**Comment by Mookiies** [comment]
bump

**Comment by sators** [comment]
+1

**Comment by GitBond** [comment]
+1

**Comment by gorhom** [comment]
i will look into this 👍

**Comment by harsh-siriah** [comment]
I am still facing this issue on v4. Any solutions?

**Comment by sators** [comment]
bump

**Comment by pronevich** [comment]
This issue is active.

**Comment by sators** [comment]
bump

**Comment by pronevich** [comment]
bump

**Comment by pronevich** [comment]
bump

**Comment by elmcapp** [comment]
This issue still persists.

**Comment by elmcapp** [comment]
Are there any temporary patches for this until this issue is fix

**Comment by sators** [comment]
Bump

**Comment by GitBond** [comment]
bump

**Comment by goxr3plus** [comment]
This issue still exists .

**Comment by GitBond** [comment]
bump

**Comment by Armisael2k** [comment]
The issue still active

**Comment by GitBond** [comment]
bump

**Comment by goxr3plus** [comment]
Light weights baaaaby

**Comment by devDoubleH** [comment]
May I try to fix this bug?

**Comment by Mookiies** [comment]
I believe this issue is fixed in `v4.4.4` by https://github.com/gorhom/react-native-bottom-sheet/commit/3b75d5d84e0a02933ef2b01d855d9f6036c756b2 and https://github.com/gorhom/react-native-bottom-sheet/commit/29af238d9eed31f0d9cad39ade8a43cf37ca2e72

If anyone is still experiencing after upgrading please comment and I will try to re-open issue

**Comment by MorganTrudeau** [comment]
I'm seeing this on v4.4.7. When I change from landscape to portrait the bottomsheet shows for a second. I'm looking into it. Let me know if you find anything. Thanks.


https://github.com/gorhom/react-native-bottom-sheet/assets/28589416/56e339cf-dfab-4ea1-bc9e-8b6d5fd1e36f

**Comment by nhutph** [comment]
> I'm seeing this on v4.4.7. When I change from landscape to portrait the bottomsheet shows for a second. I'm looking into it. Let me know if you find anything. Thanks.
> 
>  Simulator.Screen.Recording.-.iPhone.14.Pro.-.2023-07-27.at.19.50.56.mp4

same issues lib many bug but the owner don't care about this

**Comment by ansarikhurshid786** [comment]
any solution for this issue.

**Comment by Mookiies** [comment]
That visual glitch in @MorganTrudeau's video seems to differ from the original issue where the bottom sheet ended up in the wrong state and callbacks were not appropriately fired. 

If that's truly an issue with this library I would make a new issue.

**Comment by vxduc9999** [comment]
Hi @Mookiies, is your issue is fixed?

**Comment by Mookiies** [comment]
@vxduc9999 yes, as of `v4.4.4` my issue with missed callbacks and incorrect openings was fixed

**Comment by ansarikhurshid786** [comment]
@Mookiies How did you fix. can you share with us.

**Comment by joonmanji** [comment]
we are currently experiencing this in our app using reanimated3 and 
| Library    | Version |
| -------------------------| ------- |
| react-native-reanimated | 3.5.4 |
| @gorhom/bottom-sheet | 4.5.1 |

we've noticed that adding this line to https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheet/BottomSheet.tsx#L1303 helps mitigate the problem.. i'm not well versed in  this library to say if this is a hack or a perm fix.

```
if(animatedNextPositionIndex.value < 0 && animatedCurrentIndex.value < 0) {
    return;
}
```

put up a PR here: https://github.com/gorhom/react-native-bottom-sheet/pull/1610

**Comment by ansarikhurshid786** [comment]
@joonmanji did this work with react-native-reanimated v2 ?

**Comment by joonmanji** [comment]
@ansarikhurshid786 didnt try it. Only tried it with the versions of bottom-sheet and reanimated listed above

**Comment by JJSLIoT** [comment]
This issue still exists in `4.6.1`!

**Comment by thomas-rx** [comment]
Thanks to @joonmanji, the problem is manageable until the source of the issue is truly identified.
I have created this patch, it resolves the problem in version 4.6.4.

```typescript
diff --git a/src/components/bottomSheet/BottomSheet.tsx b/src/components/bottomSheet/BottomSheet.tsx
index cd6ea6bfbace8e9e0b5f0759d4dc7559d48d248f..72208159c5c613aceb7b35a05fc6fac2947b8036 100644
--- a/src/components/bottomSheet/BottomSheet.tsx
+++ b/src/components/bottomSheet/BottomSheet.tsx
@@ -1331,6 +1331,10 @@ const BottomSheetComponent = forwardRef<BottomSheet, BottomSheetProps>(
         let animationConfig;
         let animationSource = ANIMATION_SOURCE.SNAP_POINT_CHANGE;
 
+        if(animatedNextPositionIndex.value < 0 && animatedCurrentIndex.value < 0) {
+          return;
+        }
+
         /**
          * if the bottom sheet is closing and the container gets resized,
          * then we restart the closing animation to the new position.
```

**Comment by bradstiff** [comment]
This is still an issue on v5. I tried to adapt the above patch to the current v5 codebase, but the codebases are too different. It is happening in the interpolation that calculates the currentIndex in BottomSheet.tsx:

```    const animatedIndex = useDerivedValue(() => {
      const adjustedSnapPoints = animatedSnapPoints.value.slice().reverse();
      const adjustedSnapPointsIndexes = animatedSnapPoints.value
        .slice()
        .map((_: any, index: number) => index)
        .reverse();

      /**
       * we add the close state index `-1`
       */
      adjustedSnapPoints.push(animatedContainerHeight.value);
      adjustedSnapPointsIndexes.push(-1);

      const currentIndex = isLayoutCalculated.value
        ? interpolate(
            animatedPosition.value,
            adjustedSnapPoints,
            adjustedSnapPointsIndexes,
            Extrapolate.CLAMP
          )
        : -1;
```

The animatedContainerHeight appears to get measured a second time. The value increases a bit, causing currentIndex to become > -1, resulting in a partial open.

**Comment by khushal87** [comment]
Hey @gorhom, do you have a suggested fix for this issue?

**Comment by thespacemanatee** [comment]
Not stale! @gorhom

**Comment by wldzimerz** [comment]
Hi, I found a solution to this problem in my expo app, until the developer fixes it.

I use this in a custom component based on BottomSheetModal and using it.

```ts
    const [isDeviceRotating, setIsDeviceRotating] = useState<boolean>(false)
    const isDeviceRotatingDebounced = useDebounce(isDeviceRotating, 1000)

    const changeOrientationListener = useCallback((_evt: ScreenOrientation.OrientationChangeEvent) => {
            setIsDeviceRotating(true)
    }, [])

    useEffect(() => {
        ScreenOrientation.addOrientationChangeListener(changeOrientationListener)
    }, [])


    useEffect(() => {
        if (isDeviceRotatingDebounced) {
            setIsDeviceRotating(false)
        }
    }, [isDeviceRotatingDebounced])

    if (isDeviceRotating) return null
```

**Comment by hbthanh5802** [comment]
> Hi, I found a solution to this problem in my expo app, until the developer fixes it.
> 
> I use this in a custom component based on BottomSheetModal and using it.
> 
>     const [isDeviceRotating, setIsDeviceRotating] = useState<boolean>(false)
>     const isDeviceRotatingDebounced = useDebounce(isDeviceRotating, 1000)
> 
>     const changeOrientationListener = useCallback((_evt: ScreenOrientation.OrientationChangeEvent) => {
>             setIsDeviceRotating(true)
>     }, [])
> 
>     useEffect(() => {
>         ScreenOrientation.addOrientationChangeListener(changeOrientationListener)
>     }, [])
> 
> 
>     useEffect(() => {
>         if (isDeviceRotatingDebounced) {
>             setIsDeviceRotating(false)
>         }
>     }, [isDeviceRotatingDebounced])
> 
>     if (isDeviceRotating) return null

Thanks, this seems to be a temporary workaround.

**Comment by bastiaanv** [comment]
Based on @bradstiff comments, we made a patch package:

```
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
index 6748c93..bb6e064 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
@@ -1746,6 +1746,23 @@ const BottomSheetComponent = forwardRef<BottomSheet, BottomSheetProps>(
       [_providedAnimatedPosition, topInset]
     );

+    /** Reset position of Bottom Sheet during screen rotate */
+    useAnimatedReaction(
+      () => animatedLayoutState.value.containerHeight,
+      (newHeight, previousHeight) => {
+        if (newHeight === previousHeight) {
+          return;
+        }
+        if (!previousHeight || animatedPosition.value < previousHeight) {
+          // Do not reset position while bottom sheet is open
+          return;
+        }
+
+        animatedPosition.value = newHeight
+      },
+      [animatedLayoutState]
+    );
+
     /**
      * sets provided animated index
      */

```

This is for version 5.2.8, unsure if it works on other versions...
Hope this helps

**Comment by hdjvieira** [comment]
> Based on [@bradstiff](https://github.com/bradstiff) comments, we made a patch package:
> 
> ```
> diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
> index 6748c93..bb6e064 100644
> --- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
> +++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
> @@ -1746,6 +1746,23 @@ const BottomSheetComponent = forwardRef<BottomSheet, BottomSheetProps>(
>        [_providedAnimatedPosition, topInset]
>      );
> 
> +    /** Reset position of Bottom Sheet during screen rotate */
> +    useAnimatedReaction(
> +      () => animatedLayoutState.value.containerHeight,
> +      (newHeight, previousHeight) => {
> +        if (newHeight === previousHeight) {
> +          return;
> +        }
> +        if (!previousHeight || animatedPosition.value < previousHeight) {
> +          // Do not reset position while bottom sheet is open
> +          return;
> +        }
> +
> +        animatedPosition.value = newHeight
> +      },
> +      [animatedLayoutState]
> +    );
> +
>      /**
>       * sets provided animated index
>       */
> ```
> 
> This is for version 5.2.8, unsure if it works on other versions... Hope this helps

Thanks a million Bastiaan, this helps a lot.
Can confirm that this works for version 5.2.8, it's not a perfect fix but very close.
