### ISSUE TITLE
Integration with React Navigation

### ISSUE THREAD

**Issue by ataravati** [gorhom/react-native-bottom-sheet#517]
## Ask your Question

How do I integrate the BottomSheetModal with React Navigation. I want to use each modal as a screen in a stack navigation. The link in the documentation is broken.

**Comment by likeSo** [comment]
Yes I noticed that too. You can still find an example in this repo

**Comment by ataravati** [comment]
@likeSo No, I was not able to find it.

**Comment by likeSo** [comment]
@ataravati https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/integrations/NavigatorExample.tsx You can find the example here.

**Comment by ataravati** [comment]
Thanks, @likeSo!

**Comment by teovillanueva** [comment]
Hey! Can't find the docs for this :( The link seems to be broken again

**Comment by bnussman** [comment]
Link is broken!

**Comment by Bileloueslati** [comment]
https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/integrations/NavigatorExample.tsx link is broken !!
