### ISSUE TITLE
runOnJS Errors in Reanimated 2.0.0-alpha.8

### ISSUE THREAD

**Issue by ksitko** [gorhom/react-native-bottom-sheet#52]
# Bug

Reanimated V2 just released [`2.0.0-alpha.8`](https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-alpha.8). It offers lots of fixes over `2.0.0-alpha.7` and no longer requires turbo modules to be globally enables (no more AppDelegate setup). There is a breaking change in that you now must explicitly specify which thread you're running a function, either runOnJS or runOnUI. Functions must either runOnUI if they are to be sync or runOnJS if they are to be async. See [here](https://github.com/software-mansion/react-native-reanimated/issues/1393).

In iOS using the bottom sheet results in this error:

![Simulator Screen Shot - iPhone 11 - 2020-11-01 at 23 09 38](https://user-images.githubusercontent.com/13754630/97834322-90d51f80-1ca5-11eb-9b99-a5ecf4cac9ce.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0-alpha.0   |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 2.0.0-alpha.8 |
| react-native-gesture-handler    | 1.7.0   |

## Steps To Reproduce

Use bottom-sheet with Reanimated V2 2.0.0-alpha.8

**Comment by gorhom** [comment]
@ksitko thanks for submitting this issue, i am already working on a new alpha release 👍

**Comment by gorhom** [comment]
i am pausing the integration to alpha 8, until `scrollTo` issue gets resolve 😞 https://github.com/software-mansion/react-native-reanimated/issues/1394

**Comment by ksitko** [comment]
Understandable, thanks for the update @gorhom!

**Comment by gorhom** [comment]
i'll keep an eye on the issue 👍

**Comment by ksitko** [comment]
Hey @gorhom just wanted to give you a heads up that [`alpha.9`](https://github.com/software-mansion/react-native-reanimated/pull/1438) should be coming real soon and along with it the [`scrollTo`](https://github.com/software-mansion/react-native-reanimated/commit/5fe32495b455c824a10c1749438c4dff0c538854) fix.

**Comment by virdesai** [comment]
@gorhom heads up, alpha.9 was released a few hours ago

**Comment by gorhom** [comment]
hi @ksitko @virdesai , 

would you mind testing this pr https://github.com/gorhom/react-native-bottom-sheet/pull/69

thanks :)

**Comment by Johan-dutoit** [comment]
Hi @gorhom,  I can confirm it fixes the errors/warnings for me, running on v2 alpha9.
This is for both Android & iOS, latest RN.

P.s. thanks for the speedy fix :D

**Comment by gorhom** [comment]
hi @Johan-dutoit, thanks for testing it on both platforms.

I will prepare the release later today 👏

**Comment by ksitko** [comment]
@gorhom Apologies for the delay. I am unfortunately getting a `Can't find variable: _frameTimestamp` using `2.0.0-alpha.9.1`. I'm going to try to isolate the issue. `alpha.9.1` just dropped, and it fixes [a different issue](https://github.com/software-mansion/react-native-reanimated/issues/1443) which was a major headache for my app.
![image](https://user-images.githubusercontent.com/13754630/99705430-b5801400-2a67-11eb-93a2-6ae630f5115a.png)

**Comment by Johan-dutoit** [comment]
I've upgraded to 9.1, just to test this and not getting any error on iOS (using the PR code)

**Comment by ksitko** [comment]
I must have messed up pulling the PR code, I tried it again and the error is gone. Thank you so much @gorhom for the great work!

**Comment by gorhom** [comment]
this should be fix with the latest release v2.0.0-alpha.1 👏

**Comment by Dajust** [comment]
@gorhom These issues have resurfaced on all version 3 of bottom-sheet. I have now reverted to the latest version 2 where it works well.

- "react-native-reanimated": "~2.1.0"
- "@gorhom/bottom-sheet": "^3"
- Android and iOS (Expo managed)
- Experimetend on the official [Usage Example](https://gorhom.github.io/react-native-bottom-sheet/usage)

**Comment by darrylyoung** [comment]
I just tried this for the first time – using version 3 – and get the same issue mentioned above. For context, I'm testing in the iOS Simulator and I'm running an ejected (bare) Expo project. Related packages installed are:

```json
{
  "@gorhom/bottom-sheet": "^3",
  "react-native-reanimated": "^2.1.0",
}
```

I'm just trying the example as shown in the documentation. Let me know if there's anything else you'd like me to check.

**Comment by darrylyoung** [comment]
@gorhom – Is it worth creating a new issue for this as this one is closed (I only just realised that after commenting earlier) or are you already aware of the issue? Thanks for your time and for all the great work you share. It's very much appreciated.

**Comment by Dajust** [comment]
So today I've found that `@babel/preset-react` is one cause of this problem in bottom-sheet ^3.

[React 17 introduced a New JSX Transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html). With this transform, it's no longer required to import React in your JSX files. One of the options to enable this feature is using `@babel/preset-react`. But for some reasons, this causes the above error when using bottom-sheet v3. 

The workaround for me was replacing the preset with `@babel/plugin-transform-react-jsx`, which is the actual babel plugin that is responsible for the new JSX transform.

```
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
    // [
    //   '@babel/preset-react', // Bottom-sheet v3 doesn't like this.
    //   {
    //     runtime: 'automatic',
    //   },
    // ],
  ],
  plugins: [
    '@babel/plugin-syntax-jsx', // I still want this plugin
    [
      '@babel/plugin-transform-react-jsx', // I really need this plugin
      {
        runtime: 'automatic',
      },
    ],
    'react-native-reanimated/plugin',
  ],
};
```

 Everything works!😅

Note: If you want to do this, make sure to check out the other plugins included in`@babel/preset-react`, incase your project might need them.

**Comment by darrylyoung** [comment]
@Dajust I noticed the same thing today but instead of `@babel/preset-react` it was `babel-preset-expo` that was causing the problem. For context, `babel-preset-expo` is basically a wrapper around `metro-react-native-babel-preset`, adding a few extra Expo-specific things. If I remove it, I have issues with icon font loading (as I started with a managed Expo project and I'm now on a bare project) but if I keep it, I have the problem shown above.

Before trying to use this package, just after upgrading to React 17, I had to use the following:

```js
module.exports = {
  presets: [
    ['babel-preset-expo'],
    ['module:metro-react-native-babel-preset', { useTransformReactJSXExperimental: true }],
  ],
  plugins: [
    [
      '@babel/plugin-transform-react-jsx',
      {
        runtime: 'automatic',
      },
    ],
    'react-native-reanimated/plugin',
  ],
}
```

It's a bit of a mess because I technically have a duplicate preset in there (with the first being a wrapper around the second), but seeing as the first – `babel-preset-expo` – pins to an _old_ version of `metro-react-native-babel-preset`, I have to include it seprately, too, so I can use the New JSX Transform). 😴

**Comment by Dajust** [comment]
@darrylyoung I hear you. I've personally decided to stop initialising a new project with expo, it has a lot of drawbacks from my little experience with it. If you can, replace your icons with their svg versions. It might be a bit of work if you have so many icons, but it's worth the peace of mind. Plus SVGs are better icons to font-icons (but that's a different conversation 🤓)...

**Comment by Shaninnik** [comment]
Just in case someone will bump into this issue, for me, it was `babel-plugin-ts-nameof` that was causing this

**Comment by He1nr1chK** [comment]
Does anyone have a fix for this? Still occurs in Expo 42 and "@gorhom/bottom-sheet": "^4.0.2",

**Comment by lander854** [comment]
still seeing this issue on latest version of reanimated + gorhom/bottom-sheet

**Comment by mydesweb** [comment]
@gorhom I can see this error in version 4.2.1 with `"react-native-reanimated": "^2.8.0",`
![Simulator Screen Shot - iPhone 13 - 2022-04-30 at 00 10 05](https://user-images.githubusercontent.com/5901386/166069665-593ed751-107d-4ff9-9fb8-362e5c5f90ce.png)

**Comment by bhavzie** [comment]
Any update on this issue?
