### ISSUE TITLE
Can't resolve './Touchables' 

### ISSUE THREAD

**Issue by FiskaniC** [gorhom/react-native-bottom-sheet#520]
# Bug

Use getting started code and paste into App https://gorhom.github.io/react-native-bottom-sheet/modal/usage

![image](https://user-images.githubusercontent.com/40929607/124440667-21a35400-dd7b-11eb-8348-3d96d83787b8.png)

![image](https://user-images.githubusercontent.com/40929607/124440676-26680800-dd7b-11eb-8573-a36f77f86f90.png)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.6   |
| react-native                    | 42.0.0   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduced

1. Add bottom sheet package with dependencies.
2. Use getting started code and paste into App https://gorhom.github.io/react-native-bottom-sheet/modal/usage

Describe what you expected to happen:

1. Have a button that allows you to open modal
2. Error above happens

## Reproducible sample code

`import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet, Button } from 'react-native';
import {
  BottomSheetModal,
  BottomSheetModalProvider,
} from '@gorhom/bottom-sheet';

const App = () => {
  // ref
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handlePresentModalPress = useCallback(() => {
    bottomSheetModalRef.current?.present();
  }, []);
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  // renders
  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button
          onPress={handlePresentModalPress}
          title="Present Modal"
          color="black"
        />
        <BottomSheetModal
          ref={bottomSheetModalRef}
          index={1}
          snapPoints={snapPoints}
          onChange={handleSheetChanges}
        >
          <View style={styles.contentContainer}>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;`

**Comment by pycraft114** [comment]
any way to solve?
