### ISSUE TITLE
Why is './Touchables' not there

### ISSUE THREAD

**Issue by FiskaniC** [gorhom/react-native-bottom-sheet#524]
## Ask your Question

Hi there seems to be an issue in the latest release 3.6.6. @gorhom/bottom-sheet/lib/module/components/touchables/index.js is looking for a Touchables file thats not there.

![image](https://user-images.githubusercontent.com/40929607/124541722-4e5e7680-de22-11eb-9309-53ee8ccf0b1b.png)

![image](https://user-images.githubusercontent.com/40929607/124541736-53232a80-de22-11eb-8687-c9d3f18fa294.png)

Library | Version
-- | --
@gorhom/bottom-sheet | 3.6.6
react-native | 42.0.0
react-native-reanimated | 2.2.0
react-native-gesture-handler | 1.10.3

**Comment by likeSo** [comment]
This library is not support `react-native-web` now, either `react-native-windows` and `react-native-macos`, we are waiting for it

**Comment by FiskaniC** [comment]
How do I test on my machine or on my iphone?

**Comment by ajturpei** [comment]
There should be a touchables file added as .web since they only target mobile devices now. Shouldn't be that hard to fix.

**Comment by barbalata** [comment]
I think the .web file should contain the same things as .ios, because all the components from it are compatible with the web platform.

**Comment by gorhom** [comment]
this should be resolved with `v4` 👍
