### ISSUE TITLE
BottomSheetBackdrop component doesn't show up at all when setting the `appearsOnIndex` prop

### ISSUE THREAD

**Issue by ramirezabel** [gorhom/react-native-bottom-sheet#527]
# Bug

The `BottomSheetBackdrop` component wont show up when setting the `appearsOnIndex={0}` for example. As I understand the prop is to tell the backdrop to show up when the snap point in on the index provided. If thats not the case then can someone provide a way of doing that. In my case the backdrop doesn't show when the index is at `0` only when dragging the component up to the other snap points does it show, however like mentioned above, if I set the property of the backdrop `appearsOnIndex={0}` it doesn't show at all. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 4.0.0-alpha.19  |
| react-native                    |  ^0.64.1   |
| react-native-reanimated         |  ^2.1.0  |
| react-native-gesture-handler    |  ^1.10.3   |

## Steps To Reproduce

1.  Set the `BottomSheetBackdrop` prop `appearsOnIndex={0}` 
2. Open the bottom sheet modal and the backdrop doesn't show

Describe what you expected to happen:

1. Set the `BottomSheetBackdrop` prop `appearsOnIndex={0}` 
2. Backdrop should show up as soon as the modal opens to the first snap point

## Reproducible sample code

<img width="810" alt="Screen Shot 2021-07-10 at 8 19 11 PM" src="https://user-images.githubusercontent.com/10616358/125179367-19ed1080-e1bc-11eb-8348-2a59a28bb5d9.png">

<img width="605" alt="Screen Shot 2021-07-10 at 8 17 51 PM" src="https://user-images.githubusercontent.com/10616358/125179351-f924bb00-e1bb-11eb-8d37-a9f6331d9027.png">

**Comment by gorhom** [comment]
@ramirezabel  you need to provide `disappearsOnIndex` with `-1` , the default value is `0`

https://github.com/gorhom/react-native-bottom-sheet/blob/73decd3f13f17f585796556fc2bd43f408be8603/src/components/bottomSheetBackdrop/types.d.ts#L24-L29

**Comment by pfcodes** [comment]
> @ramirezabel you need to provide `disappearsOnIndex` with `-1` , the default value is `0`
> 
> https://github.com/gorhom/react-native-bottom-sheet/blob/73decd3f13f17f585796556fc2bd43f408be8603/src/components/bottomSheetBackdrop/types.d.ts#L24-L29

Feel like this should be the default behavior. Thanks though

**Comment by aymather** [comment]
This should definitely be the default behavior, can't really think of a situation where I would even use other options.

**Comment by Alaa-Ben** [comment]
@gorhom A bit weird: on some phones (Honor, Android 12 for example), setting disappearsOnIndex={-1} "freezes" the UI when navigating to the concerned screen. After some investigation, it seems it's the backdrop not unmounting correctly: bottomsheet is closed but backdrop still mounted.

**Comment by fubd** [comment]
> This should definitely be the default behavior, can't really think of a situation where I would even use other options.

i think so.

**Comment by ghost** [comment]
backdropComponent={(props) => (
          <BottomSheetBackdrop
            {...props}
            onPress={() => ref.current?.close()}
            disappearsOnIndex={-1}
          />
        )}
