### ISSUE TITLE
Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?

### ISSUE THREAD

**Issue by hristowwe** [gorhom/react-native-bottom-sheet#529]
# Bug
Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin? shows me when i tried to run this lib in expo project.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         |Release 3.6.6  |
| react-native                    |0.64   |
| react-native-reanimated         |2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Copy and paste code in example and got error
Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?

Describe what you expected to happen:

1.Expected to run example in github
![image](https://user-images.githubusercontent.com/57602380/125187872-624b1380-e23a-11eb-9b6c-3b892465bb10.png)

## Reproducible sample code
My code so far:
```
import React, { useCallback, useRef, useMemo } from "react";
import { StyleSheet, View, Text, Button } from "react-native";
import BottomSheet, { BottomSheetFlatList } from "@gorhom/bottom-sheet";

const App = () => {
  // hooks
  const sheetRef = useRef(null);

  // variables
  const data = useMemo(
    () =>
      Array(50)
        .fill(0)
        .map((_, index) => `index-${index}`),
    []
  );
  const snapPoints = useMemo(() => ["25%", "50%", "90%"], []);

  // callbacks
  const handleSheetChange = useCallback((index) => {
    console.log("handleSheetChange", index);
  }, []);
  const handleSnapPress = useCallback((index) => {
    sheetRef.current?.snapTo(index);
  }, []);
  const handleClosePress = useCallback(() => {
    sheetRef.current?.close();
  }, []);

  // render
  const renderItem = useCallback(
    ({ item }) => (
      <View style={styles.itemContainer}>
        <Text>{item}</Text>
      </View>
    ),
    []
  );
  return (
    <View style={styles.container}>
      <Button title="Snap To 90%" onPress={() => handleSnapPress(2)} />
      <Button title="Snap To 50%" onPress={() => handleSnapPress(1)} />
      <Button title="Snap To 25%" onPress={() => handleSnapPress(0)} />
      <Button title="Close" onPress={() => handleClosePress()} />
      <BottomSheet
        ref={sheetRef}
        snapPoints={snapPoints}
        onChange={handleSheetChange}
      >
        <BottomSheetFlatList
          data={data}
          keyExtractor={(i) => i}
          renderItem={renderItem}
          contentContainerStyle={styles.contentContainer}
        />
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 200,
  },
  contentContainer: {
    backgroundColor: "white",
  },
  itemContainer: {
    padding: 6,
    margin: 6,
    backgroundColor: "#eee",
  },
});

export default App;

```

**Comment by likeSo** [comment]
Have you followed expo's install guide? Configured babel config?

**Comment by hristowwe** [comment]
ye i have already added
 ```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['react-native-reanimated/plugin'],
  };
```
};

But it doesnt work again

**Comment by likeSo** [comment]
- Please make sure you installed reanimated latest version by `expo install`
- babel plugin
- try start your project by `expo start --clear`

May this helpful

**Comment by hristowwe** [comment]
Ok works fine now thanks !

**Comment by hristowwe** [comment]
Perfect lib everything works fine !!!!

**Comment by talaikis** [comment]
--clear-cache Does not work for non-expo.

**Comment by vamshi9666** [comment]
> --clear-cache Does not work for non-expo.

use `yarn start --reset-cache ` or "npm start --reset-cache" for bare react-native projects.

**Comment by DMezhenskyi** [comment]
Hi! I have a similar issue. The only difference is that I don't use expo and what I also noticed is that everything works fine if I start packager like `yarn start`. However, when packager starts via `node_modules/react-native/scripts/launchPackager.command` (which happens automatically when you run react-native run-ios) then it fails with an error described in the issue. Is there any idea why it could happen? 

```json
    "react-native": "0.65.1",
    "@gorhom/bottom-sheet": "^4",
    "react-native-reanimated": "^2.2.2",
    "react-native-gesture-handler": "^1.10.3",
```
