### ISSUE TITLE
Using FlatList in BottomSheet cause error

### ISSUE THREAD

**Issue by hristowwe** [gorhom/react-native-bottom-sheet#531]
# Bug
I am trying to implant FlatList in BottomSheet but i got following error

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `App`.
> 
> This error is located at:
>     in RCTView (at View.js:34)
>     in View (at App.js:67)
>     in App (created by ExpoRoot)
>     in ExpoRoot (at renderApplication.js:45)
>     in RCTView (at View.js:34)
>     in View (at AppContainer.js:106)
>     in RCTView (at View.js:34)
>     in View (at AppContainer.js:132)
>     in AppContainer (at renderApplication.js:39)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         |Release 3.6.6   |
| react-native                    | 0.64   |
| react-native-reanimated    |2.0  |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. First if all i import **BottomSheetFlatList** and **BottomSheet**

Describe what you expected to happen:

1.I want to create sothing like example (image below) using FlatList
![image](https://user-images.githubusercontent.com/57602380/125196254-db119600-e261-11eb-9a70-31a91c2d0fb8.png)

## Reproducible sample code
My code so far: 
```
import React, { useCallback, useMemo, useRef } from "react";
import { View, Text, StyleSheet } from "react-native";
import {
  BottomSheetFlatList,
  BottomSheet,
} from "@gorhom/bottom-sheet";
const App = () => {
  // ref
  const bottomSheetRef = useRef(null);

  // variables
  const snapPoints = useMemo(() => ["25%", "50%"], []);
  const DATA = [
    {
      id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
      title: "First Item",
    },
    {
      id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
      title: "Second Item",
    },
    {
      id: "58694a0f-3da1-471f-bd96-145571e29d72",
      title: "Third Item",
    },
    {
      id: "586fdfd94a0f-3da1-471f-bd96-145571e29d72",
      title: "ffThird Item",
    },
    {
      id: "586fdfdfdsfdsfsdfds94a0f-3da1-471f-bd96-145571e29d72",
      title: "ffThird Item",
    },
    {
      id: "586fdffdsfdsfdsd9fdsfsd4a0f-3da1-471f-bd96-145571e29d72",
      title: "ffThird Item",
    },
    {
      id: "586fdfdfdsfdsfds9fdsfsd4a0f-3da1-471f-bd96-145571e29d72",
      title: "ffThird Item",
    },
    {
      id: "586fdfdsfdsfdsfdsfd9fdsfsd4a0f-3da1-471f-bd96-145571e29d72",
      title: "ffThird Item",
    },
    {
      id: "586ffdsfsddfd9fdsfsd4a0f-3da1-471f-bd96-145571e29d72",
      title: "ffThird Item",
    },
  ];
  const renderItem = ({ item }) => (
    <View key={item.key}>
      <Text style={{ fontSize: 30 }}>{item.title}</Text>
    </View>
  );

  // callbacks
  function test() {
    console.log("fdsfsd");
  }

  // renders
  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        onChange={test}
      >
        <View style={styles.contentContainer}>
          <BottomSheetFlatList
            initialNumToRender={5}
            windowSize={10}
            maxToRenderPerBatch={5}
            data={DATA}
            renderItem={ren}
          />
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: "grey",
  },
  contentContainer: {
    flex: 1,
    alignItems: "center",
  },
});

export default App;
```

**Comment by hssdiv** [comment]
got same error and figured it out:
correct import is this:
import BottomSheet, { BottomSheetScrollView } from "@gorhom/bottom-sheet";

not 
import { BottomSheetFlatList, BottomSheet } from "@gorhom/bottom-sheet";
