### ISSUE TITLE
FlatList inside BottomSheetView doesn't readjust when BottomSheet gets expanded

### ISSUE THREAD

**Issue by sorioinc** [gorhom/react-native-bottom-sheet#533]
Hi, thank you for this amazing library, it's awesome!

I got this problem with a FlatList inside a BottomSheetView. The FlatList doesn't adjust quite correctly when the BottomSheet is out of the viewport it seems. When expanded the FlatList overflows the container. I need to have a textinput at the bottom.

However, this is issue isn't consistent, if you see the gif below, on the first two times the BottomSheet is expanded, the textinput is shown, however, the third time it overflows. What could be possibly happening?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.6   |
| react-native                    | 0.63   |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.3  |

You can try checking it yourself here:
https://snack.expo.io/@sorioinc/suspicious-ramen

![RPReplay_Final1625995946](https://user-images.githubusercontent.com/6693933/125212431-950d0000-e26a-11eb-9bc6-2b524ca90b9b.gif)

**Comment by gorhom** [comment]
hi @sorioinc  could you test on the latest `v4` alpha release ? thanks

**Comment by sorioinc** [comment]
Hi @gorhom, thanks for the response. I've tried using v4 alpha 25, but the bottom sheet doesn't even show. Rolled back to v3, and it does. I can't create a snack, there's an issue says it can't find ./Touchables.

**Comment by gorhom** [comment]
@sorioinc that issue is because the web support , but it should work on Android/iOS

**Comment by sorioinc** [comment]
I made v4-alpha-30 work on some of my screens. I'm just left with one issue, have a useEffect that controls if the bottomsheet is visible, from a variable in useState, changed by a button tap. However, it's until the 3rd tap the bottomsheet comes into view. 

Traced it back to here: https://github.com/gorhom/react-native-bottom-sheet/blob/d8276041e140b7b50f7b3f392c5f0ed0be088c8c/src/components/bottomSheet/BottomSheet.tsx#L1446

```
if (_animationState !== ANIMATION_STATE.STOPPED) {
   return;
}
```
_animationState seems to be undetermined the first two times, this is consistent every time `bottomSheetRef.current?.expand();` is called; third time it works as expected.

Do you have any idea what could be going on?

**Comment by sorioinc** [comment]
I have my bottomsheet's `index={-1}` and this as snap points: 
```
const snapPoints = useMemo(() => ['100%'], []);
```
Changed it to:
```
const snapPoints = useMemo(() => ['99%'], []);
```

And it works all of the sudden, what's the difference?

**Comment by gorhom** [comment]
@sorioinc `inverted` is not supported yet. #512
