### ISSUE TITLE
Appium IOS XCUiTest E2E tests does not see contents of the panel

### ISSUE THREAD

**Issue by vitalyiegorov** [gorhom/react-native-bottom-sheet#534]
# Bug

Using Appium e2e tests perfectly works on Android but due to the differences of accessibility behaviours and rendering on iOS they just do not see anything inside the panel children. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet             | 2.3.0    |
| react-native                                 | 0.64.2. |
| react-native-reanimated            | 1.13.2    |
| react-native-gesture-handler    | 1.10.3    |
| appium                                         | 2.0.0-beta.12    |
| appium-xcuitest-driver               | 1.66.2    |

## Steps To Reproduce

1. Run e2e test that interacts with bottom-sheet panel contents

Describe what you expected to happen:

1. Appium should be able to find elements inside the bottom-sheet panel

## Reproducible sample code

We have investigated source code and found that this patch makes content available to Appium XCUiTest, we understand that this could break one accessibility feature:
```
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
index 4bc4cf8..49fa359 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheet/BottomSheet.tsx
@@ -631,7 +631,7 @@ const BottomSheetComponent = forwardRef<BottomSheet, BottomSheetProps>(
             {...containerTapGestureHandler}
           >
             <Animated.View
-              accessible={true}
+              accessible={false}
               accessibilityRole="adjustable"
               accessibilityLabel="Bottom Sheet"
               style={containerStyle}
diff --git a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContentWrapper/BottomSheetContentWrapper.ios.tsx b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContentWrapper/BottomSheetContentWrapper.ios.tsx
index 7ea5fbb..6625034 100644
--- a/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContentWrapper/BottomSheetContentWrapper.ios.tsx
+++ b/node_modules/@gorhom/bottom-sheet/src/components/bottomSheetContentWrapper/BottomSheetContentWrapper.ios.tsx
@@ -16,7 +16,7 @@ const BottomSheetContentWrapperComponent = forwardRef<
       onGestureEvent={onGestureEvent}
       onHandlerStateChange={onHandlerStateChange}
     >
-      <Animated.View pointerEvents="box-none">{children}</Animated.View>
+      <Animated.View style={{flex:1}} pointerEvents="box-none">{children}</Animated.View>
     </TapGestureHandler>
   );
 });
```

**Comment by valeriashpiner** [comment]
It would be nice if someone could take a look at this, because I am facing the same issue and it's impossible to run E2E on ios right now.

**Comment by ChernenkoDmitriy** [comment]
Have the same problem, any ideas?

**Comment by JoNesVai** [comment]
I have the same problem. Is there any solution for this problem or some fix in near future scope?
