### ISSUE TITLE
[v4] Content height is incorrect when handleComponent={null}

### ISSUE THREAD

**Issue by ozasadnyy** [gorhom/react-native-bottom-sheet#535]
# Bug

If `handleComponent={null}` `BottomSheetHandleContainerComponent` will not be rendered and as a result `handleContainerLayout` will never be invoked, so `animatedHandleHeight` (`BottomSheet.tsx`) have `value === INITIAL_HANDLE_HEIGHT === -999`. That's why `animatedContentHeight` returns a wrong number, so scrollable content huge and content will be clipped.  

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | v4.0.0-alpha.19   |
| react-native                    | 0.64.1   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Set `handleComponent={null}` on `BottomSheet`
2. Put some scrollable content inside (ex. `BottomSheetScrollView`)

Describe what you expected to happen:

1. Content is not scrollable (container height is too big)

## Reproducible sample code

```
		<BottomSheet
          snapPoints={['25%', '50%', '90%']}
          handleComponent={null}
        >
          <BottomSheetScrollView>
            {Array(50)
              .fill(0)
              .map((_, index) => `index-${index}`)
              .map(({ item }) => (
                <View
                  key={item}
                  style={{
                    padding: 6,
                    margin: 6,
                    backgroundColor: '#eee',
                  }}
                >
                  <Text>{item}</Text>
                </View>
              ))}
          </BottomSheetScrollView>
        </BottomSheet>
```

**Comment by ozasadnyy** [comment]
My current solution `BottomSheet.tsx`:
```
	const animatedHandleHeight = useReactiveSharedValue(
      handleComponent === null ? 0 : _providedHandleHeight ?? INITIAL_HANDLE_HEIGHT
    );
```

**Comment by gorhom** [comment]
thanks @ozasadnyy for reporting this issue , it should be resolved on the next alpha release https://github.com/gorhom/react-native-bottom-sheet/commit/01e1e8716477aa904bedbda2aa08642f8a0c3c9c
