### ISSUE TITLE
[v4] showsVerticalScrollIndicator param is not working

### ISSUE THREAD

**Issue by ozasadnyy** [gorhom/react-native-bottom-sheet#537]
# Bug

`showsVerticalScrollIndicator` prop is not working as it is overwritten with `animatedProps` (`{decelerationRate: number; showsVerticalScrollIndicator: boolean;}`)

File `components/bottomSheetScrollable/createBottomSheetScrollableComponent.tsx`
```tsx
		<ScrollableComponent
            {...rest} <----- this is where we pass our configuration
            // @ts-ignore
            ref={scrollableRef}
            overScrollMode={overScrollMode}
            keyboardDismissMode={keyboardDismissMode}
            scrollEventThrottle={16}
            refreshing={refreshing}
            onRefresh={onRefresh}
            progressViewOffset={progressViewOffset}
            refreshControl={refreshControl}
            onScroll={handleScrollEvent}
            animatedProps={scrollableAnimatedProps}  <----- here it is overwritten 
            style={containerStyle}
          />
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | v4.0.0-alpha.20   |
| react-native                    | 0.64.1   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Add `BottomSheetScrollView` inside `BottomSheet`
2. Set `showsVerticalScrollIndicator` props on `BottomSheetScrollView` to `false`
3. Scroll down and observe that indicator still persist

Describe what you expected to happen:

1. Hide vertical indicator when `howsVerticalScrollIndicator={false}`

## Reproducible sample code

```tsx
		<BottomSheet
          snapPoints={['25%', '50%', '90%']}
        >
          <BottomSheetScrollView
		    showsVerticalScrollIndicator={false} <----- this line
		  >
            {Array(50)
              .fill(0)
              .map((_, index) => `index-${index}`)
              .map(({ item }) => (
                <View
                  key={item}
                  style={{
                    padding: 6,
                    margin: 6,
                    backgroundColor: '#eee',
                  }}
                >
                  <Text>{item}</Text>
                </View>
              ))}
          </BottomSheetScrollView>
        </BottomSheet>
```

**Comment by gorhom** [comment]
it should be fixed on the next alpha release https://github.com/gorhom/react-native-bottom-sheet/commit/11cdc344e029200435280389b291441c1c363e97 👍
