### ISSUE TITLE
Snap point of '0%' throws error

### ISSUE THREAD

**Issue by Johan-dutoit** [gorhom/react-native-bottom-sheet#54]
# Bug

Is having a bottom sheet completely hidden/off the screen against design guidelines, or simply missed?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0-alpha.0   |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 2.0.0-alpha.7   |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce

1. Set any bottom sheet with a snap point that contains '0%' (i.e. `['0%', '80%']`) 

Describe what you expected to happen:

1. To allow the user to completely 'swipe away' the bottom sheet. 

## Reproducible sample code

```
<BottomSheet
  ref={bsRef}
  initialSnapIndex={-1}
  onChange={onBottomSheetChanged}
  animatedPositionIndex={position}
  snapPoints={['0%', '80%']}>
...
</BottomSheet>
```

**Comment by alz10** [comment]
you can put 0 or -1

**Comment by Johan-dutoit** [comment]
No idea why I didn't try 0 on it's own.  Closing.
