### ISSUE TITLE
TypeError: Cannot read property 'BottomSheetModalProvider' of undefined, testing

### ISSUE THREAD

**Issue by ricardopdj** [gorhom/react-native-bottom-sheet#540]
## Ask your Question
Hi. Need some support regarding testing the bottomSheetModal
Im writing a simple test to check if its rendering right, but Im having the following error.
![Screen Shot 2021-07-14 at 17 59 13](https://user-images.githubusercontent.com/2244129/125692058-a0506a1c-2b9d-41d2-b9fd-6f8de2b9f729.png)

Ive already setup the mock on my test

```
require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();

jest.mock('@gorhom/bottom-sheet', () => {
require('react-native-reanimated/mock');
});
```

any help? tks

**Comment by tausani-ah-chong** [comment]
I am getting the same error also

**Comment by khushal87** [comment]
@gorhom Any fix for this?

**Comment by thtRajasthaniGuy** [comment]
@gorhom  any solution?

**Comment by rheng001** [comment]
Facing same problem

**Comment by vtrrsl** [comment]
Pinning react-native-reanimated to 2.6.0 instead of using 2.7.0 worked for in this case for me

**Comment by JoyCood** [comment]
> Pinning react-native-reanimated to 2.6.0 instead of using 2.7.0 worked for in this case for me

i use **"react-native-reanimated": "^2.13.0"**,  **"@gorhom/bottom-sheet": "^4.4.5"** face the same problem
