### ISSUE TITLE
[V3] ref.current.dismiss() does not close modal when the bottom sheet is still opening

### ISSUE THREAD

**Issue by TheReidZhang** [gorhom/react-native-bottom-sheet#542]
# Bug

[V3] ref.current.dismiss() does not close modal when the bottom sheet is in the process of opening from bottom. And dismiss() won't no longer works. But click on backdrop makes it dismiss.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | v3   |
| react-native                    | 0.64.2   |
| react-native-reanimated         | 2.2.0  |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

```
const renderCategorySectionHeader = useCallback(
    ({ section }) => (
      <View>
        <Title>{section.category}</Title>
      </View>
    ),
    []
  );

 const renderCategoryItem = useCallback(
    ({ section, item }) => (
      <TouchableOpacity
        onPress={() => {
          console.log('press')
          addPostStore.setCategory(item);
          categorySheetRef.current.dismiss();
        }}>
        <View style={{ padding: 5 }}>
          <Subheading>{item}</Subheading>
        </View>
      </TouchableOpacity>
    ),
    []
  );

const CATEGORY_LIST = [
  { category: 'Automotive', data: ['Cars', 'Motorcycles', 'Parts'] },
  { category: 'Art', data: ['Music', 'Movies', 'Instruments', 'Antiques', 'Collections', 'Books'] },
  { category: 'Electronics', data: ['Phones', 'Computers', 'General', 'Games'] },
];


const categorySheetRef = useRef(null);
  const categoryIndexRef = useRef(0);
  const categorySnapPoints = useMemo(() => ['85%'], []);
  const CategoryBottomSheet = () => {
    return (
      <BottomSheetModal
        ref={categorySheetRef}
        index={0}
        snapPoints={categorySnapPoints}
        onAnimate={(fromIndex, toIndex) =>
          (categoryIndexRef.current = toIndex)
        }>
        <BottomSheetSectionList
          sections={CATEGORY_LIST}
          keyExtractor={(item, index) => item + index}
          renderSectionHeader={renderCategorySectionHeader}
          renderItem={renderCategoryItem}
          stickySectionHeadersEnabled={false}
          contentContainerStyle={{
            alignItems: 'center',
          }}
        />
      </BottomSheetModal>
    );
  };
````
1. Click some button that make the modal present.
2. When it is opening, click on a section tab.
3. Dismiss() should be called and close the sheet. But it won't and won't work afterwards. (Waiting for the sheet to going up completely and call dismiss() works fine)

Describe what you expected to happen:

1. Expect when it is the in the process of opening sheet, dismiss() can do effect.
2. Worst case, after it get pop up completely, dismiss() should work instead of breaking.

**Comment by VinitBhavsar** [comment]
Did you find any solution @ZijianZhang991203 ?

I'm also facing the same issue

**Comment by VinitBhavsar** [comment]
Try onTouchStart and onTouchEnd Event

`onTouchStart={() => { this.bottomSheetRef.current.dismiss() }}
                                onTouchEnd={() => { this.bottomSheetRef.current.dismiss() }}`
                                
@ZijianZhang991203
