### ISSUE TITLE
Nested BottomSheetFlatList/SectionList/ScrollView won't scroll on iPhone 12 series (14.6)

### ISSUE THREAD

**Issue by Arcaneless** [gorhom/react-native-bottom-sheet#543]
# Bug

This issue occurred when I was testing on ip12 series, this doesn't happen on other devices.

Although #266 the gesture handler's FlatList did the trick for me. There are some other issues popping: 
	1. The scrolling behaviour does not work as expected, bottom sheet won't move up when the FlatList has reached its end.
	2. The content is out of screen when the List has scrolled to the bottom.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 3.6.6   |
| react-native                    | 0.64.2  |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

1. Create a BottomSheet containing a BottomSheetFlatList
2. Scroll the FlatList

Describe what you expected to happen:

1. The list will begin scroll once the BottomSheet reached its top
2. The BottomSheet will move once the List reached its top

## Reproducible sample code

	  <BottomSheet
		  snapPoints={[1, '30%', '60%']}
		  handleHeight={101}
	  >
		  <BottomSheetFlatList
			  data={Array(10).fill(0)}
			  renderItem={({ index, item }) => (
				  <View
	                style={{
	                  width: '100%',
	                  padding: 30,
	                }}>
	                <Text>{index}</Text>
		          </View>
			  )}
	      />
	  </BottomSheet>

**Comment by Arcaneless** [comment]
After doing some research in the source code, this is related to the rounding issue with the snapPoint and animatedPosition value when using percentage in the snapPoints.
animatedPosition.value = 186.2 
snapPoint                       = 186.20000000000005

this will lead the code treat the sheet as OVER_EXTENDED instead of EXTENDED

My workaround is to change this at line 364 in BottomSheet.tsx
```diff
<         animatedPosition.value === extendedSheetPosition ||
---
>         Math.abs(extendedSheetPosition - animatedPosition.value) < 1e-13 ||
```

**Comment by gorhom** [comment]
@Arcaneless could you test on `v4` ? thanks

**Comment by Arcaneless** [comment]
`v4` works for me as far as I tested.

> @Arcaneless could you test on `v4` ? thanks

**Comment by gorhom** [comment]
thanks @Arcaneless for testing, I will deprecate v3 soon, so i would suggest to you to update to `v4` 👍
