### ISSUE TITLE
Is there a way to listen event when drag the sheet?

### ISSUE THREAD

**Issue by moxspoy** [gorhom/react-native-bottom-sheet#544]
## Ask your Question

Hello guys!
I want to make the top end and top start radius of handle component depends on sheet position. When the sheet is fully expanded, the radius is 0. When the sheet start to collapse/dragged down, the radius will change *immediately* into 12 (without waiting for the sheet finish to animate).
I have tried to use onChange, but the radius did not change immediately. 

anyone who can help me?
Thank you!

**Comment by moxspoy** [comment]
do you know how to solve this? @gorhom

**Comment by gorhom** [comment]
look at the example here https://github.com/gorhom/react-native-bottom-sheet/blob/v4/example/src/components/customHandle/CustomHandle.tsx
