### ISSUE TITLE
dragFromHandleOnly

### ISSUE THREAD

**Issue by alz10** [gorhom/react-native-bottom-sheet#55]
I used `react-native-raw-bottom-sheet` before and it has a prop `dragFromTopOnly` in which the bottom-sheet can only be close (when being drag) by the handle not by the entire bottom-sheet itself. I like this library compare to that because of performance. I hope you can add this, thanks

**Comment by gorhom** [comment]
I just pushed an alpha release for v2, please try it and let me know :)

also check out the new [documents website ( still in progress )](https://gorhom.github.io/react-native-bottom-sheet/) 🎉

```bash
yarn add @gorhom/bottom-sheet@2.0.0-alpha.2
```
