### ISSUE TITLE
keyboardBehavior is not working on Modal

### ISSUE THREAD

**Issue by Fantomiald** [gorhom/react-native-bottom-sheet#551]
# Bug

The keyboardBehavior props is not working so the keyboard is on the modal

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^3   |
| react-native                    | ^0.64.2   |
| react-native-reanimated         | ^2.2.0   |
| react-native-gesture-handler    | ^1.10.3  |

## Steps To Reproduce

1. Press a button to open the modal
2. Open a TextInput inside it
3. Let the keyboard become opened

Describe what you expected to happen:

1. I'm expecting that the modal got a offset to be above the keyboard

## Reproducible sample code

```
const Test = () => {
  const bottomSheetRef = useRef(null);
  const snapPoints = useMemo(() => ['35%'], []);

  const openMessageModal = useCallback(() => {
    bottomSheetRef.current.present();
  }, []);

  const backdropComponent = useCallback((backdropProps) => (
    <BottomSheetBackdrop {...backdropProps} enableTouchThrough closeOnPress />
  ), []);

  return(
    <View style={{flex: 1}}>
      <Button onPress={openMessageModal} />
      <BottomSheetModal
        backdropComponent={backdropComponent}
        ref={bottomSheetRef}
        index={0}
        snapPoints={snapPoints}
        keyboardBehavior="interactive"
      >
        <TextInput/>
      </BottomSheetModal>
    </View>
  );
}
```

**Comment by Fantomiald** [comment]
I think I got it, i must use the BottomSheetTextInput and not my own TextInput component so the keyboardBehavior is working.

**Comment by gorhom** [comment]
@Fantomiald yup! i would advice to use `v4` for better handling 👍

**Comment by Chehow** [comment]
Hi @gorhom 
Is there any way to get this work with own TextInput instead of BottomSheetTextInput? Thanks.

**Comment by JoyCood** [comment]
> Hi @gorhom Is there any way to get this work with own TextInput instead of BottomSheetTextInput? Thanks.

when i use custome textInput instedad of BottomSheetTextInput, when close the modal, but the keyboard does not disappear, any solution for this problem?
