### ISSUE TITLE
How to change color of the top of Bottom Sheet Modal

### ISSUE THREAD

**Issue by hristowwe** [gorhom/react-native-bottom-sheet#553]
## Ask your Question
I want to change color of the top of Bottom Sheet Modal(image below) but i dont know how?

![image](https://user-images.githubusercontent.com/57602380/126806627-818d5f2a-8e52-4c5d-be93-ce1ee2e59f19.png)

**Comment by kickbk** [comment]
Create a custom BottomSheet handle and pass it as `handleComponent={YourHandle}` prop to `BottomSheet`

**Comment by hristowwe** [comment]
Thank you !
