### ISSUE TITLE
BottomSheet jump on snapTo(1) with dynamic snapPoints

### ISSUE THREAD

**Issue by gran33** [gorhom/react-native-bottom-sheet#557]
# Bug
`BottomSheet` snapTo(1) and immediately collapse.
the bottom sheet snap points is dynamic regarding to the items in it.
Using `snapTo(1)`. 

https://user-images.githubusercontent.com/1650967/127987401-760c5c82-fdd3-4496-860c-75d7d6edc744.mov

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.6.6   |
| react-native                    | 0.64.0   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Create dynamic `snapPoints`
2. Call to `snapTo(1)`

Describe what you expected to happen:

1. Bottom sheet to open to the desired height 
2. Stay there and not collapse immediately 

## Reproducible sample code
```
const snapPoints = useMemo(() => {
    const CLOSE_HEIGHT = 103;
    const dynamicHeight = numOfItems * 100 

    return [CLOSE_HEIGHT, dynamicHeight];
  }, [numOfItems]);

const onButtonPress = useCallback(() => {
  drawerRef.snapTo(1)
}, []);
```

**Comment by gorhom** [comment]
@gran33 could you test on `v4`, thanks
