### ISSUE TITLE
How to get Y position of the sheet?

### ISSUE THREAD

**Issue by questionablequestion** [gorhom/react-native-bottom-sheet#559]
## Ask your Question

I'm trying to have fixed header above bottom sheet and if let's say bottom sheet Y position is 50, I want to add background to the header so it "fits" in to the bottom sheet. Currently I could do that with onChange/onAnimate but that takes effect after transition is completed, not while user is still dragging the bottom sheet.

Any solutions for v3?

Thanks

**Comment by mateuszmazurek** [comment]
pass some shared value to `animatedPosition` prop and use it in `useAnimatedStyle` hook

**Comment by questionablequestion** [comment]
Thanks. If anyone needs this, check out example folder with Map screen and Weather component how to animate something based on Bottom sheet position.

**Comment by VityaSchel** [comment]
Isolated example:
```javascript
import Animated, { useAnimatedStyle, useSharedValue } from 'react-native-reanimated'
import BottomSheet from '@gorhom/bottom-sheet'

function Screen() {
  const animatedPosition = useSharedValue(0)
  const animatedStyle = useAnimatedStyle(() => {
    console.log(animatedPosition.value);
    return {
      // write styles here as css-in-js object
    }
  })
  return (
    <BottomSheet>
        {/* ... */}
        animatedPosition={animatedPosition}
    >
      {/* ... */}
    </BottomSheet>
    <Animated.View style={animatedStyle} />
  )
}
```

**Comment by SimajjiHans** [comment]
What if I use class component?

**Comment by VityaSchel** [comment]
> What if I use class component?

stop using class component? how are you even gonna use built-in hooks
