### ISSUE TITLE
Tests failing due to TypeError: _reactNativeReanimated.default.addWhitelistedUIProps is not a function

### ISSUE THREAD

**Issue by joegoodall1** [gorhom/react-native-bottom-sheet#56]
# Bug

The library works well in our code with no errors but we're seeing this failing test and I'm not sure how to resolve.

<img width="940" alt="Screenshot 2020-11-03 at 12 06 57" src="https://user-images.githubusercontent.com/8888799/97983802-c2490a80-1dcd-11eb-9629-ed963d915ac0.png">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 1.4.1  |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 1.13.1   |
| react-native-gesture-handler    | 1.8.0   |

**Comment by joegoodall1** [comment]
Fixed by adding `jest.mock('@gorhom/bottom-sheet', () => require('react-native-reanimated/mock'))` to jest setup

**Comment by JanithaR** [comment]
> Fixed by adding `jest.mock('@gorhom/bottom-sheet', () => require('react-native-reanimated/mock'))` to jest setup

Doing this causes another error.

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

How to handle that?

Jest setup
```
import 'react-native-gesture-handler/jestSetup';

jest.mock('react-native-reanimated', () => {
    const Reanimated = require('react-native-reanimated/mock');

    // The mock for `call` immediately calls the callback which is incorrect
    // So we override it with a no-op
    Reanimated.default.call = () => {};

    return Reanimated;
});

// Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');

// https://github.com/gorhom/react-native-bottom-sheet/issues/56#issuecomment-721130963
jest.mock('@gorhom/bottom-sheet', () =>
    require('react-native-reanimated/mock'),
);

```

BottomSheet.tsx

```
import React, { useCallback, useMemo, useState } from 'react';
import { View, StyleSheet, LayoutChangeEvent } from 'react-native';
import { EvaProp, withStyles } from '@ui-kitten/components';
import ReactNativeBottomSheet, {
    BottomSheetHandleProps,
    BottomSheetView,
} from '@gorhom/bottom-sheet';

import { BottomSheetHandle } from '../../src/SVGs';

type Props = {
    children: React.ReactNode | React.ReactNode[];
    eva?: EvaProp;
    enableHandlePanningGesture?: boolean;
};

// https://gorhom.github.io/react-native-bottom-sheet/props
const _BottomSheet = ({ children, eva, enableHandlePanningGesture }: Props) => {
    const sheetRef = React.useRef(null);

    const [contentHeight, setContentHeight] = useState(0);

    const snapPoints = useMemo(() => [0, contentHeight], [contentHeight]);

    const handleOnLayout = useCallback(
        ({
            nativeEvent: {
                layout: { height },
            },
        }: LayoutChangeEvent) => {
            setContentHeight(height);
        },
        [],
    );

    const renderContent = useCallback(() => {
        if (eva && eva.style) {
            const { mainWrapper } = eva.style;
            const style = { ...styles.mainWrapper, ...mainWrapper };

            return (
                <BottomSheetView style={style} onLayout={handleOnLayout}>
                    {children}
                </BottomSheetView>
            );
        }
    }, [children, eva, handleOnLayout]);

    const Handle: React.FC<BottomSheetHandleProps> = useCallback(() => {
        let backgroundColor = '#000';

        if (eva && eva.style) {
            backgroundColor = eva.style.mainWrapper.backgroundColor;
        }
        return (
            <View style={[styles.handleWrapper, { backgroundColor }]}>
                <BottomSheetHandle />
            </View>
        );
    }, [eva]);

    return (
        <ReactNativeBottomSheet
            ref={sheetRef}
            snapPoints={snapPoints}
            handleComponent={Handle}
            index={1}
            enableContentPanningGesture={false}
            enableHandlePanningGesture={enableHandlePanningGesture}>
            {renderContent()}
        </ReactNativeBottomSheet>
    );
};

const styles = StyleSheet.create({
    mainWrapper: {
        padding: 16,
    },
    handleWrapper: {
        alignItems: 'center',
        paddingVertical: 10,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
    },
});

export const BottomSheet = withStyles(_BottomSheet, (theme) => ({
    mainWrapper: {
        backgroundColor: theme['background-basic-color-1'],
    },
}));

```

Usage

```
import React from 'react';
import { Layout } from '@ui-kitten/components';

import { Loading, BottomSheet } from '../../components';
import { DummyGMap } from '../../SVGs';

export const HomeScreen = () => {
    return (
        <Layout>
            <DummyGMap />
            <BottomSheet enableHandlePanningGesture={false}>
                <Loading text="Finding orders..." />
            </BottomSheet>
        </Layout>
    );
};
```

Test

```
import React from 'react';
import { ApplicationProvider } from '@ui-kitten/components';
import * as eva from '@eva-design/eva';
import { render } from '@testing-library/react-native';

import { HomeScreen } from '../screens/Home';

// https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/getting_started/#testing
jest.mock('react-native-reanimated', () =>
    require('react-native-reanimated/mock'),
);

const setup = () => {
    const WrapperComponent = ({
        children,
    }: {
        children: React.ReactElement,
    }): React.ReactElement => (
        <ApplicationProvider {...eva} theme={eva.light}>
            {children}
        </ApplicationProvider>
    );

    return render(<HomeScreen />, { wrapper: WrapperComponent });
};
describe('Home screen', () => {
    it('should fetch data from foodApi.task()', () => {
        const { queryByText } = setup();

        expect(queryByText('Finding orders...')).toBeTruthy();
    });
});

```

Error

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> 
>     Check the render method of `_BottomSheet`.
> 
>       at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14410:21)
>       at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14433:15)
>       at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4982:23)
>       at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5042:35)
>       at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7234:28)
>       at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7968:5)
>       at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9019:16)
>       at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12649:12)
>       at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12622:22)
>       at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12333:9)
> 
>   console.error
>     Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
>     
>     Check the render method of `_BottomSheet`.
>         in _BottomSheet (created by Context.Consumer)
>         in Wrapper (created by _BottomSheet)
>         in _BottomSheet (created by HomeScreen)
>         in View (created by View)
>         in View (created by Layout)
>         in Layout (created by Context.Consumer)
>         in Wrapper (created by Layout)
>         in Layout (created by HomeScreen)
>         in HomeScreen
>         in View (created by View)
>         in View (created by ModalPanel)
>         in ModalPanel (created by ApplicationProvider)
>         in ThemeProvider (created by StyleProvider)
>         in MappingProvider (created by StyleProvider)
>         in StyleProvider (created by ApplicationProvider)
>         in ApplicationProvider (created by WrapperComponent)
>         in WrapperComponent
> 
>       40 | 
>       41 |             return (
>     > 42 |                 <BottomSheetView style={style} onLayout={handleOnLayout}>
>          |                 ^
>       43 |                     {children}
>       44 |                 </BottomSheetView>
>       45 |             );
> 
>       at printWarning (node_modules/react/cjs/react.development.js:315:30)
>       at error (node_modules/react/cjs/react.development.js:287:5)
>       at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1788:7)
>       at renderContent (src/components/BottomSheet.tsx:42:17)
>       at _BottomSheet (src/components/BottomSheet.tsx:70:14)
>       at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5552:18)
>       at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7918:13)
> 
>   console.error
>     Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
>     
>     Check the render method of `_BottomSheet`.
>         in _BottomSheet (created by Context.Consumer)
>         in Wrapper (created by _BottomSheet)
>         in _BottomSheet (created by HomeScreen)
>         in View (created by View)
>         in View (created by Layout)
>         in Layout (created by Context.Consumer)
>         in Wrapper (created by Layout)
>         in Layout (created by HomeScreen)
>         in HomeScreen
>         in View (created by View)
>         in View (created by ModalPanel)
>         in ModalPanel (created by ApplicationProvider)
>         in ThemeProvider (created by StyleProvider)
>         in MappingProvider (created by StyleProvider)
>         in StyleProvider (created by ApplicationProvider)
>         in ApplicationProvider (created by WrapperComponent)
>         in WrapperComponent
> 
>       61 | 
>       62 |     return (
>     > 63 |         <ReactNativeBottomSheet
>          |         ^
>       64 |             ref={sheetRef}
>       65 |             snapPoints={snapPoints}
>       66 |             handleComponent={Handle}
> 
>       at printWarning (node_modules/react/cjs/react.development.js:315:30)
>       at error (node_modules/react/cjs/react.development.js:287:5)
>       at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1788:7)
>       at _BottomSheet (src/components/BottomSheet.tsx:63:9)
>       at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5552:18)
>       at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7918:13)
>       at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9019:16)
> 
>   console.error
>     The above error occurred in the <_BottomSheet> component:
>         in _BottomSheet (created by Context.Consumer)
>         in Wrapper (created by _BottomSheet)
>         in _BottomSheet (created by HomeScreen)
>         in View (created by View)
>         in View (created by Layout)
>         in Layout (created by Context.Consumer)
>         in Wrapper (created by Layout)
>         in Layout (created by HomeScreen)
>         in HomeScreen
>         in View (created by View)
>         in View (created by ModalPanel)
>         in ModalPanel (created by ApplicationProvider)
>         in ThemeProvider (created by StyleProvider)
>         in MappingProvider (created by StyleProvider)
>         in StyleProvider (created by ApplicationProvider)
>         in ApplicationProvider (created by WrapperComponent)
>         in WrapperComponent
>     
>     Consider adding an error boundary to your tree to customize error handling behavior.
>     Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
> 
>       at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10141:21)
>       at logError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10178:5)
>       at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11288:5)
>       at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3259:12)
>       at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3280:9)
>       at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10497:11)
>       at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13295:7)

**Comment by madandrija** [comment]
> > Fixed by adding `jest.mock('@gorhom/bottom-sheet', () => require('react-native-reanimated/mock'))` to jest setup
> 
> Doing this causes another error.
> 
> > Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
> 
> How to handle that?
>....

I have a similar setup as @JanithaR and I'm getting the same problem

**Comment by JanithaR** [comment]
> > > Fixed by adding `jest.mock('@gorhom/bottom-sheet', () => require('react-native-reanimated/mock'))` to jest setup
> > 
> > 
> > Doing this causes another error.
> > > Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
> > 
> > 
> > How to handle that?
> > ....
> 
> I have a similar setup as @JanithaR and I'm getting the same problem

https://github.com/software-mansion/react-native-reanimated/issues/1555#issue-772367484

**Comment by madandrija** [comment]
> > > > Fixed by adding `jest.mock('@gorhom/bottom-sheet', () => require('react-native-reanimated/mock'))` to jest setup
> > > 
> > > 
> > > Doing this causes another error.
> > > > Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
> > > 
> > > 
> > > How to handle that?
> > > ....
> > 
> > 
> > I have a similar setup as @JanithaR and I'm getting the same problem
> 
> [software-mansion/react-native-reanimated#1555 (comment)](https://github.com/software-mansion/react-native-reanimated/issues/1555#issue-772367484)

Thanks, tried that, but now I have another problem so I'll open up a new issue

**Comment by Ovsdrak** [comment]
I also have this problem

`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.` 

with the this configuration in jest-setup.js.

I'm using react-native-reanimated **2.0.0** 

```
// @ts-ignore
require('react-native-reanimated/src/reanimated2/jestUtils').setUpTests();

// @ts-ignore https://github.com/wcandillon/react-native-redash/issues/395
global.__reanimatedWorkletInit = () => {};

//@ts-ignore
jest.mock('react-native-reanimated', () => {
    const reanimated = require('react-native-reanimated/mock');

    // The mock for `call` immediately calls the callback which is incorrect
    // So we override it with a no-op
    reanimated.default.call = () => {};
    reanimated.default.addWhitelistedUIProps = () => {};

    return reanimated;
})
// Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');

jest.mock("@gorhom/bottom-sheet", () => require("react-native-reanimated/mock"));
```

Is there anyone with reanimated 2.0.0 working?

**Reference:**
https://github.com/software-mansion/react-native-reanimated/pull/1731
https://docs.swmansion.com/react-native-reanimated/docs/testing

**Comment by JanithaR** [comment]
> I also have this problem
> 
> `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`
> 
> with the this configuration in jest-setup.js.
> 
> I'm using react-native-reanimated **2.0.0**
> 
> ```
> // @ts-ignore
> require('react-native-reanimated/src/reanimated2/jestUtils').setUpTests();
> 
> // @ts-ignore https://github.com/wcandillon/react-native-redash/issues/395
> global.__reanimatedWorkletInit = () => {};
> 
> //@ts-ignore
> jest.mock('react-native-reanimated', () => {
>     const reanimated = require('react-native-reanimated/mock');
> 
>     // The mock for `call` immediately calls the callback which is incorrect
>     // So we override it with a no-op
>     reanimated.default.call = () => {};
>     reanimated.default.addWhitelistedUIProps = () => {};
> 
>     return reanimated;
> })
> // Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
> jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');
> 
> jest.mock("@gorhom/bottom-sheet", () => require("react-native-reanimated/mock"));
> ```
> 
> Is there anyone with reanimated 2.0.0 working?
> 
> **Reference:**
> [software-mansion/react-native-reanimated#1731](https://github.com/software-mansion/react-native-reanimated/pull/1731)
> https://docs.swmansion.com/react-native-reanimated/docs/testing

Could elaborate on what you mean by 

> I also have this problem

The root of this particular issue was that react-native-reanimated mock didn't include all the functions thus leading to the specific error 

> TypeError: _reactNativeReanimated.default.addWhitelistedUIProps is not a function

which is now fixed. https://github.com/software-mansion/react-native-reanimated/issues/1555#issue-772367484

The error you're quoting is different.

**Comment by donatoaguirre24** [comment]
@JanithaR @Ovsdrak the following mock works for me:

```js
require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();

// Silence the warning: Animated: `useNativeDriver` is not supported
jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper');

jest.mock('@gorhom/bottom-sheet', () => {
  const RN = require('react-native');
  
  return {
    __esModule: true,
    default: RN.View, // mocks the BottomSheet
    namedExport: {
      ...require('react-native-reanimated/mock'),
      ...jest.requireActual('@gorhom/bottom-sheet'),
    },
  };
});
```

I'm using:

```
"@gorhom/bottom-sheet": "^3.6.5",    
"react-native": "0.64.2",
"react-native-reanimated": "^2.2.0",
```

**Comment by puelocesar** [comment]
> @JanithaR @Ovsdrak the following mock works for me:
> 
> ```js
> require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();
> 
> // Silence the warning: Animated: `useNativeDriver` is not supported
> jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper');
> 
> jest.mock('@gorhom/bottom-sheet', () => {
>   const RN = require('react-native');
>   
>   return {
>     __esModule: true,
>     default: RN.View, // mocks the BottomSheet
>     namedExport: {
>       ...require('react-native-reanimated/mock'),
>       ...jest.requireActual('@gorhom/bottom-sheet'),
>     },
>   };
> });
> ```
> 
> I'm using:
> 
> ```
> "@gorhom/bottom-sheet": "^3.6.5",    
> "react-native": "0.64.2",
> "react-native-reanimated": "^2.2.0",
> ```

This doesn't work anymore on current React Native and bottom-sheet versions

**Comment by alexander126** [comment]
> > @JanithaR @Ovsdrak the following mock works for me:
> > ```js
> > require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();
> > 
> > // Silence the warning: Animated: `useNativeDriver` is not supported
> > jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper');
> > 
> > jest.mock('@gorhom/bottom-sheet', () => {
> >   const RN = require('react-native');
> >   
> >   return {
> >     __esModule: true,
> >     default: RN.View, // mocks the BottomSheet
> >     namedExport: {
> >       ...require('react-native-reanimated/mock'),
> >       ...jest.requireActual('@gorhom/bottom-sheet'),
> >     },
> >   };
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm using:
> > ```
> > "@gorhom/bottom-sheet": "^3.6.5",    
> > "react-native": "0.64.2",
> > "react-native-reanimated": "^2.2.0",
> > ```
> 
> This doesn't work anymore on current React Native and bottom-sheet versions

I've made a small adjustment to the mock of the bottom sheet library and it works for me
```
jest.mock('@gorhom/bottom-sheet', () => {
  const RN = require('react-native');
  const {forwardRef} = jest.requireActual('react');
  const mockView = () => RN.View;

  return {
    __esModule: true,
    default: forwardRef(() => mockView),
    namedExport: {
      ...require('react-native-reanimated/mock'),
      ...jest.requireActual('@gorhom/bottom-sheet'),
    },
  };
});
```

**Comment by eyupdalan** [comment]
> > > @JanithaR @Ovsdrak the following mock works for me:
> > > ```js
> > > require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();
> > > 
> > > // Silence the warning: Animated: `useNativeDriver` is not supported
> > > jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper');
> > > 
> > > jest.mock('@gorhom/bottom-sheet', () => {
> > >   const RN = require('react-native');
> > >   
> > >   return {
> > >     __esModule: true,
> > >     default: RN.View, // mocks the BottomSheet
> > >     namedExport: {
> > >       ...require('react-native-reanimated/mock'),
> > >       ...jest.requireActual('@gorhom/bottom-sheet'),
> > >     },
> > >   };
> > > });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I'm using:
> > > ```
> > > "@gorhom/bottom-sheet": "^3.6.5",    
> > > "react-native": "0.64.2",
> > > "react-native-reanimated": "^2.2.0",
> > > ```
> > 
> > 
> > This doesn't work anymore on current React Native and bottom-sheet versions
> 
> I've made a small adjustment to the mock of the bottom sheet library and it works for me
> 
> ```
> jest.mock('@gorhom/bottom-sheet', () => {
>   const RN = require('react-native');
>   const {forwardRef} = jest.requireActual('react');
>   const mockView = () => RN.View;
> 
>   return {
>     __esModule: true,
>     default: forwardRef(() => mockView),
>     namedExport: {
>       ...require('react-native-reanimated/mock'),
>       ...jest.requireActual('@gorhom/bottom-sheet'),
>     },
>   };
> });
> ```

This worked for me. 

First I tried ```jest.mock('@gorhom/bottom-sheet', () => require('react-native-reanimated/mock')) ```
But I got following error:
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Then I tried @alexander126's solution and that worked for me. Thanks.

**Comment by aman-technyx** [comment]
> > > @JanithaR @Ovsdrak the following mock works for me:
> > > ```js
> > > require('react-native-reanimated/lib/reanimated2/jestUtils').setUpTests();
> > > 
> > > // Silence the warning: Animated: `useNativeDriver` is not supported
> > > jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper');
> > > 
> > > jest.mock('@gorhom/bottom-sheet', () => {
> > >   const RN = require('react-native');
> > >   
> > >   return {
> > >     __esModule: true,
> > >     default: RN.View, // mocks the BottomSheet
> > >     namedExport: {
> > >       ...require('react-native-reanimated/mock'),
> > >       ...jest.requireActual('@gorhom/bottom-sheet'),
> > >     },
> > >   };
> > > });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I'm using:
> > > ```
> > > "@gorhom/bottom-sheet": "^3.6.5",    
> > > "react-native": "0.64.2",
> > > "react-native-reanimated": "^2.2.0",
> > > ```
> > 
> > 
> > This doesn't work anymore on current React Native and bottom-sheet versions
> 
> I've made a small adjustment to the mock of the bottom sheet library and it works for me
> 
> ```
> jest.mock('@gorhom/bottom-sheet', () => {
>   const RN = require('react-native');
>   const {forwardRef} = jest.requireActual('react');
>   const mockView = () => RN.View;
> 
>   return {
>     __esModule: true,
>     default: forwardRef(() => mockView),
>     namedExport: {
>       ...require('react-native-reanimated/mock'),
>       ...jest.requireActual('@gorhom/bottom-sheet'),
>     },
>   };
> });
> ```

i got the error on this 

TypeError: _reactNativeReanimated.default.addWhitelistedUIProps is not a function

**Comment by syed-minhaj-hussain** [comment]
Mocking **react-native-animated** worked for me.

``` __mocks__/react-native-animated.js```

```
const real = jest.requireActual('react-native-reanimated/mock');
const {View} = jest.requireActual('react-native');

module.exports = {
  ...real,
  Value: jest.fn(),
  event: jest.fn(),
  add: jest.fn(),
  eq: jest.fn(),
  set: jest.fn(),
  cond: jest.fn(),
  interpolate: jest.fn(),
  sub: jest.fn(),
  multiply: jest.fn(),
  sqrt: jest.fn(),
  max: jest.fn(),
  diff: jest.fn(),
  onChange: jest.fn(),
  View,
  Extrapolate: {CLAMP: jest.fn()},
  Clock: jest.fn(),
  greaterThan: jest.fn(),
  lessThan: jest.fn(),
  startClock: jest.fn(),
  stopClock: jest.fn(),
  clockRunning: jest.fn(),
  not: jest.fn(),
  or: jest.fn(),
  and: jest.fn(),
  spring: jest.fn(),
  decay: jest.fn(),
  defined: jest.fn(),
  call: jest.fn(),
  block: jest.fn(),
  abs: jest.fn(),
  greaterOrEq: jest.fn(),
  lessOrEq: jest.fn(),
  debug: jest.fn(),
  Transition: {
    Together: 'Together',
    Out: 'Out',
    In: 'In',
  },
};

**Comment by leymytel** [comment]
In case someone is looking for a solution here.
This worked for me:
```
jest.mock('@gorhom/bottom-sheet', () => ({
  __esModule: true,
  ...require('@gorhom/bottom-sheet/mock'),
}));
```

**Comment by anabeatrizzz** [comment]
> In case someone is looking for a solution here. This worked for me:
> 
> ```
> jest.mock('@gorhom/bottom-sheet', () => ({
>   __esModule: true,
>   ...require('@gorhom/bottom-sheet/mock'),
> }));
> ```

I have a screen with three `BottomSheet` components. When I run a test case, all of them are opened on debug tree and overlap a button that must be pressed. Do you have any tips regarding this mock, thus none of the components stay opened?
@leymytel
