### ISSUE TITLE
Unable to trigger any Android onPress events on snapPoints 0

### ISSUE THREAD

**Issue by enigmablue** [gorhom/react-native-bottom-sheet#567]
# Bug
Hi, 
I'm unable to initiate any onPress (eg. Touchable, Buttton onpress) on my Android Samsung Note10, when using snapPoints[0] for the Bottomsheet. Does anyone have the same problem?

 const snapPoints = useMemo(() => ['25%', '50%'], []);
My BottomSheet is in a View style="absolute"

I wanted to try to reproduce it with a reanimated v2 but it has many problems so haven't been able to upgrade yet.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | "@gorhom/bottom-sheet": "^2",   |
| react-native                    | "react-native": "0.65.1",   |
| react-native-reanimated         |     "react-native-reanimated": "^1",  |
| react-native-gesture-handler    | "react-native-gesture-handler": "^1.10.3"   |

## Steps To Reproduce

1. Add a button on the bottom sheet
2. Press it and try to trigger the event
3. Dosen't trigger consistently. I pressed like 30 times and it only triggered three times.

![can't press](https://user-images.githubusercontent.com/35584085/130209189-07886066-2f87-4ae7-b4a9-fe434e5bdb7f.gif)

Describe what you expected to happen:

1. Event should trigger consistently

## Reproducible sample code

I created a repo here
https://github.com/EnigmaGlobe/bottomsheetbug

**Comment by GoGiants1** [comment]
My app crashes too.
When i call  functions in example.
```
const handleSnapPress = useCallback((index) => {
    sheetRef.current?.snapTo(index);
  }, []);
```

```
TypeError: _sheetRef$current.snapTo is not a function. (In '_sheetRef$current.snapTo(index)', '_sheetRef$current.snapTo' is undefined)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

"@gorhom/bottom-sheet": "^4.0.0-alpha.25",
"react-native-reanimated": "~2.1.0",
"react-native-gesture-handler": "~1.10.2",

**Comment by GoGiants1** [comment]
I resolve my Error by change snapTo(index) function to snapToIndex(index).

I printed out sheetRef object. And get some hint from this result.
![image](https://user-images.githubusercontent.com/69342392/128669699-c6e208fc-b661-4f35-831e-688a286b9615.png)

**Comment by gorhom** [comment]
@enigmablue  could you update the issue and follow the template, thanks .

**Comment by enigmablue** [comment]
> @enigmablue could you update the issue and follow the template, thanks .

Updated! Thanks

**Comment by gorhom** [comment]
@enigmablue you should use `TouchableOpacity` from the library https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#pressables--touchables-are-not-working-on-android
