### ISSUE TITLE
close(): ability to add force parameter without providing animation config

### ISSUE THREAD

**Issue by likern** [gorhom/react-native-bottom-sheet#572]
# Feature Request

If I want to call `close()` function with `force=true` I need to provide animation config.

```ts
close: (
    animationConfigs?: Animated.WithSpringConfig | Animated.WithTimingConfig,
    force?: boolean
) => void;
```

I want to provide **default config**, which is used in `react-native-bottom-sheet`. Couldn't find how easy to do that. We can expose that default configuration or pass parameters to function as object.

**Comment by likern** [comment]
Also there is inconsistency between default config in `useBottomSheetTimingConfigs()` and `animate()` function in animate.ts.

For example, `DEFAULT_ANIMATION_DURATION=500` in `useBottomSheetTimingConfigs()` and `250` in `animate()` (on Android).

**Comment by gorhom** [comment]
thanks @likern  for spotting this out, i have refactored the animation configs to be unified and extracted the force close implementation into a separate method 👍

**Comment by likern** [comment]
Thanks for your awesome work

**Comment by likern** [comment]
@gorhom Could you please describe what this `force` parameter means? I'm not sure I understand it correctly.

I thought I couldn't interrupt bottom sheet, but I could.
Here is description https://github.com/gorhom/react-native-bottom-sheet/discussions/575.

Bottom sheet stopped at middle (there's no such snap point - only hidden and full content)
