### ISSUE TITLE
pull to refresh in lowest position

### ISSUE THREAD

**Issue by megantaylor** [gorhom/react-native-bottom-sheet#576]
# Feature Request

I am using @4.0.0-alpha.25 and implementing a BottomSheet with BottomSheetScrollView where the lowest snap point is 50% of the screen. I implemented pull to refresh and noticed that the PTR only works at the highest position. I would like to be able to pull to refresh at the lowest position, (but not scroll the scrollview). Ideally, in the highest position, PTR would be disabled and the sheet would retain the drag down behavior.

**Comment by gorhom** [comment]
you could implement your own gesture/scroll interaction with `v4`, look at the [CustomGestureHandling example].(https://github.com/gorhom/react-native-bottom-sheet/tree/master/example/src/screens/advanced/customGestureHandling)
