### ISSUE TITLE
How to adjust snappoint to keyboard height?

### ISSUE THREAD

**Issue by cloudorbush** [gorhom/react-native-bottom-sheet#577]
How would you go about reducing the vertical space between the TextInput and the keyboard when the keyboard is expanded?

Thank you.

https://user-images.githubusercontent.com/57633368/129399171-2e44bc0f-2ca2-407a-9048-186d43e7a174.MOV

**Comment by likern** [comment]
Expanded keyboard should reduce available screen size. So you can accustom to it's opening.

Have you tried `snapToPosition()` in v4 version? It might help.

Or you can split view to TextInput and View below it. On   keyboard expansion rerender, deleting View.

Doing that with animation might be tricky as you need to know keyboard animation parameters (duration).

**Comment by likern** [comment]
You could also combine this with dynamic snap points. But I think all of this would require experimentation.
