### ISSUE TITLE
[v3][v4] BottomSheetFlatList (scrollToOffset or scrollToIndex) scrolling to 0 when BottomSheet is collapsed 

### ISSUE THREAD

**Issue by emadhajjar** [gorhom/react-native-bottom-sheet#579]
# Bug

https://user-images.githubusercontent.com/3524824/129570109-e3808f8d-00f9-49dc-9812-2f0e37401804.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^4.0.0-alpha.27   |
| react-native                    | ^0.64.2  |
| react-native-reanimated         | ^2.3.0-alpha.2   |
| react-native-gesture-handler    | ^1.10.3   |

## Steps To Reproduce

when run ref.current?.scrollToOffset({animated: true, offset: 400}) it should change the y to 400 but this only work when expanded

Describe what you expected to happen:

Change the y position to selected offset.

## Reproducible sample code

```
import BottomSheet, {BottomSheetFlatList} from '@gorhom/bottom-sheet'
import React, {useRef} from 'react'
import {FlatList, View, Text, StyleSheet} from 'react-native'

export default function CaricatureScreen({navigation}: Props) {
  const ref = useRef<FlatList | null>(null)
  const data = ['Test 1', 'Test 2', 'Test 3', 'Test 4', 'Test 5']
  const styles = StyleSheet.create({
    view: {
      height: 200,
      flex: 1,
    },
  }

  setInterval(() => ref.current?.scrollToOffset({animated: true, offset: 400}), 1000)

  return (
    <BottomSheet index={0} snapPoints={[100, '70%']}>
      <BottomSheetFlatList 
        ref={ref} 
        data={data}
        renderItem={({index, item}) => (
          <View style={styles.view}>
            <Text>{item}</Text>
          </View>
        )}
      />
    </BottomSheet>
  )
}

```

**Comment by akinyele** [comment]
Was there any solution for this issue. I'm encountering something similar. `ref.current.scrollToIndex` only works when the bottom sheet is expanded to the final snap point.

**Comment by LorandP** [comment]
I would also like to know how to scroll to a specific index

**Comment by francescovenica** [comment]
are there any update on this issue? I've tried different solutions but nothing is working :(

**Comment by AntonioA-D-C** [comment]
Did you fix it?
