### ISSUE TITLE
Button / Pressable rendered inside Bottom Sheet are not clickable on Android device

### ISSUE THREAD

**Issue by mrmarktyy** [gorhom/react-native-bottom-sheet#58]
# Bug

Button / Pressable rendered inside Bottom Sheet are barely clickable on Android device.
It behaves differently than a normal Button/Preesable outside of bottom sheet.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0-alpha.0      |
| react-native                    | 0.63.2   |
| react-native-reanimated         | 2.0.0-alpha.6   |
| react-native-gesture-handler    | 1.7.0   |

## Steps To Reproduce

Describe what you expected to happen:

1. Press the "Press me" to see 'xxxxx' display in terminal

## Reproducible sample code

```javascript
 <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        initialSnapIndex={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <Pressable onPress={() => console.log('xxxxx')} style={{ backgroundColor: 'cyan', height: 100 }}>
            <Text>Press me</Text>
          </Pressable>
      </BottomSheet>
    </View>
```

**Comment by mrmarktyy** [comment]
I literally have to press very very hard on the android phone to make the `onPress` triggered 
where is not normal compared to a `Pressable` outside of the BottomSheet I only need to tap. (same device)

Please help to look into this.

**Comment by gorhom** [comment]
look at https://github.com/gorhom/react-native-bottom-sheet/blob/master/docs/touchables.md

**Comment by mrmarktyy** [comment]
@gorhom Thanks, much appreciated that.
I tried and they work all fine now! 

Just there is one more thing in my use case, where I have `Switch` from `react-native`.
I think it also needs to be wrapped in `touchables` to be properly working.

**Comment by efstathiosntonas** [comment]
@gorhom the touchables readme gets 404, looked at docs page but couldn’t find it there either.

**Comment by gorhom** [comment]
Hi @efstathiosntonas, docs moved to the new website https://gorhom.github.io/react-native-bottom-sheet/troubleshooting

**Comment by efstathiosntonas** [comment]
Thanks for the link, I visited the new docs and didn’t visited that section,  I think that this should live on it’s own section and not under troubleshooting, just saying. 

Keep it up!

**Comment by buitrbao222** [comment]
How can I use the touchables with react-native-paper Button component?

**Comment by JulienS1987** [comment]
@gorhom thank you for your hard work. I am still having a problem with links inside a URL even after adding the above. When clicking on any URL inside the inner webview on ANDROID only it's not responding. I am a new react native dev.Thanks! My code goes like:

<View style={{ height: height, width: width }}>
      <WebView style={{ height: height, width: width }}
        source={{ uri: `http://192.168.100.60:8000/gis_workorder/indexw.html?assignee=${addnum}#15/${latt}/${lonng}` }}
      />
      <BottomSheet
        ref={sheetRef}
        index={1}
        snapPoints={snapPoints}
      >
        <BottomSheetScrollView
          contentContainerStyle={{ flexGrow: 1, height: styles.header.height + webViewHeight }} 
        >
          <WebView style={{ height: height, width: width }} source={{ uri: `http://192.168.100.60:83/jde/ShortcutLauncher?Environment=JDV920&Role=*ALL&User=jde&Password=jde&OID=PL994810_WL994810A_ZJDE0001&FormDSTmpl=|1|11|&FormDSData=||${addnum}|` }}
            bounces={true}
            scrollEnabled={false}
            onMessage={onMessage}
            javaScriptEnabled={true}

            onShouldStartLoadWithRequest ={onShouldStartLoadWithRequest}
            injectedJavaScript="window.ReactNativeWebView.postMessage(Math.max(document.body.offsetHeight, document.body.scrollHeight));"
            style={styles.content}      
          />
        </BottomSheetScrollView>
      </BottomSheet>
    </View>

**Comment by naytun** [comment]
> look at https://github.com/gorhom/react-native-bottom-sheet/blob/master/docs/touchables.md

This link is not working. See below for new link

**Comment by krishnan-456** [comment]
Does still anyone facing this issue ?

**Comment by MariuzM** [comment]
So I'm was facing this issue on android so using import {
  TouchableOpacity,
  TouchableHighlight,
  TouchableWithoutFeedback,
} from '@gorhom/bottom-sheet'; worked

**Comment by MariuzM** [comment]
but for some reason other poblems are I'm unable to interact with map and text input...
