### ISSUE TITLE
[v4] Dismiss BottomSheetModal after focus BottomSheetTextInput with enabled autofocus 

### ISSUE THREAD

**Issue by NikitaZaharenko** [gorhom/react-native-bottom-sheet#583]
# Bug

When autofocus is enabled and keyboard Behavior={'interactive'}, the BottomSheetModal is dismissed

## Environment info

| Library                         | 3.6.6 |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            |  3.6.6   |
| react-native                    | 0.64.2   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3  |

## Steps To Reproduce

Describe what you expected to happen:

It is expected to focus on the TextInput, but when focused, the BottomSheetModal dismiss is called

## Reproducible sample code

```
import React, { useEffect } from 'react';
import { View } from 'react-native';
import {
  BottomSheetModal,
  BottomSheetModalProvider,
  BottomSheetScrollView,
  BottomSheetView,
} from '@gorhom/bottom-sheet';

const Component = ({}) => {
  useEffect(() => {
    bottomSheetRef.current?.present();
  }, []);

  return (
    <BottomSheetModalProvider>
      <View style={styles.bgShadow}>
        <BottomSheetModal
          ref={bottomSheetRef}
          style={styles.container}
          snapPoints={[140]}
          handleComponent={null}
          dismissOnPanDown={false}
          keyboardBehavior={'interactive'}
          onDismiss={() => console.log('dismiss')}
        >
          <View style={styles.contentWrapper}>
            <BottomSheetTextInput autoFocus />
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

```

**Comment by sirajtahrawashmen** [comment]
@znanick how did you manage to fix this issue ? I am still facing it
