### ISSUE TITLE
[v4.0.0-alpha.27] Backdrop dissapeared (is not rendered)

### ISSUE THREAD

**Issue by likern** [gorhom/react-native-bottom-sheet#585]
# Bug

Following previous discussion https://github.com/gorhom/react-native-bottom-sheet/issues/578 I deleted `-1` from snap points.
Immediatelly after that `Backdrop` stopped rendering.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | v4.0.0-alpha.27   |
| react-native                    | 0.64.0   |
| react-native-reanimated         | 2.3.0-alpha.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Go to https://snack.expo.dev/@victormalov/bottom-sheet-v4-reproducible-issue-template
2. Delete `-1` from snap points array

Describe what you expected to happen:

1. Backdrop should be rendered

https://user-images.githubusercontent.com/842306/129732771-a7286a5a-590e-4b7a-8624-49871c5a6ba1.mp4

**Comment by gorhom** [comment]
you should modify the default `BottomSheetBackdrop` props, `disappearsOnIndex` & `appearsOnIndex`

```tsx
  const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop
        disappearsOnIndex={-1}
        appearsOnIndex={0}
        {...props}
      />
    ),
    []
  );
  ```

**Comment by giacomocerquone** [comment]
> you should modify the default `BottomSheetBackdrop` props, `disappearsOnIndex` & `appearsOnIndex`
> 
> ```tsx
>   const renderBackdrop = useCallback(
>     props => (
>       <BottomSheetBackdrop
>         disappearsOnIndex={-1}
>         appearsOnIndex={0}
>         {...props}
>       />
>     ),
>     []
>   );
> ```

this should be documented
