### ISSUE TITLE
[v2] Uncaught Error - null is not an object (evaluating 'containerRef.current.setNativeProps')

### ISSUE THREAD

**Issue by dochonglo** [gorhom/react-native-bottom-sheet#588]
# Bug

 I've implemented the bottom sheet to be rendered for each FlatList item rendered in the view. When I swipe through each element, the following error arises: `Uncaught Error - null is not an object (evaluating 'containerRef.current.setNativeProps')`

Interestingly, I've had this implementation in the past and everything work perfectly. However, I'm getting this error for some reason.

Now, the bottom sheet works like it's intended to, errors continue to pop up. Below is a screenshot of some errors. 

![IMG_6136](https://user-images.githubusercontent.com/13290756/129803465-46494faa-203b-4eae-a0c8-51a68e50031b.PNG)
![IMG_6135](https://user-images.githubusercontent.com/13290756/129803469-3caba376-963a-4e22-8c32-9c292b988b86.PNG)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet                 ^2   
| react-native                                  ^0.64.2  
| react-native-reanimated               ~2.1.0   
| react-native-gesture-handler     ~1.10.2   

Describe what you expected to happen:

1. No errors to pop up and affect the user experience. However, In production, the app crashes unfortunately.

Any help would be gladly appreciated--thanks! :)

**Comment by gorhom** [comment]
this should be fixed with `v2.4.1`
