### ISSUE TITLE
[v4] Keyboard handling brakes the snap position on dismiss

### ISSUE THREAD

**Issue by Ferossgp** [gorhom/react-native-bottom-sheet#592]
# Bug

When dismissing the keyboard in a list by dragging it down (`keyboardDismissMode`), if during the dismiss the sheet is dragged back (the interaction is not stoped during the whole process) to the top it is snaped to a non-existing snap point and results in a broken interaction. The expected correct behavior is to snap back to the previous snap point.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.0-alpha.28   |

## Steps To Reproduce

While the keyboard is opened, drag the bottom sheet to the bottom to dismiss the keyboard. While keeping the gesture active drag the sheet to the top.

https://user-images.githubusercontent.com/5794620/129932293-c7162fa1-6f53-4d96-9b64-9287527637ad.MP4

Describe what you expected to happen:

After the keyboard is dismissed the bottom sheet should snap back to the previous position.

## Reproducible sample code

https://snack.expo.dev/@ferossgp/keyboard-handling-issue

**Comment by gorhom** [comment]
this is expected behaviour , the sheet is in temporary position until the user snap it back to its previous position

**Comment by Ferossgp** [comment]
Interestingly, in our app, we have the input on the bottom (also updated the snack), and then seems like the issue is the height of the scroll view. In the new video, I also dismiss then quickly drag it to the top, and the height remains in the middle of a transition.

https://user-images.githubusercontent.com/5794620/130025548-cd3cdec9-cdf4-41df-957b-2b6aa6fb1aaf.MP4

**Comment by Ferossgp** [comment]
I've debugged the values and seems like the [keyboardHeightInContainer](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheet/BottomSheet.tsx#L429) gets the value of the hidden state while it seems to me it should use the previous value of the open state.
