### ISSUE TITLE
[v4] Snap point '0' is invalid

### ISSUE THREAD

**Issue by shensven** [gorhom/react-native-bottom-sheet#593]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.0-alpha.28   |
| react-native                    | 0.64.2   |
| react-native-reanimated         | ^2.2.0   |
| react-native-gesture-handler    | ^1.10.3   |

## Steps To Reproduce

yarn upgrade from 4.0.0-alpha.27 to 4.0.0-alpha.28 

## Reproducible sample code

```tsx

...
const snapPoints = useMemo(() => [0, '45%'], []);

return (
    ...
    <BottomSheet
        ref={bottomSheetRef}
        index={-1}
        snapPoints={snapPoints}
        enablePanDownToClose
        onChange={handleSheetChanges}
        backdropComponent={backdropProps => <BottomSheetBackdrop {...backdropProps} />}>
        {bottomsheetContentType === 1 ? <Type1Content /> : null}
        {bottomsheetContentType === 2 ? <Type2Content /> : null}
    </BottomSheet>
)
```

When I used yarn upgrade, the SemVer of `@gorhom/bottom-sheet` was upgraded from `4.0.0-alpha.27` to `4.0.0-alpha.29` and then I got the error `Snap point '0' is invalid`, I found this error is already present in `4.0.0-alpha.28`

**Comment by gorhom** [comment]
`0` is no longer supported as a snap point, if you want to allow user to snap down to close the sheet , use `enablePanDownToClose` which does the same thing 👍
