### ISSUE TITLE
[v4] | not working with native stack react navigation(Solved)

### ISSUE THREAD

**Issue by sanketkheni01** [gorhom/react-native-bottom-sheet#596]
# Bug

The bottom sheet was not a problem but the react-native-gesture-handler was.I just solved it by reinstalling gesture-handler..

When using the Bottom sheet with react-navigation's "native stack", the bottom Sheet is not draggable on android(Works fine on ios👍). But with a normal stack navigator, everything is fine.

with native stack:-

https://user-images.githubusercontent.com/68942390/130320716-b2883960-7398-447f-a094-4590d3501f2c.mp4

with normal stack:-

https://user-images.githubusercontent.com/68942390/130320769-e5ef7750-3435-4fd2-b60d-3ef5269025f4.mp4

# Environment info

  "@gorhom/bottom-sheet": "^4.0.0-alpha.29",
  "@react-navigation/native": "^6.0.1",
  "@react-navigation/native-stack": "^6.1.0",
   "react-native-reanimated": "^2.2.0",
   "react-native-gesture-handler": "^1.10.3",
   "@react-navigation/native": "^6.0.1",

# Steps To Reproduce

1.use `import { createNativeStackNavigator } from '@react-navigation/native-stack'
             const Stack = createNativeStackNavigator()`

Describe what you expected to happen:

bottom sheet to work as expected

**Comment by Developeranees** [comment]
same issue @react-navigation/bottom-tabs

**Comment by sergeymild** [comment]
same problem, bottom sheet modal show under native view

**Comment by U-OK** [comment]
@sanketkheni01 hello! How you solved this issue?

**Comment by U-OK** [comment]
Ok. guys, I solved this issue too. To solve this you need to wrap your `BottomSheetMovalProvier` in `GestureHandlerRootView`. In my case it's look like that:
![image](https://user-images.githubusercontent.com/46742892/145151146-8e43c258-0453-4862-9fd5-87d8ea9779b6.png)
I hope this help you

**Comment by NewvilleMedia** [comment]
I wish this worked
