### ISSUE TITLE
[v4] | [v2] Bottom Sheet doesn't open 

### ISSUE THREAD

**Issue by ZanPerse** [gorhom/react-native-bottom-sheet#598]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.0-alpha.29  |
| react-native                    | 0.63   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.2 |

## Steps To Reproduce

1.Just run the code I provided down bellow and I can't open bottom sheet anymore.
2. I added useEffect at the start that closes the bottom sheet and provided index of -1

Describe what you expected to happen:

1. I expect that bottom sheet if has index of -1 should ignore the ref call.

## Reproducible sample code

https://snack.expo.dev/@pers/healthy-turkish-delight

**Comment by gorhom** [comment]
should be fixed on the next release https://github.com/gorhom/react-native-bottom-sheet/commit/445a9645366af04931f4464d1befb1bc8e1dbbed 👍

**Comment by sorinrinse** [comment]
@gorhom still running into this, I'm using v4.1.5 (also tried v4.0.0).
