### ISSUE TITLE
[v3] | [v4] undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[12], "./constants").DEFAULT_ANIMATION_DURATION')

### ISSUE THREAD

**Issue by miketrinh1995** [gorhom/react-native-bottom-sheet#599]
# Bug

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 3   |
| react-native                    | 0.64.2   |
| react-native-reanimated         | 1.13.2  |
| react-native-gesture-handler    |1.10.3 |

## Steps To Reproduce

1. Install the library
2. Try the sample code
3. Crash

Describe what you expected to happen:

1. Not crash the app
2. Able to show the bottom sheet

## Reproducible sample code
`import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import BottomSheet from '@gorhom/bottom-sheet';

const App = () => {
  // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%'], []);

  // callbacks
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  // renders
  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;`

**Comment by gorhom** [comment]
could you try to install `v4` instead ?
