### ISSUE TITLE
[v4] Bottom Sheet Backdrop not showing up

### ISSUE THREAD

**Issue by Ripul01** [gorhom/react-native-bottom-sheet#600]
# Bug

The backdrop doesn't show up in the latest build. Not sure why

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.0-alpha.30   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.1.0   |
| react-native-gesture-handler    | 1.10.2   |

## Steps To Reproduce

1. Add Bottom Sheet Backdrop as Backdrop component.

Describe what you expected to happen:

1. Backdrop overlay should appear

## Reproducible sample code

https://snack.expo.dev/@ripul/backdrop-component-not-visible

I just changed the template and added the backdrop component as the Bottom Sheet Backdrop and nothing shows up.

Note: I changed bottom sheet to BottomSheetModal because that is what I'm using in my own project.

**Comment by Moh-Kassim** [comment]
#585 
You Need To Modify Backdrop props , Check this issue

**Comment by Ripul01** [comment]
@Moh-Kassim Thank you very much. It worked like a charm. Looking into the closed issues did not occur to me.
@gorhom It would be great if you could update the backdrop example so no one gets confused like me.

**Comment by gorhom** [comment]
it is
