### ISSUE TITLE
How to track each bottom sheet position during dragging up and down, to make smooth animation (for example, to smoothly change the header when the bottom sheet is reaches the top point)?

### ISSUE THREAD

**Issue by solomonik07** [gorhom/react-native-bottom-sheet#607]

**Comment by RomanSuvorov** [comment]
@gorhom, I'm also interested in this.

**Comment by gorhom** [comment]
you could provide your own `animatedIndex` or `animatedPosition` props to track the sheet position 
https://gorhom.github.io/react-native-bottom-sheet/props#animated-nodes

**Comment by RomanSuvorov** [comment]
@gorhom Could you provide some very simple code snippet as example, please.
I read all the project documentation, but did not find an example of using these two properties.

**Comment by RomanSuvorov** [comment]
> @gorhom Could you provide some very simple code snippet as example, please.
> I read all the project documentation, but did not find an example of using these two properties.

Maybe there is a discussion or issue  related to these properties?

**Comment by gorhom** [comment]
>I read all the project documentation, but did not find an example of using these two properties.

you could look at the [map example](https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/integrations/MapExample.tsx), i used animated position to animate the weather component

**Comment by RomanSuvorov** [comment]
@gorhom 
Cool, thank you
