### ISSUE TITLE
[v4] Setting zIndex isn't being set in the root container (BottomSheetContainer)

### ISSUE THREAD

**Issue by sorioinc** [gorhom/react-native-bottom-sheet#608]
# Bug

Setting `zIndex` in the style for the `<BottomSheet />` component doesn't take effect.

Looking a little deeper, I found that BottomSheetContainer is the root `View`:

https://github.com/gorhom/react-native-bottom-sheet/blob/3b1428199f49339d5aa8a607cd0f496907fcb2e5/src/components/bottomSheetContainer/BottomSheetContainer.tsx#L75

By changing the above with this worked as expected:
```js
style={[containerStyle, {zIndex: 1000}]}
```

Can you please make some style prop to bubble up the main container View?

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.0.3   |
| react-native                    | Expo SDK 41   |
| react-native-reanimated         | ~2.1.0   |
| react-native-gesture-handler    | ~1.10.3   |

## Steps To Reproduce

1. Set a zIndex to a sibling View.
2. Set a greater zIndez to the BottomSheet style prop.
3. BottomSheet is shown underneath the View.

Describe what you expected to happen:

1. BottomSheet has to follow the zIndex given in the style. If it's greater than any other View in the element tree, then it should stack at the top.

## Reproducible sample code

https://snack.expo.dev/@sorioinc/bottom-sheet-v4-reproducible-issue-template

**Comment by SohelIslamImran** [comment]
Same issue

**Comment by BrotskyS** [comment]
containerStyle={{zIndex: 100}}
