### ISSUE TITLE
[v4] BottomSheetBackdrop animation is not smooth

### ISSUE THREAD

**Issue by mydesweb** [gorhom/react-native-bottom-sheet#614]
# Bug

I know that there are many issues reported about BottomSheetBackdrop, I also notice that the Backdrop animation is even worse when you close the BottomSheet and right after you try to navigate to another stack or screen.

I never see this issue with react-native-bottomsheet-reanimated maybe you can check their implementation.

This library is awesome but since the Backdrop animation is not running at 60 fps is very annoying.

Hope it can be fixed soon. Thank you.
-->

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.0-alpha.30   |
| react-native                    | 0.64.2   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. sheetRef.current.close();
2. navigation.navigate('AnotherStack')

Describe what you expected to happen:
1. the Backdrop animation should be smooth

**Comment by gorhom** [comment]
@mydesweb please follow the template and provide reproducible sample code
