### ISSUE TITLE
[v4] Can configure to show backdrop on initial snap point

### ISSUE THREAD

**Issue by max-frai** [gorhom/react-native-bottom-sheet#615]
# Bug

I try backdrop component from v4:

        const renderBackdrop = useCallback(
            (props) => (
                <BottomSheetBackdrop
                    {...props}
                    opacity={0.7}
                    appearsOnIndex={0}
                />
            ),
            []
        );

And I set appers on index to zero, so I want backdrop as soon as bottomsheet appers on the screen. But it's ignored and only visible from second snap point.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.1   |
| react-native                    | latest stable expo   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.3   |

**Comment by cepintos** [comment]
For anyone out there, I managed to solve this by passing both the props `appearsOnIndex={0} disappearsOnIndex={-1}`
