### ISSUE TITLE
BottomSheetModal in class component

### ISSUE THREAD

**Issue by sam9010** [gorhom/react-native-bottom-sheet#617]
hello 
I want to use BottomSheetModal in class component
 my sample code
plz help me

`
import  React, {Component} from 'react';
import {BackHandler, StyleSheet,View,Text} from 'react-native';
import { Button } from 'react-native';
import {
    BottomSheetModal,
    BottomSheetModalProvider,
} from '@gorhom/bottom-sheet';
const SNAP_POINTS = [150, 300];
export default class Main extends Component {
    constructor(props) {
        super(props);
        this.state = {
            show:false,
        }
    }
    show(){
        this.setState({show:true});
    }

    render() {
        return(
            <View style={styles.container}>

                <BottomSheetModalProvider>
                    <View style={styles.container}>
                        <Button
                            onPress={this.show()}
                            title="Present Modal"
                            color="black"
                        />
                        <BottomSheetModal
                            ref={this.state.show}
                            index={1}
                            snapPoints={SNAP_POINTS}
                            // onChange={handleSheetChanges}
                        >
                            <View style={styles.contentContainer}>
                                <Text>Awesome</Text>
                            </View>
                        </BottomSheetModal>
                    </View>
                </BottomSheetModalProvider>

            </View>
        )
    }

}

const
    styles = StyleSheet.create({
        container: {
            flex: 1,
            padding: 24,
            justifyContent: 'center',
            backgroundColor: 'grey',
        },
        contentContainer: {
            flex: 1,
            alignItems: 'center',
        },
    })
`

**Comment by robinvw1** [comment]
For class-based React components you need to use [React.createRef](https://reactjs.org/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element).

I've tweaked your code:

```jsx
import React, { Component } from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';
import { BottomSheetModal, BottomSheetModalProvider } from '@gorhom/bottom-sheet';

const SNAP_POINTS = [150, 300];

export default class Main extends Component {
    constructor(props) {
        super(props);

        this.bottomSheetModalRef = React.createRef();
    }

    show() {
        this.bottomSheetModalRef.current?.present();
    }

    render() {
        return (
            <BottomSheetModalProvider>
                <View style={styles.container}>
                    <Button
                        onPress={this.show.bind(this)}
                        title="Present Modal"
                        color="black"
                    />
                    <BottomSheetModal
                        ref={this.bottomSheetModalRef}
                        index={1}
                        snapPoints={SNAP_POINTS}
                    >
                        <View style={styles.contentContainer}>
                            <Text>Awesome</Text>
                        </View>
                    </BottomSheetModal>
                </View>
            </BottomSheetModalProvider>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 24,
        justifyContent: 'center',
        backgroundColor: 'grey'
    },
    contentContainer: {
        flex: 1,
        alignItems: 'center'
    }
});

```

**Comment by gorhom** [comment]
thanks @robinvw1 for providing the class example ❤️

**Comment by PartypayNL** [comment]
How can we change the animation duration when using BottomSheetModal inside a class component?
