### ISSUE TITLE
zIndex for main container

### ISSUE THREAD

**Issue by iutin** [gorhom/react-native-bottom-sheet#62]
Hi, @gorhom.
Is it possible to set zIndex for main bottom-sheet container? 
Thanks

**Comment by MaximoSucari** [comment]
did you resolve it?

**Comment by gorhom** [comment]
you can use `BottomSheetModal` for this use case 

https://gorhom.github.io/react-native-bottom-sheet/modal

**Comment by MaximoSucari** [comment]
Im using modal, any idea? Thanks

![Screenshot_1608222220](https://user-images.githubusercontent.com/43243247/102514438-3df3d380-406b-11eb-94ed-0f47ce952221.png)
![Screenshot_1608222332](https://user-images.githubusercontent.com/43243247/102514553-5fed5600-406b-11eb-8ba1-6ccc48f8dee1.png)

`return (
    <>
      <BottomSheetModalProvider>
        <View style={NowCommentsComponentStyleStyle.container}>
          <View style={NowCommentsComponentStyleStyle.commentBox}>
            <CommentBox userName={userName} sheetReference={sheetReference} />
          </View>
          <BottomSheetModal
            ref={sheetReference}
            index={1}
            snapPoints={snapPoints}
          >
            <BottomSheetView onLayout={handleOnLayout}>
              <CommentsSheet userName={userName} />
            </BottomSheetView>
          </BottomSheetModal>
        </View>
      </BottomSheetModalProvider>
    </>
  );`

**Comment by gorhom** [comment]
You need to set the ‘BottomSheetModalProvider’ at the top level of your app, so the modal will be on top of everything else

**Comment by MaximoSucari** [comment]
thankssss
