### ISSUE TITLE
[v4] Add TouchableRipple to Touchables

### ISSUE THREAD

**Issue by VityaSchel** [gorhom/react-native-bottom-sheet#622]
# Feature Request

Please add [TouchableRipple](https://callstack.github.io/react-native-paper/touchable-ripple.html) from `react-native-paper` to [touchables](https://gorhom.github.io/react-native-bottom-sheet/troubleshooting#pressables--touchables-are-not-working-on-android)!

## Why it is needed

Current implementation only has highlight and opacity effects, but not ripple.

## Possible implementation

Try to copy it from callstack's library?

### Code sample
```javascript
import { Button } from 'react-native-paper'
import { TouchableRipple } from 'react-native-bottom-sheet'

<TouchableRipple onPress={() => console.log('OnPress')}>
  <Button title='Hello world' />
</TouchableRipple>
```

**Comment by gorhom** [comment]
you can `RectButton` from `react-native-gesture-handler`, it should give you the ripple effect on android

**Comment by VityaSchel** [comment]
> you can `RectButton` from `react-native-gesture-handler`, it should give you the ripple effect on android

It works, thanks!
