### ISSUE TITLE
Cannot convert undefined value to object

### ISSUE THREAD

**Issue by AyoubAtba** [gorhom/react-native-bottom-sheet#625]
# Bug

I've done everything correctly.
1- installed reanimated and gesture-handler
2- cleared the android build
3- cleared the metro cache

But still throws this

Error:
Cannot convert undefined value to object

Source: myproject\node_modules\react-native-reanimated\src\reanimated2\Hooks.ts (useDerivedValue)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.0.3   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | ^2.2.0   |
| react-native-gesture-handler    | ^1.10.3   |

**Comment by RomSribn** [comment]
The same issue!

**Comment by gorhom** [comment]
did you install Reanimated correctly ? https://docs.swmansion.com/react-native-reanimated/docs/installation

try to:
- remove `node-modules`
- reset metro cache
- try again

**Comment by KrasniqiR** [comment]
I'm running into the same issue in React-Native web

**Comment by romanonthego** [comment]
Hey, I've encountered the same issue.
Haven't you by any chance used react-native version of storybook?
Because issue is that package code is not traspiled by babel (I don't know why exactly, but many react-native packages are not transpiled) with reanimated-plugin.
I've fixed this by setting `resolveMainFields`:
```js
resolver: {
    resolverMainFields: ['sbmodern', 'react-native', 'main'],
   //...
}
```

in metro.config.js;

**Comment by KrasniqiR** [comment]
> I'm running into the same issue in React-Native web

Solution for me was updating `webpack.config.js` in my `expo` project to the example shown below. It turns out the package wasn't being transpiled by Babel. (This also helps with Moti and @motify)

```
const { createWebpackConfigAsync } = require('expo-yarn-workspaces/webpack');
const webpack = require('webpack');

module.exports = async function (env, argv) {
  const config = await createWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: ['@gorhom/bottom-sheet'],
      },
    },
    argv,
  );
```

**Comment by holyris** [comment]
@KrasniqiR nice fix, but now I'm having this error from react-native-reanimated 2.2.2 :

can't convert null to object
Source : node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/Mapper.js (extractMutables)
