### ISSUE TITLE
Access shared value of scrollY in Scrollables

### ISSUE THREAD

**Issue by branikclimbs** [gorhom/react-native-bottom-sheet#630]
## Ask your Question

Is there a way to access the scrollY value of `BottomSheetScrollView` so I can animate other elements while the user scrolls? If so, how can I achieve this?
In v3 I was able to achieve this by setting value in onScroll prop which is not accessible anymore.

**Comment by mohandere** [comment]
Hey @gorhom Many thanks for amazing library.

Do you have any thoughts on how can we access scrollY value of BottomSheetScrollView? I didn’t found any doc around it.

Thanks.

**Comment by branikclimbs** [comment]
@mohandere sorry for the late response. I was able to access scrollY by customizing scrollEventsHandlersHook. My solution is not perfect but works for now if anyone has an idea how this can be achieved in a better way let us know, please. 

**Solution**:
I copied [useScrollEventsHandlersDefault](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/hooks/useScrollEventsHandlersDefault.ts) to my repository and renamed it to `useCustomScrollEventsHandlers` also added third argument `scrollY`, than I added this block of code to `handleOnScroll` callback
```
if (animatedScrollableState.value !== SCROLLABLE_STATE.LOCKED) {
       scrollY.value = e.contentOffset.y
 }
 ```

after that, you can use it in a bottom sheet like this

```
const scrollY = useSharedValue(0)

<BottomSheetScrollView
      scrollEventsHandlersHook={(ref, contentOffsetY) =>
          useCustomScrollEventsHandlers(ref, contentOffsetY, scrollY)
      }
>
```

**Comment by mohandere** [comment]
> 

Thanks @branislaav for your reply, Will try this out.

**Comment by branikclimbs** [comment]
just spotted a bug in my implementation. 🙈  I had sticky header animation styles applied on scrollY but after I called `bottomSheetRef.current?.collapse()` when still scrolled and then expanded bottom sheet back to full height, header animated styles were still applied.

It looks that I was able to fix it by adding 
```
if (animatedScrollableState.value === SCROLLABLE_STATE.LOCKED) {
     scrollY.value = 0
}
```
to handleOnScroll callback

**Comment by NicholasKuchiniski** [comment]
I was facing the same problem (i had to access the scroll y position of the flatlist to make some animations) and i found a way to access this value without having to copy the `useScrollEventsHandlersDefault` to my repo, i just extended it into a new hook, in case anyone needs it:

```typescript
export function useCustomScrollEventsHandlers(
  ref: RefObject<Scrollable>,
  contentOffsetY: SharedValue<number>,
): ReturnType<typeof useScrollEventsHandlersDefault> {
  const { handleOnScroll, ...handlers } = useScrollEventsHandlersDefault(ref, contentOffsetY);

  const customHandleOnScroll: ScrollEventHandlerCallbackType<unknown> = useWorkletCallback(
    (event, context) => {
      console.log(event.contentOffset.y);

      handleOnScroll?.(event, context);
    },
  );

  return {
    ...handlers,
    handleOnScroll: customHandleOnScroll,
  };
}
```
