### ISSUE TITLE
[v4] handleUnmountSheet seems to fire twice in some scenarios

### ISSUE THREAD

**Issue by beinginorbit** [gorhom/react-native-bottom-sheet#632]
# Bug

We're encountering an issue where handleUnmountSheet seems to fire twice when quickly dismissing and presenting modals causing the sheetsQueue to be incorrect. This happens in real world scenarios when there is heavy bridge traffic occuring. The actual bug is that the first (lower) bottom sheet gets stuck open, you can see this in the video provided. There's other bugs I think this introduces such as preventing presenting future bottom sheets in some scenarios simply because the internal sheetsQueue is incorrect.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.3   |
| react-native                    | 0.63.4   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce

1. Reduce animationConfig speed via animationConfigs prop
2. .present() second BottomSheet
3. .dismiss() second BottomSheet
4. repeat 2 and 3 quickly

Describe what you expected to happen:

handleUnmountSheet should fire once per dismiss.

## Reproducible sample code

https://snack.expo.dev/Y_ZK1ozQ-

https://user-images.githubusercontent.com/2807897/132748996-9f9d51a6-1d3f-4b1c-9d68-c2f35c28b48e.mp4

**Comment by gorhom** [comment]
pressing that fast will cause the sheet queue to break, the solution would be to prevent any interactivity for the content until the animation is complete, this issue seemed related to #575

**Comment by gorhom** [comment]
@spacesuitdiver could you test this pr https://github.com/gorhom/react-native-bottom-sheet/pull/638, thanks

**Comment by beinginorbit** [comment]
Hey @gorhom I can try this and look at the PR in more detail on Monday but briefly looking at it I was also thinking we entertain putting the queue in a shared value so we can allow the interactions to occur quickly. I’m not sure if this would work but I’m curious your thoughts. Thanks.

**Comment by ashernguyen** [comment]
@gorhom  I tested with pr #638 and it seems the issue is still there. This issue can be reproduced when passing a custom `animationConfigs` from `useBottomSheetSpringConfigs`

**Comment by zachgibson** [comment]
Just curious, any updates on this?

**Comment by gorhom** [comment]
Hi @spacesuitdiver, @ashernguyen, @zachgibson , would you mind testing https://github.com/gorhom/react-native-bottom-sheet/pull/769

**Comment by SaeedZhiany** [comment]
@gorhom

I'm using v4.1.5 and I'm still facing that problem. is it any config needs to be set?

**Comment by Lurtt** [comment]
hame similar issue when the bottom sheet is able to open but not close

**Comment by artymir** [comment]
same issue with useBottomSheetSpringConfigs
