### ISSUE TITLE
[v4] | BottomSheetFlatList scroll not working when scroll bottom to top 

### ISSUE THREAD

**Issue by zuhairnaqi** [gorhom/react-native-bottom-sheet#636]
# Bug

The bottom sheet content is not scrolling when it's not opened fully by snapPoints. The content should be scroll when 
we scroll from top to bottom.
I used FlatList form react-native-gesture-handler, but that has another issue that it not taking up the sheet when scroll to the top.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.0.3  |
| react-native                    | 0.65.1  |
| react-native-reanimated         | ^2.3.0-alpha.3  |
| react-native-gesture-handler    | ^1.10.3 |

## Steps To Reproduce

1. Scroll from the bottom to the top until the whole expanded component is shown
2. Scroll from top to bottom sliding on the top of the component
3. Scroll from top to bottom sliding inside the component

Describe what you expected to happen:

1. It should scroll when we scroll from top to bottom but when we scroll to bottom to top the sheet should expand (which is working)
2. 

## Reproducible sample code

```
<BottomSheet
            snapPoints={bottomSheetSnapPoints}
            {...(renderContentHeader && {
              handleComponent: (): ReactElement => (
                <Handle>{!contentIsLoading && renderContentHeader}</Handle>
              ),
            })}>
            {props.componentType === 'FlatList' && (
              <BottomSheetFlatList
                data={data}
                keyExtractor={keyExtractor}
                renderItem={renderItem}
                contentContainerStyle={[
                  styles.contentContainer,
                  {
                    backgroundColor: theme.colors?.white,
                    minHeight: '100%',
                  },
                  contentContainerStyle,
                ]}
              />
            )}
          </BottomSheet>
```

https://user-images.githubusercontent.com/38198958/132880351-40833480-4a0e-4c2d-ab0e-93979c247412.mov

**Comment by gorhom** [comment]
this is expected behaviour, however you can override it , look at the custom gesture handling example

**Comment by fukemy** [comment]
hi, how did u solved this, i am got same issues
