### ISSUE TITLE
[v4] initial snap points & index

### ISSUE THREAD

**Issue by pnogier** [gorhom/react-native-bottom-sheet#637]
# Bug

Hi guys,
Just migrated from v3 (`3.6.6`) to v4 (`4.0.3`),

Here is the code I was using in v3: 

```javascript
<BottomSheetModal
    key={index}
    ref={index === 0 ? modalRef0 : index === 1 ? modalRef1 : null}
    index={1}
    snapPoints={[-1, '75%']}
    onDismiss={handleDismiss}
    backdropComponent={BottomSheetBackdrop}
    stackBehavior={'push'}
    onChange={(e) => handleModalStateChange(e)}
>
    {...}
</BottomSheetModal>
```

When I use this code, I am getting the following error : 
`Invariant Violation: Snap point '-1' is invalid. if you want to allow user to close the sheet, Please use 'enablePanDownToClose' prop.`

So I change my snapPoints prop to be `snapPoints={['75%']}` and add `enablePanDownToClose={true}`

Then I am getting the following error :
`Invariant Violation: 'index' was provided but out of the provided snap points range! expected value to be between -1, 0`

So, I change my index value to -1, but nothing happens when I try to open the sheet,
And if i change the index to 0 and then open the sheet, it opens and then instantly closes itself like this :

https://user-images.githubusercontent.com/25363506/132926910-dd90ea3f-abd7-4093-8d0e-1c195cf7c8a3.mov

Has someone already faced the same issue while migrating ?

Issues checked : 
- https://github.com/gorhom/react-native-bottom-sheet/issues/593

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.0.3   |
| react-native                    | 0.64.2   |
| react-native-reanimated         | 2.2.1   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Migrate from v3 to v4
2. Use the props provided above to BottomSheetModal
3. Check the other steps above

Describe what you expected to happen:

1. The sheet opens properly as it was opening on v3

## Reproducible sample code

Please check find a reproducible sample [here](https://snack.expo.dev/p1MVa0pVq)

Cheers

**Comment by sorioinc** [comment]
Maybe a rerender issue? I had something like it happening but a parent component rerender was the culprit. I was handling the expand/close using the ref from the parent state actually did something funky.

Can you create a minimal reproducible example using the following template?
https://snack.expo.dev/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by likern** [comment]
@pnogier Sorry for out of scope question. Where did you find that tab switcher (A l`heure / A la`journee) in bottom sheet? I'm looking for something exactly like this ❤️

**Comment by pnogier** [comment]
@sorioinc Thank you for your answer, here is my minimal reproducible example : https://snack.expo.dev/p1MVa0pVq
I am still getting the error using percentages as snapPoints which was very useful for my case, is there a solution for it ? Else i'll do calculations to get the proper height and pass it as snapPoint.

@likern Hi dude, this isn't something really fancy, just a View, containing 2 Button which toggles a boolean to true or false, then I apply the style checking the value of the boolean.

**Comment by gorhom** [comment]
@pnogier in your provided snack , you set `index` prop to `1`, but you only have 1 provided snap point ? you need to set it to `0` instead to get it working
