### ISSUE TITLE
[v2] Presenting a BottomSheetModal with Closing another BottomSheetModal causes the first to reappear

### ISSUE THREAD

**Issue by SCasarotto** [gorhom/react-native-bottom-sheet#639]
# Bug

I believe this is related to or similar to #204. 

I have a bottom sheet modal that contains a  list of buttons. Once of those buttons should hide that current bottom sheet modal and show another one. I am using the ref for call `present` on one and `close` on the other but when the second bottom sheet modal appears the first doesn't close. 

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 2.3.0   |
| react-native                    | 0.65.1   |
| react-native-reanimated         | 1.13.3   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

See Code Below

 See Code Same Below, I think it does a good job of demonstrating the bug.
1.
2.
3. 

Describe what you expected to happen:

1. I expect the first bottom sheet to close and the second to open.
2.

## Reproducible sample code

I attempted to create the simplest version I could.
```
import React, { useRef } from 'react';
import { Text, ScrollView, View, SafeAreaView, Pressable } from 'react-native';
import {
  BottomSheetModal,
  BottomSheetModalProvider,
} from '@gorhom/bottom-sheet';

export const SomePage = () => {
  const bottomSheetModal1Ref = useRef<BottomSheetModal>(null);
  const bottomSheetModal2Ref = useRef<BottomSheetModal>(null);

  return (
    <BottomSheetModalProvider>
      <View>
        <Pressable
          onPress={() => {
            bottomSheetModal1Ref?.current?.present();
          }}
        >
          <Text>Show BottomSheetModal 1</Text>
        </Pressable>
      </View>
      <BottomSheetModal ref={bottomSheetModal1Ref} snapPoints={['50%']}>
        <Pressable
          onPress={() => {
            bottomSheetModal1Ref?.current?.close();
            bottomSheetModal2Ref?.current?.present();
          }}
        >
          <Text>Hide BottomSheetModal 1 and Show BottomSheetModal 2</Text>
        </Pressable>
      </BottomSheetModal>
      <BottomSheetModal ref={bottomSheetModal2Ref} snapPoints={['50%']}>
        <Pressable
          onPress={() => {
            bottomSheetModal2Ref?.current?.close();
          }}
        >
          <Text>Hide BottomSheetModal 2</Text>
        </Pressable>
      </BottomSheetModal>
    </BottomSheetModalProvider>
  );
```

Also here is a video, please ignore some of the UI around the example, I didn't feel like spinning up a whole new app from the one I was working in. Its a bit hard to tell but the two lines are the `Pressable`s from above and I click on them. 

https://user-images.githubusercontent.com/13336976/132954814-b442c22c-3fac-494f-aa03-7b400544a888.mp4

**Comment by SCasarotto** [comment]
After looking in the source code mode I found `dismiss` and when using that it seems to do whats expected. Sorry for the extra noise.

**Comment by Louigee-creator** [comment]
I am facing the same issue and i want to know where you used the dismiss

> After looking in the source code mode I found `dismiss` and when using that it seems to do whats expected. Sorry for the extra noise.

**Comment by nikin94** [comment]
I had the similar problem and adding the `name` prop to the `<BottomSheetModal>` component worked for me

**Comment by rawr-code** [comment]
@SCasarotto I had the same problem and I use the stackBehavior prop  and worked for me
https://ui.gorhom.dev/components/bottom-sheet/modal/props
