### ISSUE TITLE
Tried to synchronously call function {assign} from a diffrent thread

### ISSUE THREAD

**Issue by WillKre** [gorhom/react-native-bottom-sheet#64]
# Bug

Getting the following error when trying to use this package: 

```
Tried to synchronously call function {assign} from a diffrent thread.
Solution is:
a) if you want to synchronously execute this method, mark it as a worklet
b) if you want to execute this method on the JS thread, wrap it using runOnJS
```

I've tracked the error message back to `node_modules/react-native-reanimated/Common/cpp/SharedItems/ShareableValue.cpp` line 15. And there is a thread on the issue here: https://github.com/software-mansion/react-native-reanimated/pull/1347

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | "2.0.0-alpha.0"   |
| react-native                    | "0.63.3"  |
| react-native-reanimated         | "^2.0.0-alpha.8"   |
| react-native-gesture-handler    | "^1.8.0"   |

## Steps To Reproduce

1. Installed `"@gorhom/bottom-sheet": "2.0.0-alpha.0"`, `"react-native-reanimated": "^2.0.0-alpha.8"` (with all changes needed for the library) and "react-native-gesture-handler": "^1.8.0"`.
2. Replace my App.tsx with the contents of any of the example docs, such as [this](https://github.com/gorhom/react-native-bottom-sheet/blob/9c92c719e9e3347613dddf0e5b253731905ff81e/docs/view.md).
3. **_Error appears on render_**

Describe what you expected to happen:

1. I'd expect no error and to see the sheet

**Comment by gorhom** [comment]
duplicated (#52)
