### ISSUE TITLE
Is Reanimated v1 still supported?

### ISSUE THREAD

**Issue by jzxchiang1** [gorhom/react-native-bottom-sheet#682]
# Feature Request

I noticed the peerDependencies specifies reanimated v2, but the README says this library is compatible with reanimated v1 & v2.

Is reanimated v1 still supported?

## Why it is needed

Some clients can't use reanimated v2 because it doesn't yet support all JS engines, for example v8.

## Possible implementation

n/a

### Code sample

n/a

**Comment by gorhom** [comment]
https://gorhom.github.io/react-native-bottom-sheet/v2/
