### ISSUE TITLE
[v4] buttonSheet.current.close closing all sheets inside Portal

### ISSUE THREAD

**Issue by Engazan** [gorhom/react-native-bottom-sheet#686]
# Bug

BottomSheet?.current?.close() closing all opened Sheets inside Portal

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.0   |
| @gorhom/portal           | 1.0.9   |
| EXPO                    | 42   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.2   |

## Steps To Reproduce
1. click button to set STATE_1 to true, to render BottomSheetModal_1
2. click button inside BottomSheetModal_1 to set STATE_2 to render BottomSheetModal_2, then close BottomSheetModal_1 with ```BottomSheetModal_1?.current?.close()```, and it close also "BottomSheetModal_2" when it is fully open ...

Describe what you expected to happen:

1. in Step 2 i expect CLOSE BottomSheetModal_1 and not BottomSheetModal_1 and BottomSheetModal_2 

## Reproducible sample code

https://snack.expo.dev/@engazan/bottom-sheet-v4-reproducible-issue-template

video example

https://user-images.githubusercontent.com/53254371/136505448-65cd3108-70a1-4460-a0d6-28b5cc129e2d.mov

**Comment by jsamr** [comment]
I have a very similar issue but I am not using portals!

**Comment by jsamr** [comment]
@Engazan I ended up with resorting to `BottomSheetModal` which handles this cases perfectly.

**Comment by gorhom** [comment]
BottomSheetModal exports a hook that includes ‘dismissAll’

**Comment by Engazan** [comment]
> BottomSheetModal exports a hook that includes ‘dismissAll’ 

Is it passible to fix it ? Without using wrapper ? Cuz it looks like wrong behevior, if you Close ref1 it should not close all refs :/, or am i wrong ? Or miss something ?, thanks

**Comment by gorhom** [comment]
@Engazan have you read the documentation ? https://gorhom.github.io/react-native-bottom-sheet/modal/hooks#usebottomsheetmodal
