### ISSUE TITLE
[v4] | Rerendering screen prevents modal to be redisplayed

### ISSUE THREAD

**Issue by nastarfan** [gorhom/react-native-bottom-sheet#697]
# Bug
BottomSheetModal cannot be shown after performing state update on the screen. It is working fine if there is no state update, thus no rendering, but once the screen is rerendered the modal cannot be shown after dismissed/closed.

When there is no state update, the sheet modal is working fine:

![without state update](https://user-images.githubusercontent.com/45551937/137223687-c581ee93-9c54-4f30-8242-a5451ac5e13f.gif)

But once we add state update, the sheet modal cannot be displayed:

![with state update](https://user-images.githubusercontent.com/45551937/137223718-3ef4d55b-64eb-49b8-9932-550fbb9ff849.gif)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.2   |
| react-native                    | 0.65.1   |
| react-native-reanimated         | 2.2.2   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Use `BottomSheetModal`
2. Add onChange callback
3. Update state within the callback
4. BottomSheetModal can no longer appear

Describe what you expected to happen:

1. Even if we perform state update on the screen, we can still show the modal

## Reproducible sample code

I have created a snack for the code to demonstrate the bug, but somehow it won't run in expo, I am not very familiar with it. If line 39 and 42 (update state code) are commented out, everything works fine.
https://snack.expo.dev/@nastarfan/bottom-sheet-v4-reproducible-issue-template

```
...
const handlePresentPress = useCallback(() => {
    bottomSheetRef.current?.present();
  }, []);

const handleSheetChanges = useCallback((index: number) => {
    if (index === -1) {
      console.log('closing');
      setBottomSheetState('closed');
    } else {
      console.log('opening');
      setBottomSheetState('opened');
    }
  }, []);

...

 <BottomSheetModal
        ref={bottomSheetRef}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
        <View style={styles.sheetContainer}>
          <Text>Hello</Text>
          <Text>
            Ullamco veniam minim sint aliquip fugiat sunt occaecat consectetur
            qui commodo.
          </Text>
        </View>
      </BottomSheetModal>
...
```

This issue only presents for `BottomSheetModal`. `BottomSheet` works fine

**Comment by sirajtahrawashmen** [comment]
+1

**Comment by gorhom** [comment]
working on fixing this

**Comment by gorhom** [comment]
this should be fixed with `v4.1.3 `

**Comment by nastarfan** [comment]
Thanks a lot @gorhom , you rock man

**Comment by He1nr1chK** [comment]
Still happens in v4.1.5

**Comment by dlombardi** [comment]
This is still occuring

**Comment by pamela-encora** [comment]
This is still occurring in v4.1.5

**Comment by pamela-encora** [comment]
I was able to fix this issue with the following code:

```
const selectOption = (option: PickerOption) => {
    selectedOptionRef.current = option;
    close();
  };

```
```
const handleChange = useCallback(
    (index: number) => {
      if (index === -1 && selectedOptionRef.current) {
        onChange(selectedOptionRef.current);

        selectedOptionRef.current = undefined;
      }
    },
    [onChange]
  );
```

Basically, I stored in a ref the value that needs to be updated and, then, delayed the `onChange` callback until index becomes -1 (which means modal was closed)

**Comment by Kjagd** [comment]
I have something that sounds like the same problem. I've found that it's seems to be the opacity which is set to 0 from the fix here: https://github.com/gorhom/react-native-bottom-sheet/pull/690#issuecomment-1135546679 (I can still press on element and fire listeners for that)

**Comment by arjendevos** [comment]
Seems like we're still having this problem on
```
    "@gorhom/bottom-sheet": "^4.4.0",
```

**Comment by arjendevos** [comment]
But only on iOS

**Comment by arjendevos** [comment]
The strange thing is, if we add a console.log to handleSheetChanges it opens but without animation 🤯 
```
  const handleSheetChanges = React.useCallback((index: number) => {
    console.log("....");
  }, []);
  ```

**Comment by mrmuke** [comment]
Hey all, was having this issue for a while, then what worked for me was setting a ref to a value during the function that would dismiss the  bottom sheet modal, then once the bottom sheet dismisses, onDismiss would trigger and call your onDismiss function which would check if that ref had a value, then modify your state after the  bottom sheet modal is dismissed.
