### ISSUE TITLE
Incompatible with reanimated v2

### ISSUE THREAD

**Issue by sa8ab** [gorhom/react-native-bottom-sheet#7]
### Current Behavior
App crashes with the example usage from docs
- What code are you running and what is happening?
with the example usage from docs

### Expected Behavior
Not to crash

### How to reproduce
Run a simple example of the library using Reanimated 2

The reason I guess since I had faced it before is that it uses interpolate instead of `interpolateNode` since in reanimated 2 it should me imported as `interpolateNode`
[one place I found that is using interpolate](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheet/BottomSheet.tsx#L22)

**Comment by gorhom** [comment]
hi @sa8ab , thanks for reporting this 

this is expected crash, the library was built with Reanimated v1, However migrating this library to Reanimated v2 is a plan for sure.

let me know if you want to contribute :)

**Comment by sa8ab** [comment]
Reanimated2 was supposed to be backward compatible with v1, if this is not the case I we almost can't have v2 installed beside the libraries that use v1!! I'm happyn't :((

**Comment by sa8ab** [comment]
@gorhom I converted imports from `interpolate` to `interpolateNode` and `easing` to `EasingNode` and it doesn't crash anymore, but I get the following error. can you help me with it?
![image](https://user-images.githubusercontent.com/59901734/90331220-63050680-dfe5-11ea-9204-3674be96356f.png)

**Comment by gorhom** [comment]
Hi @sa8ab! Try pulling latest commits from master again ! It should work

**Comment by sa8ab** [comment]
I made it work with Reanimated v2 and it looks quite emazing, I will pull a request for v2.

Only issue I am facing it that, when you scroll out of bottomsheet, I mean "while scrolling to bottom and finger goes out of the bottom sheet" , all the gestures disable which does not feel quite perfect in this case. You have any idea how to make it work? @gorhom

**Comment by gorhom** [comment]
Great! Not sure why, but ill need to examine the gestures states

**Comment by sa8ab** [comment]
Nice, let me know if you need screen recording of what is happening

**Comment by gorhom** [comment]
You could submit a draft pr, and ill investigate it with you
