### ISSUE TITLE
[v4] BottomSheet on Android crashes but works fine on iOS

### ISSUE THREAD

**Issue by jimmy-chiang** [gorhom/react-native-bottom-sheet#709]
# Bug

Hi, I'm currently developing with expo. I used to work with bottom sheet before, and it works well on both Android and iOS.

But in today it crashes on Android but still works fine on iOS.
First I wonder if it's my problem. So I copy the code in this [tutorial](https://gorhom.github.io/react-native-bottom-sheet/usage) to test this problem. In [this video](https://drive.google.com/file/d/15WOkmQE5Pwmevq1lVuBgOa9isYJW09iu/view?usp=sharing), I set the bottom sheet test button to navigate to the code in this tutorial. The problem still occurred.

The video Android version is Android 12, and I have test it on Android 11 too. And the problem still exist.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.3   |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 2.2.3   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Followed the instruction of the tutorial.

Describe what you expected to happen:

1. Expected to have the same output of the tutorial.

**Comment by daniel-parlapan** [comment]
@qaws5503 what was the issue?
