### ISSUE TITLE
Bug Opening dialog strange effect

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-bottom-sheet#73]
# Bug

<img width="852" alt="Schermata 2020-11-20 alle 18 23 23" src="https://user-images.githubusercontent.com/20476002/99830122-8b108280-2b5d-11eb-9d64-c448973a20d7.png">

![Registrazione schermo 2020-11-20 alle 18 20 24](https://user-images.githubusercontent.com/20476002/99829972-4d135e80-2b5d-11eb-8094-578b7a09d7d0.gif)

Hi @gorhom , 

as you can see from the images when I open the dialog bottom sheet, that effect happens.
I could see that it happens both with short times and with long times as in the example in the gif.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 1.4.1   |
| react-native                    | 0.63.3 |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.8.0   |

## Reproducible sample code

```
const bottomSheetLang = useCallback((newValue, id) => {
    present(
      <View style={{ flex: 1, backgroundColor }}>
        <Text>{settings.item.lang}</Text>
        <RadioButton.Group
          onValueChange={(newValue) => changeButtonLang(newValue)}
          value={settings.item.lang}>
          <View style={(Layout.row, Layout.rowHCenter)}>
            <RadioButton value="en" />
            <Text>En</Text>
          </View>
          <View style={(Layout.row, Layout.rowHCenter)}>
            <RadioButton value="fr" />
            <Text>Fr</Text>
          </View>
          <View style={(Layout.row, Layout.rowHCenter)}>
            <RadioButton value="it" />
            <Text>It</Text>
          </View>
        </RadioButton.Group>
      </View>,
      {
        snapPoints: ['50%'],
        animationDuration: 5000,
        overlayComponent: BottomSheetOverlay,
        overlayOpacity: 0.5,
        dismissOnOverlayPress: true,
        //handleComponent: handle,
        //backgroundComponent: BlurredBackground,
        //onChange: handleChange,
      }
    );
  }, [settings]);
```

**Comment by gorhom** [comment]
this caused by the easing function, you could set `animationEasing` to `Easing.linear`.

```ts
import { Easing } from 'react-native-reanimated';
```

**Comment by Angelk90** [comment]
@gorhom : I did as you told me, it seems that the problem is solved, but I have now noticed something else.

See image, it seems that at least I can only notice this problem on android.

So the problem below seems correct, but not above.

![Senza nome](https://user-images.githubusercontent.com/20476002/100359634-1c697400-2ff8-11eb-8f23-43ebf7457717.gif)

```javascript
{
          snapPoints: ['25%'],
          animationDuration: 800,
          overlayComponent: BottomSheetOverlay,
          overlayOpacity: 0.5,
          dismissOnOverlayPress: true,
          animationEasing: Easing.out(Easing.exp) //<- Here Easing.linear, Easing.out(Easing.linear), Easing.out(Easing.exp)
}
```
