### ISSUE TITLE
Props color handle and handle container

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-bottom-sheet#74]
# Feature Request

<img width="366" alt="Schermata 2020-11-20 alle 16 25 50" src="https://user-images.githubusercontent.com/20476002/99831018-c8c1db00-2b5e-11eb-83a1-f720a554748d.png">

First Device Pixel 3a, Second Device 4xl.

<img width="872" alt="Schermata 2020-11-20 alle 18 41 33" src="https://user-images.githubusercontent.com/20476002/99832034-46d2b180-2b60-11eb-8c7c-706e4ae03f8a.png">

## Why it is needed

Hi @gorhom , 

It would be possible to implement two props to be able to change the color of both the handle and the container that contains the handle.

I tried to create my own handle in order to do this but I realized that on two devices both android their display changes as you can see in the image above.
Instead using the normal non-customized one remains the same.

I don't know if I did something wrong, below is the code of the handle I use.

### Code sample

```

indicator: {
    alignSelf: 'center',
    width: (8 * SCREEN_WIDTH) / 100,
    height: 5,
    borderRadius: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  }

const handle = () => {
    return (
      <View
        style={{
          paddingHorizontal: 16,
          paddingVertical: 5,
          backgroundColor,
        }}>
        <View
          style={[
            styles.indicator,
            {
              backgroundColor:
                settings.item.colorScheme === 'light'
                  ? 'rgba(0, 0, 0, 0.25)'
                  : 'rgba(255, 255, 255, 0.25)',
            },
          ]}
        />
      </View>
    );
  };
```

**Comment by Angelk90** [comment]
@gorhom :  would it be possible to do such a thing?
which can also be used using `present`.

https://github.com/gorhom/react-native-bottom-sheet/blob/377c2b38cf4fbb8b02facd04c5171289658aec79/src/components/handle/Handle.tsx#L6-L12

```javascript
const BottomSheetHandleComponent = ({ containerStyle, indicatorStyle }) => {
  return (
    <View style={[styles.container, containerStyle]}>
      <View style={[styles.indicator, indicatorStyle]} />
    </View>
  );
};

//example invert color dark mode
containerStyle={{
   backgroundColor: 'rgba(0, 0, 0, 0.75)'
}}

indicatorStyle={{
   backgroundColor: 'white'
}}
```

**Comment by gorhom** [comment]
@Angelk90 you provide `backgroundComponent` with `StyleSheet.absoluteFillObject` as style and it will be behind both `handle` & `sheet content` views.

**Comment by Angelk90** [comment]
@gorhom , I'm sorry I'm not understanding well.

I am using `present` at the moment, see code below.

what I want to do is change the color of the handle and the color of the container of the handle, without having to use `handleComponent` because I have noticed that on android in particular it gives me problems, instead the normal one no problem.


The problem arises from the fact that user can change the theme (from light to dark mode) at any time, I would like the handle and the container of the handle to change color as well.

But there is also the problem with this #71, which doesn't allow it to change at runtime.

```javascript
const bottomSheetTheme = useCallback(
    (newValue, id) => {
      present(
        <View style={{ flex: 1, backgroundColor }}>
          <Text>{settings.item.colorScheme}</Text>
          {theme.map(({ title, value }) => {
            return (
              <TouchableWithoutFeedback
                key={value}
                onPress={() => {
                  //dismiss();
                  changeButtonTheme(value);
                }}>
                <View
                  style={[
                    Layout.row,
                    Layout.rowHCenter,
                    Gutters.tinyVMargin,
                    Gutters.tinyHMargin,
                  ]}>
                  <View style={[Layout.fill]}>
                    <Text>{title}</Text>
                  </View>
                  {settings.item.colorScheme === value ? (
                    <Svgs.RadioButton size={32} color={backgroundColor} />
                  ) : (
                    <Svgs.RadioButtonEmpty size={32} color={backgroundColor} />
                  )}
                </View>
              </TouchableWithoutFeedback>
            );
          })}
        </View>,
        {
          snapPoints: ['25%'],
          animationDuration: 800,
          overlayComponent: BottomSheetOverlay,
          overlayOpacity: 0.5,
          dismissOnOverlayPress: true,
          animationEasing: Easing.out(Easing.exp),
          //handleComponent: handle,
          //backgroundComponent: BlurredBackground,
          //onChange: handleChange,
        }
      );
    },
    [settings]
  );
```

**Comment by gorhom** [comment]
then you will need to pass a custom `handleComponent` that uses theme provider under to update its styling , also for `backgroundComponent` too.

make sure both custom components internally fetch the theme variables
