### ISSUE TITLE
snapPoints it differs a lot between operating systems

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-bottom-sheet#77]
# Bug

90%
<img width="890" alt="Schermata 2020-11-20 alle 22 24 05" src="https://user-images.githubusercontent.com/20476002/99851327-485fa200-2b7f-11eb-843c-e7546fb019ce.png">

100%

<img width="865" alt="Schermata 2020-11-20 alle 22 30 53" src="https://user-images.githubusercontent.com/20476002/99851836-14d14780-2b80-11eb-99b3-d37567f4a576.png">

Hi @gorhom , 

I am using your component on different devices, I tried to put snapPoints = "90%".
I noticed that it differs a lot between the two, as can be seen from the image.

I tried with higher values (100%), it seems that on android it works fine but on ios it gives problems, it goes further.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 1.4.1   |
| react-native                    | 0.63.3 |
| react-native-reanimated         | 1.13.2   |
| react-native-gesture-handler    | 1.8.0   |

## Reproducible sample code

```
{
          snapPoints: ['90%'],
          animationDuration: 10,
          overlayComponent: BottomSheetOverlay,
          overlayOpacity: 0.5,
          dismissOnOverlayPress: true,
        }
```

**Comment by gorhom** [comment]
hi @Angelk90 , thanks for reporting this bug, i am well aware of it and currently working on a fix 👍
