### ISSUE TITLE
Close Keyboard in sync with dismissing BottomSheet

### ISSUE THREAD

**Issue by izakfilmalter** [gorhom/react-native-bottom-sheet#82]
# Feature Request

Wondering if there is a way to close the keyboard in sync with the BottomSheet being dismissed via drag. I have it working nicely when you press the close button:
```ts
  const handleDismissPress = useCallback(() => {
    Keyboard.dismiss()
    dismiss()
  }, [dismiss])
```

## Why it is needed

Seems janky to watch the BottomSheet dismiss fully and then watch the keyboard dismiss.

## Possible implementation

I poked around for a couple min to see if I could do this easily on a ListView in the lib. Should be possible.

**Comment by gorhom** [comment]
hi @izakfilmalter,

good suggestion, i would think of a callback whenever the sheet about to animate to a snap point, that would give the user more control. it would be something like `onSnapToPoint` or `onAnimate`:

```ts
type onAnimate = (fromIndex: number, toIndex: number) => void
```

**Comment by izakfilmalter** [comment]
Ya that would be super helpful. I think you can can also do animations in the sheet then based on where it is snapped.
