### ISSUE TITLE
Failed to import Modal hooks and provider; TypeScript

### ISSUE THREAD

**Issue by doylemark** [gorhom/react-native-bottom-sheet#83]
# Bug
Per the docs it should be possible to import Modal Provider like this:
`import { BottomSheetModalProvider, useBottomSheetModal } from "@gorhom/bottom-sheet";` however this errors to:

```Module '"../../node_modules/@gorhom/bottom-sheet/lib/typescript"' has no exported member 'BottomSheetModalProvider'. Did you mean to use 'import BottomSheetModalProvider from "../../node_modules/@gorhom/bottom-sheet/lib/typescript"' instead?```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0-alpha.0   |
| react-native                    | 0.63.3  |
| react-native-reanimated         | 2.0.0-alpha.8   |
| react-native-gesture-handler    | 1.8.0   |

## Steps To Reproduce
1. add module with `yarn add @gorhom/bottom-sheet@2.0.0-alpha.0`
2. attempt described import

Describe what you expected to happen:
1. The module to import successfully

## Reproducible sample code
`import { BottomSheetModalProvider, useBottomSheetModal } from "@gorhom/bottom-sheet";`

**Comment by gorhom** [comment]
hi @doylemark thanks for submitting this issue.

unfortunately, `BottomSheetModal` is not available - yet - for `2.0.0-alpha.x`, [However it is on the roadmap 👍](https://github.com/gorhom/react-native-bottom-sheet/issues/76 )

**Comment by doylemark** [comment]
Ah, my apologies, I assumed the documentation in the master readme was current. Thanks :)
