### ISSUE TITLE
Bottom Sheet Modal - unable to swipe close modal on Android

### ISSUE THREAD

**Issue by maxckelly** [gorhom/react-native-bottom-sheet#84]
# Bug
- Unable to close bottom sheet modal on Android. iOS works great.

## Environment info
| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^1.4.1  |
| react-native                    | 0.62.2   |
| react-native-reanimated         | ^1.9.0   |
| react-native-gesture-handler    | ^1.6.1   |

## Steps To Reproduce

1. Implement bottom sheet modal
2. Try to swipe down on Android
3. 

Describe what you expected to happen:

1. Expect the modal to close when user swipes down

## Reproducible sample code

Wrapped my navigation in modal provider
```
const AppNavigation = () => {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <AlertContextProvider customStyles={customStyles}>
          <BottomSheetModalProvider dismissOnScrollDown={true} allowTouchThroughOverlay={false}>
            <PlayerContextProvider>
              <MainStackNavigator />
            </PlayerContextProvider>
          </BottomSheetModalProvider>
        </AlertContextProvider>
      </NavigationContainer>
    </SafeAreaProvider>
  );
};
```
- Rendering modal on button press 
```
// Makes the search full page modal appear 
  const handlePresentPress = useCallback(() => {
    present(
      <SearchComponent 
        updateSearch={(search) => setSearch(search)} 
        onTagSelect={(tag) => updateSearch(tag.title)}
        search={search} 
        isLoading={isLoading} 
        tags={storyReducer.allTags}
      />,
      {
        snapPoints: snapPoints, 
        onChange: handleSheetChanges,
      }
    );
  }, [present, snapPoints, handleSheetChanges]);
```

**Comment by adamsoutar** [comment]
Are you able to swipe on normal (non-modal) sheets?
I had an issue where I was unable to drag sheets on Android, and it turned out I hadn't set up `react-native-gesture-handler` [properly for Android](https://docs.swmansion.com/react-native-gesture-handler/docs/#android) in `MainActivity.java`

**Comment by mr-moto** [comment]
Im having the same issue as well.
normal non-modal sheets work and my RNGH is configured correctly.
seems to work if present() is called inside the stack navigator ( using react-navigation )
```
// Doesnt work ( cant drag )
<BottomSheetModalProvider>
    <Stack.Navigator>
        <Stack.Screen name="Screen" component={Screen} /> //If sheet is called within the Screen component, cant drag
    </Stack.Navigator>
</BottomSheetModalProvider>
```

**Comment by maxckelly** [comment]
@adamsoutar - Thanks for the response.  I believe my MainApplication is set up correctly. Tested just then and still no luck. On other modal sheets used by this library (BottomSheetFlatList, BottomSheetSectionList), all work fine on Android. It just seems to be the newly released bottom sheet modal.

```
package com.example;

import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
import org.devio.rn.splashscreen.SplashScreen;

public class MainActivity extends ReactActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    SplashScreen.show(this);
    super.onCreate(savedInstanceState);
  }

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "Example";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
       return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }
}
```

**Comment by gorhom** [comment]
@maxckelly thanks for submitting this issue, could you provide a reproducible sample code that I can test on, thanks

**Comment by maxckelly** [comment]
Hey @gorhom 

Let me know if the below is okay. First time doing this so if there is a better way for me to provide a test case let me know :). I'm wrapping my App.js with `<BottomSheetModalProvider>`

- SearchScreen.js

```
import React, { useState, useCallback, useMemo } from 'react';
import { View, TouchableOpacity } from 'react-native';
import { useBottomSheetModal } from '@gorhom/bottom-sheet';

const SearchScreen = () => {

  const { present, dismiss } = useBottomSheetModal();

  // bottomSheet
  const snapPoints = useMemo(() => ['95%'], []);
  const contentSheetRef = null;

  // callbacks
  const handleSheetChanges = useCallback((index) => {
    console.log('handleSheetChanges', index);
  }, []);


  // Makes the search full page modal appear 
  const handlePresentPress = useCallback(() => {
    present(
      <View>
       <Text>MODAL</Text>
      </View> 
      ,
      {
        snapPoints: snapPoints, 
        onChange: handleSheetChanges
      },
    );
  }, [present, snapPoints, handleSheetChanges]);

  const handleDismissPress = useCallback(() => {
    dismiss();
  }, [dismiss]);

  return (
    <View>
      <TouchableOpacity onPress={() =>  handlePresentPress()}>
         <Text>Open modal</Text>
      </TouchableOpacity>
    </View>
  );
};

export default SearchScreen;
```

**Comment by gorhom** [comment]
hi @maxckelly , i have tested your provided reproducible sample code and it seems working fine on Android & iOS 🤔

Have you tried to use your reproducible sample code in the example project ? it might be something with the React Native Gesture Handler setup.

**Comment by maxckelly** [comment]
Thanks @gorhom - I'll give that a go. Seems to be my own project, I'll let you know if I find the solution in case anyone else faces it. 

Thanks a lot for your help! :)

**Comment by gorhom** [comment]
no problem :)

**Comment by sergeymild** [comment]
When using BottomSheetModal from version 2 on android swipe to dismiss doesn't working but on ios everything forks fine

**Comment by michaelbayday** [comment]
@sergeymild did you solve this?

**Comment by launcherx** [comment]
I had the same issues (using bottom-sheet@v3), but in my case @adamsoutar suggestion helped, `react-native-gesture-handler` in my project was not configured correctly.

**Comment by ameer-taghavi** [comment]
> I had the same issues (using bottom-sheet@v3), but in my case @adamsoutar suggestion helped, `react-native-gesture-handler` in my project was not configured correctly.

I have same problem with the latest version but in `iOS` . how did you fix it by config `react-native-gesture-handler`?

**Comment by Myzel394** [comment]
I also faced this issue. [Just had to wrap my app with `<GestureHandlerRootView />`](https://docs.swmansion.com/react-native-gesture-handler/docs/installation#js).

**Comment by jahnagoldman** [comment]
> I also faced this issue. [Just had to wrap my app with `<GestureHandlerRootView />`](https://docs.swmansion.com/react-native-gesture-handler/docs/installation#js).

This worked for me, but then I get a console warning `Warning: Cannot record touch end without a touch start.` whenever I dismiss the bottom sheet modal. Anyone else get this / know how to fix it? Just a warning, but would be nice to be able to resolve it.

**Comment by paulrostorp** [comment]
@jahnagoldman Did you ever find a solution ? I am also facing this...

**Comment by quicksilverr** [comment]
@jahnagoldman Did you find a fix for that warning, it seems, while trying to use a scrollable within the bottom sheet modal I'm getting it.

**Comment by margabit** [comment]
In my case, I was facing a problem in Android where the BottomSheet was not responsive at all when used inside of a react native modal.
I found the solution, in my case, wrapping the content of the modal with the gestureHandlerRootHOC as described here:
https://docs.swmansion.com/react-native-gesture-handler/docs/installation#usage-with-modals-on-android

```
const ExampleWithHoc = gestureHandlerRootHOC(() => (
    <View>
      <DraggableBox />
    </View>
  );
);

export default function Example() {
  return (
    <Modal>
      <ExampleWithHoc />
    </Modal>
  );
}
```
