### ISSUE TITLE
[v2][Android] Taps on the bottom sheet are not activated

### ISSUE THREAD

**Issue by Johan-dutoit** [gorhom/react-native-bottom-sheet#86]
# Bug

With my limited knowledge of the entire gesture handler from Software Mansion, it seems that `ContentWrapper.android.tsx` is configured incorrectly (or something there anyway).

When tapping 'quickly' (read a normal tap), the gesture handler responds in the following manner (not sure why duplicated) and doesn't call the `onPress` handler (although the UI updates the opacity when pressed on a TouchableOpacity component):

```js
[Thu Nov 26 2020 13:37:02.521]  LOG      start
[Thu Nov 26 2020 13:37:02.524]  LOG     start
[Thu Nov 26 2020 13:37:02.611]   LOG     active
[Thu Nov 26 2020 13:37:02.612]  LOG      active
[Thu Nov 26 2020 13:37:02.615]  LOG      end
[Thu Nov 26 2020 13:37:02.616]  LOG      finish
[Thu Nov 26 2020 13:37:02.620]  LOG     end
[Thu Nov 26 2020 13:37:02.622]  LOG     finish
```

Changing [line 17](https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/contentWrapper/ContentWrapper.android.tsx#L17) to lets say 50, results in the following log (once again not sure why the duplication occurs):

```js
[Thu Nov 26 2020 13:43:44.274]  LOG     start
[Thu Nov 26 2020 13:43:44.276]  LOG     start
[Thu Nov 26 2020 13:43:44.784]  LOG     fail
[Thu Nov 26 2020 13:43:44.785]  LOG     finish
[Thu Nov 26 2020 13:43:44.786]  LOG     fail
[Thu Nov 26 2020 13:43:44.786]  LOG     finish
```

Currently my code structure looks like this (react-navigation based)

```js
<BottomSheet>
  <BottomSheetView>
    <Header /> // title and close button
    <BottomSheetScrollView>
      {items} // Array with TouchableOpacity items from react-native
    </BottomSheetScrollView>
  </BottomSheetView>
</BottomSheet>

```

## Logs
To reproduce the logs above, I updated `useTapGestureHandler` to log each of the gesture handler events

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 2.0.0-alpha.1   |
| react-native                    | 0.63.3   |
| react-native-reanimated         | 2.0.0-alpha.9.1  |
| react-native-gesture-handler    | 1.8.0   |

**Comment by gorhom** [comment]
thanks @Johan-dutoit for submitting this issue.

could you try to import the `TouchableOpacity` from the library, also you could look at [Touchable](https://github.com/gorhom/react-native-bottom-sheet/blob/master/docs/touchables.md)

please let me know if it still not working to investigate it :)

**Comment by Johan-dutoit** [comment]
Apologies, no idea how I missed that.  Ignore it all!

**Comment by gorhom** [comment]
@Johan-dutoit no worries 👏

**Comment by Johan-dutoit** [comment]
@gorhom perhaps it can be made more prominent in the docs/readme?

**Comment by gorhom** [comment]
@Johan-dutoit yeah , i am working on that already 😅
