### ISSUE TITLE
How can you make the BottomSheet the size of the content?

### ISSUE THREAD

**Issue by vishgoel007** [gorhom/react-native-bottom-sheet#87]
Hi!
I have a list as the content and I want to make the bottom sheet only as much bigger as the size of the whole list.
I'm a bit lost in how to do this. Is there a way to do this?

**Comment by likern** [comment]
@vishgoel007 There is an example of how to do that in example application.
You can find it in `master` branch. Generally you have to measure you content using `onLayout` and pass `height` to `contentHeight` props of BottomSheet.

**Comment by Angelk90** [comment]
@likern : 

Say use this: https://github.com/gorhom/react-native-bottom-sheet/blob/7304867dab76d1dd62e6052ad6cfcb18ff8492e7/example/src/screens/advanced/DynamicSnapPointExample.tsx#L91

https://github.com/gorhom/react-native-bottom-sheet/blob/7304867dab76d1dd62e6052ad6cfcb18ff8492e7/example/src/screens/advanced/DynamicSnapPointExample.tsx#L33-L43

But if one uses the `modal` type with `present()`, what should one do?

**Comment by stephenlaughton** [comment]
@gorhom does the new declarative `BottomSheetModal` now handle this use-case?

**Comment by gorhom** [comment]
@stephenlaughton good question, it does.. however i found a small bug i will prepare a new fix now 👍

**Comment by gorhom** [comment]
dynamic snap point support in bottom sheet modal will be released with alpha.7 👏

check https://github.com/gorhom/react-native-bottom-sheet/issues/75
