### ISSUE TITLE
Add Velocity To Animation

### ISSUE THREAD

**Issue by zachgibson** [gorhom/react-native-bottom-sheet#93]
# Feature Request

If you flick the bottom sheet softly or as hard as you can, the sheet will animate to its appropriate snap point but always at the same speed. It would be awesome to include velocity.

## Why it is needed

It will feel more native.

## Possible implementation

Not sure if Reanimated supports but velocity but if it does then this should be fairly straightforward.

**Comment by zachgibson** [comment]
Did some research and Reanimated's spring has some of the same properties as RN's core Animated spring, which I believe to just be general concepts in spring physics animations. RN docs explains what these properties affect and it seems we can achieve dynamic velocity. I will look into this and open a PR if I can get it working.

**Comment by AppKidd** [comment]
Would be really great to see spring-loaded animation! Definitely would give a more native feel.
