### ISSUE TITLE
Move modal up when the keyboard appears

### ISSUE THREAD

**Issue by onmotion** [gorhom/react-native-bottom-sheet#96]
# Feature Request

Is there a way to make the modal move up when the keyboard appears?
On android it's works, not perfect, but works

1. iOS kb hidden/shown
<div style="display: flex">
<img src="https://user-images.githubusercontent.com/12899080/101052803-1c3d1b80-3598-11eb-8fd0-fc0b93876098.png" width="250px">
<img src="https://user-images.githubusercontent.com/12899080/101052969-4989c980-3598-11eb-859e-a461a3134a80.png" width="250px" >
</div>

2. Android kb hidden/shown
<div style="display: flex">
<img src="https://user-images.githubusercontent.com/12899080/101053906-5ce96480-3599-11eb-9abe-5270d422ece5.png" width="250px">
<img src="https://user-images.githubusercontent.com/12899080/101053946-6672cc80-3599-11eb-9d7c-038372ac3d64.png" width="250px" >
</div>

The first what I think is make custom bottom offset for container when kb event happened. But maybe there is another simple way. 

Thank you!

**Comment by gorhom** [comment]
@onmotion thanks for submitting this issue. Unfortunately, I can't help if the issue does not follow the issue template :( 

please update the issue

**Comment by SteliosKornelakis** [comment]
Use this:

import KeyboardSpacer from "react-native-keyboard-spacer";

//TextInput here
{
  (Platform.OS === 'ios') ? <KeyboardSpacer /> : null
}

**Comment by theianjohnson** [comment]
@gorhom also having this issue only on iOS, they keyboard just covers the bottom sheet up when using `BottomSheetModal`

Edit: Using v2

**Comment by theianjohnson** [comment]
https://github.com/gorhom/react-native-bottom-sheet/issues/330
