### ISSUE TITLE
[v4] | [v2] Flex 1 doesn't work on web

### ISSUE THREAD

**Issue by Ryanjso** [gorhom/react-native-bottom-sheet#969]
# Bug

Using `{flex: 1}` does not work on web with expo. While applying it to a view expands the view fully on IOS, it does nothing on web. 
Here's a snack example https://snack.expo.dev/@ryanjso/bottom-sheet-v4-reproducible-issue-template and here's some screen shots comparing web to ios

<img width="331" alt="Screen Shot 2022-06-01 at 10 17 24 AM" src="https://user-images.githubusercontent.com/39172778/171427215-a84ffff6-d925-4ade-a87f-3c31adc0f2cb.png">
<img width="167" alt="Screen Shot 2022-06-01 at 10 15 43 AM" src="https://user-images.githubusercontent.com/39172778/171427218-09a78b95-d034-4181-bd03-f8c67ea6821b.png">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.2.2   |
| react-native                    | ^0.68.1   |
| react-native-reanimated         | ~2.8.0   |
| react-native-gesture-handler    | ~2.2.0   |
| expo    | ^45.0.1   |

## Steps To Reproduce

1. Add `{flex: 1}` to the top level of the Bottom Sheet children

Describe what you expected to happen:

1. The view should expand to fill the bottom sheet container, but does not on web

## Reproducible sample code

https://snack.expo.dev/@ryanjso/bottom-sheet-v4-reproducible-issue-template

**Comment by hirbod** [comment]
This library is currently not optimized for web, but @gorhom is working on it.
https://twitter.com/gorhom/status/1528846132817842176
