### ISSUE TITLE
Pagination, Infinite scroll, Load more 

### ISSUE THREAD

**Issue by Angelk90** [gorhom/react-native-bottom-sheet#98]
# Feature Request

![image](https://user-images.githubusercontent.com/20476002/101183272-97add400-364f-11eb-9a81-be054659542a.png)

Hi @gorhom , 

would it be possible to implement examples such as those of the image where for example data are taken from http and are paginated?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by Angelk90** [comment]
@gorhom : are there any news?

**Comment by dlombardi** [comment]
infinite scroll not working too well with bottom sheet

**Comment by Angelk90** [comment]
@gorhom : are there any news?
